#!/usr/bin/env python3
"""Generate a complete typed rocBLAS compatibility bridge from an API snapshot."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


CUSTOM_FACADE = {
    "rocblas_create_handle",
    "rocblas_destroy_handle",
    "rocblas_device_malloc_alloc",
    "rocblas_set_optimal_device_memory_size_impl",
}


@dataclass(frozen=True)
class Parameter:
    name: str
    type: str


@dataclass(frozen=True)
class Function:
    name: str
    return_type: str
    parameters: tuple[Parameter, ...]
    variadic: bool

    @property
    def has_handle(self) -> bool:
        return bool(self.parameters) and self.parameters[0].type == "rocblas_handle"


def cpp_type(value: str) -> str:
    return value.replace("_Bool", "bool")


def load_functions(path: Path) -> list[Function]:
    with path.open(encoding="utf-8") as stream:
        document = json.load(stream)
    declarations = document.get("declarations")
    if not isinstance(declarations, list):
        raise ValueError(f"{path}: declarations must be an array")
    result: list[Function] = []
    for declaration in declarations:
        if not isinstance(declaration, dict) or declaration.get("kind") != "function":
            continue
        name = declaration.get("name")
        return_type = declaration.get("return_type")
        parameters = declaration.get("parameters")
        variadic = declaration.get("variadic")
        if (not isinstance(name, str) or not isinstance(return_type, str)
                or not isinstance(parameters, list) or not isinstance(variadic, bool)):
            raise ValueError(f"{path}: malformed function declaration")
        parsed: list[Parameter] = []
        for parameter in parameters:
            if (not isinstance(parameter, dict)
                    or not isinstance(parameter.get("name"), str)
                    or not isinstance(parameter.get("type"), str)):
                raise ValueError(f"{path}: malformed parameter in {name}")
            parsed.append(Parameter(parameter["name"], cpp_type(parameter["type"])))
        result.append(Function(name, cpp_type(return_type), tuple(parsed), variadic))
    result.sort(key=lambda function: function.name)
    if len(result) != len({function.name for function in result}):
        raise ValueError("rocBLAS snapshot contains duplicate function names")
    if {function.name for function in result if function.variadic} != {
        "rocblas_device_malloc_alloc",
        "rocblas_set_optimal_device_memory_size_impl",
    }:
        raise ValueError("unexpected rocBLAS variadic function set")
    return result


def signature(function: Function) -> str:
    parameters = [f"{parameter.type} {parameter.name}" for parameter in function.parameters]
    if function.variadic:
        parameters.append("...")
    return ", ".join(parameters) if parameters else "void"


def call_arguments(function: Function, replace_handle: bool = False) -> str:
    arguments = [parameter.name for parameter in function.parameters]
    if replace_handle and function.has_handle:
        arguments[0] = "rocm::interfaces::rocblas_bridge_native_handle(handle)"
    return ", ".join(arguments)


def fallback(return_type: str) -> str:
    if return_type == "void":
        return "return;"
    if return_type == "rocblas_status":
        return "return rocblas_status_internal_error;"
    if return_type == "bool":
        return "return false;"
    if return_type == "rocblas_pointer_mode":
        return "return rocblas_pointer_mode_host;"
    if return_type == "const char *":
        return 'return "rocBLAS bridge unavailable";'
    raise ValueError(f"no fallback for return type {return_type}")


def write_header(functions: list[Function], path: Path) -> None:
    lines = [
        "// Generated by generate_rocblas_bridge.py. Do not edit.",
        "#ifndef ROCM_INTERFACES_ROCBLAS_BRIDGE_GENERATED_H_",
        "#define ROCM_INTERFACES_ROCBLAS_BRIDGE_GENERATED_H_",
        "",
        '#include "rocm/interfaces/common.h"',
        "#include <rocblas/rocblas.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "typedef struct rocm_rocblas_bridge_v1 {",
        "  rocm_interfaces_abi_header header;",
    ]
    for function in functions:
        lines.append(
            f"  {function.return_type} (ROCM_INTERFACES_CALL* {function.name})"
            f"({signature(function)});"
        )
    lines.extend([
        "  rocblas_status (ROCM_INTERFACES_CALL* rocblas_device_malloc_alloc_sizes)(",
        "      rocblas_handle, struct rocblas_device_malloc_base**, size_t, const size_t*);",
        "  rocblas_status (ROCM_INTERFACES_CALL* rocblas_set_optimal_device_memory_sizes)(",
        "      rocblas_handle, size_t, const size_t*);",
        "} rocm_rocblas_bridge_v1;",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "#endif",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")


def write_facade(functions: list[Function], path: Path) -> None:
    lines = [
        "// Generated by generate_rocblas_bridge.py. Do not edit.",
        '#include "rocblas_bridge_runtime.h"',
        "#include <cstdlib>",
        "",
        'extern "C" {',
    ]
    for function in functions:
        if function.name in CUSTOM_FACADE:
            continue
        lines.append("")
        lines.append(f"{function.return_type} {function.name}({signature(function)}) {{")
        if function.has_handle:
            if function.return_type == "rocblas_status":
                lines.append("  if (!handle) return rocblas_status_invalid_handle;")
            elif function.return_type == "bool":
                lines.append("  if (!handle) return false;")
            else:
                raise ValueError(f"unsupported handle return type in {function.name}")
            lines.append("  const auto* table = rocm::interfaces::rocblas_bridge_table(handle);")
        else:
            lines.append("  const auto* table = rocm::interfaces::rocblas_bridge_table();")
        unavailable = ("std::abort();" if function.name == "rocblas_abort"
                       else fallback(function.return_type))
        lines.append(f"  if (!table || !table->{function.name}) {{ {unavailable} }}")
        call = f"table->{function.name}({call_arguments(function, replace_handle=True)})"
        lines.append("  try {")
        if function.return_type == "void":
            lines.append(f"    {call};")
            if function.name == "rocblas_abort":
                lines.append("    std::abort();")
        else:
            lines.append(f"    return {call};")
        lines.append("  } catch (...) {")
        caught = ("std::abort();" if function.name == "rocblas_abort"
                  else fallback(function.return_type))
        lines.append(f"    {caught}")
        lines.append("  }")
        lines.append("}")
    lines.extend(["", '}  // extern "C"', ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def stub_body(function: Function) -> list[str]:
    if function.name == "rocblas_abort":
        return ["  std::abort();"]
    if function.name == "rocblas_create_handle":
        return [
            "  if (!handle) return rocblas_status_invalid_pointer;",
            "  *handle = new (std::nothrow) _rocblas_handle{};",
            "  return *handle ? rocblas_status_success : rocblas_status_memory_error;",
        ]
    if function.name == "rocblas_destroy_handle":
        return [
            "  if (!handle) return rocblas_status_invalid_handle;",
            "  delete handle;",
            "  return rocblas_status_success;",
        ]
    if function.return_type == "rocblas_status":
        prefix = ["  if (!handle) return rocblas_status_invalid_handle;"] if function.has_handle else []
        return prefix + ["  return rocblas_status_not_implemented;"]
    if function.return_type == "void":
        return ["  return;"]
    if function.return_type == "bool":
        return ["  return false;"]
    if function.return_type == "rocblas_pointer_mode":
        return ["  return rocblas_pointer_mode_host;"]
    if function.return_type == "const char *":
        return ['  return "recording rocBLAS brute-force provider";']
    raise ValueError(f"no stub body for {function.name}: {function.return_type}")


def write_provider(functions: list[Function], path: Path) -> None:
    lines = [
        "// Generated by generate_rocblas_bridge.py. Do not edit.",
        '#include "rocblas_bridge_generated.h"',
        "",
        "#include <new>",
        "#include <cstdlib>",
        "",
        "struct _rocblas_handle {",
        "  unsigned char marker = 0;",
        "};",
        "",
        "namespace {",
    ]
    for function in functions:
        lines.extend(["", f"{function.return_type} stub_{function.name}({signature(function)}) {{"])
        lines.extend(f"  (void){parameter.name};" for parameter in function.parameters)
        lines.extend(stub_body(function))
        lines.append("}")
    lines.extend([
        "",
        "rocblas_status stub_device_malloc_alloc_sizes(",
        "    rocblas_handle handle, struct rocblas_device_malloc_base**, size_t, const size_t*) {",
        "  return handle ? rocblas_status_not_implemented : rocblas_status_invalid_handle;",
        "}",
        "",
        "rocblas_status stub_set_optimal_device_memory_sizes(",
        "    rocblas_handle handle, size_t, const size_t*) {",
        "  return handle ? rocblas_status_not_implemented : rocblas_status_invalid_handle;",
        "}",
        "",
        "const rocm_rocblas_bridge_v1 table = {",
        "  {sizeof(rocm_rocblas_bridge_v1), ROCM_INTERFACES_ABI_MAJOR, ROCM_INTERFACES_ABI_MINOR},",
    ])
    lines.extend(f"  stub_{function.name}," for function in functions)
    lines.extend([
        "  stub_device_malloc_alloc_sizes,",
        "  stub_set_optimal_device_memory_sizes,",
        "};",
        "}  // namespace",
        "",
        'extern "C" ROCM_INTERFACES_EXPORT rocm_interfaces_status ROCM_INTERFACES_CALL',
        "rocm_interfaces_provider_query_v1(const rocm_interfaces_provider_request* request,",
        "                                  rocm_interfaces_provider_response* response) {",
        "  if (!request || !response || request->domain != ROCM_INTERFACES_DOMAIN_ROCBLAS_BRIDGE ||",
        "      request->header.abi_major != ROCM_INTERFACES_ABI_MAJOR ||",
        "      request->required_table_size > sizeof(table))",
        "    return ROCM_INTERFACES_STATUS_INCOMPATIBLE_ABI;",
        "  response->header = {sizeof(*response), ROCM_INTERFACES_ABI_MAJOR,",
        "                      ROCM_INTERFACES_ABI_MINOR};",
        '  response->provider_id = "recording-rocblas-bruteforce";',
        '  response->build_id = "interfaces-spike-v1";',
        "  response->dispatch_table = &table;",
        "  response->dispatch_table_size = sizeof(table);",
        "  response->capability_mask = 0;",
        "  return ROCM_INTERFACES_STATUS_SUCCESS;",
        "}",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")


def zero_argument(parameter: Parameter) -> str:
    if parameter.type == "rocblas_handle":
        return "nullptr"
    return "{}"


def write_link_test(functions: list[Function], path: Path) -> None:
    lines = [
        "// Generated by generate_rocblas_bridge.py. Do not edit.",
        "#include <rocblas/rocblas.h>",
        "",
        "#include <cstddef>",
        "",
        "int main() {",
    ]
    for function in functions:
        lines.append(f"  (void)&{function.name};")
    for function in functions:
        if not function.has_handle or function.name in CUSTOM_FACADE:
            continue
        arguments = ", ".join(zero_argument(parameter) for parameter in function.parameters)
        if function.return_type == "rocblas_status":
            lines.extend([
                f"  if ({function.name}({arguments}) != rocblas_status_invalid_handle)",
                "    return 1;",
            ])
        elif function.return_type == "bool":
            lines.extend([f"  if ({function.name}({arguments}))", "    return 2;"])
    lines.extend(["  return 0;", "}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def write_version_script(functions: list[Function], path: Path) -> None:
    lines = ["ROCBLAS_ABI_5 {", "  global:"]
    lines.extend(f"    {function.name};" for function in functions)
    lines.extend(["  local:", "    *;", "};", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def write_exports(functions: list[Function], path: Path) -> None:
    path.write_text("\n".join(function.name for function in functions) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--snapshot", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    functions = load_functions(args.snapshot)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    write_header(functions, args.output_dir / "rocblas_bridge_generated.h")
    write_facade(functions, args.output_dir / "rocblas_bridge_facade.cpp")
    write_provider(functions, args.output_dir / "rocblas_bridge_provider.cpp")
    write_link_test(functions, args.output_dir / "rocblas_bridge_link_test.cpp")
    write_version_script(functions, args.output_dir / "rocblas_bridge.map")
    write_exports(functions, args.output_dir / "rocblas_bridge.exports")


if __name__ == "__main__":
    main()
