#!/usr/bin/env python3
"""Generate a complete typed rocBLAS compatibility bridge from an API snapshot."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


CUSTOM_FACADE = {
    "rocblas_create_handle",
    "rocblas_destroy_handle",
    "rocblas_device_malloc_alloc",
    "rocblas_set_optimal_device_memory_size_impl",
}

GROUPED_GEMM_COMPAT_SHIMS = {
    "rocblas_sgemm_grouped_batched": "rocblas_sgemm",
    "rocblas_dgemm_grouped_batched": "rocblas_dgemm",
    "rocblas_sgemm_grouped_batched_64": "rocblas_sgemm_64",
    "rocblas_dgemm_grouped_batched_64": "rocblas_dgemm_64",
    "rocblas_gemm_grouped_batched_ex": "rocblas_gemm_ex",
    "rocblas_gemm_grouped_batched_ex_64": "rocblas_gemm_ex_64",
}


@dataclass(frozen=True)
class Parameter:
    name: str
    type: str


@dataclass(frozen=True)
class Function:
    name: str
    return_type: str
    parameters: tuple[Parameter, ...]
    variadic: bool

    @property
    def has_handle(self) -> bool:
        return bool(self.parameters) and self.parameters[0].type == "rocblas_handle"


def cpp_type(value: str) -> str:
    return value.replace("_Bool", "bool")


def load_functions(path: Path) -> list[Function]:
    with path.open(encoding="utf-8") as stream:
        document = json.load(stream)
    declarations = document.get("declarations")
    if not isinstance(declarations, list):
        raise ValueError(f"{path}: declarations must be an array")
    result: list[Function] = []
    for declaration in declarations:
        if not isinstance(declaration, dict) or declaration.get("kind") != "function":
            continue
        name = declaration.get("name")
        return_type = declaration.get("return_type")
        parameters = declaration.get("parameters")
        variadic = declaration.get("variadic")
        if (
            not isinstance(name, str)
            or not isinstance(return_type, str)
            or not isinstance(parameters, list)
            or not isinstance(variadic, bool)
        ):
            raise ValueError(f"{path}: malformed function declaration")
        parsed: list[Parameter] = []
        for parameter in parameters:
            if (
                not isinstance(parameter, dict)
                or not isinstance(parameter.get("name"), str)
                or not isinstance(parameter.get("type"), str)
            ):
                raise ValueError(f"{path}: malformed parameter in {name}")
            parsed.append(Parameter(parameter["name"], cpp_type(parameter["type"])))
        result.append(Function(name, cpp_type(return_type), tuple(parsed), variadic))
    result.sort(key=lambda function: function.name)
    if len(result) != len({function.name for function in result}):
        raise ValueError("rocBLAS snapshot contains duplicate function names")
    if {function.name for function in result if function.variadic} != {
        "rocblas_device_malloc_alloc",
        "rocblas_set_optimal_device_memory_size_impl",
    }:
        raise ValueError("unexpected rocBLAS variadic function set")
    return result


def signature(function: Function) -> str:
    parameters = [
        f"{parameter.type} {parameter.name}" for parameter in function.parameters
    ]
    if function.variadic:
        parameters.append("...")
    return ", ".join(parameters) if parameters else "void"


def call_arguments(function: Function, replace_handle: bool = False) -> str:
    arguments = [parameter.name for parameter in function.parameters]
    if replace_handle and function.has_handle:
        arguments[0] = "rocm::interfaces::rocblas_bridge_native_handle(handle)"
    return ", ".join(arguments)


def fallback(return_type: str) -> str:
    if return_type == "void":
        return "return;"
    if return_type == "rocblas_status":
        return "return rocblas_status_internal_error;"
    if return_type == "bool":
        return "return false;"
    if return_type == "rocblas_pointer_mode":
        return "return rocblas_pointer_mode_host;"
    if return_type == "const char *":
        return 'return "rocBLAS bridge unavailable";'
    raise ValueError(f"no fallback for return type {return_type}")


def write_header(functions: list[Function], path: Path) -> None:
    lines = [
        "// Generated by generate_rocblas_bridge.py. Do not edit.",
        "#ifndef ROCM_INTERFACES_ROCBLAS_BRIDGE_GENERATED_H_",
        "#define ROCM_INTERFACES_ROCBLAS_BRIDGE_GENERATED_H_",
        "",
        '#include "rocm/interfaces/common.h"',
        "#include <rocblas/rocblas.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "typedef struct rocm_rocblas_bridge_v1 {",
        "  rocm_interfaces_abi_header header;",
    ]
    for function in functions:
        lines.append(
            f"  {function.return_type} (ROCM_INTERFACES_CALL* {function.name})"
            f"({signature(function)});"
        )
    lines.extend(
        [
            "  rocblas_status (ROCM_INTERFACES_CALL* rocblas_device_malloc_alloc_sizes)(",
            "      rocblas_handle, struct rocblas_device_malloc_base**, size_t, const size_t*);",
            "  rocblas_status (ROCM_INTERFACES_CALL* rocblas_set_optimal_device_memory_sizes)(",
            "      rocblas_handle, size_t, const size_t*);",
            "} rocm_rocblas_bridge_v1;",
            "",
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "#endif",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def write_facade(functions: list[Function], path: Path) -> None:
    lines = [
        "// Generated by generate_rocblas_bridge.py. Do not edit.",
        '#include "rocblas_bridge_runtime.h"',
        "#include <cstdlib>",
        "",
        'extern "C" {',
    ]
    for function in functions:
        if function.name in CUSTOM_FACADE:
            continue
        lines.append("")
        lines.append(
            f"{function.return_type} {function.name}({signature(function)}) {{"
        )
        if function.has_handle:
            if function.return_type == "rocblas_status":
                lines.append("  if (!handle) return rocblas_status_invalid_handle;")
            elif function.return_type == "bool":
                lines.append("  if (!handle) return false;")
            else:
                raise ValueError(f"unsupported handle return type in {function.name}")
            lines.append(
                "  const auto* table = rocm::interfaces::rocblas_bridge_table(handle);"
            )
        else:
            lines.append(
                "  const auto* table = rocm::interfaces::rocblas_bridge_table();"
            )
        unavailable = (
            "std::abort();"
            if function.name == "rocblas_abort"
            else fallback(function.return_type)
        )
        lines.append(f"  if (!table || !table->{function.name}) {{ {unavailable} }}")
        call = (
            f"table->{function.name}({call_arguments(function, replace_handle=True)})"
        )
        lines.append("  try {")
        if function.return_type == "void":
            lines.append(f"    {call};")
            if function.name == "rocblas_abort":
                lines.append("    std::abort();")
        else:
            lines.append(f"    return {call};")
        lines.append("  } catch (...) {")
        caught = (
            "std::abort();"
            if function.name == "rocblas_abort"
            else fallback(function.return_type)
        )
        lines.append(f"    {caught}")
        lines.append("  }")
        lines.append("}")
    lines.extend(["", '}  // extern "C"', ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def stub_body(function: Function) -> list[str]:
    if function.name == "rocblas_abort":
        return ["  std::abort();"]
    if function.name == "rocblas_create_handle":
        return [
            "  if (!handle) return rocblas_status_invalid_pointer;",
            "  *handle = new (std::nothrow) _rocblas_handle{};",
            "  return *handle ? rocblas_status_success : rocblas_status_memory_error;",
        ]
    if function.name == "rocblas_destroy_handle":
        return [
            "  if (!handle) return rocblas_status_invalid_handle;",
            "  delete handle;",
            "  return rocblas_status_success;",
        ]
    if function.return_type == "rocblas_status":
        prefix = (
            ["  if (!handle) return rocblas_status_invalid_handle;"]
            if function.has_handle
            else []
        )
        return prefix + ["  return rocblas_status_not_implemented;"]
    if function.return_type == "void":
        return ["  return;"]
    if function.return_type == "bool":
        return ["  return false;"]
    if function.return_type == "rocblas_pointer_mode":
        return ["  return rocblas_pointer_mode_host;"]
    if function.return_type == "const char *":
        return ['  return "recording rocBLAS brute-force provider";']
    raise ValueError(f"no stub body for {function.name}: {function.return_type}")


def write_provider(functions: list[Function], path: Path) -> None:
    lines = [
        "// Generated by generate_rocblas_bridge.py. Do not edit.",
        '#include "rocblas_bridge_generated.h"',
        "",
        "#include <new>",
        "#include <cstdlib>",
        "",
        "struct _rocblas_handle {",
        "  unsigned char marker = 0;",
        "};",
        "",
        "namespace {",
    ]
    for function in functions:
        lines.extend(
            [
                "",
                f"{function.return_type} stub_{function.name}({signature(function)}) {{",
            ]
        )
        lines.extend(f"  (void){parameter.name};" for parameter in function.parameters)
        lines.extend(stub_body(function))
        lines.append("}")
    lines.extend(
        [
            "",
            "rocblas_status stub_device_malloc_alloc_sizes(",
            "    rocblas_handle handle, struct rocblas_device_malloc_base**, size_t, const size_t*) {",
            "  return handle ? rocblas_status_not_implemented : rocblas_status_invalid_handle;",
            "}",
            "",
            "rocblas_status stub_set_optimal_device_memory_sizes(",
            "    rocblas_handle handle, size_t, const size_t*) {",
            "  return handle ? rocblas_status_not_implemented : rocblas_status_invalid_handle;",
            "}",
            "",
            "const rocm_rocblas_bridge_v1 table = {",
            "  {sizeof(rocm_rocblas_bridge_v1), ROCM_INTERFACES_ABI_MAJOR, ROCM_INTERFACES_ABI_MINOR},",
        ]
    )
    lines.extend(f"  stub_{function.name}," for function in functions)
    lines.extend(
        [
            "  stub_device_malloc_alloc_sizes,",
            "  stub_set_optimal_device_memory_sizes,",
            "};",
            "}  // namespace",
            "",
            'extern "C" ROCM_INTERFACES_EXPORT rocm_interfaces_status ROCM_INTERFACES_CALL',
            "rocm_interfaces_provider_query_v1(const rocm_interfaces_provider_request* request,",
            "                                  rocm_interfaces_provider_response* response) {",
            "  if (!request || !response || request->domain != ROCM_INTERFACES_DOMAIN_ROCBLAS_BRIDGE ||",
            "      request->header.abi_major != ROCM_INTERFACES_ABI_MAJOR ||",
            "      request->required_table_size > sizeof(table))",
            "    return ROCM_INTERFACES_STATUS_INCOMPATIBLE_ABI;",
            "  response->header = {sizeof(*response), ROCM_INTERFACES_ABI_MAJOR,",
            "                      ROCM_INTERFACES_ABI_MINOR};",
            '  response->provider_id = "recording-rocblas-bruteforce";',
            '  response->build_id = "interfaces-spike-v1";',
            "  response->dispatch_table = &table;",
            "  response->dispatch_table_size = sizeof(table);",
            "  response->capability_mask = 0;",
            "  return ROCM_INTERFACES_STATUS_SUCCESS;",
            "}",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def write_forwarding_provider(functions: list[Function], path: Path) -> None:
    """Generate the real provider that binds a canonical rocBLAS DSO by handle.

    The shadow loader and canonical backend intentionally have different SONAMEs.
    Resolving every entry with dlsym on the backend handle avoids global-symbol
    recursion through the shadow facade. The six grouped-GEMM entry points are
    adapted to their non-grouped counterparts for one release of backward
    compatibility with rocBLAS 5 DSOs that predate those public spellings.
    """
    by_name = {function.name: function for function in functions}
    missing = sorted(
        (set(GROUPED_GEMM_COMPAT_SHIMS) | set(GROUPED_GEMM_COMPAT_SHIMS.values()))
        - by_name.keys()
    )
    if missing:
        raise ValueError(f"rocBLAS forwarding-provider inputs are missing: {missing}")

    lines = [
        "// Generated by generate_rocblas_bridge.py. Do not edit.",
        '#include "rocblas_bridge_generated.h"',
        "",
        "#include <dlfcn.h>",
        "",
        "#include <cstdlib>",
        "#include <memory>",
        "#include <mutex>",
        "#include <stdexcept>",
        "#include <string>",
        "",
        "#ifndef ROCM_INTERFACES_ROCBLAS_BACKEND_SONAME",
        '#define ROCM_INTERFACES_ROCBLAS_BACKEND_SONAME "librocblas.so.5"',
        "#endif",
        "#if defined(__has_feature)",
        "#if __has_feature(address_sanitizer) || __has_feature(thread_sanitizer)",
        "#define ROCM_INTERFACES_SANITIZED_BUILD 1",
        "#endif",
        "#endif",
        "#if defined(__SANITIZE_ADDRESS__) || defined(__SANITIZE_THREAD__)",
        "#define ROCM_INTERFACES_SANITIZED_BUILD 1",
        "#endif",
        "",
        "namespace {",
        "rocm_rocblas_bridge_v1 table{};",
        "void* backend_handle = nullptr;",
        "std::once_flag backend_once;",
        "struct DlCloser {",
        "  void operator()(void* handle) const noexcept {",
        "    if (handle) dlclose(handle);",
        "  }",
        "};",
        "",
        "const char* backend_path() {",
        '  const char* override_path = std::getenv("ROCM_INTERFACES_REAL_ROCBLAS_LIBRARY");',
        "  return override_path && *override_path ? override_path",
        "                                         : ROCM_INTERFACES_ROCBLAS_BACKEND_SONAME;",
        "}",
        "",
        "template <typename Pointer>",
        "bool resolve(void* module, Pointer& result, const char* name) {",
        "  dlerror();",
        "  void* symbol = dlsym(module, name);",
        "  if (!symbol || dlerror()) return false;",
        "  result = reinterpret_cast<Pointer>(symbol);",
        "  return true;",
        "}",
        "",
        "size_t scalar_size(rocblas_datatype type) {",
        "  switch (type) {",
        "    case rocblas_datatype_f16_r: return 2;",
        "    case rocblas_datatype_f32_r:",
        "    case rocblas_datatype_i32_r: return 4;",
        "    case rocblas_datatype_f64_r:",
        "    case rocblas_datatype_f32_c: return 8;",
        "    case rocblas_datatype_f64_c: return 16;",
        "    default: return 0;",
        "  }",
        "}",
    ]

    for name in (
        "rocblas_sgemm_grouped_batched",
        "rocblas_dgemm_grouped_batched",
        "rocblas_sgemm_grouped_batched_64",
        "rocblas_dgemm_grouped_batched_64",
    ):
        function = by_name[name]
        base = GROUPED_GEMM_COMPAT_SHIMS[name]
        index_type = "int64_t" if name.endswith("_64") else "rocblas_int"
        lines.extend(
            [
                "",
                f"rocblas_status compat_{name}({signature(function)}) {{",
                "  if (!handle) return rocblas_status_invalid_handle;",
                "  if (group_count < 0) return rocblas_status_invalid_size;",
                "  if (group_count == 0) return rocblas_status_success;",
                "  if (!transa_array || !transb_array || !m_array || !n_array || !k_array ||",
                "      !alpha_array || !lda_array || !ldb_array || !beta_array || !ldc_array ||",
                "      !group_size)",
                "    return rocblas_status_invalid_pointer;",
                "  int64_t problem_count = 0;",
                f"  for ({index_type} group = 0; group < group_count; ++group) {{",
                "    if (group_size[group] < 0) return rocblas_status_invalid_size;",
                "    problem_count += group_size[group];",
                "  }",
                "  if (problem_count && (!Aarray || !Barray || !Carray))",
                "    return rocblas_status_invalid_pointer;",
                f"  {index_type} offset = 0;",
                f"  for ({index_type} group = 0; group < group_count; ++group) {{",
                f"    for ({index_type} item = 0; item < group_size[group]; ++item) {{",
                f"      rocblas_status status = table.{base}(",
                "          handle, transa_array[group], transb_array[group], m_array[group],",
                "          n_array[group], k_array[group], &alpha_array[group], Aarray[offset + item],",
                "          lda_array[group], Barray[offset + item], ldb_array[group],",
                "          &beta_array[group], Carray[offset + item], ldc_array[group]);",
                "      if (status != rocblas_status_success) return status;",
                "    }",
                "    offset += group_size[group];",
                "  }",
                "  return rocblas_status_success;",
                "}",
            ]
        )

    for name in (
        "rocblas_gemm_grouped_batched_ex",
        "rocblas_gemm_grouped_batched_ex_64",
    ):
        function = by_name[name]
        base = GROUPED_GEMM_COMPAT_SHIMS[name]
        index_type = "int64_t" if name.endswith("_64") else "rocblas_int"
        lines.extend(
            [
                "",
                f"rocblas_status compat_{name}({signature(function)}) {{",
                "  if (!handle) return rocblas_status_invalid_handle;",
                "  if (group_count < 0) return rocblas_status_invalid_size;",
                "  if (group_count == 0) return rocblas_status_success;",
                "  if (!transa_array || !transb_array || !m_array || !n_array || !k_array ||",
                "      !alpha_array || !lda_array || !ldb_array || !beta_array || !ldc_array ||",
                "      !ldd_array || !group_size)",
                "    return rocblas_status_invalid_pointer;",
                "  const size_t value_size = scalar_size(compute_type);",
                "  if (!value_size) return rocblas_status_invalid_value;",
                "  const auto* alphas = static_cast<const unsigned char*>(alpha_array);",
                "  const auto* betas = static_cast<const unsigned char*>(beta_array);",
                "  int64_t problem_count = 0;",
                f"  for ({index_type} group = 0; group < group_count; ++group) {{",
                "    if (group_size[group] < 0) return rocblas_status_invalid_size;",
                "    problem_count += group_size[group];",
                "  }",
                "  if (problem_count && (!Aarray || !Barray || !Carray || !Darray))",
                "    return rocblas_status_invalid_pointer;",
                f"  {index_type} offset = 0;",
                f"  for ({index_type} group = 0; group < group_count; ++group) {{",
                f"    for ({index_type} item = 0; item < group_size[group]; ++item) {{",
                f"      rocblas_status status = table.{base}(",
                "          handle, transa_array[group], transb_array[group], m_array[group],",
                "          n_array[group], k_array[group], alphas + group * value_size,",
                "          Aarray[offset + item], a_type, lda_array[group], Barray[offset + item],",
                "          b_type, ldb_array[group], betas + group * value_size, Carray[offset + item],",
                "          c_type, ldc_array[group], Darray[offset + item], d_type, ldd_array[group],",
                "          compute_type, algo, 0, flags);",
                "      if (status != rocblas_status_success) return status;",
                "    }",
                "    offset += group_size[group];",
                "  }",
                "  return rocblas_status_success;",
                "}",
            ]
        )

    def variadic_dispatch(
        helper_name: str, target_name: str, with_result: bool
    ) -> None:
        prefix = "handle, result, count" if with_result else "handle, count"
        lines.extend(
            [
                "",
                f"rocblas_status {helper_name}(",
                (
                    "    rocblas_handle handle, struct rocblas_device_malloc_base** result,"
                    " size_t count, const size_t* sizes) {"
                    if with_result
                    else "    rocblas_handle handle, size_t count, const size_t* sizes) {"
                ),
                "  if (!handle) return rocblas_status_invalid_handle;",
                "  if (count && !sizes) return rocblas_status_invalid_pointer;",
                "  switch (count) {",
            ]
        )
        for count in range(33):
            arguments = ", ".join(f"sizes[{index}]" for index in range(count))
            suffix = f", {arguments}" if arguments else ""
            lines.append(
                f"    case {count}: return table.{target_name}({prefix}{suffix});"
            )
        lines.extend(
            [
                "    default: return rocblas_status_invalid_size;",
                "  }",
                "}",
            ]
        )

    variadic_dispatch(
        "forward_device_malloc_alloc_sizes", "rocblas_device_malloc_alloc", True
    )
    variadic_dispatch(
        "forward_set_optimal_device_memory_sizes",
        "rocblas_set_optimal_device_memory_size_impl",
        False,
    )

    lines.extend(
        [
            "",
            "void initialize_backend() {",
            "  std::call_once(backend_once, [] {",
            "    int flags = RTLD_NOW | RTLD_LOCAL;",
            "#if defined(RTLD_DEEPBIND) && !defined(ROCM_INTERFACES_SANITIZED_BUILD)",
            "    flags |= RTLD_DEEPBIND;",
            "#endif",
            "    void* opened = dlopen(backend_path(), flags);",
            "    if (!opened) {",
            "      const char* error = dlerror();",
            '      throw std::runtime_error(std::string("cannot load canonical rocBLAS backend: ") +',
            '                               (error ? error : "unknown loader error"));',
            "    }",
            "    std::unique_ptr<void, DlCloser> guard(opened);",
            "    rocm_rocblas_bridge_v1 candidate{};",
            "    candidate.header = {sizeof(candidate), ROCM_INTERFACES_ABI_MAJOR,",
            "                        ROCM_INTERFACES_ABI_MINOR};",
        ]
    )
    for function in functions:
        if function.name in GROUPED_GEMM_COMPAT_SHIMS:
            lines.extend(
                [
                    f'    if (!resolve(opened, candidate.{function.name}, "{function.name}"))',
                    f"      candidate.{function.name} = compat_{function.name};",
                ]
            )
        else:
            lines.extend(
                [
                    f'    if (!resolve(opened, candidate.{function.name}, "{function.name}"))',
                    f'      throw std::runtime_error("canonical rocBLAS backend is missing {function.name}");',
                ]
            )
    lines.extend(
        [
            "    candidate.rocblas_device_malloc_alloc_sizes = forward_device_malloc_alloc_sizes;",
            "    candidate.rocblas_set_optimal_device_memory_sizes =",
            "        forward_set_optimal_device_memory_sizes;",
            "    table = candidate;",
            "    backend_handle = guard.release();",
            "  });",
            "}",
            "",
            "void trace_failure(const rocm_interfaces_provider_request* request, const char* message) {",
            "  if (request && request->host && request->host->trace)",
            '    request->host->trace(request->host->user_data, "rocblas_bridge",',
            '                         "backend_load_failure", message, std::char_traits<char>::length(message));',
            "}",
            "}  // namespace",
            "",
            'extern "C" ROCM_INTERFACES_EXPORT rocm_interfaces_status ROCM_INTERFACES_CALL',
            "rocm_interfaces_provider_query_v1(const rocm_interfaces_provider_request* request,",
            "                                  rocm_interfaces_provider_response* response) {",
            "  if (!request || !response || request->domain != ROCM_INTERFACES_DOMAIN_ROCBLAS_BRIDGE ||",
            "      request->header.abi_major != ROCM_INTERFACES_ABI_MAJOR ||",
            "      response->header.struct_size < sizeof(*response) ||",
            "      request->required_table_size > sizeof(table))",
            "    return ROCM_INTERFACES_STATUS_INCOMPATIBLE_ABI;",
            "  try {",
            "    initialize_backend();",
            "  } catch (const std::exception& error) {",
            "    trace_failure(request, error.what());",
            "    return ROCM_INTERFACES_STATUS_PROVIDER_FAILURE;",
            "  } catch (...) {",
            '    trace_failure(request, "unknown canonical rocBLAS backend failure");',
            "    return ROCM_INTERFACES_STATUS_PROVIDER_FAILURE;",
            "  }",
            "  response->header = {sizeof(*response), ROCM_INTERFACES_ABI_MAJOR,",
            "                      ROCM_INTERFACES_ABI_MINOR};",
            '  response->provider_id = "system-rocblas-bridge";',
            '  response->build_id = "interfaces-real-v1";',
            "  response->dispatch_table = &table;",
            "  response->dispatch_table_size = sizeof(table);",
            "  response->capability_mask = 0;",
            "  return backend_handle ? ROCM_INTERFACES_STATUS_SUCCESS",
            "                        : ROCM_INTERFACES_STATUS_PROVIDER_FAILURE;",
            "}",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def zero_argument(parameter: Parameter) -> str:
    if parameter.type == "rocblas_handle":
        return "nullptr"
    return "{}"


def write_link_test(functions: list[Function], path: Path) -> None:
    lines = [
        "// Generated by generate_rocblas_bridge.py. Do not edit.",
        "#include <rocblas/rocblas.h>",
        "",
        "#include <cstddef>",
        "",
        "int main() {",
    ]
    for function in functions:
        lines.append(f"  (void)&{function.name};")
    for function in functions:
        if not function.has_handle or function.name in CUSTOM_FACADE:
            continue
        arguments = ", ".join(
            zero_argument(parameter) for parameter in function.parameters
        )
        if function.return_type == "rocblas_status":
            lines.extend(
                [
                    f"  if ({function.name}({arguments}) != rocblas_status_invalid_handle)",
                    "    return 1;",
                ]
            )
        elif function.return_type == "bool":
            lines.extend([f"  if ({function.name}({arguments}))", "    return 2;"])
    lines.extend(["  return 0;", "}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def write_version_script(functions: list[Function], path: Path) -> None:
    lines = ["ROCBLAS_ABI_5 {", "  global:"]
    lines.extend(f"    {function.name};" for function in functions)
    lines.extend(["  local:", "    *;", "};", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def write_exports(functions: list[Function], path: Path) -> None:
    path.write_text(
        "\n".join(function.name for function in functions) + "\n", encoding="utf-8"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--snapshot", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    functions = load_functions(args.snapshot)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    write_header(functions, args.output_dir / "rocblas_bridge_generated.h")
    write_facade(functions, args.output_dir / "rocblas_bridge_facade.cpp")
    write_provider(functions, args.output_dir / "rocblas_bridge_provider.cpp")
    write_forwarding_provider(
        functions, args.output_dir / "rocblas_forwarding_provider.cpp"
    )
    write_link_test(functions, args.output_dir / "rocblas_bridge_link_test.cpp")
    write_version_script(functions, args.output_dir / "rocblas_bridge.map")
    write_exports(functions, args.output_dir / "rocblas_bridge.exports")


if __name__ == "__main__":
    main()
