#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

"""Generate the C++ FMHA featurizer from the Python FmhaFeatureEngine.

The dispatcher must produce, at inference, the SAME 69-feature vector the Python
FmhaFeatureEngine.extract() produces at train time -- byte-identical, or the
model scores inputs that don't mean what it trained on. Rather than hand-port
extract() (drift-prone), this script emits the C++ featurizer from a single
source of the formulas here, and a Python<->C++ round-trip test
(test_fmha_featurizer_roundtrip.py) gates that they agree exactly.

The emitted C++ mirrors extract() (feature_engine.py) term-for-term and in the
SAME operation order (floating-point + is not associative, so order matters for
bit-identity). The two dtype lookup tables are emitted from the Python dicts, not
retyped.

Emits:
  <out>/FmhaFeatures.hpp   -- named-field struct + to_array() (feature_spec order)
  <out>/FmhaFeaturizer.hpp -- featurize(problem, instance-knobs, hw) -> FmhaFeatures

Usage:
  python -m rocke.heuristics.gen_fmha_featurizer -o <dispatcher/sdpa_fwd dir>
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# The 69 feature names in order -- pulled live from the engine so the struct and
# array order can never diverge from the training contract.
from feature_engine import FMHA_DTYPE_MAP, FmhaFeatureEngine  # noqa: E402


def _dtype_bytes_cpp() -> str:
    # Mirrors _fmha_dtype_bytes: fp32->4, fp8/bf8->1, else 2.
    return """\
inline double fmha_dtype_bytes(const std::string& dt) {
    if (dt == "fp32") return 4.0;
    if (dt == "fp8" || dt == "bf8") return 1.0;
    return 2.0;
}"""


def _dtype_enc_cpp() -> str:
    # Emitted from FMHA_DTYPE_MAP (not retyped): default 0 for unknown.
    arms = "\n".join(
        f'    if (dt == "{k}") return {int(v)}.0;' for k, v in FMHA_DTYPE_MAP.items()
    )
    return f"""\
inline double fmha_dtype_enc(const std::string& dt) {{
{arms}
    return 0.0;
}}"""


def emit_features_struct(names: list[str]) -> str:
    fields = "\n".join(f"    double {n} = 0.0;" for n in names)
    inits = ",\n".join(f"        {n}" for n in names)
    return f"""\
// GENERATED by rocke gen_fmha_featurizer.py -- DO NOT EDIT.
// Named-field mirror of FmhaFeatureEngine.get_feature_names() ({len(names)} feats).
#pragma once
#include <array>

namespace rocke_client::dispatcher {{

struct FmhaFeatures {{
{fields}

    static constexpr int kNumFeatures = {len(names)};

    // Flatten to the model's double[] in feature_spec.json order.
    std::array<double, kNumFeatures> to_array() const {{
        return {{
{inits}
        }};
    }}
}};

}}  // namespace rocke_client::dispatcher
"""


def emit_featurizer() -> str:
    # The body mirrors extract() (feature_engine.py:755-923) term-for-term and in
    # the same operation order. Inputs:
    #   prob: FmhaProblemInputs (batch, sq, sk, hq, hk, dq, dv, dtype)
    #   cfg:  FmhaConfigInputs (pip, tm0, tn0, tk0, tn1, tk1, tk0max, num_warps,
    #         ps, psk, pd, pdv, mask, bias, lse, dropout, logits, sink, skip,
    #         qscale, paged)
    #   hw:   HardwareProfile
    return """\
// GENERATED by rocke gen_fmha_featurizer.py -- DO NOT EDIT.
// Mirrors FmhaFeatureEngine.extract() term-for-term (same op order for bit
// identity). Gated by test_fmha_featurizer_roundtrip.py.
#pragma once
#include <algorithm>
#include <cmath>
#include <string>

#include "dispatcher/sdpa_fwd/FmhaFeatures.hpp"

namespace rocke_client::dispatcher {

inline double fmha_dtype_bytes(const std::string& dt) {
    if (dt == "fp32") return 4.0;
    if (dt == "fp8" || dt == "bf8") return 1.0;
    return 2.0;
}
inline double fmha_dtype_enc(const std::string& dt) {
    if (dt == "fp16") return 0.0;
    if (dt == "f16") return 0.0;
    if (dt == "bf16") return 1.0;
    return 0.0;
}

// Raw problem-shape inputs (from SdpaProblem).
struct FmhaProblemInputs {
    double batch = 0, sq = 0, sk = 0, hq = 0, hk = 0, dq = 0, dv = 0;
    std::string dtype = "fp16";
};
// Raw config/knob inputs (from AotInstance + arch defaults).
struct FmhaConfigInputs {
    double pip = 1, tm0 = 16, tn0 = 0, tk0 = 0, tn1 = 0, tk1 = 0, tk0max = 0;
    double num_warps = 1;
    double ps = 0, psk = 0, pd = 0, pdv = 0, mask = 0, bias = 0, lse = 0;
    double dropout = 0, logits = 0, sink = 0, skip = 0, qscale = 0, paged = 1;
};
// hw fields (name-matched to FmhaFeatureEngine._hw).
struct FmhaHwInputs {
    double num_cus = 0, simds_per_cu = 4, total_simds = 0, shader_engines = 0;
    double max_clock_mhz = 0, wavefront_size = 64, lds_capacity = 0, num_xcd = 0;
};

inline FmhaFeatures fmha_featurize(const FmhaProblemInputs& p,
                                   const FmhaConfigInputs& c,
                                   const FmhaHwInputs& hw) {
    const double batch = p.batch, sq = p.sq, sk = p.sk, hq = p.hq;
    const double hk = std::max(p.hk, 1.0);
    const double dq = p.dq;
    const double dv = (p.dv != 0.0 ? p.dv : dq);
    const double bpe = fmha_dtype_bytes(p.dtype);
    const double dt_enc = fmha_dtype_enc(p.dtype);

    auto l2 = [](double x) { return std::log2(std::max(x, 1.0)); };

    const double gqa = hq / hk;
    const double asp = sq / std::max(sk, 1.0);
    const double ops = 2.0 * batch * hq * sq * sk * (dq + dv);
    const double mem = (batch * hq * sq * dq
                        + batch * hk * sk * dq
                        + batch * hk * sk * dv
                        + batch * hq * sq * dv) * bpe;
    const double ai = ops / std::max(mem, 1.0);
    const double decode = (sq <= 1.0) ? 1.0 : 0.0;

    const double pip = c.pip, tm0 = c.tm0, tn0 = c.tn0;
    const double tk0 = (c.tk0 != 0.0 ? c.tk0 : dq);
    const double tn1 = (c.tn1 != 0.0 ? c.tn1 : dv);
    const double tk1 = (c.tk1 != 0.0 ? c.tk1 : tn0);
    const double tk0max = (c.tk0max != 0.0 ? c.tk0max : tk0);
    const double num_warps = c.num_warps;

    const double ps = c.ps, psk = c.psk, pd = c.pd, pdv = c.pdv;
    const double mask = c.mask, bias = c.bias, lse = c.lse, dropout = c.dropout;
    const double logits = c.logits, sink = c.sink, skip = c.skip;
    const double qscale = c.qscale, paged = c.paged;

    const double ntm = std::ceil(sq / std::max(tm0, 1.0));
    const double ntk = std::ceil(sk / std::max(tn0, 1.0));
    const double tot = batch * hq * ntm * ntk;

    auto eff = [](double d, double t) -> double {
        if (t <= 0.0) return 1.0;
        double r = std::fmod(d, t);
        return (r > 0.0) ? r / t : 1.0;
    };
    const double esq = eff(sq, tm0);
    const double esk = eff(sk, tn0);
    const double oeff = esq * esk;
    const double cu = tot / std::max(hw.num_cus, 1.0);
    const double tvol = tm0 * tn0 * tk0;
    const double tarea = tm0 * tn0;
    const double lds = (tm0 * tk0 + tn0 * tk0) * bpe;
    const double ldsr = lds / std::max(hw.lds_capacity, 1.0);
    const double rdk0 = dq / std::max(tk0, 1.0);
    const double rdn1 = (tn1 > 0.0) ? dv / tn1 : 0.0;
    const double sq1 = (sq <= tm0) ? 1.0 : 0.0;
    const double sk1 = (sk <= tn0) ? 1.0 : 0.0;
    const double deq = (dq == dv) ? 1.0 : 0.0;
    const double gqa_f = (hq != hk) ? 1.0 : 0.0;
    const double totq = batch * hq * sq * dq;
    const double totkv = batch * hk * sk * (dq + dv);
    const double fc = lse + dropout + logits + sink + skip + paged
                      + ((mask > 0.0) ? 1.0 : 0.0)
                      + ((bias > 0.0) ? 1.0 : 0.0);

    FmhaFeatures f;
    f.batch = batch; f.seqlen_q = sq; f.seqlen_k = sk;
    f.nhead_q = hq; f.nhead_k = hk; f.hdim_q = dq; f.hdim_v = dv;
    f.dtype_enc = dt_enc;
    f.log2_batch = l2(batch); f.log2_seqlen_q = l2(sq); f.log2_seqlen_k = l2(sk);
    f.log2_nhead_q = l2(hq); f.log2_nhead_k = l2(hk);
    f.log2_hdim_q = l2(dq); f.log2_hdim_v = l2(dv);
    f.gqa_ratio = gqa; f.aspect_sq_sk = asp; f.log2_ops = l2(ops);
    f.arithmetic_intensity = ai; f.decode_flag = decode;
    f.pipeline_code = pip; f.tile_m0 = tm0; f.tile_n0 = tn0; f.tile_k0 = tk0;
    f.tile_n1 = tn1; f.tile_k1 = tk1; f.tile_k0max = tk0max;
    f.pad_s = ps; f.pad_sk = psk; f.pad_d = pd; f.pad_dv = pdv;
    f.mask = mask; f.bias = bias; f.lse = lse; f.dropout = dropout;
    f.logits = logits; f.sink = sink; f.skip = skip; f.qscale = qscale;
    f.paged = paged;
    f.num_tiles_m = ntm; f.num_tiles_k = ntk; f.total_tiles = tot;
    f.tile_eff_sq = esq; f.tile_eff_sk = esk; f.overall_tile_efficiency = oeff;
    f.cu_utilization = cu; f.tile_volume = tvol; f.tile_area = tarea;
    f.lds_usage_estimate = lds; f.lds_usage_ratio = ldsr;
    f.ratio_d_to_tk0 = rdk0; f.ratio_dv_to_tn1 = rdn1;
    f.sq_le_tm0 = sq1; f.sk_le_tn0 = sk1; f.d_eq_dv = deq; f.gqa_flag = gqa_f;
    f.total_q_elems = totq; f.total_kv_elems = totkv; f.feature_count = fc;
    f.hw_num_cus = hw.num_cus; f.hw_simds_per_cu = hw.simds_per_cu;
    f.hw_total_simds = hw.total_simds; f.hw_shader_engines = hw.shader_engines;
    f.hw_max_clock_mhz = hw.max_clock_mhz; f.hw_wavefront_size = hw.wavefront_size;
    f.hw_lds_capacity = hw.lds_capacity; f.hw_num_xcd = hw.num_xcd;
    f.num_warps = num_warps;
    return f;
}

}  // namespace rocke_client::dispatcher
"""


def generate(out_dir: Path) -> list[str]:
    names = FmhaFeatureEngine().get_feature_names()
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "FmhaFeatures.hpp").write_text(emit_features_struct(names))
    (out_dir / "FmhaFeaturizer.hpp").write_text(emit_featurizer())
    return names


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "-o",
        "--out-dir",
        type=Path,
        required=True,
        help="dispatcher/sdpa_fwd dir for FmhaFeatures.hpp/FmhaFeaturizer.hpp",
    )
    args = ap.parse_args(argv)
    names = generate(args.out_dir)
    print(
        f"featurizer: {len(names)} features -> {args.out_dir}/"
        "FmhaFeatures.hpp, FmhaFeaturizer.hpp",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
