#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

"""Generate C++ hardware profile supplement data from Python HW_PROFILES.

Emits HardwareProfileSupplements.hpp with fields HIP cannot query:
- shader_engines, num_xcd, simds_per_cu, max_waves_per_cu
- l1_cache_kb, l2_cache_kb, l3_cache_kb

Fields HIP CAN query (num_cus, max_clock_mhz, wavefront_size, lds_capacity)
are populated at runtime via hipGetDeviceProperties and NOT included in the
generated supplement.

Usage:
  python -m rocke.heuristics.gen_hw_profiles -o <dispatcher dir>
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

# Import the authoritative HW_PROFILES from gen_sweep_data
from .gen_sweep_data import HW_PROFILES


# Fields that HIP can query (excluded from supplement)
HIP_QUERYABLE_FIELDS = {
    "hw_num_cus",  # hipDeviceProp_t::multiProcessorCount
    "hw_max_clock_mhz",  # hipDeviceProp_t::clockRate / 1000
    "hw_wavefront_size",  # hipDeviceProp_t::warpSize
    "hw_lds_capacity",  # hipDeviceProp_t::sharedMemPerBlock
}

# Fields that must come from supplement (HIP doesn't expose them)
SUPPLEMENT_FIELDS = [
    "hw_shader_engines",
    "hw_num_xcd",
    "hw_simds_per_cu",
    "hw_max_waves_per_cu",
    "hw_l1_cache_kb",
    "hw_l2_cache_kb",
    "hw_l3_cache_kb",
]


def _compute_checksum(archs: list[str]) -> str:
    """Compute a checksum of HW_PROFILES supplement data for validation."""
    # Extract only supplement fields in sorted order for deterministic hash
    data = {}
    for arch in sorted(archs):
        profile = HW_PROFILES[arch]
        data[arch] = {field: profile[field] for field in SUPPLEMENT_FIELDS}

    # Serialize to JSON with sorted keys for deterministic output
    serialized = json.dumps(data, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(serialized.encode()).hexdigest()[:16]


def _emit_header(archs: list[str]) -> str:
    """Generate the HardwareProfileSupplements.hpp header."""

    checksum = _compute_checksum(archs)

    # Build supplement struct values for each arch
    supplement_inits = []
    for arch in sorted(archs):
        profile = HW_PROFILES[arch]
        values = [str(profile[field]) for field in SUPPLEMENT_FIELDS]
        supplement_inits.append(
            f"constexpr HardwareProfileSupplement k{arch.capitalize()}Supplement = "
            f"{{{', '.join(values)}}};"
        )

    # Build getSupplement() if-chain
    get_supplement_cases = []
    for arch in sorted(archs):
        get_supplement_cases.append(
            f'    if (arch == "{arch}") return &k{arch.capitalize()}Supplement;'
        )

    return f"""\
// GENERATED by rocke gen_hw_profiles.py -- DO NOT EDIT.
// Hardware profile supplement data for fields hipGetDeviceProperties cannot query.
// Source: rocke/platform/python/rocke/heuristics/gen_sweep_data.py HW_PROFILES
//
// To regenerate after updating HW_PROFILES:
//   cd build && cmake --build . --target rocke_regenerate_hw_profiles
//
// Commit both gen_sweep_data.py and this generated file together.
//
// Checksum: {checksum}
// (First 16 hex digits of SHA256 of supplement data. Tests verify this matches
// the Python source to catch stale generated files.)
#pragma once
#include <string>

namespace rocke_client::dispatcher {{

// Checksum of HW_PROFILES supplement data for drift detection
constexpr const char* kSupplementChecksum = "{checksum}";

// Supplement data for fields HIP doesn't expose
struct HardwareProfileSupplement {{
    int shader_engines;
    int num_xcd;
    int simds_per_cu;
    int max_waves_per_cu;
    int l1_cache_kb;
    int l2_cache_kb;
    int l3_cache_kb;
}};

// Arch-specific supplement tables (from Python HW_PROFILES)
{chr(10).join(supplement_inits)}

inline const HardwareProfileSupplement* getSupplement(const std::string& arch) {{
{chr(10).join(get_supplement_cases)}
    return nullptr; // unknown arch
}}

}}  // namespace rocke_client::dispatcher
"""


def generate(out_dir: Path) -> None:
    """Generate HardwareProfileSupplements.hpp."""
    out_dir.mkdir(parents=True, exist_ok=True)

    # Validate that all archs have the required fields
    for arch, profile in HW_PROFILES.items():
        missing = [f for f in SUPPLEMENT_FIELDS if f not in profile]
        if missing:
            raise ValueError(
                f"HW_PROFILES[{arch!r}] missing required fields: {missing}"
            )

    archs = list(HW_PROFILES.keys())
    header_content = _emit_header(archs)

    out_path = out_dir / "HardwareProfileSupplements.hpp"
    out_path.write_text(header_content)
    print(f"Generated {out_path} with {len(archs)} arch supplements", file=sys.stderr)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "-o",
        "--out-dir",
        type=Path,
        required=True,
        help="Output directory for HardwareProfileSupplements.hpp",
    )
    args = ap.parse_args(argv)
    generate(args.out_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
