#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

"""Generate the C model registry from committed Route-A predictors.

Each committed predictor (lgbm_to_c output) exports a unique symbol
``rocke_score_<op>_<dtype>_<arch>_tflops`` and a ``..._NUM_FEATURES`` define, so
many models statically link into one dispatcher binary. This script scans a
``dispatcher/models/`` tree for those predictors and emits:

    rocke_model_registry.h   -- RockeModelEntry + rocke_lookup_model() decl
    rocke_model_registry.c   -- extern decls + the static table + lookup

The registry is keyed by (op, arch, dtype) -- exactly what the dispatcher has at
select time (SdpaProblem.op/arch + CompileSpec.dtype). Each entry carries
``num_features`` so the caller can assert the predictor's width equals the
featurizer's output and FAIL LOUD on drift (a feature added to an op but the
predictor not regenerated) rather than silently score a wrong-width vector.

Model metadata comes from a sidecar ``<predictor>.meta.json`` written next to the
committed .c (op/arch/dtype/num_features/symbol), so the scan needs no C parsing
and no filename convention. Run this whenever a predictor is added/updated.

Usage:
    python -m rocke.heuristics.gen_model_registry MODELS_DIR [-o OUT_DIR]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import List


# The pipeline trains with its canonical op token ("fmha"), but the dispatcher
# queries the registry with the op token it derives from the graph
# (SdpaProblem.op == "sdpa_fwd"). The registry is the dispatcher-side artifact, so
# it must speak the dispatcher's vocabulary: alias the pipeline op -> dispatcher
# op at generation time. Without this, rocke_lookup_model("sdpa_fwd",...) misses
# an "fmha" entry and the model tie-break silently never fires (first-match).
_OP_ALIASES = {"fmha": "sdpa_fwd"}


def _dispatcher_op(pipeline_op: str) -> str:
    return _OP_ALIASES.get(pipeline_op, pipeline_op)


def _discover(models_dir: Path) -> List[dict]:
    """Find every predictor meta sidecar under models_dir; return sorted entries.

    A predictor contributes an entry iff a ``*.meta.json`` sits beside its .c with
    keys: symbol, op, arch, dtype, num_features. The op is aliased to the
    dispatcher's token (see _OP_ALIASES). Sorting by (op, arch, dtype) makes the
    generated table deterministic (stable diffs, reproducible builds).
    """
    entries: List[dict] = []
    for meta_path in sorted(models_dir.rglob("*.meta.json")):
        meta = json.loads(meta_path.read_text())
        for key in ("symbol", "op", "arch", "dtype", "num_features"):
            if key not in meta:
                raise ValueError(f"{meta_path}: missing required key {key!r}")
        meta = dict(meta)
        meta["op"] = _dispatcher_op(str(meta["op"]))  # pipeline op -> dispatcher op
        entries.append(meta)
    entries.sort(key=lambda m: (m["op"], m["arch"], m["dtype"]))
    return entries


def _emit_header() -> str:
    return """\
// GENERATED by rocke gen_model_registry.py -- DO NOT EDIT.
#ifndef ROCKE_MODEL_REGISTRY_H
#define ROCKE_MODEL_REGISTRY_H

#ifdef __cplusplus
extern "C" {
#endif

// Raw booster score for one candidate; f[] is the op's feature vector in
// feature_spec.json order, length == num_features. Log-space (monotone) -- exact
// for argmax; apply expm1 for a physical value.
typedef double (*RockeScoreFn)(const double* f);

typedef struct {
    const char*  op;            // "fmha", "gemm_universal", ...
    const char*  arch;          // "gfx950", "gfx942", ...
    const char*  dtype;         // "fp16", "bf16", "fp8", ...
    RockeScoreFn score;         // the compiled predictor entry point
    int          num_features;  // MUST equal the op featurizer's output length
} RockeModelEntry;

// Look up the predictor for (op, arch, dtype). Returns NULL when none is
// registered -- callers fall back to Phase-1 first-match. The caller MUST also
// verify entry->num_features == featurizer_output_len before scoring and treat a
// mismatch as "no model" (fail loud), so a feature-contract drift can never feed
// a wrong-width vector to a stale predictor.
const RockeModelEntry* rocke_lookup_model(const char* op,
                                          const char* arch,
                                          const char* dtype);

// Number of registered models (for tests / diagnostics).
int rocke_model_count(void);

#ifdef __cplusplus
}
#endif

#endif  // ROCKE_MODEL_REGISTRY_H
"""


def _emit_source(entries: List[dict]) -> str:
    lines: List[str] = []
    lines.append("// GENERATED by rocke gen_model_registry.py -- DO NOT EDIT.")
    lines.append('#include "rocke_model_registry.h"')
    lines.append("")
    lines.append("#include <string.h>")
    lines.append("")
    if not entries:
        lines.append("// No predictors committed yet: empty registry (dispatcher")
        lines.append("// falls back to Phase-1 first-match for every graph).")
    # extern decls for each predictor symbol (defined in its committed .c).
    for e in entries:
        lines.append(f"extern double {e['symbol']}(const double* f);")
    lines.append("")
    if entries:
        lines.append("static const RockeModelEntry kModels[] = {")
        for e in entries:
            lines.append(
                f'    {{ "{e["op"]}", "{e["arch"]}", "{e["dtype"]}", '
                f'{e["symbol"]}, {int(e["num_features"])} }},'
            )
        lines.append("};")
    else:
        # Zero-length arrays are non-standard (trips -Wpedantic -Werror); emit a
        # size-1 zero sentinel and a count of 0 so the lookup loop never reads it.
        lines.append(
            "static const RockeModelEntry kModels[1] = " "{ { 0, 0, 0, 0, 0 } };"
        )
    lines.append("")
    # Count emitted as a literal (known at generation time): no cast, warning-
    # clean under the strict C++ flags, valid in both C and C++.
    lines.append(f"static const int kModelCount = {len(entries)};")
    lines.append("")
    lines.append("int rocke_model_count(void) { return kModelCount; }")
    lines.append("")
    lines.append("const RockeModelEntry* rocke_lookup_model(const char* op,")
    lines.append("                                          const char* arch,")
    lines.append("                                          const char* dtype)")
    lines.append("{")
    lines.append("    if (!op || !arch || !dtype) return 0;")
    lines.append("    for (int i = 0; i < kModelCount; ++i) {")
    lines.append("        const RockeModelEntry* m = &kModels[i];")
    lines.append("        if (strcmp(m->op, op) == 0 && strcmp(m->arch, arch) == 0")
    lines.append("            && strcmp(m->dtype, dtype) == 0) {")
    lines.append("            return m;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return 0;  // no model for this key -> caller uses Phase-1")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate(models_dir: Path, out_dir: Path) -> List[dict]:
    entries = _discover(models_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "rocke_model_registry.h").write_text(_emit_header())
    (out_dir / "rocke_model_registry.c").write_text(_emit_source(entries))
    return entries


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "models_dir", type=Path, help="dispatcher/models tree to scan for *.meta.json"
    )
    ap.add_argument(
        "-o",
        "--out-dir",
        type=Path,
        default=None,
        help="where to write the registry .c/.h (default: models_dir)",
    )
    args = ap.parse_args(argv)
    out_dir = args.out_dir or args.models_dir
    entries = generate(args.models_dir, out_dir)
    print(
        f"registry: {len(entries)} model(s) -> {out_dir}/rocke_model_registry.[ch]",
        file=sys.stderr,
    )
    for e in entries:
        print(
            f"    {e['op']:16} {e['arch']:8} {e['dtype']:5} "
            f"nfeat={e['num_features']} sym={e['symbol']}",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
