#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

"""Generate per-arch tiled-spec default headers from the kernel dataclasses.

The base AotInstance carries only the knobs common across arches (dtype, shape,
tileSize, numWarps, ...). Arch-specific knobs (use_iglp_opt, kv_ring_depth, ...)
live on each arch's UnifiedAttention2DTiledSpec and, until arch-specific instance
subclasses exist, must be defaulted to the arch's own value. That default IS the
dataclass field default, so this script introspects each arch's
attention_tiled_2d.py and emits a C++ header of those defaults -- single source,
no hand-mirroring, no drift.

Only fields with a literal default are emitted (bool/int/float/str/None). The 8
required fields (head_size, block_size, ... -- problem-derived, no default) are
skipped: they come from the problem, not a static default.

Emits: <out>/<arch>/TiledSpecDefaults.hpp

Usage:
  python -m rocke.heuristics.gen_arch_tiled_defaults \\
      --kernels-root <.../rocke/library/kernels> \\
      --out-root <.../dispatcher/sdpa_fwd> \\
      --arch gfx942 gfx950 gfx1250
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path
from typing import Any


def _extract_defaults(spec_path: Path) -> list[tuple[str, Any]]:
    """Return [(field, literal_default)] for UnifiedAttention2DTiledSpec, in
    declaration order. Fields without a default (problem-derived) are skipped."""
    tree = ast.parse(spec_path.read_text())
    cls = next(
        (n for n in ast.walk(tree)
         if isinstance(n, ast.ClassDef) and n.name == "UnifiedAttention2DTiledSpec"),
        None,
    )
    if cls is None:
        raise ValueError(f"{spec_path}: UnifiedAttention2DTiledSpec not found")
    out: list[tuple[str, Any]] = []
    for x in cls.body:
        if isinstance(x, ast.AnnAssign) and isinstance(x.target, ast.Name):
            if x.value is None:
                continue  # required (problem-derived) field, no static default
            try:
                out.append((x.target.id, ast.literal_eval(x.value)))
            except (ValueError, SyntaxError):
                # Non-literal default (shouldn't happen today); skip loudly.
                print(f"  WARN {spec_path.parent.name}.{x.target.id}: "
                      "non-literal default skipped", file=sys.stderr)
    return out


def _cpp_value(v: Any) -> tuple[str, str]:
    """(c++ type, c++ literal) for a python literal default."""
    if isinstance(v, bool):
        return "bool", "true" if v else "false"
    if isinstance(v, int):
        return "int", str(v)
    if isinstance(v, float):
        return "double", repr(v)
    if v is None:
        # Optional[...] defaults (e.g. kv_storage_dtype=None / tile_size=None):
        # represent as an empty-string sentinel; consumers treat "" as unset.
        return "const char*", '""'
    if isinstance(v, str):
        return "const char*", f'"{v}"'
    raise TypeError(f"unhandled default type {type(v)}: {v!r}")


def emit_header(arch: str, defaults: list[tuple[str, Any]]) -> str:
    lines: list[str] = []
    lines.append("// GENERATED by rocke gen_arch_tiled_defaults.py -- DO NOT EDIT.")
    lines.append(f"// Per-arch tiled-spec knob defaults for {arch}, introspected")
    lines.append(f"// from kernels/{arch}/attention_tiled_2d.py "
                 "UnifiedAttention2DTiledSpec.")
    lines.append("// Used to default arch-specific knobs not carried on the base")
    lines.append("// AotInstance until arch-specific instance subclasses exist.")
    lines.append("#pragma once")
    lines.append("")
    guard_arch = arch.replace("-", "_")
    lines.append(f"namespace rocke_client::dispatcher::{guard_arch}_defaults {{")
    lines.append("")
    for name, val in defaults:
        ctype, cval = _cpp_value(val)
        lines.append(f"inline constexpr {ctype} {name} = {cval};"
                     if ctype != "const char*"
                     else f"inline constexpr {ctype} {name} = {cval};")
    lines.append("")
    lines.append(f"}}  // namespace rocke_client::dispatcher::{guard_arch}_defaults")
    lines.append("")
    return "\n".join(lines)


def generate(kernels_root: Path, out_root: Path, arches: list[str]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for arch in arches:
        spec = kernels_root / arch / "attention_tiled_2d.py"
        if not spec.is_file():
            print(f"  SKIP {arch}: {spec} not found", file=sys.stderr)
            continue
        defaults = _extract_defaults(spec)
        out_dir = out_root / arch
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "TiledSpecDefaults.hpp").write_text(emit_header(arch, defaults))
        counts[arch] = len(defaults)
    return counts


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--kernels-root", type=Path, required=True,
                    help=".../rocke/library/kernels")
    ap.add_argument("--out-root", type=Path, required=True,
                    help=".../dispatcher/sdpa_fwd (per-arch subdirs created)")
    ap.add_argument("--arch", nargs="+", default=["gfx942", "gfx950", "gfx1250"])
    args = ap.parse_args(argv)
    counts = generate(args.kernels_root, args.out_root, args.arch)
    for arch, n in counts.items():
        print(f"  {arch}: {n} default knobs -> {args.out_root}/{arch}/"
              "TiledSpecDefaults.hpp", file=sys.stderr)
    return 0 if counts else 1


if __name__ == "__main__":
    sys.exit(main())
