"""Emit a LightGBM regression booster as standalone C (no liblightgbm at runtime).

The FMHA tie-break dispatcher wants to score kernel candidates without linking
liblightgbm.so / libgomp. A plain regression booster is just a sum of decision
trees whose splits are all numeric ``<=`` tests, so it lowers cleanly to nested
if/else C: one function per tree, a top-level function that sums them.

Contract / caveats:
- Only ``regression`` boosters with numeric (``<=``) splits are supported. A
  categorical split raises -- the emitter refuses rather than emit a wrong
  predictor. (Our FMHA models have no categorical splits in practice; the
  declared-categorical columns don't vary enough to split on.)
- The emitted function returns the RAW booster sum (log-space when the model was
  trained on log1p targets). For ranking/argmax this is exactly right: expm1 is
  monotonic, so the argmax kernel is identical with or without the inverse. A
  caller that needs a physical TFLOPS value applies expm1 itself (mirrors the
  existing C++ ``MLHeuristic`` ``log_t_`` handling).
- Features are read from a ``const double* f`` in ``feature_spec.json`` order;
  the caller's featurizer must fill ``f`` in that same order (idx 0..N-1).
- Missing values follow LightGBM's ``default_left``: a NaN goes left when
  default_left is true. We emit ``!(f[i] > thr)`` so NaN (where both ``>`` and
  ``<=`` are false) takes the same branch LightGBM's default_left=true uses.
  When default_left is false we emit ``(f[i] <= thr)`` so NaN goes right.
"""

from __future__ import annotations

from typing import Any


class UnsupportedModelError(ValueError):
    """Raised when a booster can't be lowered to pure numeric if/else C."""


def _emit_node(node: dict[str, Any], out: list[str], indent: str) -> None:
    """Recursively emit one tree node as C into ``out``."""
    if "leaf_value" in node:
        out.append(f"{indent}return {float(node['leaf_value']):.17g};")
        return

    dtype = node.get("decision_type")
    if dtype != "<=":
        raise UnsupportedModelError(
            f"unsupported split decision_type {dtype!r} (only numeric '<=' "
            "splits lower to C; a categorical split needs different codegen)"
        )

    fidx = int(node["split_feature"])
    thr = float(node["threshold"])
    default_left = bool(node.get("default_left", False))

    # LightGBM: a sample goes LEFT when (f <= threshold). Missing (NaN) goes to
    # default_left's side. NaN comparisons are all false, so:
    #   default_left=True  -> want NaN left  -> test !(f > thr) (true for NaN)
    #   default_left=False -> want NaN right -> test (f <= thr) (false for NaN)
    if default_left:
        cond = f"!(f[{fidx}] > {thr:.17g})"
    else:
        cond = f"(f[{fidx}] <= {thr:.17g})"

    out.append(f"{indent}if ({cond}) {{")
    _emit_node(node["left_child"], out, indent + "    ")
    out.append(f"{indent}}} else {{")
    _emit_node(node["right_child"], out, indent + "    ")
    out.append(f"{indent}}}")


def booster_to_c(
    dumped: dict[str, Any],
    func_name: str,
    *,
    num_features: int,
    source_note: str = "",
) -> str:
    """Lower a ``Booster.dump_model()`` dict to a C source string.

    Parameters
    ----------
    dumped : dict
        The output of ``lgb.Booster.dump_model()``.
    func_name : str
        Name of the top-level scoring function, e.g.
        ``rocke_fmha_score_fp16_gfx950_tflops``.
    num_features : int
        Expected feature-vector length (feature_spec.json order). Emitted as a
        ``#define`` so the caller can static-assert its featurizer agrees.
    source_note : str
        Free-text provenance (model id, rocke sha, feature_spec hash) embedded in
        the header comment for traceability.
    """
    objective = str(dumped.get("objective", ""))
    if not objective.startswith("regression"):
        raise UnsupportedModelError(
            f"objective {objective!r} not supported (only 'regression'); ranking "
            "argmax requires a real-valued per-candidate score"
        )

    trees = dumped["tree_info"]
    lines: list[str] = []
    lines.append("// GENERATED by rocke heuristics lgbm_to_c.py -- DO NOT EDIT.")
    lines.append("// Regenerate by retraining the model through the pipeline.")
    if source_note:
        for ln in source_note.splitlines():
            lines.append(f"// {ln}")
    lines.append("//")
    lines.append("// Returns the RAW booster sum (log-space if trained on log1p);")
    lines.append("// monotonic, so argmax over candidates is exact. Apply expm1 for a")
    lines.append("// physical value. Features are read from f[] in feature_spec order.")
    lines.append("")
    lines.append(f"#define {func_name.upper()}_NUM_FEATURES {int(num_features)}")
    lines.append("")

    # Per-tree functions (static: internal linkage, one predictor per TU).
    for t in trees:
        idx = int(t["tree_index"])
        body: list[str] = []
        _emit_node(t["tree_structure"], body, "    ")
        lines.append(f"static double {func_name}_tree_{idx}(const double* f) {{")
        lines.extend(body)
        lines.append("}")
        lines.append("")

    # Top-level: sum of all trees.
    lines.append(f"double {func_name}(const double* f) {{")
    lines.append("    double s = 0.0;")
    for t in trees:
        idx = int(t["tree_index"])
        lines.append(f"    s += {func_name}_tree_{idx}(f);")
    lines.append("    return s;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def booster_to_c_header(
    func_name: str, *, num_features: int, source_note: str = ""
) -> str:
    """Emit the matching ``.h`` (extern decl + feature-count define)."""
    guard = f"{func_name.upper()}_H"
    lines: list[str] = []
    lines.append("// GENERATED by rocke heuristics lgbm_to_c.py -- DO NOT EDIT.")
    if source_note:
        for ln in source_note.splitlines():
            lines.append(f"// {ln}")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append(f"#define {func_name.upper()}_NUM_FEATURES {int(num_features)}")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")
    lines.append("// Raw booster score (log-space; monotonic for argmax). f[] in")
    lines.append("// feature_spec.json order, length *_NUM_FEATURES.")
    lines.append(f"double {func_name}(const double* f);")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append(f"#endif  // {guard}")
    lines.append("")
    return "\n".join(lines)


def emit_c_predictor(
    booster: Any,
    func_name: str,
    *,
    num_features: int,
    source_note: str = "",
) -> tuple[str, str]:
    """Convenience: (c_source, h_source) from a live ``lgb.Booster``."""
    dumped = booster.dump_model()
    c_src = booster_to_c(
        dumped, func_name, num_features=num_features, source_note=source_note
    )
    h_src = booster_to_c_header(
        func_name, num_features=num_features, source_note=source_note
    )
    return c_src, h_src
