#!/usr/bin/env bash
# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT
#
# Pre-commit guard: refuses to commit compiled build artifacts that belong to
# the ck_dsl engine (projects/composablekernel/python/ck_dsl_c) or the
# ck-dsl-provider plugin. These artifacts are regenerated by every build and a
# stale one checked into the tree silently shadows a fresh build, producing
# phantom failures (e.g. a stale libckc_core.a used in place of a just-built
# one).
#
# A file is rejected when its repo-relative path is under one of the guarded
# trees AND it looks like a build product:
#   - any path component matching build*/ , cmake-build*/ , CMakeFiles/ ,
#     _deps/ , __pycache__/
#   - a CMakeCache.txt
#   - a *.a / *.o / *.so / *.dylib / *.dll / *.lib file
#   - a *.cpython-*.so compiled Python extension
#
# Intentionally-shipped kernel bundles are NOT artifacts and are allowed:
#   dnn-providers/ck-dsl-provider/kernels/<arch>/**/*.{hsaco,ll,json,co}
#   dnn-providers/ck-dsl-provider/kernels/<arch>/models/**/*.lgbm
#
# pre-commit passes the staged files as positional arguments. When run without
# arguments it inspects the current staged index, so it is also usable as a
# stand-alone check.
set -euo pipefail

# Trees whose build products must never be committed (repo-relative prefixes).
GUARDED_PREFIXES=(
  "projects/composablekernel/python/ck_dsl_c/"
  "dnn-providers/ck-dsl-provider/"
)

is_guarded() {
  local f="$1" pfx
  for pfx in "${GUARDED_PREFIXES[@]}"; do
    case "$f" in
      "$pfx"*) return 0 ;;
    esac
  done
  return 1
}

# Allow the intentionally-committed, regeneratable kernel bundles through.
is_allowed_bundle() {
  local f="$1"
  case "$f" in
    dnn-providers/ck-dsl-provider/kernels/*) return 0 ;;
  esac
  return 1
}

looks_like_artifact() {
  local f="$1"
  case "$f" in
    */build/*|build/*|*/build_*/*|build_*/*) return 0 ;;
    */cmake-build*/*|cmake-build*/*) return 0 ;;
    */CMakeFiles/*|CMakeFiles/*) return 0 ;;
    */_deps/*|_deps/*) return 0 ;;
    */__pycache__/*|__pycache__/*) return 0 ;;
    */CMakeCache.txt|CMakeCache.txt) return 0 ;;
  esac
  case "$f" in
    *.cpython-*.so) return 0 ;;
    *.a|*.o|*.so|*.dylib|*.dll|*.lib) return 0 ;;
  esac
  return 1
}

# Determine the file list: arguments from pre-commit, else the staged index.
declare -a FILES=()
if [ "$#" -gt 0 ]; then
  FILES=("$@")
else
  while IFS= read -r line; do
    [ -n "$line" ] && FILES+=("$line")
  done < <(git diff --cached --name-only --diff-filter=ACM 2>/dev/null || true)
fi

declare -a BAD=()
for f in "${FILES[@]}"; do
  is_guarded "$f" || continue
  is_allowed_bundle "$f" && continue
  if looks_like_artifact "$f"; then
    BAD+=("$f")
  fi
done

if [ "${#BAD[@]}" -gt 0 ]; then
  echo "ERROR: refusing to commit ck_dsl build artifacts (regenerated by every build):" >&2
  for f in "${BAD[@]}"; do
    echo "  $f" >&2
  done
  echo "" >&2
  echo "These are not source. Build products belong in a build directory, never" >&2
  echo "in the tree -- a stale one silently shadows a fresh build. Unstage them:" >&2
  echo "  git rm --cached <path>      # if already tracked" >&2
  echo "  git restore --staged <path> # if only staged" >&2
  echo "Shipped kernel bundles under kernels/<arch>/ are exempt and allowed." >&2
  exit 1
fi

exit 0
