# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT
#
# sparge_sage codegen. Launch chain: fused preprocess + Q/K quant -> mask prediction ->
# quantized sage attention.

import fnmatch
import os.path as path
from pathlib import Path
from typing import List, Optional, Tuple

GEN_DIR = ""


def update_file(file_path, content):
    existing = ""
    if path.exists(file_path):
        with open(file_path, "r") as f:
            existing = f.read()
    if existing == content:
        return
    with open(file_path, "w") as f:
        f.write(content)


# PERWARP: Q/K scale block 32/64. PERTENSOR: one global scale per (b,h) via a dedicated quant kernel.
KERNEL_CPP = """// SPDX-License-Identifier: MIT
// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// auto generated by generate.py  --api fwd_sparge_sage
#include "ck_tile/ops/fmha/block/variants.hpp"
#include "ck_tile/ops/sageattention/pipeline/tile_sageattn_shape.hpp"
#include "ck_tile/ops/sageattention/pipeline/tile_sageattn_traits.hpp"
#include "ck_tile/ops/sageattention/pipeline/block_sageattn_pipeline_problem.hpp"
#include "ck_tile/ops/epilogue.hpp"
#include "sparse_attn_fwd.hpp"
#include "kernel/fmha_fwd_sparge_sage_kernel.hpp"
#include <hip/hip_runtime.h>
#include <iostream>
#include <cstddef>

using cfg = {F_cfg};

using sage_block_tile = ck_tile::sequence<128, 128, 32, 128, 32, 128>;
using sage_shape = ck_tile::TileSageAttnShape<sage_block_tile,
                       ck_tile::sequence<4, 1, 1>,
                       ck_tile::sequence<32, 32, 32>,
                       ck_tile::sequence<4, 1, 1>,
                       ck_tile::sequence<32, 32, 32>,
                       true /*v rowmajor*/>;

// TileSageAttnTraits: spad, skpad, dpad, dvpad, qscale_enum, occupancy, skip_min_seqlen_q
using sage_traits = ck_tile::TileSageAttnTraits<true, true, true, true,
                       ck_tile::BlockSageAttentionQuantScaleEnum::{F_qscale_enum}, -1, false>;

using sage_variant = ck_tile::ComposedAttention<false * ck_tile::LOGITS_SOFT_CAP, true>;
using sage_mask = ck_tile::GenericAttentionMask<{F_mask_bool}>;

using sage_problem = ck_tile::BlockSageAttnPipelineProblem<
    cfg::QDataType, cfg::KDataType, cfg::VDataType,
    cfg::SaccDataType, cfg::SMPLComputeDataType, cfg::PDataType,
    cfg::OaccDataType, cfg::ODataType,
    sage_shape,
    {F_group_bool} /*group*/,
    sage_variant,
    sage_mask,
    sage_traits>;

using sage_pipeline = ck_tile::BlockFmhaPipelineQRKSVSAsyncSpargeSage<sage_problem>;

using sage_epilogue = ck_tile::Default2DEpilogue<
    ck_tile::Default2DEpilogueProblem<cfg::OaccDataType, cfg::ODataType, true, true>>;

using sage_kernel = ck_tile::FmhaFwdSpargeSageKernel<sage_pipeline, sage_epilogue,
                       ck_tile::BlockAttentionBiasEnum::{F_bias_enum}>;

using pp_fused_kernel = ck_tile::FmhaFwdSpargePreprocessFusedKernel<
    cfg::InputDataType, {F_group_bool}, 256,
    ck_tile::BlockSageAttentionQuantScaleEnum::{F_pp_qscale_enum}, cfg::QDataType>;
// Mask prediction, sort capacity multi-variant (256/512/1024) dispatched by seqlen.
template <ck_tile::index_t kMaxKBlocksPow2>
using mask_kernel_t = ck_tile::FmhaFwdSpargeMaskPredictionKernel<{F_group_bool}, kMaxKBlocksPow2, 256>;
// PERTENSOR: per-(b,h) global-absmax Q/K quant.
using qkquant_kernel = ck_tile::FmhaFwdSpargeQKQuantKernel<
    cfg::InputDataType, {F_group_bool}, 256, cfg::QDataType>;
static constexpr bool kIsPerTensor =
    ck_tile::BlockSageAttentionQuantScaleEnum::{F_qscale_enum} ==
    ck_tile::BlockSageAttentionQuantScaleEnum::PERTENSOR;

using sage_trait_ = fmha_sparge_sage_fwd_traits_<128, cfg::InputDataType,
                       ck_tile::BlockSageAttentionQuantScaleEnum::{F_qscale_enum},
                       {F_mask_bool}, {F_group_bool},
                       ck_tile::BlockAttentionBiasEnum::{F_bias_enum}, {F_qkfp8_bool}>;

template<>
float fmha_sparge_sage_fwd_<sage_trait_>(const ck_tile::stream_config& s,
                                         fmha_sparge_sage_fwd_args a)
{
    if(s.log_level_ > 0)
        std::cout << ", sparge_sage_{F_dtype_name}_{F_qscale_name}_{F_mode_name}{F_log_suffix}{F_bias_suffix}"
                  << std::flush;

    constexpr bool kIsGroup = {F_group_bool};

    const ck_tile::index_t num_k_blocks = (a.seqlen_k + a.pp_block_size - 1) / a.pp_block_size;
    const ck_tile::index_t num_q_blocks = (a.seqlen_q + a.pp_block_size - 1) / a.pp_block_size;

    const auto ws = kIsGroup ? compute_sparge_sage_workspace_layout_group(a)
                             : compute_sparge_sage_workspace_layout(a);

    char* workspace = reinterpret_cast<char*>(a.workspace_ptr);
    float*   d_k_means = reinterpret_cast<float*>(workspace + ws.base.k_means_off);
    float*   d_q_means = reinterpret_cast<float*>(workspace + ws.base.q_means_off);
    int32_t* d_lut     = reinterpret_cast<int32_t*>(workspace + ws.base.lut_off);
    int32_t* d_vbn     = reinterpret_cast<int32_t*>(workspace + ws.base.vbn_off);
    cfg::QDataType* d_q_quant = reinterpret_cast<cfg::QDataType*>(workspace + ws.q_quant_off);
    cfg::QDataType* d_k_quant = reinterpret_cast<cfg::QDataType*>(workspace + ws.k_quant_off);
    float*   d_q_scale = reinterpret_cast<float*>(workspace + ws.q_scale_off);
    float*   d_k_scale = reinterpret_cast<float*>(workspace + ws.k_scale_off);
    // sim buffers sized only when cosine-sim block selection is enabled.
    const bool sim_enabled = (a.hp.simthreshold > 0.0f);
    float*   d_k_sim = sim_enabled ? reinterpret_cast<float*>(workspace + ws.base.k_sim_off) : nullptr;
    float*   d_q_sim = sim_enabled ? reinterpret_cast<float*>(workspace + ws.base.q_sim_off) : nullptr;

    // 1. Fused preprocess (means + quant).
    ck_tile::SpargePreprocessFusedKargs pp_kargs{};
    pp_kargs.k.data             = a.k_ptr;
    pp_kargs.k.means            = d_k_means;
    pp_kargs.k.sim              = d_k_sim;
    pp_kargs.k.batch            = a.batch;
    pp_kargs.k.nhead            = a.nhead_k;
    pp_kargs.k.seqlen           = a.seqlen_k;
    pp_kargs.k.hdim             = a.hdim_q;
    pp_kargs.k.block_size       = a.pp_block_size;
    pp_kargs.k.num_blocks       = num_k_blocks;
    pp_kargs.k.batch_stride     = a.batch_stride_k;
    pp_kargs.k.head_stride      = a.nhead_stride_k;
    pp_kargs.k.seq_stride       = a.stride_k;
    pp_kargs.k.simthreshold     = a.hp.simthreshold;
    // smooth_k: center K by per-channel global mean before quant.
    pp_kargs.k.km_ptr           = reinterpret_cast<const float*>(a.km_ptr);
    pp_kargs.k.quant_out        = reinterpret_cast<int8_t*>(d_k_quant);
    pp_kargs.k.scale_out        = d_k_scale;
    pp_kargs.k.tokens_per_scale = a.block_scale_size_k;
    pp_kargs.k.num_block_scale  = static_cast<ck_tile::index_t>(ws.num_block_scale_k);

    pp_kargs.q.data             = a.q_ptr;
    pp_kargs.q.means            = d_q_means;
    pp_kargs.q.sim              = d_q_sim;
    pp_kargs.q.batch            = a.batch;
    pp_kargs.q.nhead            = a.nhead_q;
    pp_kargs.q.seqlen           = a.seqlen_q;
    pp_kargs.q.hdim             = a.hdim_q;
    pp_kargs.q.block_size       = a.pp_block_size;
    pp_kargs.q.num_blocks       = num_q_blocks;
    pp_kargs.q.batch_stride     = a.batch_stride_q;
    pp_kargs.q.head_stride      = a.nhead_stride_q;
    pp_kargs.q.seq_stride       = a.stride_q;
    pp_kargs.q.simthreshold     = a.hp.simthreshold;
    pp_kargs.q.km_ptr           = nullptr;
    pp_kargs.q.quant_out        = reinterpret_cast<int8_t*>(d_q_quant);
    pp_kargs.q.scale_out        = d_q_scale;
    pp_kargs.q.tokens_per_scale = a.block_scale_size_q;
    pp_kargs.q.num_block_scale  = static_cast<ck_tile::index_t>(ws.num_block_scale_q);

    if constexpr(kIsGroup)
    {
        pp_kargs.k.seqstart_ptr       = static_cast<const int32_t*>(a.seqstart_k_ptr);
        pp_kargs.k.seqlen_ptr         = static_cast<const int32_t*>(a.seqlen_k_ptr);
        pp_kargs.k.seqstart_block_ptr = static_cast<const int32_t*>(a.seqstart_k_block_ptr);
        pp_kargs.k.total_blocks       = a.total_k_blocks;
        pp_kargs.q.seqstart_ptr       = static_cast<const int32_t*>(a.seqstart_q_ptr);
        pp_kargs.q.seqlen_ptr         = static_cast<const int32_t*>(a.seqlen_q_ptr);
        pp_kargs.q.seqstart_block_ptr = static_cast<const int32_t*>(a.seqstart_q_block_ptr);
        pp_kargs.q.total_blocks       = a.total_q_blocks;
    }

    auto pp_callable = ck_tile::make_kernel<pp_fused_kernel::kBlockPerCu>(
        pp_fused_kernel{}, pp_fused_kernel::GridSize(pp_kargs), pp_fused_kernel::BlockSize(),
        pp_fused_kernel::GetSmemSize(a.hdim_q), pp_kargs);

    // 2. Mask prediction.
    ck_tile::SpargeMaskPredictionKargs mp_kargs{};
    mp_kargs.k_means             = d_k_means;
    mp_kargs.q_means             = d_q_means;
    mp_kargs.k_sim               = d_k_sim;
    mp_kargs.q_sim               = d_q_sim;
    mp_kargs.lut_out             = d_lut;
    mp_kargs.valid_block_num_out = d_vbn;
    mp_kargs.batch               = a.batch;
    mp_kargs.nhead_q             = a.nhead_q;
    mp_kargs.nhead_k             = a.nhead_k;
    mp_kargs.nhead_ratio_qk      = a.nhead_q / a.nhead_k;
    mp_kargs.num_q_blocks        = num_q_blocks;
    mp_kargs.num_k_blocks        = num_k_blocks;
    mp_kargs.hdim                = a.hdim_q;
    mp_kargs.scale               = a.scale_s;
    mp_kargs.cdfthreshd          = a.hp.cdfthreshd;
    mp_kargs.topk                = a.hp.topk;
    mp_kargs.simthreshold        = a.hp.simthreshold;
    mp_kargs.cdfthreshd_per_head = reinterpret_cast<const float*>(a.hp.cdfthreshd_per_head_ptr);
    mp_kargs.topk_per_head       = reinterpret_cast<const float*>(a.hp.topk_per_head_ptr);
    mp_kargs.simthreshold_per_head = reinterpret_cast<const float*>(a.hp.simthreshold_per_head_ptr);
    mp_kargs.causal_type         = static_cast<ck_tile::index_t>(a.causal_type);
    mp_kargs.attention_sink      = a.attention_sink;
    mp_kargs.seqlen_q            = a.seqlen_q;
    mp_kargs.seqlen_k            = a.seqlen_k;
    mp_kargs.block_size          = a.pp_block_size;
    mp_kargs.window_left         = a.window_size_left;
    mp_kargs.window_right        = a.window_size_right;

    if constexpr(kIsGroup)
    {
        mp_kargs.seqstart_q_ptr       = static_cast<const int32_t*>(a.seqstart_q_ptr);
        mp_kargs.seqstart_k_ptr       = static_cast<const int32_t*>(a.seqstart_k_ptr);
        mp_kargs.seqlen_q_ptr         = static_cast<const int32_t*>(a.seqlen_q_ptr);
        mp_kargs.seqlen_k_ptr         = static_cast<const int32_t*>(a.seqlen_k_ptr);
        mp_kargs.seqstart_q_block_ptr = static_cast<const int32_t*>(a.seqstart_q_block_ptr);
        mp_kargs.seqstart_k_block_ptr = static_cast<const int32_t*>(a.seqstart_k_block_ptr);
        mp_kargs.mask_batch_offset_ptr = static_cast<const int32_t*>(a.mask_batch_offset_ptr);
        mp_kargs.total_q_blocks       = a.total_q_blocks;
        mp_kargs.total_k_blocks       = a.total_k_blocks;
    }

    auto make_mp = [&](auto cap_const) {
        constexpr ck_tile::index_t kCap = decltype(cap_const)::value;
        using mk_ = mask_kernel_t<kCap>;
        return ck_tile::make_kernel<mk_::kBlockPerCu>(
            mk_{}, mk_::GridSize(mp_kargs), mk_::BlockSize(),
            mk_::GetSmemSize(a.hdim_q, num_k_blocks), mp_kargs);
    };

    // 2c. PERTENSOR global-absmax Q/K quant; built always, launched only when kIsPerTensor.
    ck_tile::SpargeQKQuantKargs qq_kargs{};
    qq_kargs.x_ptr     = a.q_ptr;
    qq_kargs.quant_ptr = d_q_quant;
    qq_kargs.scale_ptr = d_q_scale;
    qq_kargs.batch     = a.batch;
    qq_kargs.nhead     = a.nhead_q;
    qq_kargs.seqlen    = a.seqlen_q;
    qq_kargs.hdim      = a.hdim_q;
    qq_kargs.batch_stride_x = a.batch_stride_q;
    qq_kargs.nhead_stride_x = a.nhead_stride_q;
    qq_kargs.stride_x       = a.stride_q;

    ck_tile::SpargeQKQuantKargs kq_kargs{};
    kq_kargs.x_ptr     = a.k_ptr;
    kq_kargs.quant_ptr = d_k_quant;
    kq_kargs.scale_ptr = d_k_scale;
    kq_kargs.batch     = a.batch;
    kq_kargs.nhead     = a.nhead_k;
    kq_kargs.seqlen    = a.seqlen_k;
    kq_kargs.hdim      = a.hdim_q;
    kq_kargs.batch_stride_x = a.batch_stride_k;
    kq_kargs.nhead_stride_x = a.nhead_stride_k;
    kq_kargs.stride_x       = a.stride_k;
    // smooth_k center.
    kq_kargs.km_ptr         = reinterpret_cast<const float*>(a.km_ptr);

    if constexpr(kIsGroup)
    {
        // packed quant Q/K [1, H, total_tokens, D].
        qq_kargs.batch_stride_quant = 0;
        qq_kargs.nhead_stride_quant = a.total_q_tokens * a.hdim_q;
        qq_kargs.stride_quant       = a.hdim_q;
        qq_kargs.seqstart_ptr      = static_cast<const int32_t*>(a.seqstart_q_ptr);
        qq_kargs.seqlen_ptr        = static_cast<const int32_t*>(a.seqlen_q_ptr);
        kq_kargs.batch_stride_quant = 0;
        kq_kargs.nhead_stride_quant = a.total_k_tokens * a.hdim_q;
        kq_kargs.stride_quant       = a.hdim_q;
        kq_kargs.seqstart_ptr      = static_cast<const int32_t*>(a.seqstart_k_ptr);
        kq_kargs.seqlen_ptr        = static_cast<const int32_t*>(a.seqlen_k_ptr);
    }
    else
    {
        // quant Q/K [batch, H, S, D].
        qq_kargs.batch_stride_quant = a.nhead_q * a.seqlen_q * a.hdim_q;
        qq_kargs.nhead_stride_quant = a.seqlen_q * a.hdim_q;
        qq_kargs.stride_quant       = a.hdim_q;
        kq_kargs.batch_stride_quant = a.nhead_k * a.seqlen_k * a.hdim_q;
        kq_kargs.nhead_stride_quant = a.seqlen_k * a.hdim_q;
        kq_kargs.stride_quant       = a.hdim_q;
    }
    auto qq_callable = ck_tile::make_kernel<qkquant_kernel::kBlockPerCu>(
        qkquant_kernel{}, qkquant_kernel::GridSize(qq_kargs), qkquant_kernel::BlockSize(),
        qkquant_kernel::GetSmemSize(a.hdim_q), qq_kargs);
    auto kq_callable = ck_tile::make_kernel<qkquant_kernel::kBlockPerCu>(
        qkquant_kernel{}, qkquant_kernel::GridSize(kq_kargs), qkquant_kernel::BlockSize(),
        qkquant_kernel::GetSmemSize(a.hdim_q), kq_kargs);

    // Pick smallest covering sort capacity; with_quant adds the PERTENSOR Q/K quant kernels.
    auto dispatch_chain = [&](auto&& attn_callable, bool with_quant) -> float {
        auto run = [&](auto cap_const) -> float {
            auto mp_callable = make_mp(cap_const);
            if(with_quant)
                return ck_tile::launch_kernel(s, pp_callable, mp_callable,
                                              qq_callable, kq_callable, attn_callable);
            return ck_tile::launch_kernel(s, pp_callable, mp_callable, attn_callable);
        };
        if(num_k_blocks <= 256)  return run(ck_tile::number<256>{});
        if(num_k_blocks <= 512)  return run(ck_tile::number<512>{});
        if(num_k_blocks <= 1024) return run(ck_tile::number<1024>{});
        std::cerr << "[sparge_sage] seqlen_k too large: num_k_blocks=" << num_k_blocks
                  << " exceeds max sort capacity 1024 (131072 tokens @ block_size=128)\\n";
        return -1.0f;
    };

    // 3. Quantized sage attention.
    if constexpr(kIsGroup)
    {
        // quant Q/K packed token-major [Hq, total_tokens, D].
        const ck_tile::index_t quant_stride_q = a.hdim_q;
        const ck_tile::index_t quant_stride_k = a.hdim_q;
        const ck_tile::index_t quant_nhead_stride_q = a.total_q_tokens * a.hdim_q;
        const ck_tile::index_t quant_nhead_stride_k = a.total_k_tokens * a.hdim_q;

        // PERTENSOR: per-(b,h) scalar scale (nhead stride 1); other modes use block-packed (stride 0).
        const ck_tile::index_t pt_nhead_stride_q_descale = kIsPerTensor ? 1 : 0;
        const ck_tile::index_t pt_nhead_stride_k_descale = kIsPerTensor ? 1 : 0;

        auto attn_kargs = sage_kernel::MakeKargsGroup(
            d_q_quant, d_k_quant, a.v_ptr, a.o_ptr, d_lut, d_vbn,
            d_q_scale, d_k_scale, a.v_descale_ptr,
            a.hdim_q, a.hdim_v, a.nhead_q, a.nhead_q / a.nhead_k, a.scale_s,
            quant_stride_q, quant_stride_k, a.stride_v, a.stride_o,
            quant_nhead_stride_q, quant_nhead_stride_k, a.nhead_stride_v, a.nhead_stride_o,
            /*nhead_stride_q_descale*/ pt_nhead_stride_q_descale,
            /*nhead_stride_k_descale*/ pt_nhead_stride_k_descale,
            /*nhead_stride_v_descale*/ a.nhead_stride_v_descale,
            /*batch_stride_v_descale*/ a.batch_stride_v_descale,
            a.block_scale_size_q, a.block_scale_size_k,
            static_cast<const int32_t*>(a.seqstart_q_ptr),
            static_cast<const int32_t*>(a.seqstart_k_ptr),
            static_cast<const int32_t*>(a.seqlen_q_ptr),
            static_cast<const int32_t*>(a.seqlen_k_ptr),
            static_cast<const int32_t*>(a.seqstart_q_block_ptr),
            static_cast<const int32_t*>(a.seqstart_k_block_ptr),
            static_cast<const int32_t*>(a.mask_batch_offset_ptr),
            a.batch,
            a.window_size_left, a.window_size_right, a.mask_type,
            a.bias_ptr, a.stride_bias, a.nhead_stride_bias, a.batch_stride_bias);
        // PERTENSOR group scale is per-(b,h) batch-major [batch, nhead]; override packed defaults.
        if constexpr(kIsPerTensor)
        {
            attn_kargs.batch_stride_q_descale = a.nhead_q;
            attn_kargs.batch_stride_k_descale = a.nhead_k;
        }
        // Stage-2 pv-skip. Group per-head ptr is gated off by the runner (scalar-only MVP).
        attn_kargs.pvthreshd              = a.hp.pvthreshd;
        attn_kargs.pvthreshd_per_head_ptr = a.hp.pvthreshd_per_head_ptr;
        attn_kargs.logits_soft_cap        = a.logits_soft_cap;

        auto attn_grids = sage_kernel::GridSize(a.batch, a.nhead_q, a.max_seqlen_q, a.hdim_v);
        auto attn_callable = ck_tile::make_kernel<sage_kernel::kBlockPerCu>(
            sage_kernel{}, attn_grids, sage_kernel::BlockSize(), 0, attn_kargs);
        return dispatch_chain(attn_callable, kIsPerTensor);
    }
    else
    {
        // descale layout: [batch, nhead, num_block_scale]; v_descale per-channel.
        const ck_tile::index_t nbs_q = static_cast<ck_tile::index_t>(ws.num_block_scale_q);
        const ck_tile::index_t nbs_k = static_cast<ck_tile::index_t>(ws.num_block_scale_k);
        const ck_tile::index_t quant_stride_q = a.hdim_q;
        const ck_tile::index_t quant_stride_k = a.hdim_q;
        const ck_tile::index_t quant_nhead_stride_q = a.seqlen_q * a.hdim_q;
        const ck_tile::index_t quant_nhead_stride_k = a.seqlen_k * a.hdim_q;
        const ck_tile::index_t quant_batch_stride_q = a.nhead_q * a.seqlen_q * a.hdim_q;
        const ck_tile::index_t quant_batch_stride_k = a.nhead_k * a.seqlen_k * a.hdim_q;

        // PERTENSOR scale [batch, nhead, 1]; other modes [batch, nhead, num_block_scale].
        const ck_tile::index_t nhsq = kIsPerTensor ? 1 : nbs_q;
        const ck_tile::index_t nhsk = kIsPerTensor ? 1 : nbs_k;
        const ck_tile::index_t bsq  = kIsPerTensor ? a.nhead_q : a.nhead_q * nbs_q;
        const ck_tile::index_t bsk  = kIsPerTensor ? a.nhead_k : a.nhead_k * nbs_k;

        auto attn_kargs = sage_kernel::MakeKargs(
            d_q_quant, d_k_quant, a.v_ptr, a.o_ptr, d_lut, d_vbn,
            d_q_scale, d_k_scale, a.v_descale_ptr,
            a.seqlen_q, a.seqlen_k, a.hdim_q, a.hdim_v,
            a.nhead_q, a.nhead_q / a.nhead_k, a.scale_s,
            quant_stride_q, quant_stride_k, a.stride_v, a.stride_o,
            quant_nhead_stride_q, quant_nhead_stride_k, a.nhead_stride_v, a.nhead_stride_o,
            quant_batch_stride_q, quant_batch_stride_k, a.batch_stride_v, a.batch_stride_o,
            /*nhead_stride_q_descale*/ nhsq, /*nhead_stride_k_descale*/ nhsk,
            /*nhead_stride_v_descale*/ a.nhead_stride_v_descale,
            /*batch_stride_q_descale*/ bsq,
            /*batch_stride_k_descale*/ bsk,
            /*batch_stride_v_descale*/ a.batch_stride_v_descale,
            a.block_scale_size_q, a.block_scale_size_k,
            a.window_size_left, a.window_size_right, a.mask_type,
            a.bias_ptr, a.stride_bias, a.nhead_stride_bias, a.batch_stride_bias);
        // Stage-2 pv-skip.
        attn_kargs.pvthreshd              = a.hp.pvthreshd;
        attn_kargs.pvthreshd_per_head_ptr = a.hp.pvthreshd_per_head_ptr;
        attn_kargs.logits_soft_cap        = a.logits_soft_cap;

        auto attn_grids = sage_kernel::GridSize(a.batch, a.nhead_q, a.max_seqlen_q, a.hdim_v);
        auto attn_callable = ck_tile::make_kernel<sage_kernel::kBlockPerCu>(
            sage_kernel{}, attn_grids, sage_kernel::BlockSize(), 0, attn_kargs);
        return dispatch_chain(attn_callable, kIsPerTensor);
    }
}
"""

API_FILENAME = "fmha_sparge_sage_fwd_api.cpp"
API_CPP = """// SPDX-License-Identifier: MIT
// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// auto generated by generate.py  --api fwd_sparge_sage
#include "sparse_attn_fwd.hpp"

#define SPARGE_SAGE_DISPATCH_MGB(QS_STR, QS_ENUM, MASK, GROUP, BTYPE, BENUM, QKFP8)         \\
    if(t.qscale.compare(QS_STR) == 0 && t.has_mask == (MASK) &&                             \\
       t.is_group_mode == (GROUP) && t.bias_type == (BTYPE))                                \\
    {                                                                                       \\
        using trait_ = fmha_sparge_sage_fwd_traits_<128,                                    \\
                           SpargeSageI8Fp8Bf16::InputDataType,                              \\
                           ck_tile::BlockSageAttentionQuantScaleEnum::QS_ENUM,              \\
                           MASK, GROUP, ck_tile::BlockAttentionBiasEnum::BENUM, QKFP8>;     \\
        return fmha_sparge_sage_fwd_<trait_>(s, a);                                         \\
    }

#define SPARGE_SAGE_DISPATCH_MG(QS_STR, QS_ENUM, MASK, GROUP, QKFP8)                        \\
    SPARGE_SAGE_DISPATCH_MGB(QS_STR, QS_ENUM, MASK, GROUP, 0, NO_BIAS, QKFP8)                \\
    SPARGE_SAGE_DISPATCH_MGB(QS_STR, QS_ENUM, MASK, GROUP, 1, ELEMENTWISE_BIAS, QKFP8)       \\
    SPARGE_SAGE_DISPATCH_MGB(QS_STR, QS_ENUM, MASK, GROUP, 2, ALIBI, QKFP8)

#define SPARGE_SAGE_DISPATCH(QS_STR, QS_ENUM, QKFP8)                                        \\
    SPARGE_SAGE_DISPATCH_MG(QS_STR, QS_ENUM, false, false, QKFP8)                            \\
    SPARGE_SAGE_DISPATCH_MG(QS_STR, QS_ENUM, true,  false, QKFP8)                            \\
    SPARGE_SAGE_DISPATCH_MG(QS_STR, QS_ENUM, false, true,  QKFP8)                            \\
    SPARGE_SAGE_DISPATCH_MG(QS_STR, QS_ENUM, true,  true,  QKFP8)

float fmha_sparge_sage_fwd(fmha_sparge_sage_fwd_traits t,
                           fmha_sparge_sage_fwd_args a,
                           const ck_tile::stream_config& s)
{
    if(t.data_type.compare("i8fp8bf16") == 0 &&
       t.hdim_q <= 128 && t.hdim_v <= 128)
    {
        SPARGE_SAGE_DISPATCH("perwarp", PERWARP, false)
        SPARGE_SAGE_DISPATCH("perblock", BLOCKSCALE, false)
        SPARGE_SAGE_DISPATCH("perthread", PERTHREAD, false)
        SPARGE_SAGE_DISPATCH("pertensor", PERTENSOR, false)
    }
    if(t.data_type.compare("fp8bf16") == 0 &&
       t.hdim_q <= 128 && t.hdim_v <= 128)
    {
        SPARGE_SAGE_DISPATCH("perwarp", PERWARP, true)
        SPARGE_SAGE_DISPATCH("perblock", BLOCKSCALE, true)
        SPARGE_SAGE_DISPATCH("perthread", PERTHREAD, true)
        SPARGE_SAGE_DISPATCH("pertensor", PERTENSOR, true)
    }
    return -1.0f;
}
#undef SPARGE_SAGE_DISPATCH
#undef SPARGE_SAGE_DISPATCH_MG
#undef SPARGE_SAGE_DISPATCH_MGB
"""

# i8fp8bf16: INT8 Q/K. fp8bf16: FP8 Q/K (fp8 MFMA gemm0).
DTYPE_VARIANTS = [
    ("i8fp8bf16", "SpargeSageI8Fp8Bf16", "false"),
    ("fp8bf16", "SpargeSageFp8Bf16", "true"),
]
QSCALE_VARIANTS = [
    ("perwarp", "PERWARP"),
    ("perblock", "BLOCKSCALE"),
    ("perthread", "PERTHREAD"),
    ("pertensor", "PERTENSOR"),
]
MASK_VARIANTS = [
    ("", "false", ""),
    ("_mask", "true", "_mask"),
]
MODE_VARIANTS = [
    ("batch", "false"),
    ("group", "true"),
]
# ELEMENTWISE bias loads a DRAM tile into the same gemm0 C (s_acc) distribution, so the
# int8-MFMA SwizzleB/TransposedC layout aligns by construction.
BIAS_VARIANTS = [
    ("", "NO_BIAS", ""),
    ("_alibi", "ALIBI", "_alibi"),
    ("_bias", "ELEMENTWISE_BIAS", "_bias"),
]


def _kernel_filename(dtype_name: str, qscale_name: str, mode_name: str, mask_suffix: str,
                     bias_suffix: str) -> str:
    return (f"fmha_sparge_sage_fwd_d128_{dtype_name}_{mode_name}_{qscale_name}"
            f"{mask_suffix}{bias_suffix}.cpp")


def _render_kernel(dtype_name: str, cfg: str, qkfp8_bool: str, qscale_name: str, qscale_enum: str,
                   mode_name: str, group_bool: str, mask_bool: str, log_suffix: str,
                   bias_enum: str, bias_suffix: str) -> str:
    # PERTENSOR: preprocess is means-only (NO_SCALE), Q/K quant runs in a dedicated kernel.
    pp_qscale_enum = "NO_SCALE" if qscale_enum == "PERTENSOR" else qscale_enum
    return (KERNEL_CPP
            .replace("{F_cfg}", cfg)
            .replace("{F_qkfp8_bool}", qkfp8_bool)
            .replace("{F_dtype_name}", dtype_name)
            .replace("{F_pp_qscale_enum}", pp_qscale_enum)
            .replace("{F_qscale_enum}", qscale_enum)
            .replace("{F_qscale_name}", qscale_name)
            .replace("{F_mode_name}", mode_name)
            .replace("{F_group_bool}", group_bool)
            .replace("{F_mask_bool}", mask_bool)
            .replace("{F_log_suffix}", log_suffix)
            .replace("{F_bias_enum}", bias_enum)
            .replace("{F_bias_suffix}", bias_suffix))


def get_blob_files() -> List[str]:
    files = []
    for dtype_name, _, _ in DTYPE_VARIANTS:
        for qscale_name, _ in QSCALE_VARIANTS:
            for mode_name, _ in MODE_VARIANTS:
                for mask_suffix, _, _ in MASK_VARIANTS:
                    for bias_suffix, _, _ in BIAS_VARIANTS:
                        files.append(_kernel_filename(dtype_name, qscale_name, mode_name,
                                                      mask_suffix, bias_suffix))
    return files + [API_FILENAME]


def write_blobs(output_dir: Path, kernel_filter, receipt, optdim_list, mask_impl) -> None:
    del receipt, mask_impl
    if optdim_list != [-1] and 128 not in optdim_list:
        pass  # sparge_sage only supports hdim128; still emit so the TU exists
    for dtype_name, cfg, qkfp8_bool in DTYPE_VARIANTS:
        for qscale_name, qscale_enum in QSCALE_VARIANTS:
            for mode_name, group_bool in MODE_VARIANTS:
                for mask_suffix, mask_bool, log_suffix in MASK_VARIANTS:
                    for bias_suffix, bias_enum, bias_log in BIAS_VARIANTS:
                        fn = _kernel_filename(dtype_name, qscale_name, mode_name, mask_suffix,
                                              bias_suffix)
                        if kernel_filter and not fnmatch.fnmatch(fn, kernel_filter):
                            continue
                        update_file(output_dir / fn,
                                    _render_kernel(dtype_name, cfg, qkfp8_bool, qscale_name,
                                                   qscale_enum, mode_name, group_bool, mask_bool,
                                                   log_suffix, bias_enum, bias_log))
    update_file(output_dir / API_FILENAME, API_CPP)


def list_blobs(file_path: Path, kernel_filter, receipt, optdim_list, mask_impl) -> None:
    del receipt, optdim_list, mask_impl
    with file_path.open("a") as f:
        for fn in get_blob_files():
            f.write(str(file_path.parent / GEN_DIR / fn) + "\n")
