# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

import copy
from dataclasses import dataclass, field
import fnmatch
import itertools
import os
import os.path as path
from pathlib import Path
from typing import List, Optional, Tuple

from codegen.cpp_symbol_map import (
    BIAS_CHECK_MAP,
    BIAS_MAP,
    BOOL_MAP,
    FWD_DTYPE_MAP,
    LAYOUT_MAP,
    MODE_MAP,
    PIPELINE_ENUM_MAP,
    PIPELINE_MAP,
    get_mask_check_map,
    get_mask_map,
)

GEN_DIR = ""


def update_file(file_path, content):
    existing_content = ""
    if path.exists(file_path):
        with open(file_path, "r") as file:
            existing_content = file.read()
    if existing_content == content:
        return
    with open(file_path, "w") as file:
        file.write(content)


DTYPE_BITS = {"fp32": 32, "fp16": 16, "bf16": 16}

FMHA_FWD_KERNEL_HEADER = """// SPDX-License-Identifier: MIT
// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.\n
// auto generated by generate.py  --api fwd_sparge
#include "ck_tile/ops/fmha/block/variants.hpp"
#include "sparse_attn_fwd.hpp"
#include "pipeline/block_fmha_pipeline_qr_ks_vs_async_sparge.hpp"
#include "kernel/fmha_fwd_sparge_kernel.hpp"
#include <hip/hip_runtime.h>
#include <iostream>
#include <vector>
#include <cstddef>

"""

FMHA_FWD_KERNEL_BODY = """
using fmha_dtype_{F_idx} = {F_dtype};

using fmha_block_tile_{F_idx} = ck_tile::sequence<{F_bm0}, {F_bn0}, {F_bk0}, {F_bn1}, {F_bk1}, {F_bk0max}>;

using fmha_shape_{F_idx} = ck_tile::TileFmhaShape<fmha_block_tile_{F_idx},
                                      ck_tile::sequence<{F_rm0}, {F_rn0}, {F_rk0}>,
                                      ck_tile::sequence<{F_wm0}, {F_wn0}, {F_wk0}>,
                                      ck_tile::sequence<{F_rm1}, {F_rn1}, {F_rk1}>,
                                      ck_tile::sequence<{F_wm1}, {F_wn1}, {F_wk1}>,
                                      {F_vlayout}>;

// TileFmhaTraits: spad, skpad, dpad, dvpad, has_logits_soft_cap, bias_enum,
//                 has_bias_grad, store_lse, has_dropout, quant_scale_enum, occupancy, skip_min_seqlen_q
using fmha_trait_{F_idx} = ck_tile::TileFmhaTraits<{F_spad},
                                                    {F_skpad},
                                                    {F_dpad},
                                                    {F_dvpad},
                                                    {F_logits_cpp},
                                                    {F_bias},
                                                    false,
                                                    false,
                                                    false,
                                                    ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                                    {F_occupancy},
                                                    false>;

using fmha_variant_{F_idx} = ck_tile::ComposedAttention<{F_logits_variant_code}, CK_TILE_FMHA_FWD_FAST_EXP2>;

using fmha_mask_{F_idx} = {F_mask};

using fmha_pipeline_problem_{F_idx} = ck_tile::BlockFmhaPipelineProblem<
    typename FmhaSparseFwdTypeConfig<fmha_dtype_{F_idx}>::QDataType,
    typename FmhaSparseFwdTypeConfig<fmha_dtype_{F_idx}>::KDataType,
    typename FmhaSparseFwdTypeConfig<fmha_dtype_{F_idx}>::VDataType,
    typename FmhaSparseFwdTypeConfig<fmha_dtype_{F_idx}>::SaccDataType,
    typename FmhaSparseFwdTypeConfig<fmha_dtype_{F_idx}>::SMPLComputeDataType,
    typename FmhaSparseFwdTypeConfig<fmha_dtype_{F_idx}>::BiasDataType,
    typename FmhaSparseFwdTypeConfig<fmha_dtype_{F_idx}>::RandValOutputDataType,
    typename FmhaSparseFwdTypeConfig<fmha_dtype_{F_idx}>::LSEDataType,
    typename FmhaSparseFwdTypeConfig<fmha_dtype_{F_idx}>::PDataType,
    typename FmhaSparseFwdTypeConfig<fmha_dtype_{F_idx}>::OaccDataType,
    typename FmhaSparseFwdTypeConfig<fmha_dtype_{F_idx}>::ODataType,
    fmha_shape_{F_idx},
    {F_mode},
    fmha_variant_{F_idx},
    fmha_mask_{F_idx},
    false,
    fmha_trait_{F_idx}>;

using fmha_pipeline_{F_idx} = {F_pipeline}<
    fmha_pipeline_problem_{F_idx}>;

using fmha_epilogue_{F_idx} =
    ck_tile::Default2DEpilogue<ck_tile::Default2DEpilogueProblem<typename FmhaSparseFwdTypeConfig<{F_dtype}>::OaccDataType,
                                           typename FmhaSparseFwdTypeConfig<{F_dtype}>::ODataType,
                                           {F_spad}, {F_dvpad}>>;

using fmha_kernel_{F_idx} =
    ck_tile::FmhaFwdSpargeKernel<fmha_pipeline_{F_idx}, fmha_epilogue_{F_idx}>;

using trait_{F_idx} = fmha_sparge_fwd_traits_<{F_hdim}, {F_dtype}, {F_bm0}, {F_bn0}, {F_bk0}, {F_bn1}, {F_bk1}, {F_bk0max}, {F_vlayout},
                        {F_pipeline_enum}, {F_logits_cpp}/*logits*/, fmha_mask_{F_idx}, {F_spad}, {F_skpad}, {F_dpad}, {F_dvpad}, {F_mode}, {F_bias}>;

// 1. Fused K+Q preprocess (block means + optional sim).
static auto make_preprocess_callable_{F_idx}(const fmha_sparge_fwd_args& a,
                                             float* d_k_means,
                                             float* d_q_means,
                                             float* d_k_sim,
                                             float* d_q_sim,
                                             ck_tile::index_t num_k_blocks,
                                             ck_tile::index_t num_q_blocks)
{{
    using pp_ = typename fmha_kernel_{F_idx}::PreprocessFusedKernel;
    constexpr bool is_group = trait_{F_idx}::kIsGroupMode;

    ck_tile::SpargePreprocessFusedKargs pp_kargs;

    pp_kargs.k.data         = a.k_ptr;
    pp_kargs.k.means        = d_k_means;
    pp_kargs.k.sim          = d_k_sim;
    pp_kargs.k.batch        = a.batch;
    pp_kargs.k.nhead        = a.nhead_k;
    pp_kargs.k.seqlen       = a.seqlen_k;
    pp_kargs.k.hdim         = a.hdim_q;
    pp_kargs.k.block_size   = a.pp_block_size;
    pp_kargs.k.num_blocks   = num_k_blocks;
    pp_kargs.k.batch_stride = a.batch_stride_k;
    pp_kargs.k.head_stride  = a.nhead_stride_k;
    pp_kargs.k.seq_stride   = a.stride_k;
    pp_kargs.k.simthreshold = a.hp.simthreshold;
    pp_kargs.k.km_ptr       = nullptr;

    pp_kargs.q.data         = a.q_ptr;
    pp_kargs.q.means        = d_q_means;
    pp_kargs.q.sim          = d_q_sim;
    pp_kargs.q.batch        = a.batch;
    pp_kargs.q.nhead        = a.nhead_q;
    pp_kargs.q.seqlen       = a.seqlen_q;
    pp_kargs.q.hdim         = a.hdim_q;
    pp_kargs.q.block_size   = a.pp_block_size;
    pp_kargs.q.num_blocks   = num_q_blocks;
    pp_kargs.q.batch_stride = a.batch_stride_q;
    pp_kargs.q.head_stride  = a.nhead_stride_q;
    pp_kargs.q.seq_stride   = a.stride_q;
    pp_kargs.q.simthreshold = a.hp.simthreshold;
    pp_kargs.q.km_ptr       = nullptr;

    if constexpr(is_group)
    {{
        pp_kargs.k.seqstart_ptr       = static_cast<const int32_t*>(a.seqstart_k_ptr);
        pp_kargs.k.seqlen_ptr         = static_cast<const int32_t*>(a.seqlen_k_ptr);
        pp_kargs.k.seqstart_block_ptr = static_cast<const int32_t*>(a.seqstart_k_block_ptr);
        pp_kargs.k.total_blocks       = a.total_k_blocks;
        pp_kargs.q.seqstart_ptr       = static_cast<const int32_t*>(a.seqstart_q_ptr);
        pp_kargs.q.seqlen_ptr         = static_cast<const int32_t*>(a.seqlen_q_ptr);
        pp_kargs.q.seqstart_block_ptr = static_cast<const int32_t*>(a.seqstart_q_block_ptr);
        pp_kargs.q.total_blocks       = a.total_q_blocks;
    }}

    return ck_tile::make_kernel<pp_::kBlockPerCu>(
        pp_{{}}, pp_::GridSize(pp_kargs), pp_::BlockSize(),
        pp_::GetSmemSize(a.hdim_q), pp_kargs);
}}

// 2. Mask prediction. Templated on kMaxKBlocksPow2 (K-block sort capacity).
template <ck_tile::index_t kMaxKBlocksPow2>
static auto make_mask_prediction_callable_{F_idx}(const fmha_sparge_fwd_args& a,
                                                  float* d_k_means,
                                                  float* d_q_means,
                                                  float* d_k_sim,
                                                  float* d_q_sim,
                                                  int32_t* d_lut,
                                                  int32_t* d_vbn,
                                                  ck_tile::index_t num_q_blocks,
                                                  ck_tile::index_t num_k_blocks)
{{
    constexpr bool is_group = trait_{F_idx}::kIsGroupMode;
    using mp_ = ck_tile::FmhaFwdSpargeMaskPredictionKernel<
        is_group, kMaxKBlocksPow2, fmha_kernel_{F_idx}::kBlockSize>;

    ck_tile::SpargeMaskPredictionKargs mp_kargs;
    mp_kargs.k_means             = d_k_means;
    mp_kargs.q_means             = d_q_means;
    mp_kargs.k_sim               = d_k_sim;
    mp_kargs.q_sim               = d_q_sim;
    mp_kargs.lut_out             = d_lut;
    mp_kargs.valid_block_num_out = d_vbn;
    mp_kargs.batch               = a.batch;
    mp_kargs.nhead_q             = a.nhead_q;
    mp_kargs.nhead_k             = a.nhead_k;
    mp_kargs.nhead_ratio_qk      = a.nhead_q / a.nhead_k;
    mp_kargs.num_q_blocks        = num_q_blocks;
    mp_kargs.num_k_blocks        = num_k_blocks;
    mp_kargs.hdim                = a.hdim_q;
    mp_kargs.scale               = a.scale_s;
    mp_kargs.cdfthreshd             = a.hp.cdfthreshd;
    mp_kargs.topk                    = a.hp.topk;
    mp_kargs.simthreshold           = a.hp.simthreshold;
    mp_kargs.cdfthreshd_per_head    = reinterpret_cast<const float*>(a.hp.cdfthreshd_per_head_ptr);
    mp_kargs.topk_per_head           = reinterpret_cast<const float*>(a.hp.topk_per_head_ptr);
    mp_kargs.simthreshold_per_head  = reinterpret_cast<const float*>(a.hp.simthreshold_per_head_ptr);
    mp_kargs.causal_type         = static_cast<ck_tile::index_t>(a.causal_type);
    mp_kargs.attention_sink      = a.attention_sink;
    mp_kargs.seqlen_q            = a.seqlen_q;
    mp_kargs.seqlen_k            = a.seqlen_k;
    mp_kargs.block_size          = a.pp_block_size;
    mp_kargs.window_left         = a.window_size_left;
    mp_kargs.window_right        = a.window_size_right;
    if constexpr(is_group)
    {{
        mp_kargs.seqstart_q_ptr       = static_cast<const int32_t*>(a.seqstart_q_ptr);
        mp_kargs.seqstart_k_ptr       = static_cast<const int32_t*>(a.seqstart_k_ptr);
        mp_kargs.seqlen_q_ptr         = static_cast<const int32_t*>(a.seqlen_q_ptr);
        mp_kargs.seqlen_k_ptr         = static_cast<const int32_t*>(a.seqlen_k_ptr);
        mp_kargs.seqstart_q_block_ptr = static_cast<const int32_t*>(a.seqstart_q_block_ptr);
        mp_kargs.seqstart_k_block_ptr = static_cast<const int32_t*>(a.seqstart_k_block_ptr);
        mp_kargs.mask_batch_offset_ptr = static_cast<const int32_t*>(a.mask_batch_offset_ptr);
        mp_kargs.total_q_blocks       = a.total_q_blocks;
        mp_kargs.total_k_blocks       = a.total_k_blocks;
    }}

    return ck_tile::make_kernel<mp_::kBlockPerCu>(
        mp_{{}}, mp_::GridSize(mp_kargs), mp_::BlockSize(),
        mp_::GetSmemSize(a.hdim_q, num_k_blocks), mp_kargs);
}}

// 3. Attention. Caller must set a.internal_lut_ptr / a.internal_vbn_ptr first.
static auto make_attention_callable_{F_idx}(fmha_sparge_fwd_args a)
{{
    using k_ = fmha_kernel_{F_idx};

    auto [kargs, grids] = fmha_fwd_create_kargs_and_grids<k_>(a);
    const dim3 blocks                      = k_::BlockSize();
    constexpr ck_tile::index_t kBlockPerCu = k_::kBlockPerCu;
    return ck_tile::make_kernel<kBlockPerCu>(k_{{}}, grids, blocks, 0, kargs);
}}

template<>
float fmha_sparge_fwd_<trait_{F_idx}>(const ck_tile::stream_config& s, fmha_sparge_fwd_args a)
{{
    if(s.log_level_ > 0)
        std::cout << ", " << "{F_kernel_name}" << std::flush;

    constexpr bool is_group = trait_{F_idx}::kIsGroupMode;
    const ck_tile::index_t num_k_blocks = (a.seqlen_k + a.pp_block_size - 1) / a.pp_block_size;
    const ck_tile::index_t num_q_blocks = (a.seqlen_q + a.pp_block_size - 1) / a.pp_block_size;

    const bool sim_enabled = (a.hp.simthreshold > 0.0f);
    // smooth_k is a no-op: the constant km shift cancels in softmax max-subtract. Kept for API compat.
    (void)a.hp.smooth_k;
    const auto ws_layout   = is_group
        ? compute_sparge_workspace_layout_group(a, a.total_q_blocks, a.total_k_blocks, a.total_qk_blocks)
        : compute_sparge_workspace_layout(a);

    bool own_workspace = (a.workspace_ptr == nullptr);
    char* workspace = nullptr;
    if(own_workspace)
    {{
        const hipError_t err = hipMalloc(&workspace, ws_layout.total_bytes);
        if(err != hipSuccess || workspace == nullptr)
        {{
            std::cerr << "[sparge] hipMalloc(" << ws_layout.total_bytes << ") failed: "
                      << hipGetErrorString(err) << std::endl;
            return -1.0f;
        }}
    }}
    else
    {{
        workspace = reinterpret_cast<char*>(a.workspace_ptr);
    }}

    float*   d_k_means = reinterpret_cast<float*>(workspace + ws_layout.k_means_off);
    float*   d_q_means = reinterpret_cast<float*>(workspace + ws_layout.q_means_off);
    float*   d_k_sim   = sim_enabled ? reinterpret_cast<float*>(workspace + ws_layout.k_sim_off) : nullptr;
    float*   d_q_sim   = sim_enabled ? reinterpret_cast<float*>(workspace + ws_layout.q_sim_off) : nullptr;
    int32_t* d_lut     = reinterpret_cast<int32_t*>(workspace + ws_layout.lut_off);
    int32_t* d_vbn     = reinterpret_cast<int32_t*>(workspace + ws_layout.vbn_off);

    auto pp_callable = make_preprocess_callable_{F_idx}(
        a, d_k_means, d_q_means, d_k_sim, d_q_sim, num_k_blocks, num_q_blocks);

    a.internal_lut_ptr = d_lut;
    a.internal_vbn_ptr = d_vbn;
    auto attn_callable = make_attention_callable_{F_idx}(a);

    // Smallest kMaxKBlocksPow2 covering num_k_blocks (only the mask kernel is multi-variant):
    // 256 -> 32k tokens, 512 -> 64k, 1024 -> 128k (BLKK=128).
    auto launch_with_cap = [&](auto cap_const) {{
        constexpr ck_tile::index_t kCap = decltype(cap_const)::value;
        auto mp_callable = make_mask_prediction_callable_{F_idx}<kCap>(
            a, d_k_means, d_q_means, d_k_sim, d_q_sim, d_lut, d_vbn, num_q_blocks, num_k_blocks);
        return ck_tile::launch_kernel(s, pp_callable, mp_callable, attn_callable);
    }};

    float r = -1.0f;
    if(num_k_blocks <= 256)
        r = launch_with_cap(ck_tile::number<256>{{}});
    else if(num_k_blocks <= 512)
        r = launch_with_cap(ck_tile::number<512>{{}});
    else if(num_k_blocks <= 1024)
        r = launch_with_cap(ck_tile::number<1024>{{}});
    else
    {{
        std::cerr << "[sparge] seqlen_k too large: num_k_blocks=" << num_k_blocks
                  << " exceeds max sort capacity 1024 (131072 tokens @ block_size=128)\\n";
        if(own_workspace) (void)hipFree(workspace);
        return -1.0f;
    }}
    (void)sim_enabled;

    if(a.sparsity_out != nullptr)
    {{
        const size_t n_vbn = is_group
            ? static_cast<size_t>(a.nhead_q) * a.total_q_blocks
            : static_cast<size_t>(a.batch) * a.nhead_q * num_q_blocks;
        std::vector<int32_t> h_vbn(n_vbn, 0);
        const hipError_t cp_err =
            hipMemcpy(h_vbn.data(), d_vbn, ws_layout.vbn_bytes, hipMemcpyDeviceToHost);
        if(cp_err != hipSuccess)
        {{
            // Readback failed -> h_vbn is garbage; report a safe 0 rather than a bogus sparsity.
            std::cerr << "[sparge] sparsity readback hipMemcpy failed: "
                      << hipGetErrorString(cp_err) << std::endl;
            *a.sparsity_out = 0.0f;
        }}
        else
        {{
            size_t total_selected = 0;
            for(size_t i = 0; i < n_vbn; ++i)
                total_selected += static_cast<size_t>(h_vbn[i]);
            const size_t total_possible = is_group
                ? static_cast<size_t>(a.nhead_q) * a.total_qk_blocks
                : n_vbn * static_cast<size_t>(num_k_blocks);
            *a.sparsity_out = total_possible > 0
                ? 1.0f - static_cast<float>(total_selected) / static_cast<float>(total_possible)
                : 0.0f;
        }}
    }}

    if(own_workspace)
    {{
        (void)hipFree(workspace);
    }}

    return r;
}}
"""

FMHA_FWD_API_FILENAME = "fmha_sparge_fwd_api.cpp"
FMHA_FWD_API = """
#include <cstdio>

#include <hip/hip_runtime.h>

namespace {{
bool get_num_cus(unsigned& num_cus) {{
    int device;
    auto status = hipGetDevice(&device);
    if(status != hipSuccess) {{
        fprintf(stderr, "failed to get device");
        return false;
    }}

    hipDeviceProp_t props{{}};
    status = hipGetDeviceProperties(&props, device);
    if(status != hipSuccess) {{
        fprintf(stderr, "failed to get device properties");
        return false;
    }}

    num_cus = props.multiProcessorCount;
    return true;
}}

unsigned get_num_thread_blocks(unsigned batch, unsigned nheads, unsigned max_seqlen_q, unsigned kM0) {{
    const unsigned num_m_blocks = (max_seqlen_q + kM0 - 1) / kM0;
    const unsigned num_n_blocks = 1;

    return batch * nheads * num_m_blocks * num_n_blocks;
}}
}} // namespace

float fmha_sparge_fwd(fmha_sparge_fwd_traits t, fmha_sparge_fwd_args a, const ck_tile::stream_config& s){{
    float r = -1;

    [[maybe_unused]] const float min_cu_util_rate = 0.8;

    unsigned num_cus;
    if (!get_num_cus(num_cus)) {{
        return r;
    }}

    [[maybe_unused]] auto get_num_blocks = [&](unsigned kM0) {{
        return get_num_thread_blocks(a.batch, a.nhead_q, a.max_seqlen_q, kM0);
    }};

{F_dispatch}
    return r;
}}
"""

FMHA_FWD_API_PER_DTYPE = """    {F_if}(t.data_type.compare(\"{F_dtype}\") == 0){{
{F_hdim_case}
    }}
"""
FMHA_FWD_API_PER_HDIM_CASE = """        {F_if} (t.hdim_q <= {F_hdim} && t.hdim_v <= {F_hdim_v}) {{
{F_inner_dispatch}
        }}
"""

FMHA_FWD_API_INNER_DISPATCH = """            {F_if}((t.is_group_mode == {F_mode}) && (t.is_v_rowmajor == {F_vlayout}) && ({F_mask_check}) &&
                        (t.bias_type == {F_bias_check}) && (t.has_logits_soft_cap == {F_logits_cpp}) &&
                        ({F_scheck}) && ({F_seqtune}) && ({F_skcheck}) && ({F_dcheck}) && ({F_dvcheck}) && ({F_constraint})) {{
                using trait_ = fmha_sparge_fwd_traits_<{F_hdim}, {F_dtype}, {F_bm0}, {F_bn0}, {F_bk0}, {F_bn1}, {F_bk1}, {F_bk0max}, {F_vlayout}, {F_pipeline_enum}, {F_logits_cpp}/*logits*/, {F_mask}, {F_spad}, {F_skpad}, {F_dpad}, {F_dvpad}, {F_mode}, {F_bias}>;
                return fmha_sparge_fwd_<trait_>(s, a);
            }}
"""


@dataclass
class CppConstraint:
    bool_expr: str = None

    def __str__(self):
        if self.bool_expr is None:
            return "true"
        else:
            return f"{self.bool_expr}"

    def __and__(self, other):
        return CppConstraint(f"({str(self)}) && ({str(other)})")


@dataclass
class FmhaFwdApiTrait:
    pipeline_tag: str
    hdim: str
    dtype: str
    mode: str
    bm0: int
    bn0: int
    bk0: int
    bn1: int
    bk1: int
    bk0max: int
    vlayout: str
    logits: str
    mask: str
    bias: str
    spad: str
    skpad: str
    dpad: str
    dvpad: str
    constraint: CppConstraint

    @property
    def name(self) -> str:
        return (
            f"{self.hdim}-{self.dtype}-{self.mode}-{self.bm0}-{self.bn0}-{self.bk0}-{self.bn0}-{self.bk1}-{self.bk0max}-"
            + f"{self.vlayout}-{self.logits}-{self.mask}-{self.bias}-{self.spad}-{self.skpad}-{self.dpad}-{self.dvpad}"
        )

    @property
    def scheck(self) -> str:
        return "true"

    @property
    def seqtune(self) -> str:
        if self.bm0 == 128:
            return "true/*fall back to largest tile*/"
        else:
            return f"a.seqlen_q <= {self.bm0}"

    @property
    def skcheck(self) -> str:
        if self.skpad == "t":
            return f"a.seqlen_k == 0 || a.seqlen_k % {self.bn0} != 0"
        return f"a.seqlen_k != 0 && a.seqlen_k % {self.bn0} == 0"

    @property
    def dcheck(self) -> str:
        vec = int((32 * 4) / DTYPE_BITS[self.dtype])
        return f"a.hdim_q % {vec} == 0"

    @property
    def dvcheck(self) -> str:
        vec = int((32 * 4) / DTYPE_BITS[self.dtype])
        return f"a.hdim_v % {vec} == 0"


@dataclass
class FmhaFwdPipeline:
    tag: str
    F_vlayout: str
    F_spad: str
    F_skpad: str
    F_dpad: str
    F_dvpad: str
    F_logits: str
    F_mask: str
    F_bias: str = "no"
    F_constraint: CppConstraint = field(default_factory=CppConstraint)

    @property
    def name(self) -> str:
        def pad_name() -> str:
            n = ""
            if self.F_spad == "t":
                n += "s"
            if self.F_skpad == "t":
                n += "sk"
            if self.F_dpad == "t":
                n += "d"
            if self.F_dvpad == "t":
                n += "dv"
            if n != "":
                n = "p" + n
            return n

        pn = pad_name()
        n = f"{self.tag}_v{self.F_vlayout[0]}"
        if pn != "":
            n += f"_{pn}"
        else:
            n += "_npad"

        if self.F_logits == "t":
            n += "_logits"
        else:
            n += "_nlogits"

        if self.F_bias == "elementwise":
            n += "_bias"
        elif self.F_bias == "alibi":
            n += "_alibi"
        else:
            n += "_nbias"

        if self.F_mask[0:2] == "s_":
            if self.F_mask == "s_mask":
                n += "_mask"
            else:
                n += "_nmask"
        else:
            if self.F_mask != "no":
                n += f"_m{self.F_mask[0]}"
            else:
                n += "_nmask"

        n += "_nskip"
        n += "_nsquant"

        return n


class FmhaFwdApiPool:
    def __init__(self, mask_impl):
        self.pool = dict()
        self.mask_impl = mask_impl

    def register_traits(self, trait: FmhaFwdApiTrait) -> None:
        if trait.dtype not in self.pool.keys():
            self.pool[trait.dtype] = dict()
        hdim = trait.hdim, trait.bn1
        if hdim not in self.pool[trait.dtype].keys():
            self.pool[trait.dtype][hdim] = list()
        self.pool[trait.dtype][hdim].append(copy.copy(trait))

    @property
    def api(self) -> str:
        per_dtypes = str()
        for i, dtype in enumerate(self.pool.keys()):
            per_hdim_case = str()
            for j, (hdim, hdim_v) in enumerate(self.pool[dtype].keys()):
                traits = self.pool[dtype][(hdim, hdim_v)]
                inners = str()
                for k, trait in enumerate(traits):
                    if_k = "if" if k == 0 else "else if"
                    inners = inners + FMHA_FWD_API_INNER_DISPATCH.format(
                        F_if=if_k,
                        F_vlayout=LAYOUT_MAP[trait.vlayout],
                        F_pipeline_enum=PIPELINE_ENUM_MAP[trait.pipeline_tag],
                        F_mask=get_mask_map(self.mask_impl)[trait.mask],
                        F_mask_check=get_mask_check_map(self.mask_impl)[trait.mask],
                        F_bias=BIAS_MAP[trait.bias],
                        F_bias_check=BIAS_CHECK_MAP[trait.bias],
                        F_logits_cpp=BOOL_MAP[trait.logits],
                        F_mode=MODE_MAP[trait.mode],
                        F_scheck=trait.scheck,
                        F_seqtune=trait.seqtune,
                        F_skcheck=trait.skcheck,
                        F_dcheck=trait.dcheck,
                        F_dvcheck=trait.dvcheck,
                        F_constraint=trait.constraint,
                        F_spad=BOOL_MAP[trait.spad],
                        F_skpad=BOOL_MAP[trait.skpad],
                        F_dpad=BOOL_MAP[trait.dpad],
                        F_dvpad=BOOL_MAP[trait.dvpad],
                        F_bm0=trait.bm0,
                        F_bn0=trait.bn0,
                        F_bk0=trait.bk0,
                        F_bn1=trait.bn1,
                        F_bk1=trait.bk1,
                        F_bk0max=trait.bk0max,
                        F_hdim=hdim,
                        F_dtype=FWD_DTYPE_MAP[dtype],
                    )
                if_j = "if" if j == 0 else "else if"
                per_hdim_case = per_hdim_case + FMHA_FWD_API_PER_HDIM_CASE.format(
                    F_if=if_j, F_hdim=hdim, F_hdim_v=hdim_v, F_inner_dispatch=inners
                )
            if_i = "if" if i == 0 else "else if"
            per_dtypes = per_dtypes + FMHA_FWD_API_PER_DTYPE.format(
                F_if=if_i, F_dtype=dtype, F_hdim_case=per_hdim_case
            )
        if not per_dtypes:
            per_dtypes += "    (void)t ; (void)s ; (void)a;"
        return FMHA_FWD_KERNEL_HEADER + FMHA_FWD_API.format(F_dispatch=per_dtypes)


@dataclass
class FmhaFwdTileSize:
    F_bm0: int
    F_bn0: int
    F_bk0: int
    F_bn1: int
    F_bk1: int
    F_bk0max: int
    F_rm0: int
    F_rn0: int
    F_rk0: int
    F_rm1: int
    F_rn1: int
    F_rk1: int
    F_wm0: int
    F_wn0: int
    F_wk0: int
    F_wm1: int
    F_wn1: int
    F_wk1: int
    F_occupancy: int
    F_constraint: CppConstraint = field(default_factory=CppConstraint)

    @property
    def name(self) -> str:
        return (
            f"b{self.F_bm0}x{self.F_bn0}x{self.F_bk0}x{self.F_bn1}x{self.F_bk1}x{self.F_bk0max}"
            + f"_r{self.F_rm0}x{self.F_rn0}x{self.F_rk0}_r{self.F_rm1}x{self.F_rn1}x{self.F_rk1}"
            + f"_w{self.F_wm0}x{self.F_wn0}x{self.F_wk0}_w{self.F_wm1}x{self.F_wn1}x{self.F_wk1}"
            + ("" if self.F_occupancy == -1 else f"_o{self.F_occupancy}")
        )


@dataclass
class FmhaFwdKernel:
    F_idx: int
    F_hdim: int
    F_dtype: str
    F_mode: str
    F_tile: FmhaFwdTileSize
    F_pipeline: FmhaFwdPipeline
    mask_impl: str

    @property
    def template(self) -> str:
        return FMHA_FWD_KERNEL_HEADER + FMHA_FWD_KERNEL_BODY.format(
            F_idx=self.F_idx,
            F_hdim=self.F_hdim,
            F_dtype=FWD_DTYPE_MAP[self.F_dtype],
            F_bm0=self.F_tile.F_bm0,
            F_bn0=self.F_tile.F_bn0,
            F_bk0=self.F_tile.F_bk0,
            F_bn1=self.F_tile.F_bn1,
            F_bk1=self.F_tile.F_bk1,
            F_bk0max=self.F_tile.F_bk0max,
            F_rm0=self.F_tile.F_rm0,
            F_rn0=self.F_tile.F_rn0,
            F_rk0=self.F_tile.F_rk0,
            F_rm1=self.F_tile.F_rm1,
            F_rn1=self.F_tile.F_rn1,
            F_rk1=self.F_tile.F_rk1,
            F_wm0=self.F_tile.F_wm0,
            F_wn0=self.F_tile.F_wn0,
            F_wk0=self.F_tile.F_wk0,
            F_wm1=self.F_tile.F_wm1,
            F_wn1=self.F_tile.F_wn1,
            F_wk1=self.F_tile.F_wk1,
            F_vlayout=LAYOUT_MAP[self.F_pipeline.F_vlayout],
            F_spad=BOOL_MAP[self.F_pipeline.F_spad],
            F_skpad=BOOL_MAP[self.F_pipeline.F_skpad],
            F_dpad=BOOL_MAP[self.F_pipeline.F_dpad],
            F_dvpad=BOOL_MAP[self.F_pipeline.F_dvpad],
            F_occupancy=self.F_tile.F_occupancy,
            F_pipeline_enum=PIPELINE_ENUM_MAP[self.F_pipeline.tag],
            F_mask=get_mask_map(self.mask_impl)[self.F_pipeline.F_mask],
            F_bias=BIAS_MAP[self.F_pipeline.F_bias],
            F_logits_cpp=BOOL_MAP[self.F_pipeline.F_logits],
            F_logits_variant_code=("4" if self.F_pipeline.F_logits == "t" else "0"),
            F_mode=MODE_MAP[self.F_mode],
            F_pipeline=PIPELINE_MAP[self.F_pipeline.tag],
            F_kernel_name=self.name,
        )

    @property
    def name(self) -> str:
        return (
            f"fmha_sparge_fwd_d{self.F_hdim}_{self.F_dtype}_{self.F_mode}_"
            + self.F_tile.name
            + "_"
            + self.F_pipeline.name
        )

    @property
    def filename(self) -> str:
        return self.name + ".cpp"

    def api_trait(self) -> FmhaFwdApiTrait:
        return FmhaFwdApiTrait(
            pipeline_tag=self.F_pipeline.tag,
            hdim=str(self.F_hdim),
            dtype=self.F_dtype,
            mode=self.F_mode,
            bm0=self.F_tile.F_bm0,
            bn0=self.F_tile.F_bn0,
            bk0=self.F_tile.F_bk0,
            bn1=self.F_tile.F_bn1,
            bk1=self.F_tile.F_bk1,
            bk0max=self.F_tile.F_bk0max,
            vlayout=self.F_pipeline.F_vlayout,
            mask=self.F_pipeline.F_mask,
            bias=self.F_pipeline.F_bias,
            logits=self.F_pipeline.F_logits,
            spad=self.F_pipeline.F_spad,
            skpad=self.F_pipeline.F_skpad,
            dpad=self.F_pipeline.F_dpad,
            dvpad=self.F_pipeline.F_dvpad,
            constraint=self.F_tile.F_constraint & self.F_pipeline.F_constraint,
        )


class KernelComponentFactory:
    @staticmethod
    def get_hdim_tile_size_dict(dtype: str) -> Optional[dict]:
        if dtype == "fp16" or dtype == "bf16":
            return {
                (128, 128): [
                    FmhaFwdTileSize(
                        128,
                        128,
                        32,
                        128,
                        32,
                        128,
                        4,
                        1,
                        1,
                        4,
                        1,
                        1,
                        32,
                        32,
                        16,
                        32,
                        32,
                        16,
                        -1,
                    ),
                ],
            }
        else:
            return None

    @staticmethod
    def get_pipelines(dtype, hdim, hdim_v, receipt, mask_impl) -> List[FmhaFwdPipeline]:
        pipelines = []
        # ALIBI requires causal context; logits soft-cap requires NO_BIAS (pipeline static_assert).
        bias_modes = ["no", "elementwise", "alibi"]
        if dtype in ["fp16", "bf16"]:
            for logits, mask, bias in itertools.product(
                ["f", "t"],
                get_mask_map(mask_impl).keys(),
                bias_modes,
            ):
                if bias == "alibi" and mask in ("no", "s_no"):
                    continue
                pipelines.append(
                    FmhaFwdPipeline(
                        "qr_async_sparge",
                        "row",
                        "t",
                        "f",
                        "t",
                        "t",
                        logits,
                        mask,
                        F_bias=bias,
                    )
                )
                pipelines.append(
                    FmhaFwdPipeline(
                        "qr_async_sparge",
                        "row",
                        "t",
                        "t",
                        "t",
                        "t",
                        logits,
                        mask,
                        F_bias=bias,
                    )
                )
        else:
            assert False, f"unsupported dtype for sparge: {dtype}"
        return pipelines


def get_fwd_blobs(
    kernel_filter: Optional[str], receipt, optdim_list, mask_impl
) -> Tuple[FmhaFwdApiPool, List[FmhaFwdKernel]]:
    gen = list()
    api_pool = FmhaFwdApiPool(mask_impl)

    factory = KernelComponentFactory

    del receipt
    for dtype in ["fp16", "bf16"]:
        d = factory.get_hdim_tile_size_dict(dtype)
        if d is None:
            continue
        for ((hdim, hdim_v), tiles), mode in itertools.product(d.items(), MODE_MAP.keys()):
            for tile, pipeline in itertools.product(
                tiles, factory.get_pipelines(dtype, hdim, hdim_v, 0, mask_impl)
            ):
                k = FmhaFwdKernel(
                    F_idx=2,
                    F_hdim=hdim,
                    F_dtype=dtype,
                    F_mode=mode,
                    F_tile=tile,
                    F_pipeline=pipeline,
                    mask_impl=mask_impl,
                )
                if kernel_filter != "":
                    if not fnmatch.fnmatch(k.name, kernel_filter):
                        continue
                if optdim_list != [-1]:
                    if hdim not in optdim_list:
                        continue
                api_pool.register_traits(k.api_trait())
                gen.append(k)

    return (api_pool, gen)


def write_single_fwd_kernel(kernel: FmhaFwdKernel, autogen_dir: Path) -> None:
    update_file(autogen_dir / kernel.filename, kernel.template)


def write_fwd_api(api_pool: FmhaFwdApiPool, autogen_dir: Path) -> None:
    update_file(autogen_dir / FMHA_FWD_API_FILENAME, api_pool.api)


def write_blobs(
    output_dir: Path, kernel_filter: str, receipt, optdim_list, mask_impl
) -> None:
    api_pool, kernels = get_fwd_blobs(kernel_filter, receipt, optdim_list, mask_impl)
    for kernel in kernels:
        write_single_fwd_kernel(kernel, output_dir)
    write_fwd_api(api_pool, output_dir)


def list_blobs(
    file_path: Path, kernel_filter: str, receipt, optdim_list, mask_impl
) -> None:
    with file_path.open("a") as f:
        _, kernels = get_fwd_blobs(kernel_filter, receipt, optdim_list, mask_impl)
        for kernel in kernels:
            f.write(str(file_path.parent / GEN_DIR / kernel.filename) + "\n")
        f.write(str(file_path.parent / GEN_DIR / FMHA_FWD_API_FILENAME) + "\n")
