// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RMSNORMATTRIBUTES_HIPDNN_DATA_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_RMSNORMATTRIBUTES_HIPDNN_DATA_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace hipdnn_data_sdk {
namespace data_objects {

struct RmsnormAttributes;
struct RmsnormAttributesBuilder;
struct RmsnormAttributesT;

bool operator==(const RmsnormAttributesT &lhs, const RmsnormAttributesT &rhs);
bool operator!=(const RmsnormAttributesT &lhs, const RmsnormAttributesT &rhs);

struct RmsnormAttributesT : public ::flatbuffers::NativeTable {
  typedef RmsnormAttributes TableType;
  int64_t x_tensor_uid = 0;
  int64_t scale_tensor_uid = 0;
  int64_t epsilon_tensor_uid = 0;
  int64_t y_tensor_uid = 0;
  ::flatbuffers::Optional<int64_t> inv_rms_tensor_uid = ::flatbuffers::nullopt;
};

struct RmsnormAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RmsnormAttributesT NativeTableType;
  typedef RmsnormAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X_TENSOR_UID = 4,
    VT_SCALE_TENSOR_UID = 6,
    VT_EPSILON_TENSOR_UID = 8,
    VT_Y_TENSOR_UID = 10,
    VT_INV_RMS_TENSOR_UID = 12
  };
  int64_t x_tensor_uid() const {
    return GetField<int64_t>(VT_X_TENSOR_UID, 0);
  }
  bool mutate_x_tensor_uid(int64_t _x_tensor_uid = 0) {
    return SetField<int64_t>(VT_X_TENSOR_UID, _x_tensor_uid, 0);
  }
  int64_t scale_tensor_uid() const {
    return GetField<int64_t>(VT_SCALE_TENSOR_UID, 0);
  }
  bool mutate_scale_tensor_uid(int64_t _scale_tensor_uid = 0) {
    return SetField<int64_t>(VT_SCALE_TENSOR_UID, _scale_tensor_uid, 0);
  }
  int64_t epsilon_tensor_uid() const {
    return GetField<int64_t>(VT_EPSILON_TENSOR_UID, 0);
  }
  bool mutate_epsilon_tensor_uid(int64_t _epsilon_tensor_uid = 0) {
    return SetField<int64_t>(VT_EPSILON_TENSOR_UID, _epsilon_tensor_uid, 0);
  }
  int64_t y_tensor_uid() const {
    return GetField<int64_t>(VT_Y_TENSOR_UID, 0);
  }
  bool mutate_y_tensor_uid(int64_t _y_tensor_uid = 0) {
    return SetField<int64_t>(VT_Y_TENSOR_UID, _y_tensor_uid, 0);
  }
  ::flatbuffers::Optional<int64_t> inv_rms_tensor_uid() const {
    return GetOptional<int64_t, int64_t>(VT_INV_RMS_TENSOR_UID);
  }
  bool mutate_inv_rms_tensor_uid(int64_t _inv_rms_tensor_uid) {
    return SetField<int64_t>(VT_INV_RMS_TENSOR_UID, _inv_rms_tensor_uid);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_X_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_SCALE_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_EPSILON_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_Y_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_INV_RMS_TENSOR_UID, 8) &&
           verifier.EndTable();
  }
  RmsnormAttributesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(RmsnormAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<RmsnormAttributes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RmsnormAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct RmsnormAttributesBuilder {
  typedef RmsnormAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x_tensor_uid(int64_t x_tensor_uid) {
    fbb_.AddElement<int64_t>(RmsnormAttributes::VT_X_TENSOR_UID, x_tensor_uid, 0);
  }
  void add_scale_tensor_uid(int64_t scale_tensor_uid) {
    fbb_.AddElement<int64_t>(RmsnormAttributes::VT_SCALE_TENSOR_UID, scale_tensor_uid, 0);
  }
  void add_epsilon_tensor_uid(int64_t epsilon_tensor_uid) {
    fbb_.AddElement<int64_t>(RmsnormAttributes::VT_EPSILON_TENSOR_UID, epsilon_tensor_uid, 0);
  }
  void add_y_tensor_uid(int64_t y_tensor_uid) {
    fbb_.AddElement<int64_t>(RmsnormAttributes::VT_Y_TENSOR_UID, y_tensor_uid, 0);
  }
  void add_inv_rms_tensor_uid(int64_t inv_rms_tensor_uid) {
    fbb_.AddElement<int64_t>(RmsnormAttributes::VT_INV_RMS_TENSOR_UID, inv_rms_tensor_uid);
  }
  explicit RmsnormAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RmsnormAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RmsnormAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RmsnormAttributes> CreateRmsnormAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t x_tensor_uid = 0,
    int64_t scale_tensor_uid = 0,
    int64_t epsilon_tensor_uid = 0,
    int64_t y_tensor_uid = 0,
    ::flatbuffers::Optional<int64_t> inv_rms_tensor_uid = ::flatbuffers::nullopt) {
  RmsnormAttributesBuilder builder_(_fbb);
  if(inv_rms_tensor_uid) { builder_.add_inv_rms_tensor_uid(*inv_rms_tensor_uid); }
  builder_.add_y_tensor_uid(y_tensor_uid);
  builder_.add_epsilon_tensor_uid(epsilon_tensor_uid);
  builder_.add_scale_tensor_uid(scale_tensor_uid);
  builder_.add_x_tensor_uid(x_tensor_uid);
  return builder_.Finish();
}

::flatbuffers::Offset<RmsnormAttributes> CreateRmsnormAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const RmsnormAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const RmsnormAttributesT &lhs, const RmsnormAttributesT &rhs) {
  return
      (lhs.x_tensor_uid == rhs.x_tensor_uid) &&
      (lhs.scale_tensor_uid == rhs.scale_tensor_uid) &&
      (lhs.epsilon_tensor_uid == rhs.epsilon_tensor_uid) &&
      (lhs.y_tensor_uid == rhs.y_tensor_uid) &&
      (lhs.inv_rms_tensor_uid == rhs.inv_rms_tensor_uid);
}

inline bool operator!=(const RmsnormAttributesT &lhs, const RmsnormAttributesT &rhs) {
    return !(lhs == rhs);
}


inline RmsnormAttributesT *RmsnormAttributes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<RmsnormAttributesT>(new RmsnormAttributesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void RmsnormAttributes::UnPackTo(RmsnormAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x_tensor_uid(); _o->x_tensor_uid = _e; }
  { auto _e = scale_tensor_uid(); _o->scale_tensor_uid = _e; }
  { auto _e = epsilon_tensor_uid(); _o->epsilon_tensor_uid = _e; }
  { auto _e = y_tensor_uid(); _o->y_tensor_uid = _e; }
  { auto _e = inv_rms_tensor_uid(); _o->inv_rms_tensor_uid = _e; }
}

inline ::flatbuffers::Offset<RmsnormAttributes> RmsnormAttributes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const RmsnormAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateRmsnormAttributes(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<RmsnormAttributes> CreateRmsnormAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const RmsnormAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const RmsnormAttributesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x_tensor_uid = _o->x_tensor_uid;
  auto _scale_tensor_uid = _o->scale_tensor_uid;
  auto _epsilon_tensor_uid = _o->epsilon_tensor_uid;
  auto _y_tensor_uid = _o->y_tensor_uid;
  auto _inv_rms_tensor_uid = _o->inv_rms_tensor_uid;
  return hipdnn_data_sdk::data_objects::CreateRmsnormAttributes(
      _fbb,
      _x_tensor_uid,
      _scale_tensor_uid,
      _epsilon_tensor_uid,
      _y_tensor_uid,
      _inv_rms_tensor_uid);
}

}  // namespace data_objects
}  // namespace hipdnn_data_sdk

#endif  // FLATBUFFERS_GENERATED_RMSNORMATTRIBUTES_HIPDNN_DATA_SDK_DATA_OBJECTS_H_
