# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

cmake_minimum_required(VERSION 3.25.2)
project(rocm-libraries LANGUAGES C CXX Fortran ASM)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")

include(GNUInstallDirs)
include(disableable_option)
include(add_subdirectory_with_message)

# --- Options and cache variables ---

option(ROCM_LIBRARIES_SUPERBUILD "Enable superbuild mode" ON)
option(ROCM_LIBRARIES_DISABLE_ALL "Disable all libraries" OFF)

# Shared
disableable_option(ENABLE_MXDATAGENERATOR "Enable mxdatagenerator" ON)
disableable_option(ENABLE_ROCROLLER "Enable rocroller" ON)
disableable_option(ENABLE_TENSILE "Enable tensile" OFF)
disableable_option(ENABLE_HIPBLAS_COMMON "Enable hipblas-common" ON)

# Projects
disableable_option(ENABLE_ROCBLAS "Enable rocblas" OFF)
disableable_option(ENABLE_ROCFFT "Enable rocfft" OFF)
disableable_option(ENABLE_ROCPRIM "Enable rocprim" OFF)
disableable_option(ENABLE_ROCRAND "Enable rocrand" OFF)
disableable_option(ENABLE_ROCSOLVER "Enable rocsolver" OFF)
disableable_option(ENABLE_ROCSPARSE "Enable rocsparse" OFF)
disableable_option(ENABLE_ROCTHRUST "Enable rocthrust" OFF)

disableable_option(ENABLE_HIPCUB "Enable hipcub" OFF)
disableable_option(ENABLE_HIPFFT "Enable hipfft" OFF)
disableable_option(ENABLE_HIPRAND "Enable hiprand" OFF)
disableable_option(ENABLE_HIPSOLVER "Enable hipsolver" OFF)
disableable_option(ENABLE_HIPSPARSE "Enable hipsparse" OFF)

disableable_option(ENABLE_CK "Enable composablekernel" OFF)
disableable_option(ENABLE_MIOPEN "Enable miopen" OFF)

disableable_option(ENABLE_HIPBLASLT "Enable hipblaslt" OFF)
disableable_option(ENABLE_HIPSPARSELT "Enable hipsparselt" OFF)

# NOTE: This is a temp option to reduce warnings generated by rocm-cmake. However, these warnings
# are reasonable and should be addressed.
option(ROCM_WARN_TOOLCHAIN_VAR "Warn if the toolchain version is not supported" OFF)

# --- Add subdirectories ---

if(ENABLE_MXDATAGENERATOR)
    add_subdirectory_with_message(shared/mxdatagenerator EXPECT_TARGET roc::mxDataGenerator)
endif()

if(ENABLE_HIPBLAS_COMMON)
    add_subdirectory_with_message(projects/hipblas-common EXPECT_TARGET roc::hipblas-common)
endif()

if(ENABLE_ROCROLLER)
    # required deps: pip install pytest-cmake
    set(ROCROLLER_ENABLE_FETCH ON)
    add_subdirectory_with_message(shared/rocroller EXPECT_TARGET roc::rocroller)
endif()

# --- Projects not yet configured for superbuild ---

if(ENABLE_TENSILE)
    message(FATAL_ERROR "tensile is not yet supported in the superbuild")
    # add_subdirectory_with_message(shared/tensile/next-cmake EXPECT_TARGET roc::tensile-host)
endif()

if(ENABLE_ROCPRIM)
    message(FATAL_ERROR "rocprim is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/rocprim EXPECT_TARGET rocprim)
endif()

if(ENABLE_ROCRAND)
    message(FATAL_ERROR "rocrand is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/rocrand EXPECT_TARGET rocrand)
endif()

if(ENABLE_ROCTHRUST)
    message(FATAL_ERROR "rocthrust is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/rocthrust EXPECT_TARGET rocthrust)
endif()

if(ENABLE_ROCFFT)
    message(FATAL_ERROR "rocfft is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/rocfft EXPECT_TARGET roc::rocfft)
endif()

if(ENABLE_ROCSPARSE)
    message(FATAL_ERROR "rocsparse is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/rocsparse EXPECT_TARGET roc::rocsparse)
endif()

if(ENABLE_HIPCUB)
    message(FATAL_ERROR "hipcub is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/hipcub EXPECT_TARGET hipcub)
endif()

if(ENABLE_HIPRAND)
    message(FATAL_ERROR "hiprand is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/hiprand EXPECT_TARGET hip::hiprand)
endif()

if(ENABLE_HIPFFT)
    message(FATAL_ERROR "hipfft is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/hipfft EXPECT_TARGET hip::hipfft)
endif()

if(ENABLE_HIPSPARSE)
    message(FATAL_ERROR "hipsparse is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/hipsparse EXPECT_TARGET roc::hipsparse)
endif()

if(ENABLE_CK)
    message(FATAL_ERROR "composablekernel is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/composablekernel EXPECT_TARGET roc::composablekernel)
endif()

if(ENABLE_MIOPEN)
    message(FATAL_ERROR "miopen is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/miopen EXPECT_TARGET roc::miopen)
endif()

if(ENABLE_HIPBLASLT)
    message(FATAL_ERROR "hipblaslt is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/hipblaslt EXPECT_TARGET roc::hipblaslt)
endif()

if(ENABLE_HIPBLAS)
    message(FATAL_ERROR "hipblas is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/hipblas EXPECT_TARGET roc::hipblas)
endif()

if(ENABLE_HIPSOLVER)
    message(FATAL_ERROR "hipsolver is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/hipsolver EXPECT_TARGET roc::hipsolver)
endif()

if(ENABLE_HIPSPARSELT)
    message(FATAL_ERROR "hipsparselt is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/hipsparselt EXPECT_TARGET roc::hipsparselt)
endif()

if(ENABLE_ROCBLAS)
    message(FATAL_ERROR "rocblas is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/rocblas EXPECT_TARGET roc::rocblas)
endif()

if(ENABLE_ROCSOLVER)
    message(FATAL_ERROR "rocsolver is not yet supported in the superbuild")
    # add_subdirectory_with_message(projects/rocsolver EXPECT_TARGET roc::rocsolver)
endif()
