// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

#pragma once

// Configuration set for the 32-channel grouped direct convolution kernel (v2).
// This header holds ONLY the instantiated configuration data (configs_map /
// KernelConfigurations). The Config struct it parameterizes, and all kernel
// implementation logic, live in kernel/impl/grouped_32c_tile_conv_impl_v2.hpp,
// which defines Config and then includes this header.

#include "ck_tile/ops/direct_convolution/utils/common.hpp"
#include "ck_tile/ops/direct_convolution/utils/conv_params.hpp"
#include "ck_tile/ops/direct_convolution/utils/config_map.hpp"

namespace ck_tile::direct_conv::grouped_32c_tile::v2 {

// All instantiated configurations.
//
// Layout: 4 variant groups × 16 configs each = 64 configs total.
// Each group has 8 Dgrad + 8 Fprop configs:
//   waves_per_wg = 16,14,12,10,8,6,4,2  (must be even)
//
// Group 0 (indices  0-15): Cyclic-shift swizzle, direct DRAM epilogue
// Group 1 (indices 16-31): Cyclic-shift swizzle, LDS-staged epilogue
// Group 2 (indices 32-47): XOR swizzle, direct DRAM epilogue
// Group 3 (indices 48-63): XOR swizzle, LDS-staged epilogue
template <DataType DT = DataType::fp16>
struct KernelConfigurations
{
    // TODO: Prune the configurations: we need 2, 4, 8, 16 waves per workgroup.
    static constexpr auto configs_map = make_config_map<Config<DT>>({
        // ---- Group 0: No swizzle, direct DRAM epilogue ----
        // Dgrad (keys 0-7)
        {0, {.waves_per_wg = 16, .direction = Direction::Dgrad}},
        {1, {.waves_per_wg = 14, .direction = Direction::Dgrad}},
        {2, {.waves_per_wg = 12, .direction = Direction::Dgrad}},
        {3, {.waves_per_wg = 10, .direction = Direction::Dgrad}},
        {4, {.waves_per_wg = 8, .direction = Direction::Dgrad}},
        {5, {.waves_per_wg = 6, .direction = Direction::Dgrad}},
        {6, {.waves_per_wg = 4, .direction = Direction::Dgrad}},
        {7, {.waves_per_wg = 2, .direction = Direction::Dgrad}},
        // Fprop (keys 8-15)
        {8, {.waves_per_wg = 16}},
        {9, {.waves_per_wg = 14}},
        {10, {.waves_per_wg = 12}},
        {11, {.waves_per_wg = 10}},
        {12, {.waves_per_wg = 8}},
        {13, {.waves_per_wg = 6}},
        {14, {.waves_per_wg = 4}},
        {15, {.waves_per_wg = 2}},
        // ---- Group 1: No swizzle, LDS-staged epilogue ----
        // Dgrad (keys 16-23)
        {16,
         {.waves_per_wg = 16,
          .direction    = Direction::Dgrad,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {17,
         {.waves_per_wg = 14,
          .direction    = Direction::Dgrad,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {18,
         {.waves_per_wg = 12,
          .direction    = Direction::Dgrad,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {19,
         {.waves_per_wg = 10,
          .direction    = Direction::Dgrad,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {20,
         {.waves_per_wg = 8,
          .direction    = Direction::Dgrad,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {21,
         {.waves_per_wg = 6,
          .direction    = Direction::Dgrad,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {22,
         {.waves_per_wg = 4,
          .direction    = Direction::Dgrad,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {23,
         {.waves_per_wg = 2,
          .direction    = Direction::Dgrad,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        // Fprop (keys 24-31)
        {24, {.waves_per_wg = 16, .epilogue = EpilogueType::RegistersToLdsToGlobalMemory}},
        {25, {.waves_per_wg = 14, .epilogue = EpilogueType::RegistersToLdsToGlobalMemory}},
        {26, {.waves_per_wg = 12, .epilogue = EpilogueType::RegistersToLdsToGlobalMemory}},
        {27, {.waves_per_wg = 10, .epilogue = EpilogueType::RegistersToLdsToGlobalMemory}},
        {28, {.waves_per_wg = 8, .epilogue = EpilogueType::RegistersToLdsToGlobalMemory}},
        {29, {.waves_per_wg = 6, .epilogue = EpilogueType::RegistersToLdsToGlobalMemory}},
        {30, {.waves_per_wg = 4, .epilogue = EpilogueType::RegistersToLdsToGlobalMemory}},
        {31, {.waves_per_wg = 2, .epilogue = EpilogueType::RegistersToLdsToGlobalMemory}},
        // ---- Group 2: XOR swizzle, direct DRAM epilogue ----
        // Dgrad (keys 32-39)
        {32, {.waves_per_wg = 16, .direction = Direction::Dgrad, .swizzle_type = SwizzleType::XOR}},
        {33, {.waves_per_wg = 14, .direction = Direction::Dgrad, .swizzle_type = SwizzleType::XOR}},
        {34, {.waves_per_wg = 12, .direction = Direction::Dgrad, .swizzle_type = SwizzleType::XOR}},
        {35, {.waves_per_wg = 10, .direction = Direction::Dgrad, .swizzle_type = SwizzleType::XOR}},
        {36, {.waves_per_wg = 8, .direction = Direction::Dgrad, .swizzle_type = SwizzleType::XOR}},
        {37, {.waves_per_wg = 6, .direction = Direction::Dgrad, .swizzle_type = SwizzleType::XOR}},
        {38, {.waves_per_wg = 4, .direction = Direction::Dgrad, .swizzle_type = SwizzleType::XOR}},
        {39, {.waves_per_wg = 2, .direction = Direction::Dgrad, .swizzle_type = SwizzleType::XOR}},
        // Fprop (keys 40-47)
        {40, {.waves_per_wg = 16, .swizzle_type = SwizzleType::XOR}},
        {41, {.waves_per_wg = 14, .swizzle_type = SwizzleType::XOR}},
        {42, {.waves_per_wg = 12, .swizzle_type = SwizzleType::XOR}},
        {43, {.waves_per_wg = 10, .swizzle_type = SwizzleType::XOR}},
        {44, {.waves_per_wg = 8, .swizzle_type = SwizzleType::XOR}},
        {45, {.waves_per_wg = 6, .swizzle_type = SwizzleType::XOR}},
        {46, {.waves_per_wg = 4, .swizzle_type = SwizzleType::XOR}},
        {47, {.waves_per_wg = 2, .swizzle_type = SwizzleType::XOR}},
        // ---- Group 3: XOR swizzle, LDS-staged epilogue ----
        // Dgrad (keys 48-55)
        {48,
         {.waves_per_wg = 16,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {49,
         {.waves_per_wg = 14,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {50,
         {.waves_per_wg = 12,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {51,
         {.waves_per_wg = 10,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {52,
         {.waves_per_wg = 8,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {53,
         {.waves_per_wg = 6,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {54,
         {.waves_per_wg = 4,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {55,
         {.waves_per_wg = 2,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        // Fprop (keys 56-63)
        {56,
         {.waves_per_wg = 16,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {57,
         {.waves_per_wg = 14,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {58,
         {.waves_per_wg = 12,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {59,
         {.waves_per_wg = 10,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {60,
         {.waves_per_wg = 8,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {61,
         {.waves_per_wg = 6,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {62,
         {.waves_per_wg = 4,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {63,
         {.waves_per_wg = 2,
          .swizzle_type = SwizzleType::XOR,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        // Cyclic shift instances (keys 64-67)
        {64,
         {.waves_per_wg = 8,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {65,
         {.waves_per_wg = 8,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToGlobalMemory}},
        {66,
         {.waves_per_wg = 8,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {67,
         {.waves_per_wg = 8,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToGlobalMemory}},
        // ---- Group 4: CyclicShift, small vector sizes for padding cases ----
        // Dgrad CyclicShift (keys 68-72) — TODO: Remove vec_size 16 and 8
        {68,
         {.waves_per_wg = 8,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory,
          .vector_size  = 16}},
        {69,
         {.waves_per_wg = 8,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory,
          .vector_size  = 8}},
        {70,
         {.waves_per_wg = 8,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory,
          .vector_size  = 4}},
        {71,
         {.waves_per_wg = 8,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory,
          .vector_size  = 2}},
        {72,
         {.waves_per_wg = 8,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory,
          .vector_size  = 1}},
        // Fprop CyclicShift (keys 73-77) — TODO: Remove vec_size 16 and 8
        {73,
         {.waves_per_wg = 8,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory,
          .vector_size  = 16}},
        {74,
         {.waves_per_wg = 8,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory,
          .vector_size  = 8}},
        {75,
         {.waves_per_wg = 8,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory,
          .vector_size  = 4}},
        {76,
         {.waves_per_wg = 8,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory,
          .vector_size  = 2}},
        {77,
         {.waves_per_wg = 8,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory,
          .vector_size  = 1}},
        // No-swizzle fallback for padding (keys 78-79)
        {78,
         {.waves_per_wg = 8,
          .direction    = Direction::Dgrad,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory,
          .vector_size  = 1}},
        {79,
         {.waves_per_wg = 8,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory,
          .vector_size  = 1}},
        // Additional cyclic-shift instances (keys 80-83)
        {80,
         {.waves_per_wg = 4,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {81,
         {.waves_per_wg = 4,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToGlobalMemory}},
        {82,
         {.waves_per_wg = 4,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToLdsToGlobalMemory}},
        {83,
         {.waves_per_wg = 4,
          .direction    = Direction::Dgrad,
          .swizzle_type = SwizzleType::CyclicShift,
          .epilogue     = EpilogueType::RegistersToGlobalMemory}},
    });
    static_assert(configs_map.is_valid(),
                  "Duplicate or negative config key in grouped_32c_tile configs_map");
    static constexpr int NUM_CONFIGS = configs_map.size;
}; // KernelConfigurations

} // namespace ck_tile::direct_conv::grouped_32c_tile::v2
