// Copyright Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

// Regression coverage for ROCM-31016 (https://github.com/ROCm/hipBLASLt/issues/2299):
// bf16 hipblasLtMatmul silently drops stores to D on gfx950 for certain large
// shapes. The original reproduction session initially suspected a single
// root cause (the buffer-store SRD's num_records ceiling), but a deeper
// investigation (with a Stream-K maintainer) found the actual reproduced
// corruption is a *different*, Stream-K-specific bug. Both are fixed, in
// ContractionProblemPredicates.hpp, but only the second one is what this
// PR's confirmed hardware reproduction (M=33,554,560, N=256, K=48, bf16 NN)
// exercises:
//
//   1. BufferStoreOffsetLimitCheck: the SRD base *is* re-based per workgroup
//      along N (computeStoreSrdStart, KernelWriterAssembly.py), so only one
//      MacroTile1's worth of column extent needs to fit under the SRD's
//      num_records ceiling (BufferOOB, 0xfffff000), not the full D extent.
//      This predicate's original std::min(MacroTile1, size[1]) formula was
//      correct; this PR only corrects its threshold constant (0xfffff000,
//      matching KernelWriterAssembly.py's BufferOOB sentinel, instead of the
//      looser 2^32 it used before). Realistic MacroTile1 values are far too
//      small for this predicate to ever reject a real end-to-end shape, so
//      it has no dedicated end-to-end test here; see Predicates_test.cpp
//      for direct unit coverage of the formula and threshold.
//
//   2. StreamKWorkgroupNumberCheck (new): resolveStreamKSettings() /
//      getSKGridImpl() (ContractionSolution.cpp) has several launch-time
//      fallbacks (workspace too small for the ideal partial-tile reduction,
//      a tree-fixup 24-bit bounds guard, a fixed-grid debug override, ...)
//      that hand a Stream-K kernel a one-workgroup-per-tile grid instead of
//      its normal CU-scaled one. When the resulting tile count itself is
//      large enough (~2^24, the same grid-dimension limit
//      WorkgroupNumberCheck already enforces for non-Stream-K solutions),
//      the actual kernel launch's 32-bit work-item count overflows, and the
//      GPU either rejects the launch or runs a much smaller grid than
//      intended, leaving most of D silently unwritten. Confirmed directly
//      on real gfx950 (MI350X) hardware: an exhaustive getAllAlgos sweep
//      found dozens of MacroTile-16x16 Stream-K-static (SK3) solutions that
//      ran correctly up to tiles == 2^24 exactly and left most of a 16 GiB D
//      unwritten (~32K of ~8.59B elements written) one shape past it.
//
// IMPORTANT CAVEAT: StreamKWorkgroupNumberCheck is a brand-new predicate
// type. Existing, already-tuned Tensile logic files do not reference it, so
// rebuilding hipBLASLt from this PR alone does not retroactively attach it
// to any already-shipped solution; that requires the gfx950 (and other
// Stream-K-capable architectures') production logic files to be
// regenerated by whoever owns that tuning/release pipeline. Until that
// regeneration happens, the exact M=33,554,560 shape reproduced here can
// still corrupt output on a stock hipBLASLt build; this test therefore only
// covers the safe/sanity case end to end. The fix itself, and the exact
// tiles == 2^24 boundary, are covered directly (and hardware-validated) in
// tensilelite/tests/Predicates_test.cpp.

#include <gtest/gtest.h>

#include <hip/hip_bf16.h>
#include <hip/hip_runtime.h>
#include <hipblaslt/hipblaslt.h>

#include <cmath>
#include <cstdint>
#include <functional>
#include <string>
#include <vector>

namespace
{
    bool gpuAvailable()
    {
        int deviceCount = 0;
        return hipGetDeviceCount(&deviceCount) == hipSuccess && deviceCount > 0;
    }

    // gcnArchName carries feature suffixes (e.g. "gfx950:sramecc+:xnack-") that
    // a plain "==" against "gfx950" would miss.
    std::string gpuArchFamily()
    {
        hipDeviceProp_t props{};
        int             device = 0;
        if(hipGetDevice(&device) != hipSuccess
           || hipGetDeviceProperties(&props, device) != hipSuccess)
            return "unknown";
        std::string arch = props.gcnArchName;
        return arch.substr(0, arch.find(':'));
    }

    __global__ void fillConstant(__hip_bfloat16* p, size_t n, float v)
    {
        for(size_t i = blockIdx.x * (size_t)blockDim.x + threadIdx.x; i < n;
            i += (size_t)gridDim.x * blockDim.x)
            p[i] = __float2bfloat16(v);
    }

    // Counts D elements that are still NaN (never written by the kernel) and,
    // separately, elements that were written but do not equal the expected
    // bit-exact value (a wrong, rather than silently-dropped, store).
    __global__ void scanAgainstExpected(const __hip_bfloat16* d,
                                         size_t                n,
                                         float                 expected,
                                         unsigned long long*   unwrittenCount,
                                         unsigned long long*   wrongCount)
    {
        for(size_t i = blockIdx.x * (size_t)blockDim.x + threadIdx.x; i < n;
            i += (size_t)gridDim.x * blockDim.x)
        {
            float v = __bfloat162float(d[i]);
            if(isnan(v))
                atomicAdd(unwrittenCount, 1ull);
            else if(v != expected)
                atomicAdd(wrongCount, 1ull);
        }
    }

    struct MatmulOutcome
    {
        hipblasStatus_t    heuristicStatus = HIPBLAS_STATUS_INTERNAL_ERROR;
        int                foundAlgoCount  = 0;
        bool               ran             = false;
        // True only if the post-run verification scan itself completed
        // cleanly (kernel launch + both hipMemcpy's succeeded). Callers must
        // check this before trusting unwrittenCount/wrongCount == 0: a
        // verification-side failure must not be misread as "nothing wrong".
        bool               verified        = false;
        unsigned long long unwrittenCount  = 0;
        unsigned long long wrongCount      = 0;
        size_t             totalElements   = 0;
    };

    // Runs `cleanups` in reverse (LIFO) order when it goes out of scope, so
    // every early return below still frees exactly the resources that were
    // successfully allocated up to that point: no leaks on any path.
    struct ScopeGuard
    {
        std::vector<std::function<void()>>& cleanups;
        ~ScopeGuard()
        {
            for(auto it = cleanups.rbegin(); it != cleanups.rend(); ++it)
                (*it)();
        }
    };

    // bf16 NN matmul, A and B filled with 1.0 everywhere, alpha=1, beta=0, so
    // the mathematically-correct D is uniformly K (exactly representable in
    // bf16 as long as K itself is, which every K used below satisfies). D is
    // pre-filled with NaN so an element left NaN after the call proves the
    // kernel never wrote it (the ROCM-31016 signature), distinct from a
    // wrong-but-written value.
    MatmulOutcome runConstantMatmul(int64_t M, int64_t N, int64_t K)
    {
        MatmulOutcome outcome;
        outcome.totalElements = (size_t)M * (size_t)N;

        std::vector<std::function<void()>> cleanups;
        ScopeGuard                         guard{cleanups};

        __hip_bfloat16* A = nullptr;
        if(hipMalloc(&A, (size_t)M * K * sizeof(*A)) != hipSuccess)
            return outcome;
        cleanups.push_back([A] { static_cast<void>(hipFree(A)); });

        __hip_bfloat16* B = nullptr;
        if(hipMalloc(&B, (size_t)K * N * sizeof(*B)) != hipSuccess)
            return outcome;
        cleanups.push_back([B] { static_cast<void>(hipFree(B)); });

        __hip_bfloat16* D = nullptr;
        if(hipMalloc(&D, (size_t)M * N * sizeof(*D)) != hipSuccess)
            return outcome;
        cleanups.push_back([D] { static_cast<void>(hipFree(D)); });

        fillConstant<<<2048, 256>>>(A, (size_t)M * K, 1.0f);
        fillConstant<<<2048, 256>>>(B, (size_t)K * N, 1.0f);
        fillConstant<<<4096, 256>>>(D, (size_t)M * N, std::nanf(""));
        if(hipDeviceSynchronize() != hipSuccess)
            return outcome;

        hipblasLtHandle_t handle;
        if(hipblasLtCreate(&handle) != HIPBLAS_STATUS_SUCCESS)
            return outcome;
        cleanups.push_back([handle] { static_cast<void>(hipblasLtDestroy(handle)); });

        hipblasLtMatrixLayout_t la;
        if(hipblasLtMatrixLayoutCreate(&la, HIP_R_16BF, M, K, M) != HIPBLAS_STATUS_SUCCESS)
            return outcome;
        cleanups.push_back([la] { static_cast<void>(hipblasLtMatrixLayoutDestroy(la)); });

        hipblasLtMatrixLayout_t lb;
        if(hipblasLtMatrixLayoutCreate(&lb, HIP_R_16BF, K, N, K) != HIPBLAS_STATUS_SUCCESS)
            return outcome;
        cleanups.push_back([lb] { static_cast<void>(hipblasLtMatrixLayoutDestroy(lb)); });

        hipblasLtMatrixLayout_t ld;
        if(hipblasLtMatrixLayoutCreate(&ld, HIP_R_16BF, M, N, M) != HIPBLAS_STATUS_SUCCESS)
            return outcome;
        cleanups.push_back([ld] { static_cast<void>(hipblasLtMatrixLayoutDestroy(ld)); });

        hipblasLtMatmulDesc_t desc;
        if(hipblasLtMatmulDescCreate(&desc, HIPBLAS_COMPUTE_32F, HIP_R_32F)
           != HIPBLAS_STATUS_SUCCESS)
            return outcome;
        cleanups.push_back([desc] { static_cast<void>(hipblasLtMatmulDescDestroy(desc)); });

        hipblasOperation_t opN = HIPBLAS_OP_N;
        if(hipblasLtMatmulDescSetAttribute(desc, HIPBLASLT_MATMUL_DESC_TRANSA, &opN, sizeof(opN))
           != HIPBLAS_STATUS_SUCCESS)
            return outcome;
        if(hipblasLtMatmulDescSetAttribute(desc, HIPBLASLT_MATMUL_DESC_TRANSB, &opN, sizeof(opN))
           != HIPBLAS_STATUS_SUCCESS)
            return outcome;

        void*  workspace = nullptr;
        size_t wsize      = 128ull << 20;
        if(hipMalloc(&workspace, wsize) != hipSuccess)
            return outcome;
        cleanups.push_back([workspace] { static_cast<void>(hipFree(workspace)); });

        hipblasLtMatmulPreference_t pref;
        if(hipblasLtMatmulPreferenceCreate(&pref) != HIPBLAS_STATUS_SUCCESS)
            return outcome;
        cleanups.push_back(
            [pref] { static_cast<void>(hipblasLtMatmulPreferenceDestroy(pref)); });
        if(hipblasLtMatmulPreferenceSetAttribute(
               pref, HIPBLASLT_MATMUL_PREF_MAX_WORKSPACE_BYTES, &wsize, sizeof(wsize))
           != HIPBLAS_STATUS_SUCCESS)
            return outcome;

        hipblasLtMatmulHeuristicResult_t heuristic[1];
        int                              found = 0;
        outcome.heuristicStatus                = hipblasLtMatmulAlgoGetHeuristic(
            handle, desc, la, lb, ld, ld, pref, 1, heuristic, &found);
        outcome.foundAlgoCount = found;

        if(found > 0 && outcome.heuristicStatus == HIPBLAS_STATUS_SUCCESS)
        {
            float alpha = 1.0f, beta = 0.0f;
            hipblasStatus_t runStatus
                = hipblasLtMatmul(handle, desc, &alpha, A, la, B, lb, &beta, D, ld, D, ld,
                                  &heuristic[0].algo, workspace, wsize, nullptr);
            outcome.ran = (runStatus == HIPBLAS_STATUS_SUCCESS
                           && hipDeviceSynchronize() == hipSuccess);
        }

        if(outcome.ran)
        {
            unsigned long long *unwrittenCount = nullptr, *wrongCount = nullptr;
            bool                verifyOk       = hipMalloc(&unwrittenCount, sizeof(*unwrittenCount))
                                    == hipSuccess
                             && hipMalloc(&wrongCount, sizeof(*wrongCount)) == hipSuccess;
            if(verifyOk)
                verifyOk = hipMemset(unwrittenCount, 0, sizeof(*unwrittenCount)) == hipSuccess
                           && hipMemset(wrongCount, 0, sizeof(*wrongCount)) == hipSuccess;
            if(verifyOk)
            {
                scanAgainstExpected<<<4096, 256>>>(
                    D, (size_t)M * N, (float)K, unwrittenCount, wrongCount);
                verifyOk = hipMemcpy(&outcome.unwrittenCount, unwrittenCount,
                                      sizeof(outcome.unwrittenCount), hipMemcpyDeviceToHost)
                               == hipSuccess
                           && hipMemcpy(&outcome.wrongCount, wrongCount,
                                        sizeof(outcome.wrongCount), hipMemcpyDeviceToHost)
                                  == hipSuccess;
            }
            outcome.verified = verifyOk;
            if(unwrittenCount)
                static_cast<void>(hipFree(unwrittenCount));
            if(wrongCount)
                static_cast<void>(hipFree(wrongCount));
        }

        return outcome;
    }

#define SKIP_UNLESS_GFX950()                                                       \
    do                                                                             \
    {                                                                              \
        if(!gpuAvailable())                                                        \
            GTEST_SKIP() << "no GPU available";                                    \
        if(gpuArchFamily() != "gfx950")                                            \
            GTEST_SKIP() << "ROCM-31016 was only reproduced/validated on gfx950, " \
                            "not "                                                 \
                         << gpuArchFamily();                                       \
    } while(0)
}

// Sanity check: a D well under the BufferOOB ceiling (~4 GiB - 4 KiB) must
// dispatch to a real algorithm and be bit-exact correct with nothing left
// unwritten. If this ever fails, the case below proves nothing about the
// guard specifically; it would just be evidence the whole GEMM path is
// broken.
TEST(BufferStoreOffsetGuard_pre_checkin, SafeOutputDispatchesAndIsExact)
{
    SKIP_UNLESS_GFX950();

    auto outcome = runConstantMatmul(/*M=*/1024, /*N=*/1024, /*K=*/1024);
    ASSERT_GT(outcome.foundAlgoCount, 0) << "no algorithm found for an ordinary, "
                                            "well within-range problem";
    ASSERT_TRUE(outcome.ran);
    ASSERT_TRUE(outcome.verified) << "post-run verification scan itself failed";
    EXPECT_EQ(outcome.unwrittenCount, 0u);
    EXPECT_EQ(outcome.wrongCount, 0u);
}

// NOTE: An end-to-end test dispatching the exact M=33,554,560 reproducer
// shape and asserting it is now guarded is deliberately NOT included here.
// See the CAVEAT in the file header: the fix for that shape
// (StreamKWorkgroupNumberCheck) is a new predicate type that only takes
// effect once the target architecture's Tensile logic files are
// regenerated, which this repository-level test cannot do. The exact
// hardware-confirmed boundary (tiles == 2^24 safe, one shape past it broken)
// is covered directly in tensilelite/tests/Predicates_test.cpp.
