/*******************************************************************************
 *
 * MIT License
 *
 * Copyright 2025 AMD ROCm(TM) Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 *******************************************************************************/

#pragma once

#include <deque>
#include <map>
#include <ostream>
#include <string>
#include <unordered_set>
#include <vector>

#include <rocRoller/DataTypes/DataTypes.hpp>
#include <rocRoller/GPUArchitecture/GPUArchitectureTarget.hpp>
#include <rocRoller/KernelGraph/Transforms/MemoryTracer.hpp>

namespace rocRoller::KernelGraph::MemoryTracer
{
    bool isLDSOperation(const MemoryEventExpression& event);

    struct Summary
    {
        static constexpr bool echoBanks = false;

        struct Banks
        {
            uint   bankIndex;
            size_t workitemsAccessed;
            bool   imbalanced;
        };
        struct Access
        {
            int                           ldsTag;
            std::vector<Banks>            accessedBanks;
            std::vector<std::vector<int>> banksToWorkitems;
        };

        std::map<int, Access> tagToAccess;
        std::set<int>         imbalancedTags;

        std::string toString() const;
    };

    std::ostream& operator<<(std::ostream& stream, Summary const& summary);

    struct RuntimeLDSInstruction
    {
        MemoryOpLDS           memoryOp;
        int                   dwords;
        std::vector<uint32_t> baseAddresses;
    };

    struct OperationAccesses
    {
        int                                operationTag;
        int                                ldsTag;
        std::vector<RuntimeLDSInstruction> instructions;
    };

    struct OperationsAnalysis
    {
        std::map<int, OperationAccesses> tagToAccess;
        GPUArchitectureGFX               gfx;

        std::string toString() const;
    };

    std::ostream& operator<<(std::ostream& stream, OperationsAnalysis const& operationAnalysis);

    struct LDSBankAccess
    {
        int          operationTag;
        int          ldsTag;
        LdsDirection direction;
        uint         workitem;
        uint         bankIndex;
    };

    /**
     * @brief Analyzes bank conflicts at the operation level for high-level understanding
     * 
     * This struct takes an operation and estimates the level of bank conflicts for that
     * operation. Does so without considering the instructions generated by that operation.
     */
    struct OperationBankConflicts
    {
    public:
        OperationBankConflicts(uint entryWidthInBytes, uint numBanks, uint numEntriesPerBank);

        bool filter(MemoryEventExpression event);
        void simulate(MemoryEventSimulated event);

        /**
         * @brief Summarize the bank access patterns and conflicts of simulated LDS operations
         */
        Summary summary() const;

    private:
        uint                                      m_entryWidthInBytes;
        uint                                      m_numBanks;
        uint                                      m_numEntriesPerBank;
        std::map<int, std::vector<LDSBankAccess>> m_bankAccesses;
    };

    /**
     * @brief Models how hardware handles ds_ instructions.
     * 
     * Core functionality is to take in an instruction (with known relative addresses),
     * and predict the number of clock cycles it will take to execute that instruction.
     * 
     * To be used by scheduler and observers for scheduling.
     */
    struct LDSBankModel
    {
        LDSBankModel(uint entryWidthInBytes, uint numBanks, uint numEntriesPerBank);

        bool filter(MemoryEventExpression event);
        void simulate(MemoryEventSimulated event);

        /**
         * @brief Perform detailed analysis of all simulated LDS operations
         * @param gfx The GPU architecture to analyze for
         * @return Operations, their instructions, and clock cycle counts
         */
        OperationsAnalysis doOperationsAnalysis(GPUArchitectureGFX gfx) const;

        /**
         * @brief Calculate the clock count for an LDS instruction
         * 
         * This function encapsulates all the logic for determining how many clock cycles
         * an LDS instruction will take, including:
         * - Dividing base addresses into thread groups based on architecture limits
         * - Maximizing threads without conflicts within groups
         * - Resolving bank conflicts to determine actual cycles
         * - Adding address transfer overhead for writes
         * 
         * @param instr The LDS instruction
         * @param gfx The GPU architecture
         */
        static uint getClockCount(const RuntimeLDSInstruction& instr, GPUArchitectureGFX gfx);

        /**
         * @brief Get the number of LDS banks for a given GPU architecture
         */
        static uint getNumLDSBanks(GPUArchitectureGFX gfx);

        /**
         * @brief Returns the number of threads that can operate per clock for a given memory operation
         * 
         * @param dwords Number of dwords (1 for b32, 2 for b64, 3 for b96, 4 for b128)
         * @param gfx The GPU architecture
         * @param memoryOp Read/write
         */
        static uint
            getThreadsPerClock(const MemoryOpLDS& memoryOp, uint dwords, GPUArchitectureGFX gfx);

        /**
         * @brief Divide addresses into thread groups based on threadsPerClock limit
         * 
         * @param addresses Vector of base addresses to divide into groups
         * @param threadsPerClock Maximum number of threads that can operate per clock
         * @return Vector of thread groups, each containing addresses for that group
         */
        static std::vector<std::vector<uint32_t>>
            divideIntoThreadGroups(const std::vector<uint32_t>& addresses, uint threadsPerClock);

        /**
         * @brief Determines how many addresses accesses each bank
         * 
         * For multi-dword accesses, includes addresses at starting at the baseAddress and
         * extending for dwords number of dwords.
         *
         * @param baseAddresses Vector of base addresses.
         * @param dwords Number of dwords accessed starting from each base address
         * @return A map, where the key is the bank index and the value is the count of addresses accessing that bank
         */
        static std::map<uint, uint> createBankToAddressCounts(
            const std::vector<uint32_t>& baseAddresses, uint dwords, GPUArchitectureGFX gfx);

        /**
         * @brief Calculate the number of clock cycles needed to resolve bank conflicts
         * 
         * Simulates the bank conflict resolution process where only one address per bank
         * can be serviced per clock cycle.
         * 
         * @param bankToAddressCounts Map from bank index to count of addresses accessing that bank
         * @return Number of clock cycles
         */
        static uint calculateBankConflictCycles(const std::map<uint, uint>& bankToAddressCounts);

        /**
         * @brief Compute bank-to-address mappings for each thread group
         * 
         * This function divides the instruction's base addresses into thread groups
         * and computes the bank-to-address count mapping for each group.
         * 
         * @param instr The LDS instruction containing memory operation details and addresses
         * @param gfx The GPU architecture
         * @return Vector of bank-to-address count mappings, one per thread group
         */
        static std::vector<std::map<uint, uint>>
            computeThreadGroupBankMappings(const RuntimeLDSInstruction& instr,
                                           GPUArchitectureGFX           gfx);

        /**
         * @brief Calculate total cycles from bank mappings
         * 
         * Takes the per-thread-group bank mappings and calculates the total
         * number of cycles needed, including bank conflict resolution
         * 
         * @param threadGroupBankMappings Vector of bank to address count mappings
         * @return Total number of clock cycles
         */
        static uint calculateTotalCyclesFromBankMappings(
            const std::vector<std::map<uint, uint>>& threadGroupBankMappings);

    private:
        std::map<int, OperationAccesses> m_tagToOperationAccesses;
    };

    /**
     * @brief Trace memory accesses in a kernel graph and analyze LDS bank conflicts
     * 
     * @param original The original kernel graph to analyze
     * @param invocation The kernel invocation parameters
     * @return Summary of LDS bank access patterns and conflicts
     */
    Summary memoryTrace(KernelGraph const& original, KernelInvocation const& invocation);
}
