// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier:  MIT

#include <gtest/gtest.h>
#include <half/half.hpp>
#include <miopen/miopen.h>

#include "conv2d_gtest.hpp"
#include "get_handle.hpp"
#include "gtest/gtest_common.hpp"
#include "lib_env_var.hpp"

namespace {

using TestCase = Conv2DBaseTestCase<NamedContainer<std::vector<size_t>>, // input_dims
                                    NamedContainer<std::vector<size_t>>  // weights_tensor_dims
                                    >;

template <typename T>
auto GenCases(bool smoke_test,
              std::vector<size_t> input_dims,
              std::vector<size_t> weight_tensor_dims,
              std::vector<int> pads_strides_dilations,
              bool enable_forward,
              bool enable_backward_data,
              bool enable_backward_weights,
              std::string in_layout,
              std::string fil_layout,
              std::string out_layout,
              int group_count = 1)
{
    Conv2DBaseTestParameters<T> baseParams(smoke_test);

    baseParams.pads_strides_dilations          = {std::move(pads_strides_dilations)};
    baseParams.base_params.do_backward_weights = {enable_backward_weights};
    baseParams.base_params.do_forward          = {enable_forward};
    baseParams.base_params.do_backward_data    = {enable_backward_data};
    baseParams.in_layout                       = {std::move(in_layout)};
    baseParams.fil_layout                      = {std::move(fil_layout)};
    baseParams.out_layout                      = {std::move(out_layout)};
    baseParams.base_params.groupCount          = {group_count};

    return conv2d_test_base<T>::GenTestParams(
        baseParams,
        MakeNamedParameterCollectionValues<std::vector<size_t>>(
            "input_dims", std::vector<std::vector<size_t>>{std::move(input_dims)}),
        MakeNamedParameterCollectionValues<std::vector<size_t>>(
            "weight_tensor_dims", std::vector<std::vector<size_t>>{std::move(weight_tensor_dims)}));
}

bool IsTestSupportedForDevice(const miopen::Handle& handle)
{
    const auto& target        = handle.GetTargetProperties();
    const std::string devName = handle.GetDeviceName();

    if(target.isXnackEnabled())
    {
        return false;
    }

    return (devName == "gfx908" || devName == "gfx90a" || devName == "gfx942");
}

} // namespace

template <typename T>
struct conv_igemm_dynamic_xdlops_nhwc_nchw_test : public conv2d_test_base<T, TestCase>
{
    void SetUp() override
    {
        prng::reset_seed();
        this->GetTestParams(this->input_dims, this->weight_tensor_dims);
    }
};

using GPU_Conv_IGEMM_DYNAMIC_XDLOPS_NHWC_NCHW_FP16 =
    conv_igemm_dynamic_xdlops_nhwc_nchw_test<half_float::half>;
using GPU_Conv_IGEMM_DYNAMIC_XDLOPS_NHWC_NCHW_FP32 =
    conv_igemm_dynamic_xdlops_nhwc_nchw_test<float>;

TEST_P(GPU_Conv_IGEMM_DYNAMIC_XDLOPS_NHWC_NCHW_FP16, TestFloat16)
{
    if(IsTestSupportedForDevice(get_handle()))
    {
        ScopedEnvironment<std::string> find_mode_env2(MIOPEN_FIND_MODE, std::string("normal"));
        ScopedEnvironment<std::string> find_only_solver_env(
            MIOPEN_DEBUG_FIND_ONLY_SOLVER,
            "ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC;ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC;"
            "ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC");

        run();
    }
    else
    {
        GTEST_SKIP() << "Test not supported for the current device";
    }
}

TEST_P(GPU_Conv_IGEMM_DYNAMIC_XDLOPS_NHWC_NCHW_FP32, TestFloat32)
{
    if(IsTestSupportedForDevice(get_handle()))
    {
        ScopedEnvironment<std::string> find_mode_env2(MIOPEN_FIND_MODE, std::string("normal"));
        ScopedEnvironment<std::string> find_only_solver_env(
            MIOPEN_DEBUG_FIND_ONLY_SOLVER,
            "ConvAsmImplicitGemmGTCDynamicFwdXdlopsNHWC;ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC;"
            "ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC");

        run();
    }
    else
    {
        GTEST_SKIP() << "Test not supported for the current device";
    }
}

#define INSTANTIATE_ALL_MIOPEN_TEST_SUITES(id, ...)                                       \
    INSTANTIATE_MIOPEN_TEST_SUITES(                                                       \
        id, GPU_Conv_IGEMM_DYNAMIC_XDLOPS_NHWC_NCHW_FP16, half_float::half, __VA_ARGS__); \
    INSTANTIATE_MIOPEN_TEST_SUITES(                                                       \
        id, GPU_Conv_IGEMM_DYNAMIC_XDLOPS_NHWC_NCHW_FP32, float, __VA_ARGS__)

// nhwc_fwd
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(0,
                                   {64, 256, 7, 7},
                                   {128, 256, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(1,
                                   {32, 160, 73, 73},
                                   {64, 160, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(2,
                                   {16, 64, 56, 56},
                                   {64, 64, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(3,
                                   {2, 256, 40, 52},
                                   {256, 256, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(4,
                                   {2, 64, 59, 57},
                                   {12, 64, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(5,
                                   {32, 128, 14, 14},
                                   {64, 128, 1, 1},
                                   {0, 0, 2, 2, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(6,
                                   {64, 64, 17, 17},
                                   {192, 64, 1, 7},
                                   {0, 3, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(7,
                                   {64, 64, 17, 17},
                                   {192, 64, 7, 1},
                                   {3, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(8,
                                   {4, 128, 28, 28},
                                   {128, 128, 2, 2},
                                   {0, 0, 2, 2, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(9,
                                   {32, 128, 8, 8},
                                   {192, 128, 3, 1},
                                   {1, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(10,
                                   {64, 192, 17, 17},
                                   {160, 192, 3, 3},
                                   {0, 0, 2, 2, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(11,
                                   {64, 32, 73, 73},
                                   {64, 32, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(12,
                                   {16, 64, 56, 56},
                                   {64, 64, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(13,
                                   {64, 3, 78, 78},
                                   {64, 3, 7, 7},
                                   {0, 0, 2, 2, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(14,
                                   {16, 192, 17, 17},
                                   {224, 192, 1, 7},
                                   {0, 3, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(15,
                                   {16, 3, 17, 17},
                                   {64, 3, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(16,
                                   {2, 64, 19, 19},
                                   {510, 64, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
// tensor, larger, than, 4GB
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(17,
                                   {2048, 1, 512, 1024},
                                   {1, 1, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
// ho=wo=1, stride=2
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(18,
                                   {256, 2048, 2, 2},
                                   {1024, 2048, 1, 1},
                                   {0, 0, 2, 2, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");

// nhwc_fwd_nchw
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(19,
                                   {64, 256, 7, 7},
                                   {128, 256, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(20,
                                   {32, 160, 73, 73},
                                   {64, 160, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(21,
                                   {16, 64, 56, 56},
                                   {64, 64, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(22,
                                   {2, 256, 40, 52},
                                   {256, 256, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(23,
                                   {2, 64, 59, 57},
                                   {12, 64, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(24,
                                   {32, 128, 14, 14},
                                   {64, 128, 1, 1},
                                   {0, 0, 2, 2, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(25,
                                   {64, 64, 17, 17},
                                   {192, 64, 1, 7},
                                   {0, 3, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(26,
                                   {64, 64, 17, 17},
                                   {192, 64, 7, 1},
                                   {3, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(27,
                                   {4, 128, 28, 28},
                                   {128, 128, 2, 2},
                                   {0, 0, 2, 2, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(28,
                                   {32, 128, 8, 8},
                                   {192, 128, 3, 1},
                                   {1, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(29,
                                   {64, 192, 17, 17},
                                   {160, 192, 3, 3},
                                   {0, 0, 2, 2, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(30,
                                   {64, 32, 73, 73},
                                   {64, 32, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(31,
                                   {16, 64, 56, 56},
                                   {64, 64, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(32,
                                   {64, 3, 78, 78},
                                   {64, 3, 7, 7},
                                   {0, 0, 2, 2, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(33,
                                   {16, 192, 17, 17},
                                   {224, 192, 1, 7},
                                   {0, 3, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(34,
                                   {16, 3, 17, 17},
                                   {64, 3, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(35,
                                   {2, 64, 19, 19},
                                   {510, 64, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");

// TODO:, disabled, for, WORKAROUND_ISSUE_1979
/*
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(36,
                                   {16, 3, 224, 224},
                                   {63, 1, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   true,
                                   false,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC",
                                   3);
*/

// nhwc_bwd
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(37,
                                   {64, 256, 7, 7},
                                   {128, 256, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(38,
                                   {32, 160, 73, 73},
                                   {64, 160, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(39,
                                   {16, 64, 56, 56},
                                   {64, 64, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(40,
                                   {2, 256, 40, 52},
                                   {256, 256, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(41,
                                   {2, 64, 32, 28},
                                   {64, 64, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(42,
                                   {32, 128, 14, 14},
                                   {64, 128, 1, 1},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(43,
                                   {64, 64, 17, 17},
                                   {192, 64, 1, 7},
                                   {0, 3, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(44,
                                   {64, 64, 17, 17},
                                   {192, 64, 7, 1},
                                   {3, 0, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(45,
                                   {4, 128, 28, 28},
                                   {128, 128, 2, 2},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(46,
                                   {32, 128, 8, 8},
                                   {192, 128, 3, 1},
                                   {1, 0, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(47,
                                   {64, 192, 17, 17},
                                   {160, 192, 3, 3},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(48,
                                   {64, 32, 73, 73},
                                   {64, 32, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(49,
                                   {16, 64, 56, 56},
                                   {64, 64, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(50,
                                   {16, 16, 25, 25},
                                   {64, 16, 3, 3},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(51,
                                   {
                                       15,
                                       256,
                                       1,
                                       1,
                                   },
                                   {340, 256, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(52,
                                   {15, 128, 10, 10},
                                   {340, 128, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(53,
                                   {2, 64, 19, 19},
                                   {510, 64, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
// tensor, larger, than, 4GB
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(54,
                                   {2048, 1, 512, 1024},
                                   {1, 1, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
// ho=wo=1, stride=2
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(55,
                                   {256, 2048, 2, 2},
                                   {1024, 2048, 1, 1},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");

// nhwc_bwd_nchw
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(56,
                                   {64, 256, 7, 7},
                                   {128, 256, 1, 1},
                                   {
                                       0,
                                       0,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(57,
                                   {32, 160, 73, 73},
                                   {64, 160, 1, 1},
                                   {
                                       0,
                                       0,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(58,
                                   {16, 64, 56, 56},
                                   {64, 64, 1, 1},
                                   {
                                       0,
                                       0,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(59,
                                   {2, 256, 40, 52},
                                   {256, 256, 1, 1},
                                   {
                                       0,
                                       0,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(60,
                                   {2, 64, 32, 28},
                                   {64, 64, 1, 1},
                                   {
                                       0,
                                       0,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(61,
                                   {32, 128, 14, 14},
                                   {64, 128, 1, 1},
                                   {
                                       0,
                                       0,
                                       2,
                                       2,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(62,
                                   {64, 64, 17, 17},
                                   {192, 64, 1, 7},
                                   {
                                       0,
                                       3,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(63,
                                   {64, 64, 17, 17},
                                   {192, 64, 7, 1},
                                   {
                                       3,
                                       0,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(64,
                                   {4, 128, 28, 28},
                                   {128, 128, 2, 2},
                                   {
                                       0,
                                       0,
                                       2,
                                       2,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(65,
                                   {32, 128, 8, 8},
                                   {192, 128, 3, 1},
                                   {
                                       1,
                                       0,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(66,
                                   {64, 192, 17, 17},
                                   {160, 192, 3, 3},
                                   {
                                       0,
                                       0,
                                       2,
                                       2,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(67,
                                   {64, 32, 73, 73},
                                   {64, 32, 3, 3},
                                   {
                                       1,
                                       1,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(68,
                                   {16, 64, 56, 56},
                                   {64, 64, 3, 3},
                                   {
                                       1,
                                       1,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(69,
                                   {16, 16, 25, 25},
                                   {64, 16, 3, 3},
                                   {
                                       0,
                                       0,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(70,
                                   {
                                       15,
                                       256,
                                       1,
                                       1,
                                   },
                                   {340, 256, 3, 3},
                                   {
                                       1,
                                       1,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(71,
                                   {15, 128, 10, 10},
                                   {340, 128, 3, 3},
                                   {
                                       1,
                                       1,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(72,
                                   {2, 64, 19, 19},
                                   {510, 64, 3, 3},
                                   {
                                       1,
                                       1,
                                       1,
                                       1,
                                       1,
                                       1,
                                   },
                                   false,
                                   true,
                                   false,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");

// nhwc_wrw
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(73,
                                   {64, 256, 7, 7},
                                   {128, 256, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(74,
                                   {32, 160, 73, 73},
                                   {64, 160, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(75,
                                   {16, 64, 56, 56},
                                   {64, 64, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(76,
                                   {2, 256, 40, 52},
                                   {256, 256, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(77,
                                   {2, 64, 32, 28},
                                   {64, 64, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(78,
                                   {32, 128, 14, 14},
                                   {64, 128, 1, 1},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(79,
                                   {64, 64, 17, 17},
                                   {192, 64, 1, 7},
                                   {0, 3, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(80,
                                   {64, 64, 17, 17},
                                   {192, 64, 7, 1},
                                   {3, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(81,
                                   {4, 128, 28, 28},
                                   {128, 128, 2, 2},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(82,
                                   {32, 128, 8, 8},
                                   {192, 128, 3, 1},
                                   {1, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(83,
                                   {64, 192, 17, 17},
                                   {160, 192, 3, 3},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(84,
                                   {64, 32, 73, 73},
                                   {64, 32, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(85,
                                   {16, 64, 56, 56},
                                   {64, 64, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(86,
                                   {16, 16, 25, 25},
                                   {64, 16, 3, 3},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(87,
                                   {4, 32, 79, 141},
                                   {64, 32, 5, 10},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(88,
                                   {400, 256, 7, 7},
                                   {1024, 256, 7, 7},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(89,
                                   {400, 256, 1, 1},
                                   {1024, 256, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(90,
                                   {1, 3, 32, 32},
                                   {1, 3, 11, 11},
                                   {1, 1, 2, 2, 2, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(91,
                                   {1, 3, 224, 224},
                                   {1, 3, 3, 3},
                                   {0, 0, 1, 1, 2, 2},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(
    92, {1, 1, 8, 8}, {1, 1, 2, 2}, {0, 0, 1, 1, 2, 2}, false, false, true, "NHWC", "NHWC", "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(93,
                                   {1, 128, 56, 56},
                                   {1, 128, 5, 5},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(94,
                                   {2, 64, 19, 19},
                                   {510, 64, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
// ho=wo=1, stride=2
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(95,
                                   {256, 2048, 2, 2},
                                   {1024, 2048, 1, 1},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");

// nhwc_wrw_nchw
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(96,
                                   {64, 256, 7, 7},
                                   {128, 256, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(97,
                                   {32, 160, 73, 73},
                                   {64, 160, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(98,
                                   {16, 64, 56, 56},
                                   {64, 64, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(99,
                                   {2, 256, 40, 52},
                                   {256, 256, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(100,
                                   {2, 64, 32, 28},
                                   {64, 64, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(101,
                                   {32, 128, 14, 14},
                                   {64, 128, 1, 1},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(102,
                                   {64, 64, 17, 17},
                                   {192, 64, 1, 7},
                                   {0, 3, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(103,
                                   {64, 64, 17, 17},
                                   {192, 64, 7, 1},
                                   {3, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(104,
                                   {4, 128, 28, 28},
                                   {128, 128, 2, 2},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(105,
                                   {32, 128, 8, 8},
                                   {192, 128, 3, 1},
                                   {1, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(106,
                                   {64, 192, 17, 17},
                                   {160, 192, 3, 3},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(107,
                                   {64, 32, 73, 73},
                                   {64, 32, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(108,
                                   {16, 64, 56, 56},
                                   {64, 64, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(109,
                                   {16, 16, 25, 25},
                                   {64, 16, 3, 3},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(110,
                                   {4, 32, 79, 141},
                                   {64, 32, 5, 10},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(111,
                                   {400, 256, 7, 7},
                                   {1024, 256, 7, 7},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(112,
                                   {400, 256, 1, 1},
                                   {1024, 256, 1, 1},
                                   {0, 0, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(113,
                                   {1, 3, 32, 32},
                                   {1, 3, 11, 11},
                                   {1, 1, 2, 2, 2, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(114,
                                   {1, 3, 224, 224},
                                   {1, 3, 3, 3},
                                   {0, 0, 1, 1, 2, 2},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(115,
                                   {1, 1, 8, 8},
                                   {1, 1, 2, 2},
                                   {0, 0, 1, 1, 2, 2},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(116,
                                   {1, 128, 56, 56},
                                   {1, 128, 5, 5},
                                   {0, 0, 2, 2, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
INSTANTIATE_ALL_MIOPEN_TEST_SUITES(117,
                                   {2, 64, 19, 19},
                                   {510, 64, 3, 3},
                                   {1, 1, 1, 1, 1, 1},
                                   false,
                                   false,
                                   true,
                                   "NHWC",
                                   "NHWC",
                                   "NHWC");
