// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier:  MIT

#include "conv2d_gtest.hpp"
#include "gtest_common.hpp"

namespace {

using TestCase = Conv2DBaseTestCase<NamedContainer<std::vector<size_t>>, // input_dims
                                    NamedContainer<std::vector<size_t>>  // weights_tensor_dims
                                    >;

template <typename T>
auto GenCases(bool smoke_test,
              std::vector<size_t> input_dims,
              std::vector<size_t> weight_tensor_dims,
              std::vector<int> pads_strides_dilations,
              std::string conv_mode,
              std::string in_layout,
              std::string fil_layout,
              std::string out_layout,
              bool enable_backward_data,
              bool enable_backward_weights,
              size_t tensor_vect,
              size_t vector_length)
{
    Conv2DBaseTestParameters<T> baseParams(smoke_test);

    baseParams.pads_strides_dilations          = {std::move(pads_strides_dilations)};
    baseParams.base_params.conv_mode           = {std::move(conv_mode)};
    baseParams.in_layout                       = {std::move(in_layout)};
    baseParams.fil_layout                      = {std::move(fil_layout)};
    baseParams.out_layout                      = {std::move(out_layout)};
    baseParams.base_params.do_backward_data    = {enable_backward_data};
    baseParams.base_params.do_backward_weights = {enable_backward_weights};
    baseParams.tensor_vect                     = {tensor_vect};
    baseParams.vector_length                   = {vector_length};

    return conv2d_test_base<T>::GenTestParams(
        baseParams,
        MakeNamedParameterCollectionValues<std::vector<size_t>>(
            "input_dims", std::vector<std::vector<size_t>>{std::move(input_dims)}),
        MakeNamedParameterCollectionValues<std::vector<size_t>>(
            "weight_tensor_dims", std::vector<std::vector<size_t>>{std::move(weight_tensor_dims)}));
}

bool IsTestSupportedForDevice()
{
    using e_mask = enabled<Gpu::gfx103X>;
    using d_mask = disabled<Gpu::gfx900, Gpu::gfx906, Gpu::gfx908, Gpu::gfx90A>;
    return ::IsTestSupportedForDevMask<d_mask, e_mask>();
}

} // namespace

template <typename T>
struct conv_igemm_dynamic_dlops_gtest : public conv2d_test_base<T, TestCase>
{
    void SetUp() override
    {
        prng::reset_seed();
        this->GetTestParams(this->input_dims, this->weight_tensor_dims);
    }
};

using GPU_Conv2dDefaultIGemmDynamicDLops_FP16 = conv_igemm_dynamic_dlops_gtest<half_float::half>;

TEST_P(GPU_Conv2dDefaultIGemmDynamicDLops_FP16, TestFloat16)
{
    if(IsTestSupportedForDevice() && !get_handle_xnack())
    {
        ScopedEnvironment<std::string> find_mode(MIOPEN_FIND_MODE, "normal");
        ScopedEnvironment<std::string> debug_find_only_solver(
            MIOPEN_DEBUG_FIND_ONLY_SOLVER, "ConvAsmImplicitGemmGTCDynamicFwdDlopsNCHWC");

        run();
    }
    else
    {
        GTEST_SKIP() << "Test not supported for the current device";
    }
};

#define INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(id, ...) \
    INSTANTIATE_MIOPEN_FULL_TEST(                           \
        id, GPU_Conv2dDefaultIGemmDynamicDLops_FP16, half_float::half, __VA_ARGS__)

// nchwc_nchwc_fwd_fp16x4
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(0,
                                           {1, 8, 10, 10},
                                           {8, 8, 3, 3},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(1,
                                           {32, 160, 73, 73},
                                           {64, 160, 1, 1},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(2,
                                           {16, 64, 56, 56},
                                           {64, 64, 1, 1},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(3,
                                           {2, 256, 40, 52},
                                           {256, 256, 1, 1},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(4,
                                           {2, 64, 32, 28},
                                           {64, 64, 1, 1},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(5,
                                           {32, 128, 14, 14},
                                           {64, 128, 1, 1},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(6,
                                           {64, 64, 17, 17},
                                           {192, 64, 1, 7},
                                           {0, 3, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(7,
                                           {64, 64, 17, 17},
                                           {192, 64, 7, 1},
                                           {3, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(8,
                                           {4, 128, 28, 28},
                                           {128, 128, 2, 2},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(9,
                                           {32, 128, 8, 8},
                                           {192, 128, 3, 1},
                                           {1, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(10,
                                           {64, 192, 17, 17},
                                           {160, 192, 3, 3},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(11,
                                           {64, 32, 73, 73},
                                           {64, 32, 3, 3},
                                           {1, 1, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(12,
                                           {16, 64, 56, 56},
                                           {64, 64, 3, 3},
                                           {1, 1, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(13,
                                           {16, 16, 25, 25},
                                           {64, 16, 3, 3},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(14,
                                           {4, 32, 79, 141},
                                           {64, 32, 5, 10},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(15,
                                           {400, 256, 7, 7},
                                           {1024, 256, 7, 7},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(16,
                                           {400, 256, 1, 1},
                                           {1024, 256, 1, 1},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);

// nchwc_chwnc_fwd_fp16x4
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(17,
                                           {64, 256, 7, 7},
                                           {256, 3, 3, 128},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(18,
                                           {32, 160, 73, 73},
                                           {160, 1, 1, 64},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(19,
                                           {16, 64, 56, 56},
                                           {64, 1, 1, 64},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(20,
                                           {2, 256, 40, 52},
                                           {256, 1, 1, 256},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(21,
                                           {2, 64, 32, 28},
                                           {64, 1, 1, 64},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(22,
                                           {32, 128, 14, 14},
                                           {128, 1, 1, 64},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(23,
                                           {64, 64, 17, 17},
                                           {64, 3, 7, 192},
                                           {0, 3, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(24,
                                           {64, 64, 17, 17},
                                           {64, 7, 1, 192},
                                           {3, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(25,
                                           {4, 128, 28, 28},
                                           {128, 2, 2, 128},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(26,
                                           {32, 128, 8, 8},
                                           {128, 3, 1, 192},
                                           {1, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(27,
                                           {64, 192, 17, 17},
                                           {192, 3, 3, 160},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(28,
                                           {64, 32, 73, 73},
                                           {32, 3, 3, 64},
                                           {1, 1, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(29,
                                           {16, 64, 56, 56},
                                           {64, 3, 3, 64},
                                           {1, 1, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(30,
                                           {16, 16, 25, 25},
                                           {16, 3, 3, 64},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(31,
                                           {4, 32, 79, 141},
                                           {32, 5, 10, 64},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(32,
                                           {400, 256, 7, 7},
                                           {256, 7, 7, 1024},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(33,
                                           {400, 256, 1, 1},
                                           {256, 1, 1, 1024},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           4);

// nchwc_nchwc_fwd_fp16x8
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(34,
                                           {1, 8, 10, 10},
                                           {8, 8, 3, 3},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(35,
                                           {32, 160, 73, 73},
                                           {64, 160, 1, 1},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(36,
                                           {16, 64, 56, 56},
                                           {64, 64, 1, 1},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(37,
                                           {2, 256, 40, 52},
                                           {256, 256, 1, 1},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(38,
                                           {2, 64, 32, 28},
                                           {64, 64, 1, 1},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(39,
                                           {32, 128, 14, 14},
                                           {64, 128, 1, 1},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(40,
                                           {64, 64, 17, 17},
                                           {192, 64, 1, 7},
                                           {0, 3, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(41,
                                           {64, 64, 17, 17},
                                           {192, 64, 7, 1},
                                           {3, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(42,
                                           {4, 128, 28, 28},
                                           {128, 128, 2, 2},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(43,
                                           {32, 128, 8, 8},
                                           {192, 128, 3, 1},
                                           {1, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(44,
                                           {64, 192, 17, 17},
                                           {160, 192, 3, 3},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(45,
                                           {64, 32, 73, 73},
                                           {64, 32, 3, 3},
                                           {1, 1, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(46,
                                           {16, 64, 56, 56},
                                           {64, 64, 3, 3},
                                           {1, 1, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(47,
                                           {16, 16, 25, 25},
                                           {64, 16, 3, 3},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(48,
                                           {4, 32, 79, 141},
                                           {64, 32, 5, 10},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(49,
                                           {400, 256, 7, 7},
                                           {1024, 256, 7, 7},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(50,
                                           {400, 256, 1, 1},
                                           {1024, 256, 1, 1},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "NCHW",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);

// nchwc_chwnc_fwd_fp16x8
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(51,
                                           {64, 256, 7, 7},
                                           {256, 1, 1, 128},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(52,
                                           {32, 160, 73, 73},
                                           {160, 1, 1, 64},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(53,
                                           {16, 64, 56, 56},
                                           {64, 1, 1, 64},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(54,
                                           {2, 256, 40, 52},
                                           {256, 1, 1, 256},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(55,
                                           {2, 64, 32, 28},
                                           {64, 1, 1, 64},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(56,
                                           {32, 128, 14, 14},
                                           {128, 1, 1, 64},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(57,
                                           {64, 64, 17, 17},
                                           {64, 1, 7, 192},
                                           {0, 3, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(58,
                                           {64, 64, 17, 17},
                                           {64, 7, 1, 192},
                                           {3, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(59,
                                           {4, 128, 28, 28},
                                           {128, 2, 2, 128},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(60,
                                           {32, 128, 8, 8},
                                           {128, 3, 1, 192},
                                           {1, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(61,
                                           {64, 192, 17, 17},
                                           {192, 3, 3, 160},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(62,
                                           {64, 32, 73, 73},
                                           {32, 3, 3, 64},
                                           {1, 1, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(63,
                                           {16, 64, 56, 56},
                                           {64, 3, 3, 64},
                                           {1, 1, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(64,
                                           {16, 16, 25, 25},
                                           {16, 3, 3, 64},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(65,
                                           {4, 32, 79, 141},
                                           {32, 5, 10, 64},
                                           {0, 0, 2, 2, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(66,
                                           {400, 256, 7, 7},
                                           {256, 7, 7, 1024},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
INSTANTIATE_MIOPEN_FLOAT16_FULL_TEST_SUITE(67,
                                           {400, 256, 1, 1},
                                           {256, 1, 1, 1024},
                                           {0, 0, 1, 1, 1, 1},
                                           "convfp16",
                                           "NCHW",
                                           "CHWN",
                                           "NCHW",
                                           false,
                                           false,
                                           1,
                                           8);
