// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

#ifndef GUARD_MIOPEN_DEVICE_PRNG_HPP
#define GUARD_MIOPEN_DEVICE_PRNG_HPP

#include <miopen/miopen.h>

#include <cstddef>
#include <cstdint>

class bfloat16;

namespace half_float {
class half;
} // namespace half_float

namespace test::gtest {

/**
 * @brief Populate a device buffer with deterministic pseudo-random values.
 *
 * Launches @ref sfc64_kernel with a fixed block size and a CU-based grid heuristic.
 * Output is grid-invariant: element i is generated by seeding SFC64 with (seed, i),
 * so results do not depend on block/grid shape.
 *
 * Type mapping is handled in the kernel (float/double normalized to [0,1), fp16/bf16 via
 * float then cast, integrals take the top N bits).
 *
 * @tparam T Host-facing element type (may be half_float::half or miopen::bfloat16).
 * @param dev_ptr Device pointer to output buffer.
 * @param size Number of elements.
 * @param seed Global seed for deterministic generation.
 *
 * @throws std::runtime_error if dev_ptr is null or HIP device queries fail.
 */
template <typename T>
void RandomizeBuffer(T* dev_ptr, size_t size, uint64_t seed, hipStream_t stream);

extern template void
RandomizeBuffer<double>(double* dev_ptr, size_t size, uint64_t seed, hipStream_t stream);
extern template void
RandomizeBuffer<float>(float* dev_ptr, size_t size, uint64_t seed, hipStream_t stream);
extern template void
RandomizeBuffer<bfloat16>(bfloat16* dev_ptr, size_t size, uint64_t seed, hipStream_t stream);
extern template void RandomizeBuffer<half_float::half>(half_float::half* dev_ptr,
                                                       size_t size,
                                                       uint64_t seed,
                                                       hipStream_t stream);
extern template void
RandomizeBuffer<int8_t>(int8_t* dev_ptr, size_t size, uint64_t seed, hipStream_t stream);
extern template void
RandomizeBuffer<int32_t>(int32_t* dev_ptr, size_t size, uint64_t seed, hipStream_t stream);

/**
 * @brief Generate deterministic reduction-test inputs on GPU (grid-invariant).
 *
 * Uses SFC64 seeded by (seed, i) per element and applies a checkerboard sign (+/- by i parity).
 * rand_val = (max_val > 0) ? (raw % max_val) : 0.
 *
 * Operator mapping:
 * - ADD/AVG:  sign*(rand_val/max_val) + 0.01  (avoid frequent exact zeros)
 * - MUL:      values near 1.0 to avoid huge/zero products across many elements
 * - AMAX:     +/- (rand_val + 0.5)           (avoid zeros for abs-max)
 * - NORM1/2:  rand_val*sign*(0.1*(1+(raw%10)))  ratio in {0.1..1.0}
 * - MIN/MAX:  rand_val*sign
 */
template <typename T>
void ReduceGenerator(T* output,
                     size_t n,
                     uint64_t seed,
                     miopenReduceTensorOp_t op,
                     uint64_t max_val,
                     hipStream_t stream);

extern template void
ReduceGenerator<float>(float*, size_t, uint64_t, miopenReduceTensorOp_t, uint64_t, hipStream_t);
extern template void
ReduceGenerator<double>(double*, size_t, uint64_t, miopenReduceTensorOp_t, uint64_t, hipStream_t);
extern template void ReduceGenerator<half_float::half>(
    half_float::half*, size_t, uint64_t, miopenReduceTensorOp_t, uint64_t, hipStream_t);
extern template void ReduceGenerator<bfloat16>(
    bfloat16*, size_t, uint64_t, miopenReduceTensorOp_t, uint64_t, hipStream_t);
extern template void
ReduceGenerator<int8_t>(int8_t*, size_t, uint64_t, miopenReduceTensorOp_t, uint64_t, hipStream_t);
extern template void
ReduceGenerator<int32_t>(int32_t*, size_t, uint64_t, miopenReduceTensorOp_t, uint64_t, hipStream_t);

} // namespace test::gtest

#endif // GUARD_MIOPEN_DEVICE_PRNG_HPP
