// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

#ifndef GUARD_MIOPEN_DEVICE_PRNG_HPP
#define GUARD_MIOPEN_DEVICE_PRNG_HPP

#include "miopen/tensor.hpp"

#include <hip/hip_runtime.h>
#include <rocrand/rocrand_philox4x32_10.h>

class bfloat16;
namespace half_float {
class half;
} // namespace half_float

namespace test::gtest {

constexpr int kMaxTensorDims = 8;

struct TensorShapeInfo
{
    int ndims                = 0;
    int lens[kMaxTensorDims] = {0};
};

inline TensorShapeInfo MakeTensorShapeInfo(const int* lengths, int ndims)
{
    TensorShapeInfo shape{};

    if(lengths == nullptr || ndims <= 0)
        return shape;

    shape.ndims = (ndims > kMaxTensorDims) ? kMaxTensorDims : ndims;
    for(int i = 0; i < shape.ndims; ++i)
        shape.lens[i] = lengths[i];

    return shape;
}

inline TensorShapeInfo MakeTensorShapeInfo(const miopen::TensorDescriptor& desc)
{
    MIOPEN_THROW_IF(desc.AllLengthsFitIntoInt() == false,
                    "ReduceGenerator only supports tensor lengths that fit into int");

    TensorShapeInfo shape{};
    const auto& lengths = desc.GetLengths();
    const auto ndims =
        lengths.size() > static_cast<size_t>(kMaxTensorDims) ? kMaxTensorDims : lengths.size();

    shape.ndims = static_cast<int>(ndims);
    for(int i = 0; i < shape.ndims; ++i)
        shape.lens[i] = static_cast<int>(lengths[static_cast<size_t>(i)]);

    return shape;
}

/**
 * @brief One deterministic 64-bit sample from Philox for a given element index.
 *
 * Using @p index as the subsequence keeps generation grid-invariant: element i is
 * generated from (seed, i) regardless of launch geometry.
 */
__device__ __forceinline__ uint64_t philox_u64(uint64_t seed, uint64_t index)
{
    rocrand_state_philox4x32_10 state;
    rocrand_init(seed, index, 0ULL, &state);

    const uint64_t hi = static_cast<uint64_t>(rocrand(&state));
    const uint64_t lo = static_cast<uint64_t>(rocrand(&state));
    return (hi << 32) | lo;
}

__device__ __forceinline__ uint32_t uint4_get(const uint4& v, int idx)
{
    switch(idx)
    {
    case 0: return v.x;
    case 1: return v.y;
    case 2: return v.z;
    default: return v.w;
    }
}

__device__ __forceinline__ double checkerboard_sign(size_t linear_idx, const TensorShapeInfo& shape)
{
    if(shape.ndims <= 0)
        return (linear_idx & 1) ? -1.0 : 1.0;

    int parity = 0;
    for(int d = shape.ndims - 1; d >= 0; --d)
    {
        const int len   = (shape.lens[d] > 0) ? shape.lens[d] : 1;
        const int coord = static_cast<int>(linear_idx % static_cast<size_t>(len));
        linear_idx /= static_cast<size_t>(len);
        parity ^= (coord & 1);
    }

    return parity ? -1.0 : 1.0;
}

template <typename T>
__global__ void philox_kernel(T* out, size_t n, uint64_t seed);

/**
 * @brief Populate a device buffer with deterministic pseudo-random values.
 *
 * Launches a Philox-based kernel with a fixed block size and a CU-based grid heuristic.
 * Output is grid-invariant: element i is generated by seeding Philox with (seed, i),
 * so results do not depend on block/grid shape.
 *
 * Type mapping is handled in the kernel (float/double normalized to [0,1), fp16/bf16 via
 * float then cast, integrals take the top N bits).
 *
 * @tparam T Host-facing element type (may be half_float::half or miopen::bfloat16).
 * @param dev_ptr Device pointer to output buffer.
 * @param size Number of elements.
 * @param seed Global seed for deterministic generation.
 *
 * @throws std::runtime_error if dev_ptr is null or HIP device queries fail.
 */

template <typename T>
void RandomizeBuffer(T* dev_ptr, size_t size, uint64_t seed, hipStream_t stream);

extern template void RandomizeBuffer<float>(float*, size_t, uint64_t, hipStream_t);
extern template void RandomizeBuffer<double>(double*, size_t, uint64_t, hipStream_t);
extern template void
RandomizeBuffer<half_float::half>(half_float::half*, size_t, uint64_t, hipStream_t);
extern template void RandomizeBuffer<bfloat16>(bfloat16*, size_t, uint64_t, hipStream_t);
extern template void RandomizeBuffer<int8_t>(int8_t*, size_t, uint64_t, hipStream_t);
extern template void RandomizeBuffer<int32_t>(int32_t*, size_t, uint64_t, hipStream_t);

} // namespace test::gtest

#endif // GUARD_MIOPEN_DEVICE_PRNG_HPP
