if(NOT DEFINED CASE)
  message(FATAL_ERROR "check_lto_linker_guard: CASE not set")
endif()
if(NOT DEFINED GUARD_MODULE)
  message(FATAL_ERROR "check_lto_linker_guard: GUARD_MODULE not set")
endif()

set(CMAKE_INTERPROCEDURAL_OPTIMIZATION OFF)
set(CMAKE_CXX_FLAGS "")
set(CMAKE_EXE_LINKER_FLAGS "")
set(CMAKE_SHARED_LINKER_FLAGS "")
set(CMAKE_MODULE_LINKER_FLAGS "")
set(CMAKE_LINKER "")
unset(CMAKE_LINKER_TYPE)

if(CASE STREQUAL "gnu_lld_lto")
  set(CMAKE_CXX_COMPILER_ID "GNU")
  set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
  set(CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld")
elseif(CASE STREQUAL "clang_lld_lto")
  set(CMAKE_CXX_COMPILER_ID "Clang")
  set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
  set(CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld")
elseif(CASE STREQUAL "gnu_bfd_lto")
  set(CMAKE_CXX_COMPILER_ID "GNU")
  set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
elseif(CASE STREQUAL "gnu_lld_nolto")
  set(CMAKE_CXX_COMPILER_ID "GNU")
  set(CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld")
else()
  message(FATAL_ERROR "check_lto_linker_guard: unknown CASE '${CASE}'")
endif()

include("${GUARD_MODULE}")
rocm_interfaces_assert_lto_linker_supported()
message(STATUS "check_lto_linker_guard: CASE=${CASE} accepted")
