name: Issue Report
description: File a report for ROCm related issues on Linux and Windows. For issues pertaining to documentation or non-bug related, please open a blank issue located below.
title: "[Issue]: "
labels:
  - ${{ values.rocm_component }}

body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this report!

      You can acquire your OS, CPU, GPU (for filling out this report) with the following commands:

      Linux:
        echo "OS:" && cat /etc/os-release | grep -E "^(NAME=|VERSION=)";
        echo "CPU: " && cat /proc/cpuinfo | grep "model name" | sort --unique;
        echo "GPU:" && /opt/rocm/bin/rocminfo | grep -E "^\s*(Name|Marketing Name)";
        
      Windows:
         (Get-WmiObject Win32_OperatingSystem).Version
         (Get-WmiObject win32_Processor).Name
         (Get-WmiObject win32_VideoController).Name

- type: textarea
  attributes:
    label: Problem Description
    description: Describe the issue you encountered.
  validations:
    required: true

- type: input
  attributes:
    label: Operating System
    description: What is the name and version number of the OS?
    placeholder: "e.g. Ubuntu 22.04.3 LTS (Jammy Jellyfish)"
  validations:
    required: true

- type: input
  attributes:
    label: CPU
    description: What CPU did you encounter the issue on?
    placeholder: "e.g. AMD Ryzen 9 5900HX with Radeon Graphics"
  validations:
    required: true

- type: dropdown
  attributes:
    label: GPU
    description: What GPU(s) did you encounter the issue on (you can select multiple GPUs from the list)
    multiple: true
    options:
        - AMD Instinct MI300
        - AMD Instinct MI300A
        - AMD Instinct MI300X
        - AMD Instinct MI250X
        - AMD Instinct MI250
        - AMD Instinct MI210
        - AMD Instinct MI100
        - AMD Instinct MI50
        - AMD Instinct MI25
        - AMD Radeon Pro V620
        - AMD Radeon Pro VII
        - AMD Radeon RX 7900 XTX
        - AMD Radeon VII
        - AMD Radeon Pro W7900
        - AMD Radeon Pro W7800
        - AMD Radeon Pro W6800
        - AMD Radeon Pro W6600
        - AMD Radeon Pro W5500
        - AMD Radeon RX 7900 XT
        - AMD Radeon RX 7600
        - AMD Radeon RX 6950 XT
        - AMD Radeon RX 6900 XT
        - AMD Radeon RX 6800 XT
        - AMD Radeon RX 6800
        - AMD Radeon RX 6750
        - AMD Radeon RX 6700 XT
        - AMD Radeon RX 6700
        - AMD Radeon RX 6650 XT
        - AMD Radeon RX 6600 XT
        - AMD Radeon RX 6600
        - Other
  validations:
    required: true

- type: input
  attributes:
    label: Other
    description: If you selected Other, please specify

- type: dropdown
  id: rocm_version
  attributes:
    label: ROCm Version
    description: What version(s) of ROCm did you encounter the issue on?
    multiple: true
    options:
    	- ROCm 6.4.1
	- ROCm 6.4.0
	- ROCm 6.3.3
	- ROCm 6.3.2
	- ROCm 6.3.1
	- ROCm 6.3.0
        - ROCm 6.2.4
	- ROCm 6.2.2
	- ROCm 6.2.1
	- ROCm 6.2.0
	- ROCm 6.1.5
	- ROCm 6.1.2
	- ROCm 6.1.1
	- ROCm 6.1.0
	- ROCm 6.0.2
	- ROCm 6.0.0
        - ROCm 5.7.1
        - ROCm 5.7.0
        - ROCm 5.6.0
        - ROCm 5.5.1
        - ROCm 5.5.0
  validations:
    required: true

- type: dropdown
  id: rocm_component
  attributes:
    label: ROCm Component
    description: (Optional) If this issue relates to a specific ROCm component, it can be mentioned here.
    options:
      - Other
      - CI/CD
      - composable_kernel
      - hipBLAS-common
      - hipBLAS
      - hipBLASlt
      - hipCUB
      - hipFFT
      - hipRAND
      - hipSOLVER
      - hipSPARSE
      - hipSPARSElt
      - MIOpen
      - rocBLAS
      - rocFFT
      - rocPRIM
      - rocRAND
      - rocSOLVER
      - rocSPARSE
      - rocThrust

- type: textarea
  attributes:
    label: Steps to Reproduce
    description: (Optional) Detailed steps to reproduce the issue.

- type: textarea
  attributes:
    label: (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support
    description: The output of rocminfo --support could help to better address the problem.

- type: textarea
  attributes:
    label: Additional Information
    description: (Optional) Any additional information that is relevant, e.g. relevant environment variables, dockerfiles, log files, dmesg output (on Linux), etc.
