// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_POOLINGFWDATTRIBUTES_HIPDNN_DATA_SDK_DATA_OBJECTS_H_
#define FLATBUFFERS_GENERATED_POOLINGFWDATTRIBUTES_HIPDNN_DATA_SDK_DATA_OBJECTS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "pooling_common_generated.h"

namespace hipdnn_data_sdk {
namespace data_objects {

struct PoolingFwdAttributes;
struct PoolingFwdAttributesBuilder;
struct PoolingFwdAttributesT;

bool operator==(const PoolingFwdAttributesT &lhs, const PoolingFwdAttributesT &rhs);
bool operator!=(const PoolingFwdAttributesT &lhs, const PoolingFwdAttributesT &rhs);

struct PoolingFwdAttributesT : public ::flatbuffers::NativeTable {
  typedef PoolingFwdAttributes TableType;
  int64_t x_tensor_uid = 0;
  int64_t y_tensor_uid = 0;
  std::vector<int64_t> pre_padding{};
  std::vector<int64_t> post_padding{};
  std::vector<int64_t> stride{};
  std::vector<int64_t> window_size{};
  hipdnn_data_sdk::data_objects::PoolingMode pooling_mode = hipdnn_data_sdk::data_objects::PoolingMode::UNSET;
};

struct PoolingFwdAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PoolingFwdAttributesT NativeTableType;
  typedef PoolingFwdAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X_TENSOR_UID = 4,
    VT_Y_TENSOR_UID = 6,
    VT_PRE_PADDING = 8,
    VT_POST_PADDING = 10,
    VT_STRIDE = 12,
    VT_WINDOW_SIZE = 14,
    VT_POOLING_MODE = 16
  };
  int64_t x_tensor_uid() const {
    return GetField<int64_t>(VT_X_TENSOR_UID, 0);
  }
  bool mutate_x_tensor_uid(int64_t _x_tensor_uid = 0) {
    return SetField<int64_t>(VT_X_TENSOR_UID, _x_tensor_uid, 0);
  }
  int64_t y_tensor_uid() const {
    return GetField<int64_t>(VT_Y_TENSOR_UID, 0);
  }
  bool mutate_y_tensor_uid(int64_t _y_tensor_uid = 0) {
    return SetField<int64_t>(VT_Y_TENSOR_UID, _y_tensor_uid, 0);
  }
  const ::flatbuffers::Vector<int64_t> *pre_padding() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_PRE_PADDING);
  }
  ::flatbuffers::Vector<int64_t> *mutable_pre_padding() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_PRE_PADDING);
  }
  const ::flatbuffers::Vector<int64_t> *post_padding() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_POST_PADDING);
  }
  ::flatbuffers::Vector<int64_t> *mutable_post_padding() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_POST_PADDING);
  }
  const ::flatbuffers::Vector<int64_t> *stride() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_STRIDE);
  }
  ::flatbuffers::Vector<int64_t> *mutable_stride() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_STRIDE);
  }
  const ::flatbuffers::Vector<int64_t> *window_size() const {
    return GetPointer<const ::flatbuffers::Vector<int64_t> *>(VT_WINDOW_SIZE);
  }
  ::flatbuffers::Vector<int64_t> *mutable_window_size() {
    return GetPointer<::flatbuffers::Vector<int64_t> *>(VT_WINDOW_SIZE);
  }
  hipdnn_data_sdk::data_objects::PoolingMode pooling_mode() const {
    return static_cast<hipdnn_data_sdk::data_objects::PoolingMode>(GetField<int8_t>(VT_POOLING_MODE, 0));
  }
  bool mutate_pooling_mode(hipdnn_data_sdk::data_objects::PoolingMode _pooling_mode = static_cast<hipdnn_data_sdk::data_objects::PoolingMode>(0)) {
    return SetField<int8_t>(VT_POOLING_MODE, static_cast<int8_t>(_pooling_mode), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_X_TENSOR_UID, 8) &&
           VerifyField<int64_t>(verifier, VT_Y_TENSOR_UID, 8) &&
           VerifyOffset(verifier, VT_PRE_PADDING) &&
           verifier.VerifyVector(pre_padding()) &&
           VerifyOffset(verifier, VT_POST_PADDING) &&
           verifier.VerifyVector(post_padding()) &&
           VerifyOffset(verifier, VT_STRIDE) &&
           verifier.VerifyVector(stride()) &&
           VerifyOffset(verifier, VT_WINDOW_SIZE) &&
           verifier.VerifyVector(window_size()) &&
           VerifyField<int8_t>(verifier, VT_POOLING_MODE, 1) &&
           verifier.EndTable();
  }
  PoolingFwdAttributesT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(PoolingFwdAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<PoolingFwdAttributes> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PoolingFwdAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct PoolingFwdAttributesBuilder {
  typedef PoolingFwdAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x_tensor_uid(int64_t x_tensor_uid) {
    fbb_.AddElement<int64_t>(PoolingFwdAttributes::VT_X_TENSOR_UID, x_tensor_uid, 0);
  }
  void add_y_tensor_uid(int64_t y_tensor_uid) {
    fbb_.AddElement<int64_t>(PoolingFwdAttributes::VT_Y_TENSOR_UID, y_tensor_uid, 0);
  }
  void add_pre_padding(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> pre_padding) {
    fbb_.AddOffset(PoolingFwdAttributes::VT_PRE_PADDING, pre_padding);
  }
  void add_post_padding(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> post_padding) {
    fbb_.AddOffset(PoolingFwdAttributes::VT_POST_PADDING, post_padding);
  }
  void add_stride(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> stride) {
    fbb_.AddOffset(PoolingFwdAttributes::VT_STRIDE, stride);
  }
  void add_window_size(::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> window_size) {
    fbb_.AddOffset(PoolingFwdAttributes::VT_WINDOW_SIZE, window_size);
  }
  void add_pooling_mode(hipdnn_data_sdk::data_objects::PoolingMode pooling_mode) {
    fbb_.AddElement<int8_t>(PoolingFwdAttributes::VT_POOLING_MODE, static_cast<int8_t>(pooling_mode), 0);
  }
  explicit PoolingFwdAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PoolingFwdAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PoolingFwdAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PoolingFwdAttributes> CreatePoolingFwdAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t x_tensor_uid = 0,
    int64_t y_tensor_uid = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> pre_padding = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> post_padding = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> stride = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<int64_t>> window_size = 0,
    hipdnn_data_sdk::data_objects::PoolingMode pooling_mode = hipdnn_data_sdk::data_objects::PoolingMode::UNSET) {
  PoolingFwdAttributesBuilder builder_(_fbb);
  builder_.add_y_tensor_uid(y_tensor_uid);
  builder_.add_x_tensor_uid(x_tensor_uid);
  builder_.add_window_size(window_size);
  builder_.add_stride(stride);
  builder_.add_post_padding(post_padding);
  builder_.add_pre_padding(pre_padding);
  builder_.add_pooling_mode(pooling_mode);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PoolingFwdAttributes> CreatePoolingFwdAttributesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t x_tensor_uid = 0,
    int64_t y_tensor_uid = 0,
    const std::vector<int64_t> *pre_padding = nullptr,
    const std::vector<int64_t> *post_padding = nullptr,
    const std::vector<int64_t> *stride = nullptr,
    const std::vector<int64_t> *window_size = nullptr,
    hipdnn_data_sdk::data_objects::PoolingMode pooling_mode = hipdnn_data_sdk::data_objects::PoolingMode::UNSET) {
  auto pre_padding__ = pre_padding ? _fbb.CreateVector<int64_t>(*pre_padding) : 0;
  auto post_padding__ = post_padding ? _fbb.CreateVector<int64_t>(*post_padding) : 0;
  auto stride__ = stride ? _fbb.CreateVector<int64_t>(*stride) : 0;
  auto window_size__ = window_size ? _fbb.CreateVector<int64_t>(*window_size) : 0;
  return hipdnn_data_sdk::data_objects::CreatePoolingFwdAttributes(
      _fbb,
      x_tensor_uid,
      y_tensor_uid,
      pre_padding__,
      post_padding__,
      stride__,
      window_size__,
      pooling_mode);
}

::flatbuffers::Offset<PoolingFwdAttributes> CreatePoolingFwdAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const PoolingFwdAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const PoolingFwdAttributesT &lhs, const PoolingFwdAttributesT &rhs) {
  return
      (lhs.x_tensor_uid == rhs.x_tensor_uid) &&
      (lhs.y_tensor_uid == rhs.y_tensor_uid) &&
      (lhs.pre_padding == rhs.pre_padding) &&
      (lhs.post_padding == rhs.post_padding) &&
      (lhs.stride == rhs.stride) &&
      (lhs.window_size == rhs.window_size) &&
      (lhs.pooling_mode == rhs.pooling_mode);
}

inline bool operator!=(const PoolingFwdAttributesT &lhs, const PoolingFwdAttributesT &rhs) {
    return !(lhs == rhs);
}


inline PoolingFwdAttributesT *PoolingFwdAttributes::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<PoolingFwdAttributesT>(new PoolingFwdAttributesT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void PoolingFwdAttributes::UnPackTo(PoolingFwdAttributesT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = x_tensor_uid(); _o->x_tensor_uid = _e; }
  { auto _e = y_tensor_uid(); _o->y_tensor_uid = _e; }
  { auto _e = pre_padding(); if (_e) { _o->pre_padding.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->pre_padding[_i] = _e->Get(_i); } } else { _o->pre_padding.resize(0); } }
  { auto _e = post_padding(); if (_e) { _o->post_padding.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->post_padding[_i] = _e->Get(_i); } } else { _o->post_padding.resize(0); } }
  { auto _e = stride(); if (_e) { _o->stride.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->stride[_i] = _e->Get(_i); } } else { _o->stride.resize(0); } }
  { auto _e = window_size(); if (_e) { _o->window_size.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->window_size[_i] = _e->Get(_i); } } else { _o->window_size.resize(0); } }
  { auto _e = pooling_mode(); _o->pooling_mode = _e; }
}

inline ::flatbuffers::Offset<PoolingFwdAttributes> PoolingFwdAttributes::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const PoolingFwdAttributesT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreatePoolingFwdAttributes(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<PoolingFwdAttributes> CreatePoolingFwdAttributes(::flatbuffers::FlatBufferBuilder &_fbb, const PoolingFwdAttributesT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const PoolingFwdAttributesT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _x_tensor_uid = _o->x_tensor_uid;
  auto _y_tensor_uid = _o->y_tensor_uid;
  auto _pre_padding = _o->pre_padding.size() ? _fbb.CreateVector(_o->pre_padding) : 0;
  auto _post_padding = _o->post_padding.size() ? _fbb.CreateVector(_o->post_padding) : 0;
  auto _stride = _o->stride.size() ? _fbb.CreateVector(_o->stride) : 0;
  auto _window_size = _o->window_size.size() ? _fbb.CreateVector(_o->window_size) : 0;
  auto _pooling_mode = _o->pooling_mode;
  return hipdnn_data_sdk::data_objects::CreatePoolingFwdAttributes(
      _fbb,
      _x_tensor_uid,
      _y_tensor_uid,
      _pre_padding,
      _post_padding,
      _stride,
      _window_size,
      _pooling_mode);
}

}  // namespace data_objects
}  // namespace hipdnn_data_sdk

#endif  // FLATBUFFERS_GENERATED_POOLINGFWDATTRIBUTES_HIPDNN_DATA_SDK_DATA_OBJECTS_H_
