#!/usr/bin/env python3
###############################################################################
 #
 # MIT License
 #
 # Copyright (C) 2023-2026 Advanced Micro Devices, Inc. All rights reserved.
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
 # in the Software without restriction, including without limitation the rights
 # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 # copies of the Software, and to permit persons to whom the Software is
 # furnished to do so, subject to the following conditions:
 #
 # The above copyright notice and this permission notice shall be included in
 # all copies or substantial portions of the Software.
 #
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 # THE SOFTWARE.
 #
 ###############################################################################

"""Generate the hipTensor public-API coverage test source.

Parses the public header for every function declared with HIPTENSOR_EXPORT and
emits a C++ translation unit that takes the address of each one. Linking the
generated source against libhiptensor therefore fails if the library does not
export some declared API function, and the GoogleTest case asserts a non-empty
set was collected. Running the codegen at configure time means a newly added
public API is picked up automatically: it gets a new address reference, so a
library that forgot to export it fails to link.
"""

import argparse
import re
import sys
from pathlib import Path


def parse_exported_functions(header: Path) -> list[str]:
    """Return the sorted list of function names declared with HIPTENSOR_EXPORT."""
    text = header.read_text()
    # Drop comments so documentation prose cannot introduce phantom names.
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)

    names: set[str] = set()
    # Each exported declaration looks like:
    #   HIPTENSOR_EXPORT <return type> hiptensorXxx( ... );
    for decl in re.findall(r"HIPTENSOR_EXPORT\b(.*?);", text, flags=re.DOTALL):
        match = re.search(r"(hiptensor[A-Za-z0-9_]*)\s*\(", decl)
        if match:
            names.add(match.group(1))
    return sorted(names)


_TEMPLATE = """\
// Auto-generated by generate_api_coverage.py. Do not edit.
//
// References the address of every HIPTENSOR_EXPORT function in the public
// header. Linking this file against libhiptensor fails if any declared public
// API symbol is not exported by the built library, turning a would-be consumer
// link error into a build/test failure for hipTensor itself.

#include <gtest/gtest.h>

#include <hiptensor/hiptensor.h>

namespace
{{
    // Taking each function's address forces the linker to resolve the symbol.
    // Stored as void pointers in a table so the references cannot be optimized
    // away and so the test can assert a non-empty, expected-size API surface.
    void* const kPublicApiSymbols[] = {{
{symbol_rows}
    }};

    constexpr int kExpectedApiSymbolCount = {count};
}}

TEST(ApiCoverage, AllPublicSymbolsExported)
{{
    constexpr int actual = static_cast<int>(sizeof(kPublicApiSymbols)
                                            / sizeof(kPublicApiSymbols[0]));
    EXPECT_EQ(actual, kExpectedApiSymbolCount);
    for(int i = 0; i < actual; ++i)
    {{
        EXPECT_NE(kPublicApiSymbols[i], nullptr) << "null API symbol at index " << i;
    }}
}}

int main(int argc, char** argv)
{{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}}
"""


def render(names: list[str]) -> str:
    rows = ",\n".join(
        f"        reinterpret_cast<void*>(&{name})" for name in names
    )
    return _TEMPLATE.format(
        symbol_rows=rows,
        count=len(names),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--header", required=True, type=Path, help="Path to public hiptensor.h"
    )
    parser.add_argument(
        "--output", required=True, type=Path, help="Path of the .cpp to generate"
    )
    args = parser.parse_args()

    names = parse_exported_functions(args.header)
    if not names:
        print(
            f"ERROR: no HIPTENSOR_EXPORT functions found in {args.header}",
            file=sys.stderr,
        )
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(names))
    print(f"Generated {args.output} referencing {len(names)} public API functions.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
