# Copyright © Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier:  MIT

# ============================================================================
# Get theRock
# ============================================================================
FROM therock_base:6a91147f22b525b79b19e909ea832d4f21e71306 AS rock

# ============================================================================
# Common base image with all dependencies
# ============================================================================
FROM miopen-build-base:latest AS base

# Copy /opt/rocm from the rock image to the base image
COPY --from=rock /opt/rocm /opt/rocm

# ============================================================================
# Build and install miopen dependencies via rbuild
# ============================================================================
FROM base as miopen_deps
ARG PROJ="miopen"
ARG PREFIX="/usr/local"

# Add requirements files
ADD ${PROJ}/rbuild.ini /rbuild.ini
ADD ${PROJ}/requirements.txt /requirements.txt
ADD ${PROJ}/dev-requirements.txt /dev-requirements.txt
# rbuild is used to trigger build of requirements.txt, dev-requirements.txt.
# Composable Kernel install separated from rbuild 
# Additionally remove components that are already installed by other compoenents as a part of the source build.
RUN cd / && \
    sed -i '/composablekernel/d; /half/d; /nlohmann/d' /requirements.txt && \
    if [ "$USE_FIN" = "ON" ]; then \
        rbuild prepare -s fin -d ${PREFIX} -DGPU_ARCHS="${THEROCK_ASIC}"; \
    else \
        rbuild prepare -s develop -d ${PREFIX} -DGPU_ARCHS="${THEROCK_ASIC}"; \
    fi && \
    ccache -s

# ============================================================================
# Build and install CK
# ============================================================================

ADD ${PROJ}/script/redis-cli.conf /redis-cli.conf
ADD ${PROJ}/script/sccache_wrapper.sh /sccache_wrapper.sh

## Sccache binary built from source for ROCm, only install if MIOPEN_SCCACHE is defined
ARG SCCACHE_REPO_URL=http://compute-artifactory.amd.com/artifactory/rocm-generic-experimental/rocm-sccache
ENV SCCACHE_INSTALL_LOCATION=/usr/local/.cargo/bin
ENV PATH=$PATH:${SCCACHE_INSTALL_LOCATION}
ARG MIOPEN_SCCACHE=""
ENV MIOPEN_SCCACHE=$MIOPEN_SCCACHE
ARG COMPILER_LAUNCHER=""
ARG MIOPEN_SCCACHE_CUSTOM_CACHE_BUSTER="MiOpen-Docker-CK"
ENV MIOPEN_SCCACHE=$MIOPEN_SCCACHE
ARG THEROCK_ASIC=""
ENV THEROCK_ASIC=${THEROCK_ASIC}

# Copy Composable Kernel
COPY /composablekernel /composable_kernel

# Build and install Composable Kernel
RUN set -x && \
    echo Building for GPU Archs: ${THEROCK_ASIC} && \
    if [ "$MIOPEN_SCCACHE" != "" ]; then \
    mkdir -p ${SCCACHE_INSTALL_LOCATION} && \
    export SCCACHE_VERSION=$(curl -s "https://api.github.com/repos/mozilla/sccache/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+') && \
    wget -qO sccache.tar.gz https://github.com/mozilla/sccache/releases/latest/download/sccache-v$SCCACHE_VERSION-x86_64-unknown-linux-musl.tar.gz && \
    tar -xzf sccache.tar.gz --strip-components=1 -C ${SCCACHE_INSTALL_LOCATION} && \
    # Extract 
    chmod +x ${SCCACHE_INSTALL_LOCATION}/sccache && \
    echo $ROCM_PATH && \
    export ROCM_PATH=/opt/rocm && \
    export SCCACHE_ENABLED=true && \
    export SCCACHE_LOG_LEVEL=debug && \
    export SCCACHE_IDLE_TIMEOUT=14400 && \
    export COMPILERS_HASH_DIR=/tmp/.sccache && \
    export SCCACHE_BIN=${SCCACHE_INSTALL_LOCATION}/sccache && \
    export SCCACHE_EXTRAFILES=/tmp/.sccache/rocm_compilers_hash_file && \
    export SCCACHE_REDIS="redis://$MIOPEN_SCCACHE" && \
    cd / && \
    echo "connect = $MIOPEN_SCCACHE" >> redis-cli.conf && \
    export SCCACHE_C_CUSTOM_CACHE_BUSTER="${MIOPEN_SCCACHE_CUSTOM_CACHE_BUSTER}" && \
    echo $SCCACHE_C_CUSTOM_CACHE_BUSTER && \
    stunnel redis-cli.conf && \
    export PATH=$PATH:${SCCACHE_INSTALL_LOCATION} && \
    ./sccache_wrapper.sh --enforce_redis; \
    pwd; \
    fi &&\
# Clear the ROCM_PATH as it causes hip errors due to theRock
    unset ROCM_PATH && \
    cd /composable_kernel && \
    mkdir build && cd build && \
    num_threads=124 && \
    echo Building CK with ${num_threads} threads && \
    export HIPCXX=/opt/rocm/llvm/bin/amdclang++ && \
    CXX=/opt/rocm/llvm/bin/amdclang++ cmake \
    cmake \
    -G Ninja \
    -D CMAKE_HIP_COMPILER_ROCM_ROOT=/opt/rocm \
    -D CMAKE_PREFIX_PATH=/opt/rocm \
    -D CMAKE_HIP_COMPILER=/opt/rocm/llvm/bin/amdclang++ \
    -D CMAKE_CXX_COMPILER_LAUNCHER=sccache \
    -D CMAKE_HIP_COMPILER_LAUNCHER=sccache \
    -D CMAKE_C_COMPILER_LAUNCHER=sccache \
    -D CMAKE_BUILD_TYPE=Release \
    -D GPU_TARGETS="${THEROCK_ASIC}" \
    -D MIOPEN_REQ_LIBS_ONLY=ON \
    -D CMAKE_CXX_FLAGS=" -O3 " .. && \
    ninja -j ${num_threads} install && \
    if [ "$MIOPEN_SCCACHE" != "" ]; then \
    sccache -s; \
    fi

# ============================================================================
# Common miopen development environment
# ============================================================================
FROM base AS miopen

COPY --from=miopen_deps /opt/rocm /opt/rocm
COPY --from=miopen_deps /usr/local /usr/local

ENV HIP_PLATFORM=amd
ENV PATH="/opt/rocm/bin:/opt/rocm:${PATH}"
