#[[
MIT License

Copyright (c) 2026 Advanced Micro Devices, Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
]]

# Script-mode half of rpp_discover_grouped_tests(). Run as a POST_BUILD step with
# TEST_EXECUTABLE / TEST_OUTPUT_FILE / TEST_WORKING_DIRECTORY / TEST_TIMEOUT defined.

cmake_minimum_required(VERSION 3.14)

foreach(_required TEST_EXECUTABLE TEST_OUTPUT_FILE TEST_WORKING_DIRECTORY TEST_TIMEOUT)
    if(NOT DEFINED ${_required})
        message(FATAL_ERROR "grouped_tests_impl.cmake: ${_required} is not set")
    endif()
endforeach()

execute_process(
    COMMAND "${TEST_EXECUTABLE}" --gtest_list_tests
    WORKING_DIRECTORY "${TEST_WORKING_DIRECTORY}"
    OUTPUT_VARIABLE _listing
    ERROR_VARIABLE _listingErrors
    RESULT_VARIABLE _listingResult)

if(NOT _listingResult EQUAL 0)
    message(FATAL_ERROR
        "Failed to list GTest suites: '${TEST_EXECUTABLE} --gtest_list_tests' exited with "
        "${_listingResult}\n${_listingErrors}")
endif()

# Split into lines. Semicolons would otherwise be read as list separators; GTest names contain
# none, but the escape keeps a stray one in a parameter comment from corrupting the parse.
string(REPLACE ";" "\\;" _listing "${_listing}")
string(REPLACE "\n" ";" _lines "${_listing}")

# --gtest_list_tests prints a suite per unindented line ending in '.', with its cases indented
# beneath it:
#
#   Image_Geometric/RotateTest.
#     Correctness/HOST_U8toU8_PKD3_FullRoi_2x36x48_a0_NN  # GetParam() =
#
# Only the suite lines are of interest -- one CTest test is registered per suite.
set(_suites "")
foreach(_line IN LISTS _lines)
    if(_line MATCHES "^[ \t]")
        continue()  # an individual case
    endif()
    string(REGEX REPLACE "[ \t]*#.*$" "" _line "${_line}")  # '# TypeParam = ...' annotation
    string(STRIP "${_line}" _line)
    if(NOT _line MATCHES "\\.$")
        continue()  # blank line, or a banner GTest printed before the listing
    endif()
    string(REGEX REPLACE "\\.$" "" _line "${_line}")
    list(APPEND _suites "${_line}")
endforeach()

if(NOT _suites)
    message(FATAL_ERROR
        "No GTest suites found in the output of '${TEST_EXECUTABLE} --gtest_list_tests'. "
        "Registering nothing would make `ctest` pass without running anything.")
endif()

set(_content "# Generated by rpp_discover_grouped_tests(). Do not edit.\n")
foreach(_suite IN LISTS _suites)
    # Labels give back the category-level selection that per-suite registration would otherwise
    # lose: `ctest -L Image_Geometric` or `ctest -L voxel`. Suite names follow
    # {Domain}_{Category}/{Op}Test; the core suites carry no prefix. Setting them makes CTest
    # print its "Label Time Summary" block after a run -- `ctest --no-label-summary` drops it.
    if(_suite MATCHES "^(([A-Za-z0-9]+)_[A-Za-z0-9]+)/")
        # Read both captures before any further regex call: every string(REGEX ...) resets
        # CMAKE_MATCH_<n>.
        set(_category "${CMAKE_MATCH_1}")
        string(TOLOWER "${CMAKE_MATCH_2}" _domain)
        set(_labels "${_category};${_domain}")
    else()
        set(_labels "core")
    endif()

    # SKIP_REGULAR_EXPRESSION deliberately does NOT match GTest's bare '[  SKIPPED ]' token the
    # way gtest_discover_tests' per-case registration does. With a whole suite in one process, a
    # single skip-list entry would then mark the entire CTest test as skipped and hide real
    # failures alongside it. The reporter prints this phrase only when nothing failed and nothing
    # ran, so it can never mask a failure.
    #
    # The legacy add_test(<name> <command> [args...]) form is used because this file is read by
    # CTest itself, whose add_test() does not implement the NAME/COMMAND keyword signature.
    string(APPEND _content
        "add_test([==[${_suite}]==]\n"
        "         [==[${TEST_EXECUTABLE}]==] [==[--gtest_filter=${_suite}.*]==])\n"
        "set_tests_properties([==[${_suite}]==] PROPERTIES\n"
        "    WORKING_DIRECTORY [==[${TEST_WORKING_DIRECTORY}]==]\n"
        "    TIMEOUT ${TEST_TIMEOUT}\n"
        "    LABELS [==[${_labels}]==]\n"
        "    SKIP_REGULAR_EXPRESSION [==[no cases ran \\(]==])\n")
endforeach()

# Write through a temporary so an unchanged suite list leaves the timestamp alone; CTest re-reads
# TEST_INCLUDE_FILES on every run, and touching it on every build would churn needlessly.
file(WRITE "${TEST_OUTPUT_FILE}.tmp" "${_content}")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different
                        "${TEST_OUTPUT_FILE}.tmp" "${TEST_OUTPUT_FILE}")
file(REMOVE "${TEST_OUTPUT_FILE}.tmp")

list(LENGTH _suites _suiteCount)
message(STATUS "Registered ${_suiteCount} CTest tests, one per GTest suite")
