#!/usr/bin/env python3

# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

"""Byte-level golden-file test for the block-scale quant GEMM code generators.

This is a *safety net* for the upcoming refactor that folds the eight
``unified_*_codegen.py`` generators into a single engine.  It captures the
exact bytes each generator emits for a comprehensive config matrix and asserts
that a re-run produces byte-identical output.  If the follow-up rewrite changes
even one byte of any generated kernel header, this test fails and prints which
config drifted plus a unified-diff snippet.

Scope
-----
Eight generators are exercised (5 non-grouped + 3 grouped quant families)::

    unified_gemm_aquant_codegen.py          <- gemm_aquant_utils
    unified_gemm_abquant_codegen.py         <- gemm_abquant_utils
    unified_gemm_bquant_codegen.py          <- gemm_bquant_utils
    unified_gemm_rowcolquant_codegen.py     <- gemm_rowcolquant_utils
    unified_gemm_tensor_quant_codegen.py    <- gemm_tensor_quant_utils
    unified_grouped_gemm_aquant_codegen.py  <- grouped_gemm_aquant_utils
    unified_grouped_gemm_abquant_codegen.py <- grouped_gemm_abquant_utils
    unified_grouped_gemm_bquant_codegen.py  <- grouped_gemm_bquant_utils

The matrix is assembled from every ``default_*_config`` factory in each
``*_utils`` module, invoked for BOTH ``gfx942`` and ``gfx950`` (the arch-derived
``warp_tile_k`` 32/64-vs-128 branch is the key arch-dependent axis).  Each
factory covers a dtype/layout/variant family (fp8, bf8, fp8i4/bf8i4, fp4, the
MX bf16bf16/bf16bf8/bf16fp4 microscale variants for bquant, preshuffle-b /
preshuffle-quant / eight-waves / permute-n variants, grouped vs non-grouped).
Using the shipped factories as the source of valid configs guarantees we never
hand-build an invalid config that the generator would reject.

Determinism
-----------
The generated bytes are fully deterministic: the header preamble carries no
timestamp and no absolute path, the config JSON is serialized with
``sort_keys=True``, and the matrix is walked in a fixed (sorted) order.  The
generator runs pure-Python with no GPU / hipcc required, so this test runs on a
CPU-only box.

Fixture layout
--------------
``tests/golden/codegen/``::

    manifest.json                   # every (module, factory, arch) case ->
                                    #   config_name, sha256(hpp_bytes), and the
                                    #   exact codegen-config dict
    hpp/<config_name>.hpp.golden    # one full body per UNIQUE generated kernel

The fixtures are stored with a ``.hpp.golden`` extension (NOT ``.hpp``) so the
CK CI "Static checks" stage -- which runs clang-format-18 over every ``*.hpp``
(and ``*.h`` / ``*.cpp`` / ``*.inc`` / ``*.cl`` / ``*.*.in``) in the repo --
neither flags these generated goldens as unformatted nor reformats them (which
would break the byte-identity this test relies on).  ``.hpp.golden`` keeps the
readable stem while matching none of the CI find patterns.

The matrix has 140 (factory x arch) cases; 31 of them are arch-invariant (the
grouped families and the MX / fp4 variants hardcode ``warp_tile_k`` independent
of arch), so they collapse to 109 unique ``.hpp.golden`` files.  The manifest
stores all 140 cases (proving each arch axis was exercised) while the kernel
bodies are deduped by ``config_name``.  A byte change is caught two ways: the
full body comparison (with a diff) AND the per-case sha256 in the manifest.

Non-quant tripwire
------------------
A second, clearly-separated golden set lives under
``tests/golden/codegen/tripwire/`` (its own ``manifest.json`` + ``hpp/``).  It
freezes representative output of the NON-quant generators that share
``codegen/codegen_common.py`` -- ``unified_gemm_codegen.py`` (gemm_universal,
the heaviest consumer), ``unified_grouped_conv_codegen.py`` (grouped conv) and
``codegen/fmha/codegen.py`` (FMHA) -- plus cheap bonus coverage of
``unified_mx_gemm_codegen.py`` and ``unified_batched_contraction_codegen.py``
(both independent of codegen_common).  The upcoming quant-engine refactor must
not perturb codegen_common; if it does, one of these non-quant goldens drifts
and the suite fails.  See the big ``NON-QUANT TRIPWIRE`` block further down.

Regeneration
------------
Refresh the goldens intentionally after a deliberate generator change::

    python3 tests/test_codegen_golden.py --update

or::

    python3 -m tests.test_codegen_golden --update
"""

import difflib
import hashlib
import json
import subprocess
import sys
import tempfile
from importlib import import_module
from pathlib import Path

import pytest

# --------------------------------------------------------------------------- #
# Paths / imports (mirror the sibling bridge tests' sys.path setup)
# --------------------------------------------------------------------------- #

_DISP = Path(__file__).resolve().parent.parent
_PY_DIR = _DISP / "python"
_CODEGEN_DIR = _DISP / "codegen"
for _p in (_PY_DIR, _CODEGEN_DIR):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

# On-disk fixture extension.  Deliberately NOT ``.hpp`` (nor any of the other
# C/C++ suffixes the CK CI "Static checks" clang-format sweep globs for:
# .h/.hpp/.cpp/.h.in/.hpp.in/.cpp.in/.inc/.cl) so CI never flags or reformats
# these generated goldens -- reformatting would break the byte-identity the
# test asserts.  The logical kernel name (the manifest key / stem) is unchanged;
# only the file suffix differs.
_FIXTURE_EXT = ".hpp.golden"

_GOLDEN_DIR = Path(__file__).resolve().parent / "golden" / "codegen"
_HPP_DIR = _GOLDEN_DIR / "hpp"
_MANIFEST = _GOLDEN_DIR / "manifest.json"

# --------------------------------------------------------------------------- #
# NON-QUANT TRIPWIRE (see the big block comment above the tripwire matrix
# further down).  Its goldens live in a *separate* subdir so they never mix
# with the quant goldens above.
# --------------------------------------------------------------------------- #

_TRIPWIRE_DIR = _GOLDEN_DIR / "tripwire"
_TRIPWIRE_HPP_DIR = _TRIPWIRE_DIR / "hpp"
_TRIPWIRE_MANIFEST = _TRIPWIRE_DIR / "manifest.json"

# The eight utils modules that own the eight generators.  Sorted for a stable
# walk order.
_UTILS_MODULES = (
    "gemm_aquant_utils",
    "gemm_abquant_utils",
    "gemm_bquant_utils",
    "gemm_rowcolquant_utils",
    "gemm_tensor_quant_utils",
    "grouped_gemm_aquant_utils",
    "grouped_gemm_abquant_utils",
    "grouped_gemm_bquant_utils",
)

# The two arches whose divergent arch-derived warp_tile_k is the key branch.
_ARCHES = ("gfx942", "gfx950")

_CODEGEN_TIMEOUT = 180


# --------------------------------------------------------------------------- #
# Matrix assembly
# --------------------------------------------------------------------------- #


def _default_config_factories(mod):
    """Return the sorted ``default_*_config`` callables exported by ``mod``."""
    names = [
        n
        for n in dir(mod)
        if n.startswith("default_")
        and n.endswith("_config")
        and callable(getattr(mod, n))
    ]
    return sorted(names)


def build_matrix():
    """Assemble the deterministic (module, factory, arch) case matrix.

    Yields dicts with everything a case needs: a stable ``case_id``, the
    codegen script path, the exact codegen-config dict, and the config's
    ``name`` (which is also the ``.hpp`` stem the generator writes).
    """
    cases = []
    for module_name in _UTILS_MODULES:
        mod = import_module(module_name)
        script = Path(getattr(mod, "_CODEGEN_SCRIPT"))
        for factory in _default_config_factories(mod):
            fn = getattr(mod, factory)
            for arch in _ARCHES:
                cfg = fn(gfx_arch=arch)
                cases.append(
                    {
                        "case_id": f"{module_name}::{factory}::{arch}",
                        "module": module_name,
                        "factory": factory,
                        "arch": arch,
                        "script": script,
                        "config_name": cfg.name,
                        "config": cfg.to_codegen_config(),
                    }
                )
    # Stable order regardless of dir()/import ordering quirks.
    cases.sort(key=lambda c: c["case_id"])
    return cases


def _config_json(config: dict) -> str:
    """Canonical (sorted-key) JSON for a codegen-config dict."""
    return json.dumps(config, sort_keys=True)


def generate_hpp_bytes(script: Path, config: dict, config_name: str) -> bytes:
    """Invoke a ``unified_*_codegen.py`` for one config; return the .hpp bytes.

    The generator CLI is identical across all eight scripts::

        python <script> --output-dir <dir> --config-json <json>

    and writes ``<dir>/<config_name>.hpp``.  Pure Python, no GPU needed.
    """
    with tempfile.TemporaryDirectory(prefix="ck_codegen_golden_") as td:
        cmd = [
            sys.executable,
            str(script),
            "--output-dir",
            td,
            "--config-json",
            _config_json(config),
        ]
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=_CODEGEN_TIMEOUT
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"codegen failed ({script.name}, {config_name}):\n{result.stderr}"
            )
        hpp = Path(td) / f"{config_name}.hpp"
        if not hpp.exists():
            raise RuntimeError(
                f"codegen produced no {config_name}.hpp ({script.name})\n"
                f"stderr:\n{result.stderr}"
            )
        return hpp.read_bytes()


# --------------------------------------------------------------------------- #
# Golden regeneration (also the module's __main__ --update entrypoint)
# --------------------------------------------------------------------------- #


def regenerate_goldens() -> int:
    """(Re)write every golden fixture and ``manifest.json``.  Returns case count.

    Fixtures are written with the ``.hpp.golden`` extension (see ``_FIXTURE_EXT``)
    so the CK CI clang-format sweep skips them.  Removes any stale fixtures first
    so a deleted/renamed kernel can't leave an orphan behind, then writes each
    unique kernel body once and records all cases in the manifest.
    """
    _HPP_DIR.mkdir(parents=True, exist_ok=True)

    for stale in _HPP_DIR.glob(f"*{_FIXTURE_EXT}"):
        stale.unlink()

    cases = build_matrix()
    manifest = {
        "_comment": (
            "Golden byte-hashes for the block-scale quant GEMM code generators. "
            "Regenerate intentionally with: python3 tests/test_codegen_golden.py "
            "--update"
        ),
        "arches": list(_ARCHES),
        "modules": list(_UTILS_MODULES),
        "case_count": len(cases),
        "cases": {},
    }

    written_hpp: dict = {}
    for case in cases:
        data = generate_hpp_bytes(case["script"], case["config"], case["config_name"])
        sha = hashlib.sha256(data).hexdigest()

        name = case["config_name"]
        prev = written_hpp.get(name)
        if prev is None:
            (_HPP_DIR / f"{name}{_FIXTURE_EXT}").write_bytes(data)
            written_hpp[name] = sha
        elif prev != sha:
            # Two cases share a config_name but produce different bytes: the
            # fixture filename can't disambiguate them.  This must never happen; if
            # it does, the naming contract is broken and we fail loudly.
            raise RuntimeError(
                f"config_name collision with differing bytes: {name} "
                f"(case {case['case_id']})"
            )

        manifest["cases"][case["case_id"]] = {
            "module": case["module"],
            "factory": case["factory"],
            "arch": case["arch"],
            "config_name": name,
            "sha256": sha,
            "config": case["config"],
        }

    _MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return len(cases)


def _load_manifest() -> dict:
    if not _MANIFEST.exists():
        raise FileNotFoundError(
            f"golden manifest missing: {_MANIFEST}\n"
            "Generate it with: python3 tests/test_codegen_golden.py --update"
        )
    return json.loads(_MANIFEST.read_text())


# --------------------------------------------------------------------------- #
# Tests
# --------------------------------------------------------------------------- #


def _matrix_ids_and_cases():
    cases = build_matrix()
    return [c["case_id"] for c in cases], cases


_IDS, _CASES = _matrix_ids_and_cases()


def test_manifest_matches_matrix():
    """The frozen manifest must describe exactly the current config matrix.

    Catches a factory being added/removed/renamed (a change to the set of
    generated kernels) even before any byte comparison runs.
    """
    manifest = _load_manifest()
    frozen = set(manifest["cases"])
    live = {c["case_id"] for c in _CASES}
    missing = frozen - live
    extra = live - frozen
    assert not missing, (
        "goldens describe cases no longer in the matrix (regenerate goldens): "
        f"{sorted(missing)}"
    )
    assert not extra, (
        "matrix has cases with no golden (regenerate goldens): "
        f"{sorted(extra)}"
    )


@pytest.mark.parametrize("case", _CASES, ids=_IDS)
def test_codegen_bytes_match_golden(case):
    """Regenerated .hpp bytes must be byte-identical to the golden fixture."""
    manifest = _load_manifest()
    entry = manifest["cases"].get(case["case_id"])
    assert entry is not None, (
        f"no golden for {case['case_id']} -- regenerate goldens"
    )

    # 1) The (factory, arch) -> config_name mapping must be stable.
    assert entry["config_name"] == case["config_name"], (
        f"{case['case_id']}: config name drifted\n"
        f"  golden: {entry['config_name']}\n"
        f"  now:    {case['config_name']}"
    )
    # 2) The codegen-config dict fed to the generator must be stable.
    assert entry["config"] == case["config"], (
        f"{case['case_id']}: codegen-config dict drifted\n"
        f"  golden: {_config_json(entry['config'])}\n"
        f"  now:    {_config_json(case['config'])}"
    )

    golden_hpp = _HPP_DIR / f"{case['config_name']}{_FIXTURE_EXT}"
    assert golden_hpp.exists(), (
        f"golden fixture missing: {golden_hpp} -- regenerate goldens"
    )
    golden_bytes = golden_hpp.read_bytes()

    # 3) The sha256 recorded in the manifest must match the stored .hpp.
    stored_sha = hashlib.sha256(golden_bytes).hexdigest()
    assert stored_sha == entry["sha256"], (
        f"{case['case_id']}: manifest sha256 disagrees with stored "
        f"{golden_hpp.name} (corrupt/edited fixture) -- regenerate goldens"
    )

    # 4) The freshly generated bytes must equal the golden bytes.
    fresh_bytes = generate_hpp_bytes(
        case["script"], case["config"], case["config_name"]
    )
    if fresh_bytes != golden_bytes:
        diff = "\n".join(
            difflib.unified_diff(
                golden_bytes.decode("utf-8", "replace").splitlines(),
                fresh_bytes.decode("utf-8", "replace").splitlines(),
                fromfile=f"golden/{case['config_name']}{_FIXTURE_EXT}",
                tofile=f"generated/{case['config_name']}.hpp",
                lineterm="",
                n=3,
            )
        )
        snippet = "\n".join(diff.splitlines()[:60])
        pytest.fail(
            f"{case['case_id']}: generated bytes differ from golden "
            f"({case['config_name']}.hpp)\n"
            f"golden sha256={entry['sha256']}\n"
            f"fresh  sha256={hashlib.sha256(fresh_bytes).hexdigest()}\n"
            f"--- unified diff (first 60 lines) ---\n{snippet}"
        )


def test_generation_is_deterministic():
    """Re-running one generator twice yields byte-identical output.

    A cheap direct guard that the codegen path itself has no run-to-run
    nondeterminism (ordering, hashing, temp-path leakage) independent of the
    stored goldens.
    """
    case = _CASES[0]
    a = generate_hpp_bytes(case["script"], case["config"], case["config_name"])
    b = generate_hpp_bytes(case["script"], case["config"], case["config_name"])
    assert a == b, f"{case['case_id']}: codegen is nondeterministic"


# =========================================================================== #
# NON-QUANT TRIPWIRE
# =========================================================================== #
#
# Why this section exists
# -----------------------
# A follow-up refactor will fold the eight QUANT generators (exercised above)
# into a single quant-only engine.  That refactor MUST NOT change the behavior
# of the shared ``codegen/codegen_common.py`` module, because three NON-quant
# generators import it and depend on it:
#
#     unified_gemm_codegen.py          (gemm_universal)  -- heaviest user:
#         imports TileConfig, TraitConfigBase, CommonTypeMappings and drives
#         the kernel-name / namespace / header-preamble build through them.
#     unified_grouped_conv_codegen.py  (grouped conv)    -- imports TileConfig,
#         TraitConfigBase, parallel_generate.
#     codegen/fmha/codegen.py          (FMHA)            -- imports
#         parallel_generate (the shared fan-out helper).
#
# This section freezes golden bytes for those generators so that if the quant
# refactor accidentally perturbs anything shared in codegen_common (name
# formatting, TileConfig/TraitConfig semantics, the type maps, or the
# parallel_generate contract), one of these non-quant goldens drifts and the
# suite fails -- the tripwire.
#
# Two extra generators are covered as cheap bonus coverage even though they do
# NOT import codegen_common (they are fully independent):
#
#     unified_mx_gemm_codegen.py            (mx_gemm)
#     unified_batched_contraction_codegen.py(batched_contraction)
#
# They are driven exactly like the quant generators (a ``default_*_config``
# factory -> ``to_codegen_config()`` -> ``--config-json`` -> ``<name>.hpp``),
# so they come almost for free.
#
# Config sourcing (same discipline as the quant matrix)
# -----------------------------------------------------
# Every tripwire config is a real, valid config taken from the way each
# generator is actually invoked:
#   * mx_gemm / batched_contraction: the shipped ``default_*_config`` factories
#     in ``python/<op>_utils.py`` (identical mechanism to the quant families).
#   * gemm_universal: the generator's own ``--tile-config-json`` single-kernel
#     path, fed tile/trait dicts drawn from ``codegen/default_config.json``.
#   * grouped conv: the generator's own individual-kernel CLI (``--tile-m`` ...)
#     with the tile shape its ``main()`` documents as defaults.
#   * FMHA: the ``FmhaKernelConfig`` dataclass defaults in ``python/fmha_utils.py``
#     (its ``to_codegen_json()`` is what production uses to invoke the codegen).
#
# Determinism note for the directory-writing generators
# -----------------------------------------------------
# gemm_universal, grouped conv and FMHA write into an output *directory* using a
# generator-derived filename (not necessarily equal to any ``config_name`` we
# hold).  For FMHA in particular the emitted stem is canonicalized with a config
# hash.  So for these three we DISCOVER the single top-level kernel ``.hpp`` the
# generator emits (ignoring ``dispatcher_wrappers/``, ``register_all_*`` and
# ``include_all_*`` aggregation files) and record that emitted stem in the
# manifest -- a filename drift is therefore also caught.  With an explicit tile
# config the emitted bytes are arch-independent, so these cases pin a single
# arch each rather than a redundant arch cross-product.
# --------------------------------------------------------------------------- #

# Tile/trait dicts lifted from codegen/default_config.json (single-value lists
# select exactly one kernel on the generator's --tile-config-json path).
_GU_TILE_16 = {
    "tile_m": [128], "tile_n": [128], "tile_k": [32],
    "warp_m": [2], "warp_n": [2], "warp_k": [1],
    "warp_tile_m": [16], "warp_tile_n": [16], "warp_tile_k": [16],
}
_GU_TILE_32 = {
    "tile_m": [128], "tile_n": [128], "tile_k": [64],
    "warp_m": [2], "warp_n": [2], "warp_k": [1],
    "warp_tile_m": [32], "warp_tile_n": [32], "warp_tile_k": [16],
}
_GU_TILE_PERSIST = {
    "tile_m": [256], "tile_n": [256], "tile_k": [32],
    "warp_m": [2], "warp_n": [2], "warp_k": [1],
    "warp_tile_m": [16], "warp_tile_n": [16], "warp_tile_k": [16],
}


def _gu_trait(persistent=False):
    return {
        "pipeline": ["compv4"],
        "epilogue": ["cshuffle"],
        "scheduler": ["intrawave"],
        "pad_m": [False], "pad_n": [False], "pad_k": [False],
        "persistent": [persistent],
    }


def _gu_tile_config_json(tile, trait, multi_d=None):
    cfg = {"tile_config": tile, "trait_config": trait}
    if multi_d is not None:
        cfg["multi_d_config"] = multi_d
    return cfg


# The explicit, hand-picked tripwire matrix.  Each entry is fully self-describing
# so the manifest can freeze exactly how the generator was invoked.
def _build_tripwire_cases():
    cases = []

    # ---- gemm_universal: the most important tripwire (heaviest codegen_common
    # user).  A spread of dtype x layout x variant x trait that all flow through
    # codegen_common's TileConfig / TraitConfig / TypeMappings / name build. ----
    gu_script = str(_CODEGEN_DIR / "unified_gemm_codegen.py")
    gu_specs = [
        # (case_tag, datatype, layout, arch, variant, tile-config-json dict)
        ("fp16_rcr_standard", "fp16", "rcr", "gfx942", "standard",
         _gu_tile_config_json(_GU_TILE_16, _gu_trait())),
        ("bf16_rrr_standard", "bf16", "rrr", "gfx942", "standard",
         _gu_tile_config_json(_GU_TILE_16, _gu_trait())),
        ("fp8_rcr_standard_wtk32", "fp8", "rcr", "gfx950", "standard",
         _gu_tile_config_json(_GU_TILE_32, _gu_trait())),
        ("fp16_rcr_persistent", "fp16", "rcr", "gfx942", "standard",
         _gu_tile_config_json(_GU_TILE_PERSIST, _gu_trait(persistent=True))),
        ("fp16_multi_d_relu", "fp16", "rcr", "gfx942", "multi_d",
         _gu_tile_config_json(
             _GU_TILE_16, _gu_trait(),
             multi_d={"elementwise_ops": ["Relu"], "num_d_tensors": [1]},
         )),
    ]
    for tag, dtype, layout, arch, variant, tcfg in gu_specs:
        cases.append({
            "case_id": f"gemm_universal::{tag}",
            "generator": "gemm_universal",
            "op": "gemm_universal",
            "script": gu_script,
            "argv": [
                "--datatype", dtype,
                "--layout", layout,
                "--gpu-target", arch,
                "--variants", variant,
                "--no-parallel",
                "--tile-config-json", json.dumps(tcfg, sort_keys=True),
            ],
        })

    # ---- grouped conv: forward across dtype / ndim (bwd_* variants are arch-
    # filtered out for this tile shape, fp32 too; forward reliably yields one
    # kernel and still exercises the shared TileConfig / TraitConfig path). ----
    gc_script = str(_CODEGEN_DIR / "unified_grouped_conv_codegen.py")
    _GC_TILE = [
        "--tile-m", "128", "--tile-n", "128", "--tile-k", "64",
        "--warp-m", "2", "--warp-n", "2", "--warp-k", "1",
        "--warp-tile-m", "32", "--warp-tile-n", "32", "--warp-tile-k", "16",
        "--pipeline", "compv4", "--scheduler", "intrawave", "--epilogue", "cshuffle",
    ]
    gc_specs = [
        ("fwd_fp16_2d", "fp16", "forward", "2", "gfx942"),
        ("fwd_bf16_2d", "bf16", "forward", "2", "gfx942"),
        ("fwd_fp16_3d", "fp16", "forward", "3", "gfx942"),
    ]
    for tag, dtype, variant, ndim, arch in gc_specs:
        cases.append({
            "case_id": f"grouped_conv::{tag}",
            "generator": "grouped_conv",
            "op": "grouped_conv",
            "script": gc_script,
            # grouped conv's CLI names its output dir --output (-o), not
            # --output-dir like the other generators.
            "output_flag": "--output",
            "argv": [
                "-d", dtype, "-v", variant, "-n", ndim, "-a", arch, *_GC_TILE,
            ],
        })

    # ---- mx_gemm + batched_contraction: driven exactly like the quant families
    # (factory -> to_codegen_config -> --config-json -> <name>.hpp).  Independent
    # of codegen_common, but cheap bonus coverage of two more generators. ----
    for module_name, factories in (
        ("mx_gemm_utils", ("default_fp8_config", "default_fp4_config")),
        ("batched_contraction_utils", ("default_fp16_config",)),
    ):
        mod = import_module(module_name)
        script = str(getattr(mod, "_CODEGEN_SCRIPT"))
        for factory in factories:
            fn = getattr(mod, factory)
            for arch in _ARCHES:
                cfg = fn(gfx_arch=arch)
                cases.append({
                    "case_id": f"{module_name}::{factory}::{arch}",
                    "generator": "utils",
                    "op": module_name.replace("_utils", ""),
                    "script": script,
                    "argv": [
                        "--config-json",
                        json.dumps(cfg.to_codegen_config(), sort_keys=True),
                    ],
                    # For the utils path the emitted stem IS the config name.
                    "expect_config_name": cfg.name,
                })

    # ---- FMHA: the shared parallel_generate helper is the codegen_common tie.
    # Driven from FmhaKernelConfig defaults (production's to_codegen_json). ----
    fmha_script = str(_CODEGEN_DIR / "fmha" / "codegen.py")
    fmha_mod = import_module("fmha_utils")
    FmhaKernelConfig = getattr(fmha_mod, "FmhaKernelConfig")
    fmha_specs = [
        ("fwd_fp16_default", {}, "gfx950"),
        ("fwd_bf16_default", {"data_type": "bf16"}, "gfx950"),
    ]
    for tag, overrides, arch in fmha_specs:
        cfg = FmhaKernelConfig(**overrides)
        cases.append({
            "case_id": f"fmha::{tag}",
            "generator": "fmha",
            "op": "fmha",
            "script": fmha_script,
            "argv": [
                "--gpu-target", arch,
                "--no-parallel",
                "--config-json", cfg.to_codegen_json(),
            ],
        })

    cases.sort(key=lambda c: c["case_id"])
    return cases


_TRIPWIRE_CASES = _build_tripwire_cases()
_TRIPWIRE_IDS = [c["case_id"] for c in _TRIPWIRE_CASES]

# Top-level aggregation / wrapper files the directory-writing generators emit
# alongside the one real kernel header.  These are NOT the kernel under test.
_TRIPWIRE_HPP_IGNORE_PREFIXES = (
    "include_all_",
    "register_all_kernels",
    "register_all_grouped_conv_kernels",
    "dispatcher_wrapper_",
)


def _discover_kernel_hpp(out_dir: Path) -> Path:
    """Return the single top-level kernel ``.hpp`` a generator emitted.

    Ignores the ``dispatcher_wrappers/`` subdir and any top-level aggregation
    include / registration headers.  Exactly one kernel header must remain,
    otherwise the case is ambiguous and we fail loudly.
    """
    candidates = [
        p
        for p in out_dir.glob("*.hpp")
        if not any(p.name.startswith(pre) for pre in _TRIPWIRE_HPP_IGNORE_PREFIXES)
    ]
    if len(candidates) != 1:
        raise RuntimeError(
            f"expected exactly one top-level kernel .hpp in {out_dir}, "
            f"found {sorted(p.name for p in candidates)}"
        )
    return candidates[0]


def generate_tripwire_hpp(case: dict):
    """Run one tripwire generator; return ``(emitted_stem, hpp_bytes)``.

    All generators accept ``--output-dir <dir>`` plus the per-case ``argv``.
    ``utils`` cases write ``<config_name>.hpp`` directly; the directory-writing
    generators (gemm_universal / grouped_conv / fmha) have their single kernel
    header discovered.
    """
    with tempfile.TemporaryDirectory(prefix="ck_codegen_tripwire_") as td:
        output_flag = case.get("output_flag", "--output-dir")
        cmd = [sys.executable, case["script"], output_flag, td, *case["argv"]]
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=_CODEGEN_TIMEOUT
        )
        if result.returncode != 0:
            raise RuntimeError(
                f"tripwire codegen failed ({case['case_id']}):\n{result.stderr}"
            )
        out_dir = Path(td)
        if case["generator"] == "utils":
            hpp = out_dir / f"{case['expect_config_name']}.hpp"
            if not hpp.exists():
                raise RuntimeError(
                    f"tripwire codegen produced no {hpp.name} "
                    f"({case['case_id']})\nstderr:\n{result.stderr}"
                )
        else:
            hpp = _discover_kernel_hpp(out_dir)
        return hpp.stem, hpp.read_bytes()


def regenerate_tripwire_goldens() -> int:
    """(Re)write every tripwire golden ``.hpp`` and its manifest.  Returns count."""
    _TRIPWIRE_HPP_DIR.mkdir(parents=True, exist_ok=True)
    for stale in _TRIPWIRE_HPP_DIR.glob(f"*{_FIXTURE_EXT}"):
        stale.unlink()

    manifest = {
        "_comment": (
            "NON-QUANT TRIPWIRE golden byte-hashes.  Freezes the output of the "
            "generators that share codegen/codegen_common.py (gemm_universal, "
            "grouped_conv, fmha) plus mx_gemm/batched_contraction bonus "
            "coverage, so the upcoming quant-engine refactor cannot silently "
            "perturb shared codegen behavior.  Regenerate intentionally with: "
            "python3 tests/test_codegen_golden.py --update"
        ),
        "case_count": len(_TRIPWIRE_CASES),
        "cases": {},
    }

    written: dict = {}
    for case in _TRIPWIRE_CASES:
        stem, data = generate_tripwire_hpp(case)
        sha = hashlib.sha256(data).hexdigest()
        prev = written.get(stem)
        if prev is None:
            (_TRIPWIRE_HPP_DIR / f"{stem}{_FIXTURE_EXT}").write_bytes(data)
            written[stem] = sha
        elif prev != sha:
            raise RuntimeError(
                f"tripwire emitted-stem collision with differing bytes: {stem} "
                f"(case {case['case_id']})"
            )
        manifest["cases"][case["case_id"]] = {
            "generator": case["generator"],
            "op": case["op"],
            "emitted_hpp": stem,
            "sha256": sha,
            "argv": case["argv"],
        }

    _TRIPWIRE_MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return len(_TRIPWIRE_CASES)


def _load_tripwire_manifest() -> dict:
    if not _TRIPWIRE_MANIFEST.exists():
        raise FileNotFoundError(
            f"tripwire manifest missing: {_TRIPWIRE_MANIFEST}\n"
            "Generate it with: python3 tests/test_codegen_golden.py --update"
        )
    return json.loads(_TRIPWIRE_MANIFEST.read_text())


def test_tripwire_manifest_matches_matrix():
    """The frozen tripwire manifest must describe exactly the current matrix."""
    manifest = _load_tripwire_manifest()
    frozen = set(manifest["cases"])
    live = {c["case_id"] for c in _TRIPWIRE_CASES}
    missing = frozen - live
    extra = live - frozen
    assert not missing, (
        "tripwire goldens describe cases no longer in the matrix "
        f"(regenerate goldens): {sorted(missing)}"
    )
    assert not extra, (
        "tripwire matrix has cases with no golden (regenerate goldens): "
        f"{sorted(extra)}"
    )


@pytest.mark.parametrize("case", _TRIPWIRE_CASES, ids=_TRIPWIRE_IDS)
def test_tripwire_bytes_match_golden(case):
    """Regenerated non-quant .hpp bytes must be byte-identical to the golden.

    This is the actual tripwire: if the quant-engine refactor changes shared
    codegen_common behavior, one of these non-quant generators drifts here.
    """
    manifest = _load_tripwire_manifest()
    entry = manifest["cases"].get(case["case_id"])
    assert entry is not None, (
        f"no tripwire golden for {case['case_id']} -- regenerate goldens"
    )
    # The exact invocation must be stable (argv drift == config drift).
    assert entry["argv"] == case["argv"], (
        f"{case['case_id']}: generator argv drifted\n"
        f"  golden: {entry['argv']}\n"
        f"  now:    {case['argv']}"
    )

    stem = entry["emitted_hpp"]
    golden_hpp = _TRIPWIRE_HPP_DIR / f"{stem}{_FIXTURE_EXT}"
    assert golden_hpp.exists(), (
        f"tripwire golden fixture missing: {golden_hpp} -- regenerate goldens"
    )
    golden_bytes = golden_hpp.read_bytes()

    stored_sha = hashlib.sha256(golden_bytes).hexdigest()
    assert stored_sha == entry["sha256"], (
        f"{case['case_id']}: manifest sha256 disagrees with stored "
        f"{golden_hpp.name} (corrupt/edited fixture) -- regenerate goldens"
    )

    fresh_stem, fresh_bytes = generate_tripwire_hpp(case)
    assert fresh_stem == stem, (
        f"{case['case_id']}: emitted .hpp stem drifted\n"
        f"  golden: {stem}\n"
        f"  now:    {fresh_stem}"
    )
    if fresh_bytes != golden_bytes:
        diff = "\n".join(
            difflib.unified_diff(
                golden_bytes.decode("utf-8", "replace").splitlines(),
                fresh_bytes.decode("utf-8", "replace").splitlines(),
                fromfile=f"golden/tripwire/{stem}{_FIXTURE_EXT}",
                tofile=f"generated/tripwire/{stem}.hpp",
                lineterm="",
                n=3,
            )
        )
        snippet = "\n".join(diff.splitlines()[:60])
        pytest.fail(
            f"{case['case_id']}: generated bytes differ from tripwire golden "
            f"({stem}.hpp) -- a shared codegen_common change likely leaked\n"
            f"golden sha256={entry['sha256']}\n"
            f"fresh  sha256={hashlib.sha256(fresh_bytes).hexdigest()}\n"
            f"--- unified diff (first 60 lines) ---\n{snippet}"
        )


def test_tripwire_exercises_codegen_common():
    """Sanity-check the tripwire really flows through shared codegen paths.

    Not a byte assertion -- a guard that the goldens we froze actually contain
    the shared header preamble + kernel-name/namespace format that a
    codegen_common change would perturb.  If a config silently stopped emitting
    a real kernel, this catches it independent of the byte goldens.
    """
    manifest = _load_tripwire_manifest()
    # gemm_universal is the heaviest codegen_common consumer; require at least
    # one such golden and assert its shared markers are present.
    gu = [
        e for e in manifest["cases"].values()
        if e["generator"] == "gemm_universal"
    ]
    assert gu, "no gemm_universal tripwire case present"
    for entry in gu:
        text = (
            _TRIPWIRE_HPP_DIR / f"{entry['emitted_hpp']}{_FIXTURE_EXT}"
        ).read_text(encoding="utf-8")
        assert "SPDX-License-Identifier: MIT" in text
        assert "Auto-generated CK Tile GEMM kernel" in text
        # codegen_common-built kernel name -> namespace + KERNEL_NAME literal.
        assert f'namespace ns_{entry["emitted_hpp"]}' in text
        assert f'KERNEL_NAME = "{entry["emitted_hpp"]}"' in text


# --------------------------------------------------------------------------- #
# CLI: regenerate goldens
# --------------------------------------------------------------------------- #


def _main(argv) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Golden byte-file harness for the quant GEMM code generators."
    )
    parser.add_argument(
        "--update",
        action="store_true",
        help="Regenerate the golden .hpp fixtures and manifest.json from the "
        "current generators, then exit.",
    )
    args = parser.parse_args(argv)

    if args.update:
        n = regenerate_goldens()
        uniq = len(list(_HPP_DIR.glob(f"*{_FIXTURE_EXT}")))
        print(
            f"Regenerated quant goldens: {n} matrix cases, {uniq} unique "
            f"{_FIXTURE_EXT} files under {_HPP_DIR}"
        )
        tn = regenerate_tripwire_goldens()
        tuniq = len(list(_TRIPWIRE_HPP_DIR.glob(f"*{_FIXTURE_EXT}")))
        print(
            f"Regenerated tripwire goldens: {tn} cases, {tuniq} unique "
            f"{_FIXTURE_EXT} files under {_TRIPWIRE_HPP_DIR}"
        )
        return 0

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv[1:]))
