resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo
- name: pytestFolder
  value: '.azuredevops/tests/pytest'

parameters:
- name: pytestList
  type: object
  default:
    - HelloWorld

trigger: none
pr: none
schedules:
  - cron: "0 5 * 11-3 *"  # 11 PM CST (November - March)
    displayName: "Nightly Build (CST)"
    branches:
      include:
        - develop
    always: false

  - cron: "0 4 * 4-10 *"  # 11 PM CDT (April - October)
    displayName: "Nightly Build (CDT)"
    branches:
      include:
        - develop
    always: false

jobs:
- job: rccl
  timeoutInMinutes: 180
  pool: rocm-ci_rccl_pool
  workspace:
    clean: all
  steps:
  - task: DeleteFiles@1
    inputs:
      Contents: '**/*'
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml@pipelines_repo
    parameters:
      submoduleBehaviour: recursive
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml@pipelines_repo
    parameters:
      installEnabled: false
      printDiskSpace: false
      extraBuildFlags: >-
        -DCMAKE_BUILD_TYPE=Release
        -DBUILD_TESTS=ON
        -GNinja
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/test.yml@pipelines_repo
    parameters:
      componentName: rccl
      testDir: $(Build.SourcesDirectory)/build/test
      testExecutable: 'LD_LIBRARY_PATH=$(Build.SourcesDirectory)/build:${LD_LIBRARY_PATH} NCCL_DEBUG=INFO RCCL_ENABLE_SIGNALHANDLER=1 ./rccl-UnitTests'
      testParameters: '--gtest_output=xml:./test_output.xml --gtest_color=yes'
  - ${{ each pytestScript in parameters.pytestList }}:
    - task: Bash@3
      displayName: Test ${{ pytestScript }}
      continueOnError: true
      inputs:
        targetType: inline
        workingDirectory: $(Build.SourcesDirectory)/$(pytestFolder)
        script: pytest ${{ pytestScript }}.py
