variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop
- name: triggerDownstreamJobs
  type: boolean
  default: true

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
  paths:
    include:
    - projects/rocrand
    exclude:
    - projects/rocrand/.githooks
    - projects/rocrand/.github
    - projects/rocrand/.jenkins
    - projects/rocrand/docs
    - projects/rocrand/'.*.y*ml'
    - projects/rocrand/'*.md'
    - projects/rocrand/LICENSE.txt

pr:
  autoCancel: true
  branches:
    include:
    - develop
  paths:
    include:
    - projects/rocrand
    exclude:
    - projects/rocrand/.githooks
    - projects/rocrand/.github
    - projects/rocrand/.jenkins
    - projects/rocrand/docs
    - projects/rocrand/'.*.y*ml'
    - projects/rocrand/'*.md'
    - projects/rocrand/LICENSE.txt
  drafts: false

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/rocRAND.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: projects/rocrand
      triggerDownstreamJobs: ${{ parameters.triggerDownstreamJobs }}
