# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier:  MIT

if(NOT HIPBLASLT_ENABLE_YAML AND NOT DEFINED tensilelite_msgpack_target)
    # See: https://github.com/msgpack/msgpack-c/wiki/Q%26A#how-to-support-both-msgpack-c-c-version-5x-and-6x-
    # Prefer 6.x (msgpack-cxx)
    find_package(msgpack-cxx CONFIG)
    if(msgpack-cxx_FOUND)
        message(STATUS "Found msgpack-cxx (>=6.x)")
        set(tensilelite_msgpack_target "msgpack-cxx")
    else()
        # TODO: set minimum version required for *-cxx library
        find_package(msgpackc-cxx CONFIG REQUIRED NAMES msgpackc-cxx msgpack)
        set(tensilelite_msgpack_target "msgpackc-cxx")
        message(STATUS "Found msgpack (<=5.x)")
    endif()
endif()

if(ROCM_LIBS_SUPERBUILD)
    if(NOT TARGET roc::origami)
        message(FATAL_ERROR "The ROCm libraries superbuild must provide the roc::origami target before configuring hipBLASLt.")
    endif()
elseif(HIPBLASLT_ENABLE_THEROCK)
    find_package(origami CONFIG REQUIRED)
elseif(NOT TARGET roc::origami)
    if(NOT TENSILELITE_STANDALONE)
        set(tensilelite_bundled_origami_component origami-devel)
    endif()
    block(SCOPE_FOR VARIABLES)
        set(ORIGAMI_INSTALL_COMPONENT "${tensilelite_bundled_origami_component}")
        set(ORIGAMI_BUILD_SHARED_LIBS OFF)
        set(ORIGAMI_ENABLE_FETCH ON)
        set(ORIGAMI_BUILD_TESTING OFF)
        set(ORIGAMI_ENABLE_PYTHON OFF)
        set(BUILD_TESTING OFF)
        set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)
        add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/../../../../shared/origami" "${CMAKE_CURRENT_BINARY_DIR}/origami")
    endblock()
endif()
