#!/bin/bash -ex

# Copyright Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

# Run install codeql script if zip not found
if [[ ! -f /opt/codeql/codeql-cli.zip ]]; then
  ./codeql/install_codeql
fi

# Sets up a QLPack with dependencies for our check(s).
mkdir -p codeql/build
cd codeql/build
unzip -q /opt/codeql/codeql-cli.zip
mv codeql-codeql-cli-* codeql-cli
