# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data_objects

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# @brief GBDT (Gradient Boosted Decision Tree) model for the tree_data adapter.
#
# This is the model artifact format for UHD's default shipping path. The model
# is exported from LightGBM or XGBoost training and converted to this FlatBuffer
# format at build time.
#
# Prediction: sum leaf_values from all trees after traversal, then add base_score:
#     score = base_score + sum(leaf_values)
#
# learning_rate is metadata only and must NOT be applied here. LightGBM's
# dump_model() already folds it into leaf_values, so multiplying again double-counts
# it. A producer whose leaf values exclude the learning rate must scale them before
# serializing. See TreeDataAdapter::score, which implements this formula.
class GbdtModel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GbdtModel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGbdtModel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def GbdtModelBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x48\x47\x42\x4D", size_prefixed=size_prefixed)

    # GbdtModel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Array of decision trees in the ensemble.
    # GbdtModel
    def Trees(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from hipdnn_flatbuffers_sdk.data_objects.GbdtTree import GbdtTree
            obj = GbdtTree()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GbdtModel
    def TreesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GbdtModel
    def TreesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Number of input features expected.
    # GbdtModel
    def NumFeatures(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # SHA-256 hash of the features_signature this model was trained on.
    # Must match UHD.features_hash at load time.
    # GbdtModel
    def FeaturesHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Base prediction (bias term).
    # GbdtModel
    def BaseScore(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Learning rate (shrinkage factor). Usually 1.0 for inference.
    # GbdtModel
    def LearningRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 1.0

    # Optional model metadata.
    # GbdtModel
    def Framework(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GbdtModel
    def TrainingDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # GbdtModel
    def NumTrainingSamples(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # GbdtModel
    def TrainingObjective(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Model provenance (RFC 0019 §9.2, §13).
    # GPU architectures the model was trained on (e.g., ["gfx942", "gfx1100"]).
    # Runtime compares $device.arch against this list; warns or degrades to
    # static_order if the device arch is unseen during training.
    # GbdtModel
    def TrainingArches(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # GbdtModel
    def TrainingArchesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GbdtModel
    def TrainingArchesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # Semantic version of the model (e.g., "1.0.0").
    # GbdtModel
    def ModelVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GbdtModelStart(builder):
    builder.StartObject(11)

def Start(builder):
    GbdtModelStart(builder)

def GbdtModelAddTrees(builder, trees):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trees), 0)

def AddTrees(builder, trees):
    GbdtModelAddTrees(builder, trees)

def GbdtModelStartTreesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTreesVector(builder, numElems):
    return GbdtModelStartTreesVector(builder, numElems)

def GbdtModelAddNumFeatures(builder, numFeatures):
    builder.PrependInt32Slot(1, numFeatures, 0)

def AddNumFeatures(builder, numFeatures):
    GbdtModelAddNumFeatures(builder, numFeatures)

def GbdtModelAddFeaturesHash(builder, featuresHash):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(featuresHash), 0)

def AddFeaturesHash(builder, featuresHash):
    GbdtModelAddFeaturesHash(builder, featuresHash)

def GbdtModelAddBaseScore(builder, baseScore):
    builder.PrependFloat64Slot(3, baseScore, 0.0)

def AddBaseScore(builder, baseScore):
    GbdtModelAddBaseScore(builder, baseScore)

def GbdtModelAddLearningRate(builder, learningRate):
    builder.PrependFloat64Slot(4, learningRate, 1.0)

def AddLearningRate(builder, learningRate):
    GbdtModelAddLearningRate(builder, learningRate)

def GbdtModelAddFramework(builder, framework):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(framework), 0)

def AddFramework(builder, framework):
    GbdtModelAddFramework(builder, framework)

def GbdtModelAddTrainingDate(builder, trainingDate):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(trainingDate), 0)

def AddTrainingDate(builder, trainingDate):
    GbdtModelAddTrainingDate(builder, trainingDate)

def GbdtModelAddNumTrainingSamples(builder, numTrainingSamples):
    builder.PrependInt64Slot(7, numTrainingSamples, 0)

def AddNumTrainingSamples(builder, numTrainingSamples):
    GbdtModelAddNumTrainingSamples(builder, numTrainingSamples)

def GbdtModelAddTrainingObjective(builder, trainingObjective):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(trainingObjective), 0)

def AddTrainingObjective(builder, trainingObjective):
    GbdtModelAddTrainingObjective(builder, trainingObjective)

def GbdtModelAddTrainingArches(builder, trainingArches):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(trainingArches), 0)

def AddTrainingArches(builder, trainingArches):
    GbdtModelAddTrainingArches(builder, trainingArches)

def GbdtModelStartTrainingArchesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTrainingArchesVector(builder, numElems):
    return GbdtModelStartTrainingArchesVector(builder, numElems)

def GbdtModelAddModelVersion(builder, modelVersion):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(modelVersion), 0)

def AddModelVersion(builder, modelVersion):
    GbdtModelAddModelVersion(builder, modelVersion)

def GbdtModelEnd(builder):
    return builder.EndObject()

def End(builder):
    return GbdtModelEnd(builder)

import hipdnn_flatbuffers_sdk.data_objects.GbdtTree
try:
    from typing import List
except:
    pass

class GbdtModelT(object):

    # GbdtModelT
    def __init__(
        self,
        trees = None,
        numFeatures = 0,
        featuresHash = None,
        baseScore = 0.0,
        learningRate = 1.0,
        framework = None,
        trainingDate = None,
        numTrainingSamples = 0,
        trainingObjective = None,
        trainingArches = None,
        modelVersion = None,
    ):
        self.trees = trees  # type: Optional[List[hipdnn_flatbuffers_sdk.data_objects.GbdtTree.GbdtTreeT]]
        self.numFeatures = numFeatures  # type: int
        self.featuresHash = featuresHash  # type: Optional[str]
        self.baseScore = baseScore  # type: float
        self.learningRate = learningRate  # type: float
        self.framework = framework  # type: Optional[str]
        self.trainingDate = trainingDate  # type: Optional[str]
        self.numTrainingSamples = numTrainingSamples  # type: int
        self.trainingObjective = trainingObjective  # type: Optional[str]
        self.trainingArches = trainingArches  # type: Optional[List[Optional[str]]]
        self.modelVersion = modelVersion  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        gbdtModel = GbdtModel()
        gbdtModel.Init(buf, pos)
        return cls.InitFromObj(gbdtModel)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, gbdtModel):
        x = GbdtModelT()
        x._UnPack(gbdtModel)
        return x

    # GbdtModelT
    def _UnPack(self, gbdtModel):
        if gbdtModel is None:
            return
        if not gbdtModel.TreesIsNone():
            self.trees = []
            for i in range(gbdtModel.TreesLength()):
                if gbdtModel.Trees(i) is None:
                    self.trees.append(None)
                else:
                    gbdtTree_ = hipdnn_flatbuffers_sdk.data_objects.GbdtTree.GbdtTreeT.InitFromObj(gbdtModel.Trees(i))
                    self.trees.append(gbdtTree_)
        self.numFeatures = gbdtModel.NumFeatures()
        self.featuresHash = gbdtModel.FeaturesHash()
        self.baseScore = gbdtModel.BaseScore()
        self.learningRate = gbdtModel.LearningRate()
        self.framework = gbdtModel.Framework()
        self.trainingDate = gbdtModel.TrainingDate()
        self.numTrainingSamples = gbdtModel.NumTrainingSamples()
        self.trainingObjective = gbdtModel.TrainingObjective()
        if not gbdtModel.TrainingArchesIsNone():
            self.trainingArches = []
            for i in range(gbdtModel.TrainingArchesLength()):
                self.trainingArches.append(gbdtModel.TrainingArches(i))
        self.modelVersion = gbdtModel.ModelVersion()

    # GbdtModelT
    def Pack(self, builder):
        if self.trees is not None:
            treeslist = []
            for i in range(len(self.trees)):
                treeslist.append(self.trees[i].Pack(builder))
            GbdtModelStartTreesVector(builder, len(self.trees))
            for i in reversed(range(len(self.trees))):
                builder.PrependUOffsetTRelative(treeslist[i])
            trees = builder.EndVector()
        if self.featuresHash is not None:
            featuresHash = builder.CreateString(self.featuresHash)
        if self.framework is not None:
            framework = builder.CreateString(self.framework)
        if self.trainingDate is not None:
            trainingDate = builder.CreateString(self.trainingDate)
        if self.trainingObjective is not None:
            trainingObjective = builder.CreateString(self.trainingObjective)
        if self.trainingArches is not None:
            trainingArcheslist = []
            for i in range(len(self.trainingArches)):
                trainingArcheslist.append(builder.CreateString(self.trainingArches[i]))
            GbdtModelStartTrainingArchesVector(builder, len(self.trainingArches))
            for i in reversed(range(len(self.trainingArches))):
                builder.PrependUOffsetTRelative(trainingArcheslist[i])
            trainingArches = builder.EndVector()
        if self.modelVersion is not None:
            modelVersion = builder.CreateString(self.modelVersion)
        GbdtModelStart(builder)
        if self.trees is not None:
            GbdtModelAddTrees(builder, trees)
        GbdtModelAddNumFeatures(builder, self.numFeatures)
        if self.featuresHash is not None:
            GbdtModelAddFeaturesHash(builder, featuresHash)
        GbdtModelAddBaseScore(builder, self.baseScore)
        GbdtModelAddLearningRate(builder, self.learningRate)
        if self.framework is not None:
            GbdtModelAddFramework(builder, framework)
        if self.trainingDate is not None:
            GbdtModelAddTrainingDate(builder, trainingDate)
        GbdtModelAddNumTrainingSamples(builder, self.numTrainingSamples)
        if self.trainingObjective is not None:
            GbdtModelAddTrainingObjective(builder, trainingObjective)
        if self.trainingArches is not None:
            GbdtModelAddTrainingArches(builder, trainingArches)
        if self.modelVersion is not None:
            GbdtModelAddModelVersion(builder, modelVersion)
        gbdtModel = GbdtModelEnd(builder)
        return gbdtModel
