# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data_objects

# @brief Adapter type for UHD model evaluation.
#
# Determines how the heuristic computes scores for kernel candidates.
class UhdAdapter(object):
    # Rank by static fields (priority, id). No model artifact needed.
    STATIC_ORDER = 0
    # GBDT tree walker over FlatBuffer tree_data artifact. Default shipping path.
    TREE_DATA = 1
    # Lookup table indexed by problem bucket hash.
    TABLE = 2
    # ONNX Runtime inference. Requires onnxruntime dependency.
    ONNX = 3
    # Custom compiled scorer loaded via dlopen. Engine supplies .so artifact.
    CUSTOM_LIBRARY = 4
    # Scorer compiled into the engine, resolved by symbol from the engine's
    # registered scorers. No model artifact. RFC 0019 §7.1: the escape hatch
    # for heuristics no model expresses, and the baseline TREE_DATA overhead
    # is measured against.
    NATIVE = 5
