# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data_objects

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

# @brief Key-value pair for derived feature expressions (RFC 0019 §6.4).
#
# Each entry is a named JsonLogic expression that can reference $device.*,
# $kernel.*, $q.*, and earlier $derived.* entries. Evaluated in order to
# form the $derived.* namespace.
class UhdDerivedEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UhdDerivedEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUhdDerivedEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def UhdDerivedEntryBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x48\x55\x48\x44", size_prefixed=size_prefixed)

    # UhdDerivedEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Feature name (e.g., "num_tiles_m", "arithmetic_intensity").
    # UhdDerivedEntry
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # JsonLogic expression as a JSON string.
    # Example: "{\"ceil_div\": [\"$q.seqlen_q\", \"$kernel.tile_m0\"]}"
    # UhdDerivedEntry
    def Expression(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def UhdDerivedEntryStart(builder):
    builder.StartObject(2)

def Start(builder):
    UhdDerivedEntryStart(builder)

def UhdDerivedEntryAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    UhdDerivedEntryAddName(builder, name)

def UhdDerivedEntryAddExpression(builder, expression):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(expression), 0)

def AddExpression(builder, expression):
    UhdDerivedEntryAddExpression(builder, expression)

def UhdDerivedEntryEnd(builder):
    return builder.EndObject()

def End(builder):
    return UhdDerivedEntryEnd(builder)


class UhdDerivedEntryT(object):

    # UhdDerivedEntryT
    def __init__(
        self,
        name = None,
        expression = None,
    ):
        self.name = name  # type: Optional[str]
        self.expression = expression  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        uhdDerivedEntry = UhdDerivedEntry()
        uhdDerivedEntry.Init(buf, pos)
        return cls.InitFromObj(uhdDerivedEntry)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, uhdDerivedEntry):
        x = UhdDerivedEntryT()
        x._UnPack(uhdDerivedEntry)
        return x

    # UhdDerivedEntryT
    def _UnPack(self, uhdDerivedEntry):
        if uhdDerivedEntry is None:
            return
        self.name = uhdDerivedEntry.Name()
        self.expression = uhdDerivedEntry.Expression()

    # UhdDerivedEntryT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.expression is not None:
            expression = builder.CreateString(self.expression)
        UhdDerivedEntryStart(builder)
        if self.name is not None:
            UhdDerivedEntryAddName(builder, name)
        if self.expression is not None:
            UhdDerivedEntryAddExpression(builder, expression)
        uhdDerivedEntry = UhdDerivedEntryEnd(builder)
        return uhdDerivedEntry
