// Copyright Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT
//
// Native C++ port of the writer-free pass-pipeline coverage from
// Tensile/Tests/unit/test_logicalSchedulerCpp.py and the overlapping emit
// snapshots from test_SubtileBasedSchedulerRef.py.
//
// The deleted Python tests compared the C++ pass pipeline against the Python
// LogicalScheduler pass-by-pass (byte-identical print_* output) and pinned
// emit-order snapshots. With the writer-free pipeline now C++-only
// (logical_scheduler_passes.hpp), these tests lock the pass-print output of
// each pass (place_LRs through emit) against committed golden snapshots across
// the same representative BF16 / fp8 / fp4 gfx950 configs and PGR=0/1/2.
//
// The golden snapshots in scheduler_pass_goldens.inc were generated by
// gen_scheduler_goldens.cpp and cross-checked against the Python
// LogicalScheduler (which emits byte-identical print_* output). They pin:
//   * pass pipeline ordering (place_LRs / place_GRs ordering),
//   * slot placement (which subIterK slot each LR/GR lands in),
//   * vmcnt / wait ordering (wait_gr counts + sync placement in print_emit),
//   * the assign_vgpr_tiles scalar metadata (via print_vgpr).
//
// NOT covered here (Python writer integration in
// test_SubtileBasedLogicalScheduler.py): populate_instructions, VGPR-pool
// allocation, and rocisa main/tail-loop emission.

#include <gtest/gtest.h>

#include <map>
#include <string>

#include "scheduler_pass_configs.hpp"
#include "tensile_writer/logical_scheduler_passes.hpp"

#include "scheduler_pass_goldens.inc"

using tw::subtile::lsched::Pass;
using tw::subtile::lsched::passes::LogicalScheduler;

// ---------------------------------------------------------------------------
// Pass-print snapshots: every pass's print output matches the golden.
// ---------------------------------------------------------------------------
TEST(LogicalSchedulerPasses, PrintSnapshotsMatchGolden) {
  for (const auto& spec : tw_test::passConfigs()) {
    for (const auto& method : tw_test::printMethods()) {
      std::string key = spec.name + "/" + method;
      auto it = kPassGoldens.find(key);
      ASSERT_NE(it, kPassGoldens.end()) << "missing golden for " << key;
      LogicalScheduler sched(tw_test::makePassConfig(spec));
      std::string got = tw_test::runPrint(sched, method);
      EXPECT_EQ(got, it->second) << "snapshot mismatch for " << key;
    }
  }
}

// ---------------------------------------------------------------------------
// assign_vgpr_tiles scalar metadata is self-consistent with print_vgpr.
// ---------------------------------------------------------------------------
TEST(LogicalSchedulerPasses, VgprMetadataConsistent) {
  for (const auto& spec : tw_test::passConfigs()) {
    SCOPED_TRACE(spec.name);
    LogicalScheduler sched(tw_test::makePassConfig(spec));
    sched.assign_vgpr_tiles();
    EXPECT_EQ(sched.needs_unrolling, sched.unroll_factor > 1);
    EXPECT_GE(sched.unroll_factor, 1);
    // tile_peaks has an entry for every active tensor.
    for (const auto& t : sched.tensors)
      EXPECT_TRUE(sched.tile_peaks.count(t)) << "missing tile_peak for " << t;
  }
}

// ---------------------------------------------------------------------------
// build() runs the full pipeline and yields the same emit output as emit().
// ---------------------------------------------------------------------------
TEST(LogicalSchedulerPasses, BuildMatchesEmit) {
  for (const auto& spec : tw_test::passConfigs()) {
    SCOPED_TRACE(spec.name);
    LogicalScheduler emitSched(tw_test::makePassConfig(spec));
    emitSched.emit();
    LogicalScheduler buildSched(tw_test::makePassConfig(spec));
    buildSched.build();
    EXPECT_EQ(buildSched.print_emit(), emitSched.print_emit());
  }
}

// ---------------------------------------------------------------------------
// Passes are idempotent: rerunning a terminal pass does not change its output.
// ---------------------------------------------------------------------------
TEST(LogicalSchedulerPasses, PassPipelineDeterministic) {
  for (const auto& spec : tw_test::passConfigs()) {
    SCOPED_TRACE(spec.name);
    LogicalScheduler a(tw_test::makePassConfig(spec));
    LogicalScheduler b(tw_test::makePassConfig(spec));
    a.emit();
    b.emit();
    EXPECT_EQ(a.print_emit(), b.print_emit());
  }
}
