// GENERATED by gen_gpu_table.py from ~/AutoResearchAllLGBM/GPUInfo/*.json.
// Do not edit by hand. Regenerate when GPUInfo or model_meta.json change.

#include <miopen/conv/heuristics/lgbm_gpu_features.hpp>

#include <array>
#include <limits>
#include <string_view>

namespace miopen {
namespace ai {
namespace lgbm {

// Order matches model_meta.json rank.categorical_vocab.spec_id, so the
// array index doubles as the spec_id categorical code.
const std::array<GpuFeatures, kNumSpecIds> kGpuTable = {{
    /* gfx1150                  */ {16.0, 32.0, 2.0, 32.0, 64.0, 64.0, 32.0, 2048.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 2900.0, std::numeric_limits<double>::quiet_NaN(), 1.0, 128.0, 536870912.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 0.0, 0.0, 0, 0, 0, 0, 0, 0},
    /* gfx1151                  */ {32.0, 32.0, 2.0, 32.0, 64.0, 64.0, 32.0, 2048.0, 32768.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 2700.0, std::numeric_limits<double>::quiet_NaN(), 2.0, 128.0, 536870912.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 0.0, 0.0, 1, 0, 0, 0, 0, 1},
    /* gfx1201                  */ {64.0, 32.0, 2.0, 32.0, 64.0, 64.0, 32.0, 8192.0, 65536.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 2400.0, 1.0, 4.0, 256.0, 17095983104.0, std::numeric_limits<double>::quiet_NaN(), 48.7, 195.0, 195.0, 779.0, std::numeric_limits<double>::quiet_NaN(), 779.0, 5.0, 7.0, 2, 4, 4, 1, 1, 2},
    /* gfx90a-mi210x            */ {104.0, 64.0, 4.0, 32.0, 64.0, 64.0, 16.0, 8192.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 1700.0, 1.0, 8.0, 128.0, 68702699520.0, 47.9, 47.9, 383.0, 383.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 383.0, 9.0, 6.0, 3, 1, 1, 2, 2, 3},
    /* gfx942-mi300a            */ {228.0, 64.0, 4.0, 32.0, 64.0, 64.0, 32.0, 4096.0, 262144.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 2100.0, 8.0, 24.0, 128.0, 67408539648.0, 81.7, 163.4, 1307.0, 1307.0, 2614.9, std::numeric_limits<double>::quiet_NaN(), 2614.9, 11.0, 8.0, 4, 2, 2, 2, 2, 4},
    /* gfx942-mi300x            */ {304.0, 64.0, 4.0, 32.0, 64.0, 64.0, 32.0, 4096.0, 262144.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 2100.0, 8.0, 32.0, 128.0, 206141652992.0, 81.7, 163.4, 1307.0, 1307.0, 2614.9, std::numeric_limits<double>::quiet_NaN(), 2614.9, 11.0, 8.0, 4, 2, 2, 2, 2, 5},
    /* gfx942-mi325x            */ {304.0, 64.0, 4.0, 32.0, 64.0, 64.0, 32.0, 4096.0, 262144.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 2100.0, 8.0, 32.0, 128.0, 274861129728.0, 81.7, 163.4, 1307.0, 1307.0, 2614.9, std::numeric_limits<double>::quiet_NaN(), 2614.9, 11.0, 8.0, 4, 2, 2, 2, 2, 6},
    /* gfx950-mi350x            */ {256.0, 64.0, 4.0, 32.0, 160.0, 160.0, 32.0, 4096.0, 262144.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 2200.0, 8.0, 32.0, 128.0, 309220868096.0, 78.6, 157.3, 2300.0, 2300.0, 4600.0, 9200.0, 4600.0, 11.0, 10.0, 5, 3, 3, 2, 2, 7},
    /* gfx950-mi355x            */ {256.0, 64.0, 4.0, 32.0, 160.0, 160.0, 32.0, 4096.0, 262144.0, std::numeric_limits<double>::quiet_NaN(), std::numeric_limits<double>::quiet_NaN(), 2400.0, 8.0, 32.0, 128.0, 309220868096.0, 78.6, 157.3, 2300.0, 2300.0, 4600.0, 9200.0, 4600.0, 11.0, 10.0, 5, 3, 3, 2, 2, 8}
}};

const std::array<std::string_view, kNumSpecIds> kSpecIdNames = {{
    "gfx1150",
    "gfx1151",
    "gfx1201",
    "gfx90a-mi210x",
    "gfx942-mi300a",
    "gfx942-mi300x",
    "gfx942-mi325x",
    "gfx950-mi350x",
    "gfx950-mi355x"
}};

int ResolveSpecId(std::string_view gfx_id, std::size_t cu_count, std::size_t vram_bytes)
{
    if(gfx_id == "gfx1150")
    {
        return 0; // gfx1150
    }
    if(gfx_id == "gfx1151")
    {
        return 1; // gfx1151
    }
    if(gfx_id == "gfx1201")
    {
        return 2; // gfx1201
    }
    if(gfx_id == "gfx90a")
    {
        return 3; // gfx90a-mi210x
    }
    if(gfx_id == "gfx942")
    {
        if(cu_count == 228)
        {
            return 4; // gfx942-mi300a
        }
        if(cu_count == 304)
        {
            if(vram_bytes < 240501391360ULL) return 5; // gfx942-mi300x
            return 6; // gfx942-mi325x
        }
        return -1;
    }
    if(gfx_id == "gfx950")
    {
        if(cu_count == 256)
        {
            return 8; // gfx950-mi355x (preferred among ['gfx950-mi350x', 'gfx950-mi355x'])
        }
        return -1;
    }
    return -1;
}

} // namespace lgbm
} // namespace ai
} // namespace miopen
