// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier:  MIT

#ifdef HIPDNN_ENABLE_KERNEL_INGESTOR

#include <algorithm>
#include <cstdint>
#include <map>
#include <set>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include <hipdnn_data_sdk/utilities/PlatformUtils.hpp>
#include <hipdnn_data_sdk/utilities/VersionUtils.hpp>
#include <hipdnn_plugin_sdk/BehaviorNote.h>
#include <hipdnn_plugin_sdk/ingestor/Descriptors.hpp>
#include <hipdnn_plugin_sdk/ingestor/MatchContext.hpp>
#include <hipdnn_plugin_sdk/ingestor/NativeRegistry.hpp>

#include "engines/kernel_ingestor_engine/KernelIngestorEngine.hpp"

/**
 * @file TestGfx950AttentionDensePacks.cpp
 * @brief A census of what hipkernel:Gfx950AttentionDense ACTUALLY LOADS, read through
 *        hip_kernel_provider::kernel_ingestor_engine::discoverDescriptorSets() --
 *        which runs the provider's real typed registration before validating and
 *        loading, so a pack whose native symbols do not register drops out here
 *        rather than at first dispatch on a device.
 *
 * The expectations below are rendered from the generator's FINALIZED emitted-bundle
 * inventory: the names, counts, runtime source kind, SDK version and architecture
 * coverage of the documents this run actually wrote, after metadata resolution, after
 * the resolved-knob check and after engine-wide de-duplication. They are not the
 * authored config, which over-counts every bundle whose generation expressions
 * overlap, and whose pack file stems are not the pack names the loader reports.
 *
 * The caller supplies HIPDNN_TEST_EXPECTED_ARCH explicitly, never from a detected
 * device or the descriptors under test (a bundle cannot be its own expectation).
 * A census entry is registered by one hkp_register_census_tests(TARGET ... PACK_NAME
 * ... SUITES TestGfx950AttentionDensePacks) call, in src/tests/CMakeLists.txt beside
 * hkp_verify_embedded_sources(). PACK_NAME selects the pack target whose own OUT_ROOT
 * and recorded arch list the entries address; CMake then registers
 * hip-kernel-provider-hkp-census-<arch>-TestGfx950AttentionDensePacks as a fresh native
 * process for each arch in that list, supplying HIPDNN_DESCRIPTOR_DIR for that pack
 * target's own shard and HIPDNN_TEST_CENSUS_SUITE=TestGfx950AttentionDensePacks.
 * The native guard requires an existing explicit root and every registered case to
 * execute and pass without skipping in every iteration; at least one iteration must
 * complete. Merely listing or selecting some cases is not proof.
 *
 * Eligibility follows the shard count, not the authored dialect: an entry hands the
 * binary exactly one directory, so a suite qualifies only where every case reads one
 * pack target's shard. An embedded_source bundle is censused on the same terms as a
 * packaged one. A suite reading two shards is censused nowhere and states its
 * inventory through its ordinary host run, supplying HIPDNN_DESCRIPTOR_DIR and an
 * explicit expected arch itself.
 *
 * This proves registration, loading and inventory. It proves nothing about dispatch.
 *
 * Generated by IngestorGenerator -- complete, not a stub.
 */
namespace
{

using namespace hip_kernel_provider::kernel_ingestor_engine;
namespace ingestor = hipdnn_plugin_sdk::ingestor;

/// One architecture's row of the emitted inventory.
struct ExpectedInventory
{
    std::set<std::string> packNames;
    std::set<std::string> kernelNames;
};

/// Wildcard key of the emitted inventory: descriptors that name no architecture at
/// all ship for every device, so they cannot be filed under a concrete id.
constexpr const char* ARCH_WILDCARD = "*";

/// The emitted inventory, keyed by architecture.
const std::map<std::string, ExpectedInventory>& expectedByArch()
{
    static const std::map<std::string, ExpectedInventory> s_expected = {
        {"gfx950",
         ExpectedInventory{
             {
                 "hipkernel:gfx950_attention_dense",
             },
             {
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh128_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v46",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh128_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v41",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh28_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v26",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh28_nkh4_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v21",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh32_nkh32_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v64",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh32_nkh32_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v59",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh32_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v6",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh32_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v1",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh40_nkh40_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v74",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh40_nkh40_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v69",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh40_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v16",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh40_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v11",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh64_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v54",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh64_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v36",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh64_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v31",
                 "gfx950_attention_dense_ba1_sq1024_sk1024_nqh64_nkh8_hs64_ca_dtbf16_sw128_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v83",
                 "gfx950_attention_dense_ba1_sq1024_sk131072_nqh16_nkh2_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v127",
                 "gfx950_attention_dense_ba1_sq1024_sk131072_nqh16_nkh2_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v101",
                 "gfx950_attention_dense_ba1_sq1024_sk131072_nqh32_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v120",
                 "gfx950_attention_dense_ba1_sq1024_sk131072_nqh32_nkh4_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v94",
                 "gfx950_attention_dense_ba1_sq1024_sk131072_nqh64_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v141",
                 "gfx950_attention_dense_ba1_sq1024_sk131072_nqh64_nkh8_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v115",
                 "gfx950_attention_dense_ba1_sq1024_sk131072_nqh8_nkh1_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v134",
                 "gfx950_attention_dense_ba1_sq1024_sk131072_nqh8_nkh1_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v108",
                 "gfx950_attention_dense_ba1_sq1024_sk65536_nqh16_nkh2_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v126",
                 "gfx950_attention_dense_ba1_sq1024_sk65536_nqh16_nkh2_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v100",
                 "gfx950_attention_dense_ba1_sq1024_sk65536_nqh32_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v119",
                 "gfx950_attention_dense_ba1_sq1024_sk65536_nqh32_nkh4_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v93",
                 "gfx950_attention_dense_ba1_sq1024_sk65536_nqh64_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v140",
                 "gfx950_attention_dense_ba1_sq1024_sk65536_nqh64_nkh8_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v114",
                 "gfx950_attention_dense_ba1_sq1024_sk65536_nqh8_nkh1_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v133",
                 "gfx950_attention_dense_ba1_sq1024_sk65536_nqh8_nkh1_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v107",
                 "gfx950_attention_dense_ba1_sq2016_sk2016_nqh64_nkh8_hs64_ca_dtbf16_sw0_ra_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v155",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh128_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v47",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh128_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v42",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh16_nkh2_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v128",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh16_nkh2_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v102",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh28_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v27",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh28_nkh4_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v22",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh32_nkh32_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v65",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh32_nkh32_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v60",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh32_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v121",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh32_nkh4_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v95",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh32_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v7",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh32_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v2",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh32_nkh8_hs64_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v156",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh40_nkh40_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v75",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh40_nkh40_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v70",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh40_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v17",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh40_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v12",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh64_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v55",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh64_nkh4_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v50",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh64_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v37",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh64_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v32",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh64_nkh8_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v78",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh64_nkh8_hs64_ca_dtbf16_sw128_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v84",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh8_nkh1_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v135",
                 "gfx950_attention_dense_ba1_sq2048_sk2048_nqh8_nkh1_hs64_ca_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v109",
                 "gfx950_attention_dense_ba1_sq2048_sk62208_nqh9_nkh9_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v86",
                 "gfx950_attention_dense_ba1_sq32768_sk32768_nqh16_nkh2_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v130",
                 "gfx950_attention_dense_ba1_sq32768_sk32768_nqh16_nkh2_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v104",
                 "gfx950_attention_dense_ba1_sq32768_sk32768_nqh32_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v123",
                 "gfx950_attention_dense_ba1_sq32768_sk32768_nqh32_nkh4_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v97",
                 "gfx950_attention_dense_ba1_sq32768_sk32768_nqh32_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v154",
                 "gfx950_attention_dense_ba1_sq32768_sk32768_nqh64_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v142",
                 "gfx950_attention_dense_ba1_sq32768_sk32768_nqh64_nkh8_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v116",
                 "gfx950_attention_dense_ba1_sq32768_sk32768_nqh8_nkh1_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v137",
                 "gfx950_attention_dense_ba1_sq32768_sk32768_nqh8_nkh1_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v111",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh128_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v48",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh128_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v43",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh28_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v28",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh28_nkh4_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v23",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh32_nkh32_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v66",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh32_nkh32_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v61",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh32_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v8",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh32_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v3",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh40_nkh40_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v76",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh40_nkh40_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v71",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh40_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v18",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh40_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v13",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh64_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v56",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh64_nkh4_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v51",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh64_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v38",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh64_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v33",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh64_nkh8_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v79",
                 "gfx950_attention_dense_ba1_sq4096_sk4096_nqh64_nkh8_hs64_ca_dtbf16_sw128_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v85",
                 "gfx950_attention_dense_ba1_sq4096_sk62208_nqh9_nkh9_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v87",
                 "gfx950_attention_dense_ba1_sq512_sk131072_nqh16_nkh2_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v125",
                 "gfx950_attention_dense_ba1_sq512_sk131072_nqh16_nkh2_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v99",
                 "gfx950_attention_dense_ba1_sq512_sk131072_nqh32_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v118",
                 "gfx950_attention_dense_ba1_sq512_sk131072_nqh32_nkh4_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v92",
                 "gfx950_attention_dense_ba1_sq512_sk131072_nqh64_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v139",
                 "gfx950_attention_dense_ba1_sq512_sk131072_nqh64_nkh8_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v113",
                 "gfx950_attention_dense_ba1_sq512_sk131072_nqh8_nkh1_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v132",
                 "gfx950_attention_dense_ba1_sq512_sk131072_nqh8_nkh1_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v106",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh128_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v45",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh128_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v40",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh28_nkh4_hs128_ca_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v25",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh28_nkh4_hs128_ca_dtfp16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v20",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh32_nkh32_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v63",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh32_nkh32_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v58",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh32_nkh8_hs128_ca_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v5",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh32_nkh8_hs128_ca_dtfp16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v0",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh40_nkh40_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v73",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh40_nkh40_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v68",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh40_nkh8_hs128_ca_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v15",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh40_nkh8_hs128_ca_dtfp16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v10",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh64_nkh4_hs128_ca_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v53",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh64_nkh8_hs128_ca_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v35",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh64_nkh8_hs128_ca_dtfp16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v30",
                 "gfx950_attention_dense_ba1_sq512_sk512_nqh64_nkh8_hs64_ca_dtbf16_sw128_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v82",
                 "gfx950_attention_dense_ba1_sq512_sk65536_nqh16_nkh2_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v124",
                 "gfx950_attention_dense_ba1_sq512_sk65536_nqh16_nkh2_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v98",
                 "gfx950_attention_dense_ba1_sq512_sk65536_nqh32_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v117",
                 "gfx950_attention_dense_ba1_sq512_sk65536_nqh32_nkh4_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v91",
                 "gfx950_attention_dense_ba1_sq512_sk65536_nqh64_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v138",
                 "gfx950_attention_dense_ba1_sq512_sk65536_nqh64_nkh8_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v112",
                 "gfx950_attention_dense_ba1_sq512_sk65536_nqh8_nkh1_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v131",
                 "gfx950_attention_dense_ba1_sq512_sk65536_nqh8_nkh1_hs64_ca_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v105",
                 "gfx950_attention_dense_ba1_sq62208_sk62208_nqh9_nkh9_hs128_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v90",
                 "gfx950_attention_dense_ba1_sq8192_sk62208_nqh9_nkh9_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v88",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh128_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v49",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh128_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v44",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh16_nkh2_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v129",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh16_nkh2_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v103",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh28_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v29",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh28_nkh4_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v24",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh32_nkh32_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v67",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh32_nkh32_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v62",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh32_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v122",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh32_nkh4_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v96",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh32_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v9",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh32_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v4",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh40_nkh40_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v77",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh40_nkh40_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v72",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh40_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v19",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh40_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v14",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh64_nkh4_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v57",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh64_nkh4_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v52",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh64_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v39",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh64_nkh8_hs128_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v34",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh64_nkh8_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v80",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh8_nkh1_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v136",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh8_nkh1_hs64_ca_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v110",
                 "gfx950_attention_dense_ba1_sq8192_sk8192_nqh9_nkh9_hs128_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v89",
                 "gfx950_attention_dense_ba2_sq1024_sk1024_nqh64_nkh8_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v81",
                 "gfx950_attention_dense_ba2_sq16384_sk16384_nqh128_nkh128_hs64_ca_dtbf16_sw0_"
                 "bm256_bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v143",
                 "gfx950_attention_dense_ba2_sq16384_sk16384_nqh64_nkh8_hs128_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_wld_v148",
                 "gfx950_attention_dense_ba2_sq16384_sk16384_nqh64_nkh8_hs128_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v149",
                 "gfx950_attention_dense_ba2_sq2048_sk2048_nqh128_nkh128_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v144",
                 "gfx950_attention_dense_ba2_sq2048_sk2048_nqh64_nkh8_hs128_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v150",
                 "gfx950_attention_dense_ba2_sq32768_sk32768_nqh128_nkh128_hs64_ca_dtbf16_sw0_"
                 "bm256_bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v145",
                 "gfx950_attention_dense_ba2_sq32768_sk32768_nqh64_nkh8_hs128_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v151",
                 "gfx950_attention_dense_ba2_sq4096_sk4096_nqh128_nkh128_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v146",
                 "gfx950_attention_dense_ba2_sq4096_sk4096_nqh64_nkh8_hs128_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v152",
                 "gfx950_attention_dense_ba2_sq64_sk64_nqh8_nkh2_hs128_ca_dtbf16_sw0_ra_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v159",
                 "gfx950_attention_dense_ba2_sq64_sk64_nqh8_nkh2_hs128_ca_dtfp16_sw0_ra_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v162",
                 "gfx950_attention_dense_ba2_sq64_sk64_nqh8_nkh8_hs128_ca_dtbf16_sw0_ra_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v157",
                 "gfx950_attention_dense_ba2_sq64_sk64_nqh8_nkh8_hs128_ca_dtfp16_sw0_ra_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v160",
                 "gfx950_attention_dense_ba2_sq64_sk64_nqh8_nkh8_hs64_ca_dtbf16_sw0_ra_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v158",
                 "gfx950_attention_dense_ba2_sq64_sk64_nqh8_nkh8_hs64_ca_dtfp16_sw0_ra_bm256_bn64_"
                 "wpe2_lkgp8_np256_pdauto_lr_bs0_nkb0_lvrp32_v161",
                 "gfx950_attention_dense_ba2_sq8192_sk8192_nqh128_nkh128_hs64_ca_dtbf16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v147",
                 "gfx950_attention_dense_ba2_sq8192_sk8192_nqh64_nkh8_hs128_dtbf16_sw0_bm256_bn64_"
                 "wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v153",
                 "gfx950_attention_dense_ba4_sq2048_sk2048_nqh64_nkh8_hs64_ca_dtfp16_sw0_bm256_"
                 "bn64_wpe2_lkgp8_pe_np256_pdauto_lr_bs0_nkb0_lvrp32_v163",
             },
         }},
    };
    return s_expected;
}

/// The runtime source kind every kernel of this bundle must declare once it reaches a
/// loader. A packaged bundle is lowered to a kpack archive before the runtime reads
/// it, so the authored builder kind is not what arrives.
constexpr ingestor::KernelSourceKind EXPECTED_SOURCE_KIND = ingestor::KernelSourceKind::KPACK;

/// A pack or kernel with no architecture of its own inherits/wildcards; one that names
/// architectures must name the requested one, or this shard is the wrong shard.
bool coversArch(const std::vector<std::string>& declared, const std::string& arch)
{
    return declared.empty() || std::find(declared.begin(), declared.end(), arch) != declared.end();
}

class TestGfx950AttentionDensePacks : public ::testing::Test
{
protected:
    void SetUp() override
    {
        _arch = hipdnn_data_sdk::utilities::getEnv("HIPDNN_TEST_EXPECTED_ARCH");
        ASSERT_FALSE(_arch.empty())
            << "HIPDNN_TEST_EXPECTED_ARCH is unset, so this census has no expectation to "
               "check against. The architecture is supplied explicitly by the caller; it "
               "is never detected from a device and never taken from the descriptors "
               "being censused.";

        const auto& table = expectedByArch();
        auto row = table.find(_arch);
        if(row == table.end())
        {
            row = table.find(ARCH_WILDCARD);
        }
        ASSERT_NE(row, table.end())
            << "this bundle emitted no descriptors for architecture '" << _arch
            << "' and no architecture-independent ones either, so there is no expected "
               "identity to check. Either the wrong architecture was requested or the "
               "generation that produced this bundle did not cover it.";
        _expected = &row->second;

        const auto& sets = discoverDescriptorSets();
        const auto match = std::find_if(sets.begin(), sets.end(), [](const auto& set) {
            return set.engine.name == "hipkernel:Gfx950AttentionDense";
        });
        ASSERT_NE(match, sets.end())
            << "descriptor set 'hipkernel:Gfx950AttentionDense' did not load. Either its "
               "descriptors were never installed under the tree this binary reads, or "
               "its pack failed to register its native symbols and every descriptor "
               "naming one of them was dropped.";
        _set = &*match;
    }

    std::string _arch;
    const ExpectedInventory* _expected = nullptr;
    const ingestor::DescriptorSet* _set = nullptr;
};

TEST_F(TestGfx950AttentionDensePacks, LoadsExactlyTheEmittedPacks)
{
    std::set<std::string> loaded;
    for(const auto& pack : _set->packs)
    {
        loaded.insert(pack.name);
    }
    // Set equality, not a count: a missing pack and an extra one cancel in a count.
    EXPECT_EQ(loaded, _expected->packNames);
}

TEST_F(TestGfx950AttentionDensePacks, LoadsExactlyTheEmittedKernels)
{
    std::set<std::string> loaded;
    for(const auto& pack : _set->packs)
    {
        for(const auto& kernel : pack.kernels)
        {
            loaded.insert(kernel.name);
        }
    }
    EXPECT_EQ(loaded, _expected->kernelNames);
}

TEST_F(TestGfx950AttentionDensePacks, EveryLoadedDescriptorCoversTheRequestedArch)
{
    for(const auto& pack : _set->packs)
    {
        EXPECT_TRUE(coversArch(pack.arch, _arch))
            << "pack '" << pack.name << "' does not cover '" << _arch
            << "', so this is not that architecture's shard";
        for(const auto& kernel : pack.kernels)
        {
            EXPECT_TRUE(coversArch(kernel.arch, _arch))
                << "kernel '" << kernel.name << "' does not cover '" << _arch << "'";
        }
    }
}

TEST_F(TestGfx950AttentionDensePacks, EveryKernelDeclaresTheEmittedRuntimeSourceKind)
{
    for(const auto& pack : _set->packs)
    {
        for(const auto& kernel : pack.kernels)
        {
            EXPECT_EQ(kernel.source.kind, EXPECTED_SOURCE_KIND)
                << "kernel '" << kernel.name << "' reached the loader as a different "
                << "source kind than this bundle ships";
        }
    }
}

TEST_F(TestGfx950AttentionDensePacks, DeclaresTheConfiguredSdkVersion)
{
    EXPECT_EQ(_set->engine.sdkVersion, hipdnn_data_sdk::utilities::Version{std::string("1.0.0")});
}

TEST_F(TestGfx950AttentionDensePacks, ExposesTheConfiguredKnobs)
{
    ASSERT_EQ(_set->engine.knobs.size(), 8U);
    EXPECT_NE(std::find(_set->engine.knobs.begin(), _set->engine.knobs.end(), "head_size"),
              _set->engine.knobs.end());
    EXPECT_NE(std::find(_set->engine.knobs.begin(), _set->engine.knobs.end(), "num_query_heads"),
              _set->engine.knobs.end());
    EXPECT_NE(std::find(_set->engine.knobs.begin(), _set->engine.knobs.end(), "num_kv_heads"),
              _set->engine.knobs.end());
    EXPECT_NE(std::find(_set->engine.knobs.begin(), _set->engine.knobs.end(), "causal"),
              _set->engine.knobs.end());
    EXPECT_NE(std::find(_set->engine.knobs.begin(), _set->engine.knobs.end(), "block_n"),
              _set->engine.knobs.end());
    EXPECT_NE(std::find(_set->engine.knobs.begin(), _set->engine.knobs.end(), "waves_per_eu"),
              _set->engine.knobs.end());
    EXPECT_NE(std::find(_set->engine.knobs.begin(), _set->engine.knobs.end(), "persistent"),
              _set->engine.knobs.end());
    EXPECT_NE(std::find(_set->engine.knobs.begin(), _set->engine.knobs.end(), "num_persistent"),
              _set->engine.knobs.end());
}

/// The engine ships a ranking model, so its score symbol must be REGISTERED, not merely
/// named: a descriptor naming an unregistered score symbol is dropped by the loader,
/// and the engine then ranks on priority as if no model had ever been authored.
TEST_F(TestGfx950AttentionDensePacks, RanksThroughItsRegisteredScoreSymbol)
{
    ASSERT_TRUE(_set->heuristic.has_value());
    EXPECT_EQ(_set->heuristic->payload, "hipkernel.gfx950_attention_dense.score");
    EXPECT_TRUE(ingestor::ScoreRegistry::isRegistered("hipkernel.gfx950_attention_dense.score"));
}

/// UMD policy check, this engine's shape: a SINGLE-pack engine has nothing to
/// discriminate between, so it carries no graph-scoped criterion at all -- the
/// engine's own graph_match both admits the node type and validates shape in one
/// pass. Mirrors TestConvFwdPack.cpp's HasAGraphMatchAndOneKernelMatcher.
TEST_F(TestGfx950AttentionDensePacks, CarriesNoGraphScopedMatcher)
{
    EXPECT_FALSE(_set->engine.graphMatchNativeSymbol.empty());
    const auto graphScoped
        = std::count_if(_set->matchers.begin(), _set->matchers.end(), [](const auto& matcher) {
              return matcher.scope == ingestor::MatchScope::GRAPH;
          });
    EXPECT_EQ(graphScoped, 0);
}

TEST_F(TestGfx950AttentionDensePacks, CarriesExactlyOneSharedKernelScopedMatcher)
{
    const auto kernelScoped
        = std::count_if(_set->matchers.begin(), _set->matchers.end(), [](const auto& matcher) {
              return matcher.scope == ingestor::MatchScope::KERNEL;
          });
    EXPECT_EQ(kernelScoped, 1);
}

} // namespace

#endif // HIPDNN_ENABLE_KERNEL_INGESTOR
