// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier:  MIT

#ifdef HIPDNN_ENABLE_KERNEL_INGESTOR

#include <algorithm>
#include <cstdint>
#include <map>
#include <set>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include <hipdnn_data_sdk/utilities/PlatformUtils.hpp>
#include <hipdnn_data_sdk/utilities/VersionUtils.hpp>
#include <hipdnn_plugin_sdk/BehaviorNote.h>
#include <hipdnn_plugin_sdk/ingestor/Descriptors.hpp>
#include <hipdnn_plugin_sdk/ingestor/MatchContext.hpp>
#include <hipdnn_plugin_sdk/ingestor/NativeRegistry.hpp>

#include "engines/kernel_ingestor_engine/KernelIngestorEngine.hpp"

/**
 * @file TestConvBiasPacks.cpp
 * @brief A census of what Hackweek:ConvBias ACTUALLY LOADS, read through
 *        hip_kernel_provider::kernel_ingestor_engine::discoverDescriptorSets() --
 *        which runs the provider's real typed registration before validating and
 *        loading, so a pack whose native symbols do not register drops out here
 *        rather than at first dispatch on a device.
 *
 * The expectations below are rendered from the generator's FINALIZED emitted-bundle
 * inventory: the names, counts, runtime source kind, SDK version and architecture
 * coverage of the documents this run actually wrote, after metadata resolution, after
 * the resolved-knob check and after engine-wide de-duplication. They are not the
 * authored config, which over-counts every bundle whose generation expressions
 * overlap, and whose pack file stems are not the pack names the loader reports.
 *
 * The architecture is supplied explicitly -- by HIPDNN_TEST_EXPECTED_ARCH where a
 * caller sets one, otherwise by CONFIGURED_ARCH below, which is rendered from the same
 * generation config as the inventory. Never from a detected device and never from the
 * descriptors under test (a bundle cannot be its own expectation).
 *
 * This direct-load engine uses ordinary host tests, not the packaged-shard census, so
 * nothing sets that variable for it and the suite must run standalone. Its descriptor
 * root likewise resolves from the binary's own HIPDNN_TEST_DESCRIPTOR_DIR staging
 * (tests/main.cpp) unless HIPDNN_DESCRIPTOR_DIR names another tree.
 *
 * This proves registration, loading and inventory. It proves nothing about dispatch.
 *
 * Generated by IngestorGenerator -- complete, not a stub.
 */
namespace
{

using namespace hip_kernel_provider::kernel_ingestor_engine;
namespace ingestor = hipdnn_plugin_sdk::ingestor;

/// One architecture's row of the emitted inventory.
struct ExpectedInventory
{
    std::set<std::string> packNames;
    std::set<std::string> kernelNames;
};

/// Wildcard key of the emitted inventory: descriptors that name no architecture at
/// all ship for every device, so they cannot be filed under a concrete id.
constexpr const char* ARCH_WILDCARD = "*";

/// The architecture this bundle was generated for, from the same generator config that
/// rendered the inventory below -- not detected from a device and not read back out of
/// the descriptors under test, so a bundle still cannot be its own expectation.
///
/// This engine is direct-load, so it is absent from HKP_CENSUS_TEST_SUITES and no
/// packaging census target sets HIPDNN_TEST_EXPECTED_ARCH for it
/// (HkpPackaging.cmake sets it only for packaged shards). Requiring the variable here
/// made the whole suite fail in SetUp for anyone running the binary directly, which is
/// the only way this suite is ever run. The variable still wins where a caller sets it,
/// so a packaged shard can point this census at the shard it built.
constexpr const char* CONFIGURED_ARCH = "gfx1151";

/// The emitted inventory, keyed by architecture.
const std::map<std::string, ExpectedInventory>& expectedByArch()
{
    static const std::map<std::string, ExpectedInventory> s_expected = {
        {"gfx1151",
         ExpectedInventory{
             {
                 "Hackweek:conv_bias",
             },
             {
                 "conv_bias.f32_block1024",
                 "conv_bias.f32_block256",
                 "conv_bias.f32_block64",
             },
         }},
    };
    return s_expected;
}

/// The runtime source kind every kernel of this bundle must declare once it reaches a
/// loader. A packaged bundle is lowered to a kpack archive before the runtime reads
/// it, so the authored builder kind is not what arrives.
constexpr ingestor::KernelSourceKind EXPECTED_SOURCE_KIND
    = ingestor::KernelSourceKind::EMBEDDED_SOURCE;

/// A pack or kernel with no architecture of its own inherits/wildcards; one that names
/// architectures must name the requested one, or this shard is the wrong shard.
bool coversArch(const std::vector<std::string>& declared, const std::string& arch)
{
    return declared.empty() || std::find(declared.begin(), declared.end(), arch) != declared.end();
}

class TestConvBiasPacks : public ::testing::Test
{
protected:
    void SetUp() override
    {
        _arch = hipdnn_data_sdk::utilities::getEnv("HIPDNN_TEST_EXPECTED_ARCH");
        if(_arch.empty())
        {
            _arch = CONFIGURED_ARCH;
        }
        ASSERT_FALSE(_arch.empty())
            << "neither HIPDNN_TEST_EXPECTED_ARCH nor the configured architecture named "
               "one, so this census has no expectation to check against. The architecture "
               "is supplied explicitly by the caller or by the generation config; it is "
               "never detected from a device and never taken from the descriptors being "
               "censused.";

        const auto& table = expectedByArch();
        auto row = table.find(_arch);
        if(row == table.end())
        {
            row = table.find(ARCH_WILDCARD);
        }
        ASSERT_NE(row, table.end())
            << "this bundle emitted no descriptors for architecture '" << _arch
            << "' and no architecture-independent ones either, so there is no expected "
               "identity to check. Either the wrong architecture was requested or the "
               "generation that produced this bundle did not cover it.";
        _expected = &row->second;

        const auto& sets = discoverDescriptorSets();
        const auto match = std::find_if(sets.begin(), sets.end(), [](const auto& set) {
            return set.engine.name == "Hackweek:ConvBias";
        });
        ASSERT_NE(match, sets.end())
            << "descriptor set 'Hackweek:ConvBias' did not load. Either its "
               "descriptors were never installed under the tree this binary reads, or "
               "its pack failed to register its native symbols and every descriptor "
               "naming one of them was dropped.";
        _set = &*match;
    }

    std::string _arch;
    const ExpectedInventory* _expected = nullptr;
    const ingestor::DescriptorSet* _set = nullptr;
};

TEST_F(TestConvBiasPacks, LoadsExactlyTheEmittedPacks)
{
    std::set<std::string> loaded;
    for(const auto& pack : _set->packs)
    {
        loaded.insert(pack.name);
    }
    // Set equality, not a count: a missing pack and an extra one cancel in a count.
    EXPECT_EQ(loaded, _expected->packNames);
}

TEST_F(TestConvBiasPacks, LoadsExactlyTheEmittedKernels)
{
    std::set<std::string> loaded;
    for(const auto& pack : _set->packs)
    {
        for(const auto& kernel : pack.kernels)
        {
            loaded.insert(kernel.name);
        }
    }
    EXPECT_EQ(loaded, _expected->kernelNames);
}

TEST_F(TestConvBiasPacks, EveryLoadedDescriptorCoversTheRequestedArch)
{
    for(const auto& pack : _set->packs)
    {
        EXPECT_TRUE(coversArch(pack.arch, _arch))
            << "pack '" << pack.name << "' does not cover '" << _arch
            << "', so this is not that architecture's shard";
        for(const auto& kernel : pack.kernels)
        {
            EXPECT_TRUE(coversArch(kernel.arch, _arch))
                << "kernel '" << kernel.name << "' does not cover '" << _arch << "'";
        }
    }
}

TEST_F(TestConvBiasPacks, EveryKernelDeclaresTheEmittedRuntimeSourceKind)
{
    for(const auto& pack : _set->packs)
    {
        for(const auto& kernel : pack.kernels)
        {
            EXPECT_EQ(kernel.source.kind, EXPECTED_SOURCE_KIND)
                << "kernel '" << kernel.name << "' reached the loader as a different "
                << "source kind than this bundle ships";
        }
    }
}

TEST_F(TestConvBiasPacks, DeclaresTheConfiguredSdkVersion)
{
    EXPECT_EQ(_set->engine.sdkVersion,
              hipdnn_data_sdk::utilities::Version{std::string("1.0.0")});
}

TEST_F(TestConvBiasPacks, ExposesTheConfiguredKnobs)
{
    ASSERT_EQ(_set->engine.knobs.size(), 1U);
    EXPECT_NE(std::find(_set->engine.knobs.begin(), _set->engine.knobs.end(), "block_size"),
              _set->engine.knobs.end());
}

/// The engine ships a ranking model, so its score symbol must be REGISTERED, not merely
/// named: a descriptor naming an unregistered score symbol is dropped by the loader,
/// and the engine then ranks on priority as if no model had ever been authored.
TEST_F(TestConvBiasPacks, RanksThroughItsRegisteredScoreSymbol)
{
    ASSERT_TRUE(_set->heuristic.has_value());
    EXPECT_EQ(_set->heuristic->payload, "Hackweek.conv_bias.score");
    EXPECT_TRUE(ingestor::ScoreRegistry::isRegistered("Hackweek.conv_bias.score"));
}

/// UMD policy check, this engine's shape: a SINGLE-pack engine has nothing to
/// discriminate between, so it carries no graph-scoped criterion at all -- the
/// engine's own graph_match both admits the node type and validates shape in one
/// pass. Mirrors TestConvFwdPack.cpp's HasAGraphMatchAndOneKernelMatcher.
TEST_F(TestConvBiasPacks, CarriesNoGraphScopedMatcher)
{
    EXPECT_FALSE(_set->engine.graphMatchNativeSymbol.empty());
    const auto graphScoped
        = std::count_if(_set->matchers.begin(), _set->matchers.end(), [](const auto& matcher) {
              return matcher.scope == ingestor::MatchScope::GRAPH;
          });
    EXPECT_EQ(graphScoped, 0);
}

TEST_F(TestConvBiasPacks, CarriesExactlyOneSharedKernelScopedMatcher)
{
    const auto kernelScoped
        = std::count_if(_set->matchers.begin(), _set->matchers.end(), [](const auto& matcher) {
              return matcher.scope == ingestor::MatchScope::KERNEL;
          });
    EXPECT_EQ(kernelScoped, 1);
}

TEST_F(TestConvBiasPacks, DeclaresItsConfiguredBehaviorNotes)
{
    const auto& notes = _set->engine.behaviorNotes;
    EXPECT_NE(std::find(notes.begin(),
                        notes.end(),
                        static_cast<int32_t>(HIPDNN_BEHAVIOR_NOTE_RUNTIME_COMPILATION)),
              notes.end());
}

} // namespace

#endif // HIPDNN_ENABLE_KERNEL_INGESTOR
