// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier:  MIT

#ifdef HIPDNN_ENABLE_KERNEL_INGESTOR

#include <algorithm>
#include <cstdint>
#include <map>
#include <set>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include <hipdnn_data_sdk/utilities/PlatformUtils.hpp>
#include <hipdnn_data_sdk/utilities/VersionUtils.hpp>
#include <hipdnn_plugin_sdk/BehaviorNote.h>
#include <hipdnn_plugin_sdk/ingestor/Descriptors.hpp>
#include <hipdnn_plugin_sdk/ingestor/MatchContext.hpp>
#include <hipdnn_plugin_sdk/ingestor/NativeRegistry.hpp>

#include "engines/kernel_ingestor_engine/KernelIngestorEngine.hpp"

/**
 * @file TestConvPointwiseRtcPacks.cpp
 * @brief A census of what hipkernel:ConvPointwiseRtc ACTUALLY LOADS, read through
 *        hip_kernel_provider::kernel_ingestor_engine::discoverDescriptorSets() --
 *        which runs the provider's real typed registration before validating and
 *        loading, so a pack whose native symbols do not register drops out here
 *        rather than at first dispatch on a device.
 *
 * The expectations below are rendered from the generator's FINALIZED emitted-bundle
 * inventory: the names, counts, runtime source kind, SDK version and architecture
 * coverage of the documents this run actually wrote, after metadata resolution, after
 * the resolved-knob check and after engine-wide de-duplication. They are not the
 * authored config, which over-counts every bundle whose generation expressions
 * overlap, and whose pack file stems are not the pack names the loader reports.
 *
 * The caller supplies HIPDNN_TEST_EXPECTED_ARCH explicitly, never from a detected
 * device or the descriptors under test (a bundle cannot be its own expectation).
 * This direct-load engine uses ordinary host tests, not the packaged-shard census.
 * Supply its descriptor root in HIPDNN_DESCRIPTOR_DIR when running this suite.
 *
 * This proves registration, loading and inventory. It proves nothing about dispatch.
 *
 * Generated by IngestorGenerator -- complete, not a stub.
 */
namespace
{

using namespace hip_kernel_provider::kernel_ingestor_engine;
namespace ingestor = hipdnn_plugin_sdk::ingestor;

/// One architecture's row of the emitted inventory.
struct ExpectedInventory
{
    std::set<std::string> packNames;
    std::set<std::string> kernelNames;
};

/// Wildcard key of the emitted inventory: descriptors that name no architecture at
/// all ship for every device, so they cannot be filed under a concrete id.
constexpr const char* ARCH_WILDCARD = "*";

/// The emitted inventory, keyed by architecture.
const std::map<std::string, ExpectedInventory>& expectedByArch()
{
    static const std::map<std::string, ExpectedInventory> s_expected = {
        {"gfx90a",
         ExpectedInventory{
             {
                 "hipkernel:conv_pointwise_rtc",
             },
             {
                 "conv_pointwise_rtc.f32_abs_block1024",
                 "conv_pointwise_rtc.f32_abs_block256",
                 "conv_pointwise_rtc.f32_abs_block64",
                 "conv_pointwise_rtc.f32_neg_block1024",
                 "conv_pointwise_rtc.f32_neg_block256",
                 "conv_pointwise_rtc.f32_neg_block64",
                 "conv_pointwise_rtc.f32_relu_fwd_block1024",
                 "conv_pointwise_rtc.f32_relu_fwd_block256",
                 "conv_pointwise_rtc.f32_relu_fwd_block64",
             },
         }},
    };
    return s_expected;
}

/// The runtime source kind every kernel of this bundle must declare once it reaches a
/// loader. A packaged bundle is lowered to a kpack archive before the runtime reads
/// it, so the authored builder kind is not what arrives.
constexpr ingestor::KernelSourceKind EXPECTED_SOURCE_KIND
    = ingestor::KernelSourceKind::EMBEDDED_SOURCE;

/// A pack or kernel with no architecture of its own inherits/wildcards; one that names
/// architectures must name the requested one, or this shard is the wrong shard.
bool coversArch(const std::vector<std::string>& declared, const std::string& arch)
{
    return declared.empty() || std::find(declared.begin(), declared.end(), arch) != declared.end();
}

/// The architecture to censuse against when the caller named none.
///
/// The generated fixture below requires HIPDNN_TEST_EXPECTED_ARCH, which is how the
/// PACKAGED census is driven: CMake registers one test per configured packaging arch and
/// passes it in (HkpPackaging.cmake). This engine is DIRECT-LOAD and is deliberately not
/// in HKP_CENSUS_TEST_SUITES, so nothing sets that variable for it and the ordinary
/// `hip_kernel_provider_tests --gtest_filter=TestConvPointwiseRtcPacks.*` invocation --
/// the one a developer and this pack's own gate actually run -- would fail on a missing
/// input rather than on a wrong inventory.
///
/// This is NOT the artifact defining its own expectation, which is the rule the explicit
/// variable exists to protect. `expectedByArch()` is generation-time data rendered from
/// the config, not read back from the installed descriptors; falling back to its single
/// key says "this bundle was generated for exactly one architecture, so censuse that one",
/// and the descriptors under test still have to match it. When the table carries more than
/// one row there is a real choice to make and the caller must make it, so the assertion
/// below still fires.
std::string soleEmittedArch()
{
    const auto& table = expectedByArch();
    return table.size() == 1 ? table.begin()->first : std::string{};
}

class TestConvPointwiseRtcPacks : public ::testing::Test
{
protected:
    void SetUp() override
    {
        _arch = hipdnn_data_sdk::utilities::getEnv("HIPDNN_TEST_EXPECTED_ARCH");
        if(_arch.empty())
        {
            _arch = soleEmittedArch();
        }
        ASSERT_FALSE(_arch.empty())
            << "HIPDNN_TEST_EXPECTED_ARCH is unset and this bundle's generated inventory "
               "covers more than one architecture, so this census has no expectation to "
               "check against. The architecture is supplied explicitly by the caller; it "
               "is never detected from a device and never taken from the descriptors "
               "being censused.";

        const auto& table = expectedByArch();
        auto row = table.find(_arch);
        if(row == table.end())
        {
            row = table.find(ARCH_WILDCARD);
        }
        ASSERT_NE(row, table.end())
            << "this bundle emitted no descriptors for architecture '" << _arch
            << "' and no architecture-independent ones either, so there is no expected "
               "identity to check. Either the wrong architecture was requested or the "
               "generation that produced this bundle did not cover it.";
        _expected = &row->second;

        const auto& sets = discoverDescriptorSets();
        const auto match = std::find_if(sets.begin(), sets.end(), [](const auto& set) {
            return set.engine.name == "hipkernel:ConvPointwiseRtc";
        });
        ASSERT_NE(match, sets.end())
            << "descriptor set 'hipkernel:ConvPointwiseRtc' did not load. Either its "
               "descriptors were never installed under the tree this binary reads, or "
               "its pack failed to register its native symbols and every descriptor "
               "naming one of them was dropped.";
        _set = &*match;
    }

    std::string _arch;
    const ExpectedInventory* _expected = nullptr;
    const ingestor::DescriptorSet* _set = nullptr;
};

TEST_F(TestConvPointwiseRtcPacks, LoadsExactlyTheEmittedPacks)
{
    std::set<std::string> loaded;
    for(const auto& pack : _set->packs)
    {
        loaded.insert(pack.name);
    }
    // Set equality, not a count: a missing pack and an extra one cancel in a count.
    EXPECT_EQ(loaded, _expected->packNames);
}

TEST_F(TestConvPointwiseRtcPacks, LoadsExactlyTheEmittedKernels)
{
    std::set<std::string> loaded;
    for(const auto& pack : _set->packs)
    {
        for(const auto& kernel : pack.kernels)
        {
            loaded.insert(kernel.name);
        }
    }
    EXPECT_EQ(loaded, _expected->kernelNames);
}

TEST_F(TestConvPointwiseRtcPacks, EveryLoadedDescriptorCoversTheRequestedArch)
{
    for(const auto& pack : _set->packs)
    {
        EXPECT_TRUE(coversArch(pack.arch, _arch))
            << "pack '" << pack.name << "' does not cover '" << _arch
            << "', so this is not that architecture's shard";
        for(const auto& kernel : pack.kernels)
        {
            EXPECT_TRUE(coversArch(kernel.arch, _arch))
                << "kernel '" << kernel.name << "' does not cover '" << _arch << "'";
        }
    }
}

TEST_F(TestConvPointwiseRtcPacks, EveryKernelDeclaresTheEmittedRuntimeSourceKind)
{
    for(const auto& pack : _set->packs)
    {
        for(const auto& kernel : pack.kernels)
        {
            EXPECT_EQ(kernel.source.kind, EXPECTED_SOURCE_KIND)
                << "kernel '" << kernel.name << "' reached the loader as a different "
                << "source kind than this bundle ships";
        }
    }
}

TEST_F(TestConvPointwiseRtcPacks, DeclaresTheConfiguredSdkVersion)
{
    EXPECT_EQ(_set->engine.sdkVersion,
              hipdnn_data_sdk::utilities::Version{std::string("1.0.0")});
}

TEST_F(TestConvPointwiseRtcPacks, ExposesTheConfiguredKnobs)
{
    ASSERT_EQ(_set->engine.knobs.size(), 1U);
    EXPECT_NE(std::find(_set->engine.knobs.begin(), _set->engine.knobs.end(), "block_size"),
              _set->engine.knobs.end());
}

/// The engine ships a ranking model, so its score symbol must be REGISTERED, not merely
/// named: a descriptor naming an unregistered score symbol is dropped by the loader,
/// and the engine then ranks on priority as if no model had ever been authored.
TEST_F(TestConvPointwiseRtcPacks, RanksThroughItsRegisteredScoreSymbol)
{
    ASSERT_TRUE(_set->heuristic.has_value());
    EXPECT_EQ(_set->heuristic->payload, "hipkernel.conv_pointwise_rtc.score");
    EXPECT_TRUE(ingestor::ScoreRegistry::isRegistered("hipkernel.conv_pointwise_rtc.score"));
}

/// UMD policy check, this engine's shape: a SINGLE-pack engine has nothing to
/// discriminate between, so it carries no graph-scoped criterion at all -- the
/// engine's own graph_match both admits the node type and validates shape in one
/// pass. Mirrors TestConvFwdPack.cpp's HasAGraphMatchAndOneKernelMatcher.
TEST_F(TestConvPointwiseRtcPacks, CarriesNoGraphScopedMatcher)
{
    EXPECT_FALSE(_set->engine.graphMatchNativeSymbol.empty());
    const auto graphScoped
        = std::count_if(_set->matchers.begin(), _set->matchers.end(), [](const auto& matcher) {
              return matcher.scope == ingestor::MatchScope::GRAPH;
          });
    EXPECT_EQ(graphScoped, 0);
}

TEST_F(TestConvPointwiseRtcPacks, CarriesExactlyOneSharedKernelScopedMatcher)
{
    const auto kernelScoped
        = std::count_if(_set->matchers.begin(), _set->matchers.end(), [](const auto& matcher) {
              return matcher.scope == ingestor::MatchScope::KERNEL;
          });
    EXPECT_EQ(kernelScoped, 1);
}

TEST_F(TestConvPointwiseRtcPacks, DeclaresItsConfiguredBehaviorNotes)
{
    const auto& notes = _set->engine.behaviorNotes;
    EXPECT_NE(std::find(notes.begin(),
                        notes.end(),
                        static_cast<int32_t>(HIPDNN_BEHAVIOR_NOTE_RUNTIME_COMPILATION)),
              notes.end());
}

} // namespace

#endif // HIPDNN_ENABLE_KERNEL_INGESTOR
