// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier:  MIT

#ifdef HIPDNN_ENABLE_KERNEL_INGESTOR

#include <algorithm>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include <hipdnn_plugin_sdk/ingestor/MatchContext.hpp>

#include "engines/kernel_ingestor_engine/KernelIngestorEngine.hpp"

/**
 * @file TestGfx950AttentionTiledPacks.cpp
 * @brief The engine's descriptor data: shape, cross-references, and engine id --
 *        a pack-shape census reading the INSTALLED descriptors via
 *        hip_kernel_provider::kernel_ingestor_engine::discoverDescriptorSets()
 *        rather than a hand-built twin, so a broken shipped descriptor fails this
 *        fast suite instead of only the slow GPU integration test.
 *
 * Generated by IngestorGenerator -- complete, not a stub: every assertion below is a
 * pure function of the config that produced this bundle.
 */
namespace
{

using namespace hip_kernel_provider::kernel_ingestor_engine;

/// The descriptor set this engine ships, read from the installed tree.
const hipdnn_plugin_sdk::ingestor::DescriptorSet& loadedSet()
{
    const auto& sets = discoverDescriptorSets();
    const auto match = std::find_if(sets.begin(), sets.end(), [](const auto& set) {
        return set.engine.name == "hipkernel:Gfx950AttentionTiled";
    });
    // Fatal rather than a returned optional: every caller here would only
    // dereference it, and a missing set means the descriptors were never
    // installed or never registered -- itself the failure this test exists
    // to catch.
    if(match == sets.end())
    {
        ADD_FAILURE() << "descriptor set 'hipkernel:Gfx950AttentionTiled' is not installed";
        static const hipdnn_plugin_sdk::ingestor::DescriptorSet s_empty{};
        return s_empty;
    }
    return *match;
}

TEST(TestGfx950AttentionTiledPacks, ShipsExactlyTheConfiguredPackCount)
{
    const auto& set = loadedSet();
    EXPECT_EQ(set.packs.size(), 1U);
}

TEST(TestGfx950AttentionTiledPacks, PackGfx950AttentionTiledShipsItsConfiguredKernels)
{
    const auto& set = loadedSet();
    const auto match = std::find_if(set.packs.begin(), set.packs.end(), [](const auto& p) {
        // The pack's real name, read from the shipped KDP rather than assumed: it is
        // the SLUG-scoped form `hipkernel:<slug>`, matching the dense sibling. The
        // generated stub guessed a doubled `hipkernel:<Engine>:<slug>`, which matches
        // nothing -- and an ASSERT_NE on find_if's end() is how that surfaces.
        return p.name == "hipkernel:gfx950_attention_tiled";
    });
    ASSERT_NE(match, set.packs.end());
    // 39, not the 48 servable SHAPES. `UnifiedAttention2DTiledSpec` has no total_q,
    // max_seqlen_q, max_seqlen_k or batch field, so shapes differing ONLY in sequence
    // length resolve to the same binary and the generator emits one kernel for them.
    // The generated stub's 48 was the shape count, which is the number to expect for a
    // seqlen-specialized kernel like the dense sibling and wrong for this one.
    EXPECT_EQ(match->kernels.size(), 39U);
}

TEST(TestGfx950AttentionTiledPacks, ExposesTheConfiguredKnobs)
{
    const auto& set = loadedSet();
    ASSERT_EQ(set.engine.knobs.size(), 10U);
    EXPECT_NE(std::find(set.engine.knobs.begin(), set.engine.knobs.end(), "head_size"),
              set.engine.knobs.end());
    EXPECT_NE(std::find(set.engine.knobs.begin(), set.engine.knobs.end(), "block_size"),
              set.engine.knobs.end());
    EXPECT_NE(std::find(set.engine.knobs.begin(), set.engine.knobs.end(), "num_query_heads"),
              set.engine.knobs.end());
    EXPECT_NE(std::find(set.engine.knobs.begin(), set.engine.knobs.end(), "num_kv_heads"),
              set.engine.knobs.end());
    EXPECT_NE(std::find(set.engine.knobs.begin(), set.engine.knobs.end(), "num_seqs"),
              set.engine.knobs.end());
    EXPECT_NE(std::find(set.engine.knobs.begin(), set.engine.knobs.end(), "sliding_window"),
              set.engine.knobs.end());
    EXPECT_NE(std::find(set.engine.knobs.begin(), set.engine.knobs.end(), "num_warps"),
              set.engine.knobs.end());
    EXPECT_NE(std::find(set.engine.knobs.begin(), set.engine.knobs.end(), "block_m_per_warp"),
              set.engine.knobs.end());
    EXPECT_NE(std::find(set.engine.knobs.begin(), set.engine.knobs.end(), "tile_size"),
              set.engine.knobs.end());
    EXPECT_NE(std::find(set.engine.knobs.begin(), set.engine.knobs.end(), "waves_per_eu"),
              set.engine.knobs.end());
}

/// UMD policy check, this engine's shape: a SINGLE-pack engine has nothing to
/// discriminate between, so it carries no graph-scoped criterion at all -- the
/// engine's own graph_match both admits the node type and validates shape in one
/// pass. Mirrors TestConvFwdPack.cpp's HasAGraphMatchAndOneKernelMatcher.
TEST(TestGfx950AttentionTiledPacks, CarriesNoGraphScopedMatcher)
{
    const auto& set = loadedSet();
    EXPECT_FALSE(set.engine.graphMatchNativeSymbol.empty());
    const auto graphScoped
        = std::count_if(set.matchers.begin(), set.matchers.end(), [](const auto& matcher) {
              return matcher.scope == hipdnn_plugin_sdk::ingestor::MatchScope::GRAPH;
          });
    EXPECT_EQ(graphScoped, 0);
}

TEST(TestGfx950AttentionTiledPacks, CarriesExactlyOneSharedKernelScopedMatcher)
{
    const auto& set = loadedSet();
    const auto kernelScoped
        = std::count_if(set.matchers.begin(), set.matchers.end(), [](const auto& matcher) {
              return matcher.scope == hipdnn_plugin_sdk::ingestor::MatchScope::KERNEL;
          });
    EXPECT_EQ(kernelScoped, 1);
}

TEST(TestGfx950AttentionTiledPacks, EveryKernelNamesItsPacksEmbeddedSource)
{
    const auto& set = loadedSet();
    for(const auto& pack : set.packs)
    {
        for(const auto& kernel : pack.kernels)
        {
            // KPACK, not EMBEDDED_SOURCE. This engine is the `packaged` dialect: the
            // descriptors are authored `kind: rocke` and hkp_pack lowers them through
            // comgr at BUILD time, rewriting them to `kind: kpack` before the runtime
            // loader ever sees them. The generated stub defaults to the direct_load
            // spelling; the dense packaged sibling asserts KPACK for the same reason.
            EXPECT_EQ(kernel.source.kind, hipdnn_plugin_sdk::ingestor::KernelSourceKind::KPACK);
        }
    }
}

} // namespace

#endif // HIPDNN_ENABLE_KERNEL_INGESTOR
