# Freeze the conv codegen closure (ck modules + shims + embedded arch_specs),
# generated by build_frozen.py. Absolute path (spike).
freeze("/home/dahawkin/repo/worktrees/ck-dsl-provider-micropython/spike/mp2/frozen_src")
