// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

#pragma once

#include "EngineRegistry.hpp"

#include <filesystem>
#include <optional>
#include <string>

namespace hipdnn_backend::heuristics::uhd
{

/// @brief Loader for UHD FlatBuffer descriptors.
///
/// Reads `.uhd.fb` files generated by the uhd_gen tool (RFC 0019 §9.2 format),
/// verifies them, and populates UhdConfig structs for registration.
///
/// Usage:
///   auto config = UhdLoader::load("path/to/uhd.fb");
///   if (config) {
///       // Use config in EngineEntry registration
///   }
class UhdLoader
{
public:
    /// Load a UHD descriptor from a FlatBuffer file.
    ///
    /// @param uhdPath Absolute or relative path to `.uhd.fb` file.
    /// @return Populated UhdConfig on success, std::nullopt on failure.
    ///         Logs errors to hipdnn_data_sdk::logging on failure.
    static std::optional<UhdConfig> load(const std::filesystem::path& uhdPath);

    /// Load a UHD descriptor from a FlatBuffer byte buffer.
    ///
    /// @param buffer FlatBuffer bytes.
    /// @param bufferSize Size of buffer in bytes.
    /// @param basePath Base directory for resolving relative model_artifact_path.
    ///                 If omitted, model_artifact_path is returned as-is.
    /// @return Populated UhdConfig on success, std::nullopt on failure.
    static std::optional<UhdConfig>
        loadFromBuffer(const void* buffer, size_t bufferSize, const std::filesystem::path& basePath = "");

    UhdLoader() = delete;
};

} // namespace hipdnn_backend::heuristics::uhd
