#!/usr/bin/env python3
"""Generate deploy/gpu_constants.h — the gfx_id -> arch-constants table for the
runtime-pure (v10) model. These are the GPU features that the model needs but
are NOT exposed by hipDeviceProp_t; they are architecture invariants keyed on
gcnArchName. The remaining GPU features come straight from hipDeviceProp_t.

Run after changing GPUInfo/*.json. The table is keyed by gfx_id; where a field
varies by SKU we take the value of the data-bearing SKUs (mi300a, which has no
data, is ignored for the gfx942 shader_engines conflict).
"""
import json, glob, collections
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Fields the model uses that come from the table (not hipDeviceProp_t).
TABLE_NUM = ["simds_per_cu", "lds_size_per_cu_kb", "l1_cache_kb_per_cu",
             "xcd_count", "shader_engines", "cacheline_size_bytes",
             "mfma_shape_count"]
TABLE_CAT = ["arch_family", "winograd_support", "asm_implicit_gemm_support"]

# SKUs with zero data — ignore when resolving per-gfx_id conflicts.
IGNORE_SPECS = {"gfx942-mi300a", "gfx1030v", "gfx1150", "gfx1200", "gfx1100w"}

by_gfx = collections.defaultdict(dict)
for f in sorted(glob.glob(str(HERE / "GPUInfo/*.json"))):
    spec_id = Path(f).stem
    if spec_id in IGNORE_SPECS:
        continue
    d = json.loads(Path(f).read_text())
    g = d.get("gfx_id")
    if not g:
        continue
    for fld in TABLE_NUM:
        v = len(d.get("mfma_shapes", [])) if fld == "mfma_shape_count" else d.get(fld)
        if v is None:
            continue
        by_gfx[g][fld] = v
    for fld in TABLE_CAT:
        by_gfx[g][fld] = d.get(fld)

# Only emit gfx_ids that actually appear in the model's spec set.
model_specs = json.loads((HERE / "feature_cols_rank_pruned59.json").read_text())["specs"]
model_gfx = sorted({s.split("-")[0] if not s.startswith("gfx1101-") else "gfx1101"
                    for s in model_specs})
model_gfx = sorted({"gfx1101" if s.startswith("gfx1101") else
                    ("gfx942" if s.startswith("gfx942") else
                     ("gfx950" if s.startswith("gfx950") else
                      ("gfx90a" if s.startswith("gfx90a") else s)))
                    for s in model_specs})

lines = []
lines.append("// AUTO-GENERATED by gen_gpu_constants_header.py — DO NOT EDIT.")
lines.append("// gfx_id -> architecture constants for the MIOpen solver-selector")
lines.append("// (v10 runtime-pure model). These fields are NOT in hipDeviceProp_t;")
lines.append("// they are arch invariants. All other GPU features come from")
lines.append("// hipGetDeviceProperties at runtime (see header comment below).")
lines.append("#pragma once")
lines.append("#include <string>")
lines.append("#include <unordered_map>")
lines.append("")
lines.append("// Runtime-sourced fields (from hipDeviceProp_t), for reference:")
lines.append("//   cu_count               = prop.multiProcessorCount")
lines.append("//   wave_size              = prop.warpSize")
lines.append("//   l2_cache_total_kb      = prop.l2CacheSize / 1024")
lines.append("//   boost_clock_mhz        = prop.clockRate / 1000   // clockRate is kHz")
lines.append("//   lds_size_per_workgroup_kb = prop.sharedMemPerBlock / 1024")
lines.append("//   vram_bytes             = prop.totalGlobalMem")
lines.append("//   gfx_id                 = prop.gcnArchName, truncated at ':' (drop :sramecc+:xnack-)")
lines.append("")
lines.append("struct GpuArchConstants {")
lines.append("    int   simds_per_cu;")
lines.append("    int   lds_size_per_cu_kb;")
lines.append("    int   l1_cache_kb_per_cu;")
lines.append("    int   xcd_count;")
lines.append("    int   shader_engines;")
lines.append("    int   cacheline_size_bytes;")
lines.append("    int   mfma_shape_count;")
lines.append("    const char* arch_family;            // categorical; \"\" if unknown")
lines.append("    bool  winograd_support;")
lines.append("    bool  asm_implicit_gemm_support;")
lines.append("};")
lines.append("")
lines.append("// Keyed by gfx_id (gcnArchName without feature suffixes).")
lines.append("inline const std::unordered_map<std::string, GpuArchConstants>&")
lines.append("gpu_arch_constants() {")
lines.append("    static const std::unordered_map<std::string, GpuArchConstants> t = {")
for g in model_gfx:
    if g not in by_gfx:
        continue
    c = by_gfx[g]
    af = c.get("arch_family") or ""
    lines.append(
        f'        {{"{g}", {{{c.get("simds_per_cu",0)}, {c.get("lds_size_per_cu_kb",0)}, '
        f'{c.get("l1_cache_kb_per_cu",0)}, {c.get("xcd_count",1)}, '
        f'{c.get("shader_engines",0)}, {c.get("cacheline_size_bytes",128)}, '
        f'{c.get("mfma_shape_count",0)}, "{af}", '
        f'{str(bool(c.get("winograd_support"))).lower()}, '
        f'{str(bool(c.get("asm_implicit_gemm_support"))).lower()}}}}},')
lines.append("    };")
lines.append("    return t;")
lines.append("}")
lines.append("")

out = HERE / "deploy" / "gpu_constants.h"
out.write_text("\n".join(lines))
print(f"wrote {out} with {len([g for g in model_gfx if g in by_gfx])} gfx_id entries:")
for g in model_gfx:
    if g in by_gfx:
        print(f"  {g}: {by_gfx[g]}")
