// MIT License
//
// Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#ifndef COMMON_UTILS_HPP_
#define COMMON_UTILS_HPP_

#include <sstream>

#include <rocprim/intrinsics/thread.hpp>

// This macro is used to print error messages generated by HIP_CHECK, below.
// If we're using GTest, FAIL is called to log the Google Test trace.
// The lambda is invoked immediately as assertions that generate a fatal failure can
// only be used in void-returning functions.
#ifdef USE_GTEST
    #define PRINT_ERROR(msg)         \
    {                                \
      const std::string err = msg;   \
      [err]() { FAIL() << err; }();  \
    }
#else
    #define PRINT_ERROR(msg)         \
    {                                \
        const std::string err = msg; \
        std::cout << err;            \
    }
#endif

// GoogleTest-compatible HIP_CHECK macro. FAIL is called to log the Google Test trace.
// The lambda is invoked immediately as assertions that generate a fatal failure can
// only be used in void-returning functions.
#define HIP_CHECK(condition)                                                            \
    {                                                                                   \
        (void) hipGetLastError();                                                       \
        const hipError_t ret_error = condition;                                         \
        const hipError_t hip_error = hipGetLastError();                                 \
        for (const hipError_t& error : {ret_error, hip_error})                          \
        {                                                                               \
            if (error != hipSuccess)                                                    \
            {                                                                           \
                std::ostringstream err_stream;                                          \
                err_stream << "HIP error: " << hipGetErrorString(error) << std::endl    \
                           << "File: " << __FILE__ << " line: " << __LINE__;            \
                const std::string err_msg = err_stream.str();                           \
                PRINT_ERROR(err_msg);                                                   \
                exit(error);                                                            \
            }                                                                           \
        }                                                                               \
    }

// GoogleTest-compatible HIP_CHECK macro that can be used for calls that don't return
// a hipError (eg. kernel launches).
// This version does not synchronize after the launch. That means that any errors that
// occur during kernel execution will not be caught. To catch those, the caller should
// invoke hipStreamSynchronize and check its return value after the launch.
#define HIP_CHECK_LAUNCH(launch)                                                        \
    {                                                                                   \
        (void) hipGetLastError();                                                       \
        launch;                                                                         \
        hipError_t error = hipGetLastError();                                           \
        {                                                                               \
            if (error != hipSuccess)                                                    \
            {                                                                           \
                std::ostringstream err_stream;                                          \
                err_stream << "HIP error: " << hipGetErrorString(error) << std::endl    \
                           << "File: " << __FILE__ << " line: " << __LINE__;            \
                const std::string err_msg = err_stream.str();                           \
                PRINT_ERROR(err_msg);                                                   \
                exit(error);                                                            \
            }                                                                           \
        }                                                                               \
    }

// GoogleTest-compatible HIP_CHECK macro that can be used for calls that don't return
// a hipError (eg. kernel launches).
// Note: we use hipGetLastError to retrieve pre-launch errors (eg. kernel argument issues)
// and hipDeviceSynchronize to retrieve in-kernel errors.
#define HIP_CHECK_LAUNCH_SYNC(launch)                                                   \
    {                                                                                   \
        (void) hipGetLastError();                                                       \
        launch;                                                                         \
        for (const hipError_t& error : {hipGetLastError(), hipDeviceSynchronize()})     \
        {                                                                               \
            if (error != hipSuccess)                                                    \
            {                                                                           \
                std::ostringstream err_stream;                                          \
                err_stream << "HIP error: " << hipGetErrorString(error) << std::endl    \
                           << "File: " << __FILE__ << " line: " << __LINE__;            \
                const std::string err_msg = err_stream.str();                           \
                PRINT_ERROR(err_msg);                                                   \
                exit(error);                                                            \
            }                                                                           \
        }                                                                               \
    }

namespace common
{
template<unsigned int LogicalWarpSize>
__device__
constexpr bool device_test_enabled_for_warp_size_v
    = ::rocprim::arch::wavefront::min_size() >= LogicalWarpSize;

inline char* __get_env(const char* name)
{
    char* env;
#ifdef _MSC_VER
    errno_t err = _dupenv_s(&env, nullptr, name);
    if(err)
    {
        return nullptr;
    }
#else
    env = std::getenv(name);
#endif
    return env;
}

inline void clean_env(char* env)
{
#ifdef _MSC_VER
    free(env);
#endif
    (void)env;
}

inline bool use_hmm()
{

    char*      env = __get_env("ROCPRIM_USE_HMM");
    const bool hmm = (env != nullptr) && (strcmp(env, "1") == 0);
    clean_env(env);
    return hmm;
}

// Helper for HMM allocations: HMM is requested through ROCPRIM_USE_HMM=1 environment variable
template<class T>
hipError_t hipMallocHelper(T** devPtr, size_t size)
{
    if(use_hmm())
    {
        return hipMallocManaged(reinterpret_cast<void**>(devPtr), size);
    }
    else
    {
        return hipMalloc(reinterpret_cast<void**>(devPtr), size);
    }
    return hipSuccess;
}

} // namespace common

#endif // COMMON_UTILS_HPP_
