# Auto Label PR
# -------------
# This GitHub Actions workflow automatically adds or removes labels on a pull request
# based on a custom Python script that analyzes the PR content and paths.
#
# Steps:
#   - Run pr-auto-label.py to determine which labels to add/remove
#   - Update labels on the PR using GitHub CLI (gh)

name: Auto Label PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Compute Labels for PR
        id: compute_labels
        run: |
          python .github/scripts/pr-auto-label.py \
            --token "${{ github.token }}" \
            --repo "${{ github.repository }}" \
            --pr "${{ github.event.pull_request.number }}"

      - name: Check for valid outputs
        run: |
          if [ -z "${{ steps.compute_labels.outputs.add }}" ] && [ -z "${{ steps.compute_labels.outputs.remove }}" ]; then
            echo "No labels to update."
            exit 0
          fi

      - name: Update labels
        run: |
          if [ -n "${{ steps.compute_labels.outputs.remove }}" ]; then
            gh pr edit "${{ github.event.pull_request.number }}" --remove-label "${{ steps.compute_labels.outputs.remove }}"
          fi
          if [ -n "${{ steps.compute_labels.outputs.add }}" ]; then
            gh pr edit "${{ github.event.pull_request.number }}" --add-label "${{ steps.compute_labels.outputs.add }}"
          fi
