name: TheRock CI

on:
  push:
    branches:
      - users/geomin12/therock-ci
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:

  # need setup step

  therock-build-linux:
    name: Build Linux Packages
    permissions:
      contents: read
      id-token: write
    uses: ROCm/TheRock/.github/workflows/build_linux_packages.yml@users/geomin12/monorepo-therock-test
    with:
        amdgpu_families: "gfx94X-dcgpu"
        expect_failure: false
        extra_cmake_options: "-DTHEROCK_ENABLE_PRIM=ON -DTHEROCK_ENABLE_ALL=OFF"

  therock-test-linux:
    name: "rocPRIM math-lib test"
    needs: therock-build-linux
    uses: ROCm/TheRock/.github/workflows/test_rocprim.yml@users/geomin12/monorepo-therock-test
    with:
        artifact_run_id: "${{ github.run_id }}"
        amdgpu_families: "gfx94X-dcgpu"
        test_runs_on: "linux-mi300-1gpu-ossci-rocm"
        platform: "linux"
