name: TheRock CI

on:
  workflow_call:
    inputs:
      cmake_options:
        type: string
      project_to_test:
        type: string
      subtree_checkout:
        type: string
    secrets:
      app_id:
        required: false
      app_private_key:
        required: false


permissions:
  contents: read

jobs:
  therock-build-linux:
    name: Build Linux Packages
    runs-on: azure-linux-scale-rocm
    permissions:
      contents: read
      id-token: write
    env:
      CACHE_DIR: ${{ github.workspace }}/.container-cache
    steps:
      - name: Generate a token for rocm-libraries
        id: generate-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.rocm_libraries_app_id }}
          private-key: ${{ secrets.rocm_libraries_app_private_key }}
          owner: ${{ github.repository_owner }}

      - name: "Checking out repository for rocm-libraries"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ github.repository }}
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          sparse-checkout: |
            .github
            ${{ inputs.subtree_checkout }}
          fetch-depth: 0  # Needed for subtree splitting
          token: ${{ steps.generate-token.outputs.token }}
          path: "rocm-libraries"
      
      - name: Runner Health Settings
        run: |
          echo "CCACHE_DIR=${CCACHE_DIR}"
          df -h
          ccache -z
          mkdir -p $CCACHE_DIR
          cmake --version
          echo "Installed Python versions:"
          ls -d /opt/python
          echo "python: $(which python), python3: $(which python3)"
          echo "Git version: $(git --version)"
          git config --global --add safe.directory $PWD
          git config fetch.parallel 10

      # TODO: We shouldn't be using a cache on actual release branches, but it
      # really helps for iteration time.
      - name: Enable cache
        uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: ${{ env.CACHE_DIR }}
          key: linux-build-packages-manylinux-v2-${{ github.sha }}
          restore-keys: |
            linux-build-packages-manylinux-v2-

      - name: Build Linux Packages
        uses: ROCm/TheRock/.github/actions/build_linux_action@users/geomin12/fix-monorepo-fork
        with:
          package_version: "ADHOCBUILD"
          amdgpu_families: "gfx94X-dcgpu"
          extra_cmake_options: "-DTHEROCK_USE_EXTERNAL_ROCM_LIBRARIES=ON -DTHEROCK_ROCM_LIBRARIES_SOURCE_DIR=rocm-libraries ${{ inputs.cmake_options }}"

      - name: Artifact Upload
        uses: ROCm/TheRock/.github/actions/artifact_upload_action@users/geomin12/fix-monorepo-fork
        with:
          build_directory: "build"
          amdgpu_families: "gfx94X-dcgpu"

      - name: Save cache
        uses: actions/cache/save@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        if: always()
        with:
          path: ${{ env.CACHE_DIR }}
          key: linux-build-packages-manylinux-v2-${{ github.sha }}

  therock-test-linux:
    name: "Test"
    needs: [therock-build-linux]
    uses: ./.github/workflows/therock-test-packages.yml
    with:
      project_to_test: ${{ inputs.project_to_test }}
      amdgpu_families: "gfx94X-dcgpu"
      test_runs_on: "linux-mi300-1gpu-ossci-rocm"
      platform: "linux"
