name: Synchronize Subtrees

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  MONOREPO_URL: github.com/ROCm/rocm-libraries.git
  MONOREPO_BRANCH: develop

jobs:
  synchronize-subtrees:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Monorepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for git subtree pull/push
          token: ${{ secrets.MONOREPO_BOT_TOKEN }}

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Repositories in the Monorepo
        run: |
          has_errors=false
          for row in $(jq -c '.repositories[]' .github/repos-config.json); do
            name=$(echo "$row" | jq -r '.name')
            repo_name=$(echo "$row" | jq -r '.repo-name')
            category=$(echo "$row" | jq -r '.category')
            url=$(echo "$row" | jq -r '.url')
            branch=$(echo "$row" | jq -r '.branch')

            git subtree pull --prefix "${category}/${name}" https://github.com/${url}.git "$branch" || {
              has_errors=true
            }

            # git subtree push --prefix "${category}/${name}" https://github.com/${url}.git "$branch" || {
            #  has_errors=true
            # }
            # popd
          done

          if [ "$has_errors" = true ]; then
            echo "One or more errors occurred during the repository update."
            exit 1
          else
            git push https://${{ env.MONOREPO_URL }} ${{ env.MONOREPO_BRANCH }}
            echo "All repositories updated successfully!"
          fi
