// Copyright © Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

#pragma once

#include <hipdnn_corpus_gen/FeasibleShapeSet.hpp>
#include <hipdnn_corpus_gen/ArgumentResolver.hpp>
#include <hipdnn_corpus_gen/OperationMetadata.hpp>
#include <hipdnn_corpus_gen/WorkloadSampling.hpp>

#include <algorithm>
#include <cstdint>
#include <functional>
#include <random>
#include <set>
#include <string>
#include <vector>

/// @file ProblemSpace.hpp
/// @brief One definition of how a problem space is explored (RFC 0019.13 §4, §5).
///
/// There is exactly one exploration here, and it is expressed once. It is not per engine and
/// not per operation: what varies is the *declaration* it reads -- the parameters an operation
/// metadata file names, their types, and the enumerable values of the categorical ones. An
/// engine never changes how the space is explored; it only says which points it will accept.
///
/// That separation is the point. An exploration written per engine would have to be rewritten
/// for the next one and could not be compared across them, and a corpus generated by different
/// rules for different engines cannot be pooled or held to one coverage standard.
///
/// The space has two kinds of axis and they are explored differently because they *are*
/// different, not as a convenience:
///
///  - **Categorical** (`enum`, `bool`): dtype, layout, mode, forward phase. The declaration
///    lists the values, so they are enumerated. There is nothing to search -- and searching
///    them would be meaningless, since a log-scaled distance between two dtypes says nothing.
///  - **Numeric** (`int64`, `float64`): extents. Nothing declares their bounds (§4.3.2 is
///    explicit that a `range` is a semantic limit, not a size guess), so the region is found by
///    asking: benchmarkability intersected with applicability, discovered by sampling.
///
/// The output is a list of problem points. Feeding them to an engine's predicate is what makes
/// one engine's corpus; the list itself is a statement about the operation.
namespace hipdnn_corpus_gen
{

/// Whether a problem point is admissible. In production this builds the graph and asks the
/// engine; the default accepts everything, which explores the declared space alone.
using ProblemOracle = std::function<bool(const ProblemPoint&)>;

/// How hard to look, and for how much. Identical in meaning for every operation.
struct ExplorationRequest
{
    /// Problem points wanted per categorical combination, so that a corpus does not spend its
    /// whole budget on one dtype and report the space as covered.
    int64_t pointsPerCombination = 50;

    /// Oracle calls per categorical combination.
    int64_t budgetPerCombination = 20000;

    /// Ceiling on every numeric parameter. Not a claim about the operation: it is the largest
    /// extent worth proposing, since anything that cannot be benchmarked cannot enter a
    /// corpus at any budget (§4.3.2).
    int64_t numericCeiling = 4096;

    /// Independent footholds per combination (see FeasibleShapeSet).
    int64_t restarts = 8;

    /// Hit-and-run steps per walk. With restarts, this bounds how many distinct problems the
    /// search can produce at all -- a corpus of ten thousand needs their product to exceed it.
    int64_t stepsPerStart = 400;

    /// Reproducibility, per §5.8.
    uint64_t seed = 0;

    /// Largest number of categorical combinations to explore. Reported when it binds, never
    /// silently applied: a corpus covering three of twelve dtype/layout combinations and
    /// saying nothing is indistinguishable from one that covered the space.
    size_t maxCombinations = 64;

    /// Largest enumerated skeleton to try before sampling. The cross product of an
    /// operation's regime buckets grows quickly, and every point costs an oracle call.
    size_t maxSkeleton = 512;
};

/// One categorical assignment and what the numeric search found under it.
struct CombinationResult
{
    /// How many of this combination's problems came from each source. A corpus that reports a
    /// count without saying where the points came from cannot be audited for realism: anchored
    /// draws and region draws are different claims about what the corpus is for.
    int64_t fromArchetypes = 0;
    int64_t fromNeighbourhood = 0;
    int64_t fromExploration = 0;

    ProblemPoint categorical;
    std::vector<ProblemPoint> problems;
    FeasibleSetStats stats;
};

/// The problem corpus: a list of inputs, and an account of how it was arrived at.
struct ProblemCorpus
{
    std::string operation;

    /// The parameter names in the order the numeric search indexed them, so a shape vector can
    /// be read back as a problem point.
    std::vector<std::string> numericParameters;

    std::vector<CombinationResult> combinations;

    /// Categorical combinations not explored because @ref ExplorationRequest::maxCombinations
    /// bound first. Named, because an unexplored dtype is a hole in the corpus.
    std::vector<std::string> skippedCombinations;

    /// Candidates a declared constraint refused, and candidates it admitted. Counted for the
    /// same reason build failures are: a constraint that is too strong empties the corpus, and
    /// an empty corpus reads as an engine that serves nothing.
    int64_t constraintRejections = 0;
    int64_t constraintAdmissions = 0;

    /// Every problem point found, flattened -- the list of inputs.
    std::vector<ProblemPoint> problems() const
    {
        std::vector<ProblemPoint> all;
        for(const auto& combination : combinations)
        {
            all.insert(all.end(), combination.problems.begin(), combination.problems.end());
        }
        return all;
    }
};

namespace detail
{

/// The cross product of every categorical parameter's declared values.
///
/// Ordered so the product is reproducible: parameters in declaration order, values in the
/// order the metadata lists them. A corpus that enumerated dtypes in hash order would draw a
/// different subset each run whenever the cap bound.
inline std::vector<ProblemPoint>
    categoricalCombinations(const std::vector<Parameter>& parameters, size_t limit, size_t& total)
{
    std::vector<ProblemPoint> combinations{ProblemPoint{}};
    total = 1;

    for(const auto& parameter : parameters)
    {
        const auto values = parameter.enumerable();
        if(values.empty())
        {
            continue;
        }
        total *= values.size();

        std::vector<ProblemPoint> expanded;
        for(const auto& base : combinations)
        {
            for(const auto& value : values)
            {
                auto point = base;
                point[parameter.name] = value;
                expanded.push_back(std::move(point));
            }
        }
        combinations = std::move(expanded);

        if(combinations.size() > limit)
        {
            combinations.resize(limit);
        }
    }
    return combinations;
}

/// Whether @p point satisfies every relation @p metadata declares.
///
/// Checked before the oracle, so a candidate that is not a problem never costs a graph build.
/// A constraint that fails to evaluate is treated as unsatisfied rather than ignored: a
/// malformed relation that silently admitted everything would restore exactly the behaviour it
/// was added to prevent.
inline bool satisfiesConstraints(const OperationMetadata& metadata, const ProblemPoint& point)
{
    if(metadata.constraints.empty())
    {
        return true;
    }

    const hipdnn_plugin_sdk::ingestor::uhd::JsonLogicEvaluator evaluator;
    const auto context = detail::contextFor(point);
    for(const auto& constraint : metadata.constraints)
    {
        try
        {
            const auto value = evaluator.evaluate(constraint, context);
            const auto* held = std::get_if<bool>(&value);
            if(held == nullptr || !*held)
            {
                return false;
            }
        }
        catch(const std::exception&)
        {
            return false;
        }
    }
    return true;
}

/// The skeleton of enumerated points a declaration already describes.
///
/// RFC 0019.13 §4.3.5's regime buckets are not only a stratification target -- they are the
/// operation's own statement of which values matter, and their cross product is valid by
/// construction in a way independent draws are not. A convolution declaring
/// `spatial: [7, 14, 28, 56, 112, 224]` and `filter: [1, 3, 5, 7]` has said that a 3x3 filter
/// on a 28x28 input is a real problem; sampling H and R independently from a shared range says
/// only that 83 might pair with 36, which the frontend then refuses.
///
/// This is the same instinct CK and rocKE follow -- powers of two, recorded model shapes,
/// deliberate edge cases -- with the difference that here it seeds a search rather than being
/// the whole corpus, because a curated list cannot say what an engine accepts that nobody
/// thought to list.
///
/// Parameters with no regime take their floor. That is deliberately unambitious: it makes the
/// skeleton valid (a padding of 0, a stride of 1) and leaves the walk to raise them, which is
/// what the walk is for.
inline std::vector<Shape> regimeSkeleton(const OperationMetadata& metadata,
                                         const std::vector<ShapeDimension>& window,
                                         const std::vector<std::string>& numericParameters,
                                         size_t limit,
                                         size_t& total)
{
    // Buckets per numeric parameter, in the declaration's order.
    std::vector<std::vector<int64_t>> choices;
    choices.reserve(numericParameters.size());
    total = 1;

    for(size_t i = 0; i < numericParameters.size(); ++i)
    {
        std::vector<int64_t> values;
        for(const auto& entry : metadata.regimes)
        {
            if(entry.second.parameter != numericParameters[i] || !entry.second.derived.empty())
            {
                continue;
            }
            for(const auto& bucket : entry.second.buckets)
            {
                if(bucket.is_number_integer())
                {
                    const auto value = bucket.get<int64_t>();
                    if(value >= window[i].low && value <= window[i].high)
                    {
                        values.push_back(value);
                    }
                }
            }
        }

        // §4.3.2's common_values are the other declared source: representative values from a
        // usage record, which is where a real model's shapes enter.
        if(const auto* parameter = metadata.find(numericParameters[i]))
        {
            for(const auto& value : parameter->commonValues)
            {
                if(const auto* held = std::get_if<int64_t>(&value))
                {
                    if(*held >= window[i].low && *held <= window[i].high)
                    {
                        values.push_back(*held);
                    }
                }
            }
        }

        if(values.empty())
        {
            values.push_back(window[i].low);
        }
        std::sort(values.begin(), values.end());
        values.erase(std::unique(values.begin(), values.end()), values.end());
        total *= values.size();
        choices.push_back(std::move(values));
    }

    std::vector<Shape> skeleton{Shape{}};
    for(const auto& values : choices)
    {
        std::vector<Shape> expanded;
        for(const auto& base : skeleton)
        {
            for(const auto value : values)
            {
                auto point = base;
                point.push_back(value);
                expanded.push_back(std::move(point));
            }
        }
        skeleton = std::move(expanded);
    }

    if(skeleton.size() > limit && limit > 0)
    {
        // Strided, not truncated. The product is generated in declaration order, so keeping a
        // prefix keeps the combinations where every early parameter is at its smallest value
        // -- a skeleton of nothing but tiny convolutions, chosen by an implementation detail.
        // Striding covers the same product evenly and stays deterministic.
        std::vector<Shape> sampled;
        sampled.reserve(limit);
        const auto step = static_cast<double>(skeleton.size()) / static_cast<double>(limit);
        for(size_t i = 0; i < limit; ++i)
        {
            sampled.push_back(skeleton[static_cast<size_t>(static_cast<double>(i) * step)]);
        }
        skeleton = std::move(sampled);
    }
    return skeleton;
}

/// A one-line rendering of a categorical assignment, for reporting what was skipped.
inline std::string describe(const ProblemPoint& point)
{
    std::string text;
    for(const auto& [name, value] : point)
    {
        if(!text.empty())
        {
            text += ",";
        }
        text += name + "=";
        std::visit(
            [&text](const auto& held) {
                using Held = std::decay_t<decltype(held)>;
                if constexpr(std::is_same_v<Held, std::string>)
                {
                    text += held;
                }
                else if constexpr(std::is_same_v<Held, bool>)
                {
                    text += held ? "true" : "false";
                }
                else
                {
                    text += std::to_string(held);
                }
            },
            value);
    }
    return text;
}

} // namespace detail

/// @brief Explores the space @p metadata declares, keeping the points @p admits accepts.
///
/// The numeric parameters of each categorical combination are searched with the same feasible
/// region algorithm used everywhere else, over a window that is the benchmarking ceiling
/// rather than an authored bound. The categorical parameters are enumerated because they are
/// declared.
///
/// Every combination gets its own budget rather than sharing one. A shared budget is spent by
/// whichever combination is searched first, and the corpus then covers one dtype thoroughly
/// and the rest not at all -- while reporting a total that looks complete.
inline ProblemCorpus exploreProblemSpace(const OperationMetadata& metadata,
                                         const ExplorationRequest& request,
                                         const ProblemOracle& admits)
{
    ProblemCorpus corpus;
    corpus.operation = metadata.operation;

    std::vector<ShapeDimension> numericWindow;
    for(const auto& parameter : metadata.parameters)
    {
        if(parameter.type != ParameterType::INT64 && parameter.type != ParameterType::FLOAT64)
        {
            continue;
        }
        corpus.numericParameters.push_back(parameter.name);

        // A semantic range, where one exists, is a genuine constraint of the operation and is
        // honoured. Its absence is the normal case and means the ceiling applies (§4.3.2).
        ShapeDimension dimension{parameter.name, 1, request.numericCeiling};
        if(parameter.range.has_value())
        {
            // The floor is taken as declared, including zero: a padding of 0 is the unpadded
            // convolution, which is the only one some engines accept.
            dimension.low = parameter.range->first;
            dimension.high = std::min(request.numericCeiling, parameter.range->second);
        }
        numericWindow.push_back(dimension);
    }

    size_t totalCombinations = 0;
    const auto combinations = detail::categoricalCombinations(
        metadata.parameters, request.maxCombinations, totalCombinations);

    if(totalCombinations > combinations.size())
    {
        corpus.skippedCombinations.push_back(
            std::to_string(totalCombinations - combinations.size())
            + " of " + std::to_string(totalCombinations)
            + " categorical combinations not explored (maxCombinations bound)");
    }

    for(size_t index = 0; index < combinations.size(); ++index)
    {
        const auto& categorical = combinations[index];

        CombinationResult result;
        result.categorical = categorical;

        if(numericWindow.empty())
        {
            // An operation whose every parameter is categorical still has problems: one per
            // combination. Returning nothing here would drop it from the corpus entirely.
            if(admits(categorical))
            {
                result.problems.push_back(categorical);
            }
            corpus.combinations.push_back(std::move(result));
            continue;
        }

        // The one place the two halves meet: the numeric search asks about whole problem
        // points, with the categorical values of this combination held fixed.
        const auto oracle = [&](const Shape& shape) {
            auto point = categorical;
            for(size_t i = 0; i < corpus.numericParameters.size(); ++i)
            {
                point[corpus.numericParameters[i]] = shape[i];
            }
            // Declared relations first: a candidate that is not a problem should not cost a
            // graph build, and should not be counted against the engine.
            if(!detail::satisfiesConstraints(metadata, point))
            {
                ++corpus.constraintRejections;
                return false;
            }
            ++corpus.constraintAdmissions;
            return admits(point);
        };

        size_t skeletonTotal = 0;
        const auto skeleton = detail::regimeSkeleton(
            metadata, numericWindow, corpus.numericParameters, request.maxSkeleton,
            skeletonTotal);
        if(skeletonTotal > skeleton.size() && index == 0)
        {
            corpus.skippedCombinations.push_back(
                std::to_string(skeletonTotal - skeleton.size()) + " of "
                + std::to_string(skeletonTotal)
                + " declared regime combinations not tried (maxSkeleton bound)");
        }

        FeasibleSetRequest search;
        search.seeds = skeleton;
        search.dimensions = numericWindow;
        search.targetCount = request.pointsPerCombination;
        search.oracleBudget = request.budgetPerCombination;
        search.restarts = request.restarts;
        search.stepsPerStart = request.stepsPerStart;
        // Varied per combination so later dtypes do not retrace the first one's draws, and
        // still fixed by `seed` so the whole corpus reproduces.
        search.seed = request.seed + index;

        // ------------------------------------------------------------------
        // The workload half (§5.2): most of the budget is drawn near recorded shapes, and the
        // rest is left to the region search so the corpus still covers what nobody wrote down.
        // ------------------------------------------------------------------
        std::mt19937_64 rng(request.seed + index + 1);
        std::set<std::string> seen;
        std::vector<ProblemPoint> anchored;

        const auto accept = [&](const ProblemPoint& point) {
            if(!seen.insert(detail::describe(point)).second)
            {
                return false;
            }
            if(!detail::satisfiesConstraints(metadata, point))
            {
                ++corpus.constraintRejections;
                return false;
            }
            ++corpus.constraintAdmissions;
            return admits(point);
        };

        size_t archetypeQuota = 0;
        size_t neighbourhoodQuota = 0;
        if(!metadata.mixture.isExplorationOnly())
        {
            const auto total = static_cast<double>(request.pointsPerCombination);
            archetypeQuota = static_cast<size_t>(
                std::max(0.0, metadata.mixture.archetypes * total));
            neighbourhoodQuota = static_cast<size_t>(
                std::max(0.0, metadata.mixture.neighbourhood * total));
        }

        // Attempts are capped rather than unbounded: an archetype set that this engine declines
        // outright would otherwise spin against the oracle for the whole budget and report a
        // failure to find anything as a failure to search.
        const size_t archetypeAttempts = archetypeQuota * 20;
        for(size_t attempt = 0; attempt < archetypeAttempts && anchored.size() < archetypeQuota;
            ++attempt)
        {
            const auto& archetype = metadata.archetypes[attempt % metadata.archetypes.size()];
            const auto drawn = detail::drawFromArchetype(metadata, archetype, categorical, rng);
            if(!drawn.has_value())
            {
                continue; // the archetype does not describe this combination
            }
            if(accept(*drawn))
            {
                anchored.push_back(*drawn);
                result.problems.push_back(*drawn);
                ++result.fromArchetypes;
            }
        }

        // Perturbation needs somewhere to stand. Anchors that survived the oracle are the best
        // starting points; if none did, there is nothing realistic to perturb and the budget
        // belongs to the exploration rather than to noise around a rejected shape.
        const size_t neighbourhoodAttempts = anchored.empty() ? 0 : neighbourhoodQuota * 20;
        size_t drawnNearby = 0;
        for(size_t attempt = 0;
            attempt < neighbourhoodAttempts && drawnNearby < neighbourhoodQuota; ++attempt)
        {
            const auto& anchor = anchored[attempt % anchored.size()];
            const auto moved = detail::perturbWithinNeighbourhood(metadata, anchor, rng);
            if(accept(moved))
            {
                result.problems.push_back(moved);
                ++result.fromNeighbourhood;
                ++drawnNearby;
            }
        }

        if(!metadata.archetypes.empty() && anchored.empty())
        {
            // Silence here would read as an operation with no declared workloads, which is a
            // different and much less interesting fact than an engine that serves none of them.
            corpus.skippedCombinations.push_back(
                "no declared archetype was admitted for " + detail::describe(categorical)
                + "; that combination is exploration only");
        }

        // Whatever the anchored halves did not fill stays with the search, so a combination is
        // never short-changed by archetypes that did not apply.
        search.targetCount
            = std::max<int64_t>(0, request.pointsPerCombination
                                       - static_cast<int64_t>(result.problems.size()));

        // Admitted realistic points are known-good footholds, and a hit-and-run walk that starts
        // inside the region finds far more than one that has to hunt for it.
        for(const auto& point : result.problems)
        {
            Shape shape;
            shape.reserve(corpus.numericParameters.size());
            for(const auto& name : corpus.numericParameters)
            {
                shape.push_back(detail::integerAt(point, name).value_or(1));
            }
            search.seeds.push_back(std::move(shape));
        }

        if(search.targetCount > 0)
        {
            const auto found = buildFeasibleShapeSet(oracle, search);
            result.stats = found.stats;
            for(const auto& shape : found.shapes)
            {
                auto point = categorical;
                for(size_t i = 0; i < corpus.numericParameters.size(); ++i)
                {
                    point[corpus.numericParameters[i]] = shape[i];
                }
                if(seen.insert(detail::describe(point)).second)
                {
                    result.problems.push_back(std::move(point));
                    ++result.fromExploration;
                }
            }
        }

        corpus.combinations.push_back(std::move(result));
    }

    return corpus;
}

} // namespace hipdnn_corpus_gen
